[[tooling-ant]]
=== Ant

Hibernate provides https://ant.apache.org/[Ant] support.
Everything Ant related is available from the
https://central.sonatype.com/artifact/org.hibernate.orm/hibernate-ant[hibernate-ant]
library.  The Ant integration supports <<tooling-ant-enhancement,bytecode enhancement>>,
<<tooling-ant-modelgen,metamodel generation>>, and <<tooling-ant-reveng,reverse engineering>>.

[[tooling-ant-enhancement]]
==== Bytecode Enhancement ====

Hibernate provides an https://ant.apache.org/[Ant] task implementation
that you can use to do build-time bytecode enhancement of your domain
model. You can visit <<BytecodeEnhancement>> for discussion of the capabilities
of an enhanced model.

[[ant-enhance-task]]
===== *Enhance Task* =====

The task implementation is in class `org.hibernate.tool.enhance.EnhancementTask`,
so you will need to include a `taskdef` in your `build.xml` that uses this class
to define your task. Below is a minimal Ant `build.xml` file that shows the use
of the enhancement task.

[[enhance-task-example]]
.Enhance Task Example
====
[source, xml,subs="attributes+"]
----
include::extras/ant-enhance-example.xml[]
----
====

As you can see above, https://ant.apache.org/ivy[Apache Ivy] was used to
handle the dependency on the
https://central.sonatype.com/artifact/org.hibernate.orm/hibernate-ant[hibernate-ant]
library. Now let's dive a little deeper in the configuration possibilities for the
enhancement task.

[[ant-enhance-configuration]]
===== *Enhance Configuration* =====

[[ant-enhance-base-attribute]]
====== `*base*` ======
This attribute is mandatory. It points to the base folder where the enhancement task will look
to discover classes that have to be enhanced. It is either combined with the `dir`
attribute that specifies a subfolder of `base` where the classes are located (or of course
the entire `base` folder) or else with a `<fileset>` child element that has a similar role.
If neither `dir` nor `<fileset>` are used, no classes will be enhanced.

====
[source, xml]]
----
<enhance base='${basedir}/dest' .../>
----
====

[[ant-enhance-dir-attribute]]
====== `*dir*` ======
This attribute is combined with the (mandatory) `base` attribute described above. It points to
a subfolder of `base` where the enhancement task will look to discover the classes to be enhanced.
If the `dir` attribute is specified, the use of a `<fileset>` child element will be ignored.
If neither `dir` nor `<fileset>` are used, no classes will be enhanced.

====
[source, xml]]
----
<enhance
   base='...'
   dir='some subfolder of base'/>
----
====

[[ant-enhance-fileset-element]]
===== `*<fileset>*` =====
This child element is combined with the (mandatory) `base` attribute described above. It can be used
to detail which classes should be selected for enhancement. The use of `<fileset>` is well documented on the
https://ant.apache.org/manual/Types/fileset.html[Ant FileSet documentation page]. If the `dir` attribute
described above is specified, the `<fileset>` element will be ignored.
If neither `dir` nor `<fileset>` are used, no classes will be enhanced.

====
[source, xml]]
----
<enhance base='${basedir}/dest'>
   <fileset dir="some subfolder of base">
      <exclude name='Baz.class' />
   </fileset>
</enhance>
----
====

[[ant-enhance-enableLazyInitialization-attribute]]
===== `*enableLazyInitialization*` =====
This attribute has a default value of `true`. It indicates that the enhance task should perform the changes
to enable lazy loading. To disable, set the value of this attribute to `false`.

====
[source, xml]]
----
<enhance
   ...
   enableLazyInitialization='false'/>
----
====


[[ant-enhance-enableDirtyTracking-attribute]]
===== `*enableDirtyTracking*` =====
This attribute has a default value of `true`. It indicates that the enhance task should perform the changes
to enable dirty tracking. To disable, set the value of this attribute to `false`.

====
[source, xml]]
----
<enhance
   ...
   enableDirtyTracking='false'/>
----
====

[[ant-enhance-enableAssociationManagement-attribute]]
===== `*enableAssociationManagement*` =====
This attribute has a default value of `false`. It indicates that the enhance task should not perform the changes
to enable association management. To enable, set the value of this attribute to `true`.

====
[source, xml]]
----
<enhance
   ...
   enableAssociationManagement='true'/>
----
====

[[ant-enhance-enableExtendedEnhancement-attribute]]
===== `*enableExtendedEnhancement*` =====
This attribute has a default value of `false`. It indicates that the enhance task should not perform the changes
to enable the extended enhancement (i.e. even on non-entities).
To enable this, set the value of this attribute to `true`.

====
[source, xml]]
----
<enhance
   ...
   enableExtendedEnhancement='true'/>
----
====

[[ant-enhance-failOnError-attribute]]
===== `*failOnError*` =====
This attribute has a default value of `true`. It indicates that the enhance task will throw an Ant BuildException
when it encounters a problem. If you prefer the build to continue, you can set the value to `false`.

====
[source, xml]]
----
<enhance
   ...
   failOnError='false'/>
----
====

===== *Final Remark* =====
If the values of the four attributes `enableLazyInitialization`, `enableDirtyTracking`, `enableAssociationManagement`,
`enableExtendedEnhancement` are all `false`, the enhancement task is not executed.

[[tooling-ant-modelgen]]
==== Static Metamodel Generation in Ant

As mentioned in <<tooling-modelgen>>, the generator is implemented as an
annotation processor and can be used anywhere javac is used - such as
Ant's https://ant.apache.org/manual/Tasks/javac.html[javac] task.

[[javac-task-example]]
.Javac task configuration
====
[source,xml,subs="attributes+"]
----
<javac srcdir="${src.dir}"
        destdir="${target.dir}"
        failonerror="false"
        fork="true"
        classpath="${classpath}">
    <compilerarg value="-processorpath" />
    <compilerarg value="/path/to/hibernate-processor-{fullVersion}.jar"/>
    <compilerarg value="-proc:only"/>
</javac>
----

====


[[tooling-ant-reveng]]
==== Reverse Engineering

Hibernate provides an Ant task for <<tooling-reveng,reverse engineering>> an existing database
into Java entities, mapping files, DAOs, configuration files, and DDL scripts.


[[tooling-ant-reveng-task]]
===== Task Definition

The reverse engineering task is implemented by `org.hibernate.tool.ant.HibernateToolTask`.
Define it in your `build.xml` using a `taskdef`:

[source,xml,subs="attributes+"]
----
<taskdef name="hibernatetool"
         classname="org.hibernate.tool.ant.HibernateToolTask"
         classpathref="toolslib"/>
----

The `toolslib` classpath must include the
https://central.sonatype.com/artifact/org.hibernate.orm/hibernate-ant[hibernate-ant]
artifact and its dependencies, as well as the JDBC driver for your database.


[[tooling-ant-reveng-hibernatetool]]
===== The `<hibernatetool>` Task

The `<hibernatetool>` task is the main entry point. It accepts the following attributes:

`destdir`:: The base output directory for generated files. Required (can be set on the task or on individual exporters).
`templatepath`:: Path to a directory containing custom FreeMarker templates.

It also accepts `<property>` child elements for passing additional properties, and
a `<classpath>` element for configuring the classpath.


[[tooling-ant-reveng-configurations]]
===== Configuration Elements

A `<hibernatetool>` task requires exactly one configuration element that defines how metadata is obtained.
For reverse engineering from a database, use `<jdbcconfiguration>`:

`<jdbcconfiguration>`:: Reads database metadata via JDBC for reverse engineering. Attributes:
+
--
`propertyfile`;; Path to a properties file containing JDBC connection settings.
`configurationfile`;; Path to a `hibernate.cfg.xml` file.
`packagename`;; The default Java package name for generated classes.
`reversestrategy`;; Fully qualified class name of a custom reverse engineering strategy.
`revengfile`;; Path containing reverse engineering configuration XML file(s) for customizing schema selection and type mappings.
`detectmanytomany`;; Whether to detect many-to-many link tables. Default: `true`.
`detectonetoone`;; Whether to detect one-to-one associations. Default: `true`.
`detectoptimisticlock`;; Whether to detect `VERSION`/`TIMESTAMP` columns for optimistic locking. Default: `true`.
--

Other configuration elements are also available for non-JDBC scenarios:

`<configuration>`:: Uses a `hibernate.cfg.xml` and/or HBM mapping files as input.
`<jpaconfiguration>`:: Uses a JPA `persistence.xml` as input.


[[tooling-ant-reveng-exporters]]
===== Exporter Elements

One or more exporter elements can be nested inside `<hibernatetool>` to specify what artifacts to generate.
Each exporter supports a `destdir` attribute to override the output directory.

`<hbm2java>`:: Generates Java entity classes.
`<hbm2hbmxml>`:: Generates `hbm.xml` mapping files.
`<hbm2dao>`:: Generates Data Access Object (DAO) classes.
`<hbm2ddl>`:: Generates DDL scripts (schema creation/drop).
`<hbm2cfgxml>`:: Generates a `hibernate.cfg.xml` configuration file.
`<hbm2doc>`:: Generates HTML documentation of the database schema.
`<hbmtemplate>`:: Runs a custom FreeMarker template for user-defined code generation.
`<query>`:: Executes HQL queries against the configured metadata.


[[tooling-ant-reveng-example]]
===== Example

The following `build.xml` generates JPA entity classes from a database:

[source,xml,subs="attributes+"]
----
<project name="reveng-example" default="generate">

    <path id="toolslib">
        <fileset dir="${lib.dir}">
            <include name="**/*.jar"/>
        </fileset>
    </path>

    <taskdef name="hibernatetool"
             classname="org.hibernate.tool.ant.HibernateToolTask"
             classpathref="toolslib"/>

    <target name="generate">
        <hibernatetool destdir="${build.dir}/generated-sources">
            <classpath>
                <path refid="toolslib"/>
            </classpath>
            <jdbcconfiguration
                propertyfile="src/main/resources/hibernate.properties"
                packagename="com.example.model"
                detectmanytomany="true"/>
            <hbm2java/>
        </hibernatetool>
    </target>

</project>
----

To generate multiple artifact types in a single run, add additional exporter elements:

[source,xml]
----
<hibernatetool destdir="${build.dir}/generated-sources">
    <jdbcconfiguration
        propertyfile="src/main/resources/hibernate.properties"
        packagename="com.example.model"/>
    <hbm2java/>
    <hbm2dao/>
    <hbm2ddl/>
</hibernatetool>
----


[[tooling-ant-schema]]
==== Schema Management

Coming soon
