[[tooling-gradle]]
=== Gradle Plugin

For integrating with https://gradle.org[Gradle], Hibernate provides the
https://plugins.gradle.org/plugin/org.hibernate.orm[org.hibernate.orm] plugin which
supports bytecode enhancement and static metamodel generation but not schema tooling.

To apply the plugin, use Gradle's `plugins {}` block:

[source,gradle]
----
plugins {
    id "org.hibernate.orm" version "<version-to-use>"
}
----


Applying the plugin creates a `hibernate` extension (`HibernateOrmSpec`) to configure the plugin.
By default, when the plugin is applied, support for both bytecode enhancement and static metamodel
generation is enabled.

[source,gradle]
----
hibernate {
    // for illustration, let's disable both
    disableEnhancement
    disableJpaMetamodel
}
----

[[tooling-gradle-enhancement]]
==== Bytecode Enhancement

Enhancement is configured through the `enhancement` extension:

[source,gradle]
----
hibernate {
    enhancement {
        // for illustration, enable them all
        lazyInitialization true
        dirtyTracking true
        associationManagement true
    }
}
----

The extension is of type `EnhancementSpec` which exposes the following properties:


enableLazyInitialization:: Whether to incorporate lazy loading support into the enhanced bytecode
enableDirtyTracking:: Whether to incorporate dirty tracking into the enhanced bytecode
enableAssociationManagement:: Whether to add bidirectional association management into the enhanced bytecode


Which all default to false (disabled).

It also exposes the following method forms:

* lazyInitialization(boolean)
* dirtyTracking(boolean)
* associationManagement(boolean)


[[tooling-gradle-modelgen]]
==== Static Metamodel Generation

One approach to integrate Static Metamodel generation into a Gradle build is to
use Gradle's support for annotation processors -

[source,gradle]
----
dependencies {
    annotationProcessor "org.hibernate.orm:hibernate-jpamodelgen:${hibernateVersion}"
}
----

When the build does not need bytecode enhancement support, this is a perfectly valid solution.

The plugin supports simpler configuration of the generator using the registered
`jpaMetamodel` extension:


[source,gradle]
----
hibernate {
    jpaMetamodel {
        applyGeneratedAnnotation false
        suppress 'raw'
        generationOutputDirectory "${buildDir}/generated/sources/modelgen"
        compileOutputDirectory "${buildDir}/classes/java/modelgen"
    }
}
----

The extension is of type `JpaMetamodelGenerationSpec`, which exposes the following configuration properties:

applyGeneratedAnnotation:: Should the `javax.annotation.processing.Generated` annotation be added to the
generated classes.  Defaults to `true`.
suppressions:: Suppressions to add to the generated classes.  Defaults to `['raw', 'deprecation']`
generationOutputDirectory:: Directory where the generated metamodel classes should be created.  Defaults
to `${buildDir}/generated/sources/jpaMetamodel`
[[tooling-gradle-modelgen-compile-output]]
compileOutputDirectory:: Directory where the classes compiled from the generated metamodel classes should be
created. Defaults to `${buildDir}/classes/java/jpaMetamodel`.

It also exposes the following method forms:

* applyGeneratedAnnotation(boolean)
* suppress(String)
* generationOutputDirectory(Object)
* compileOutputDirectory(Object)

