[[tooling-gradle]]
=== Gradle

Hibernate provides the ability to integrate both
<<tooling-gradle-enhancement,bytecode enhancement>> and <<tooling-gradle-modelgen,metamodel generation>> capabilities into Gradle builds.

[[tooling-gradle-enhancement]]
==== Bytecode Enhancement

Bytecode enhancement is incorporated into Gradle builds using Hibernate's
https://plugins.gradle.org/plugin/org.hibernate.orm[Gradle plugin].
To apply the plugin, use Gradle's `plugins {}` block:

[source,gradle]
----
plugins {
    id "org.hibernate.orm" version "<version-to-use>"
}
----

Applying the plugin creates a `hibernate` extension (`HibernateOrmSpec`) to configure the plugin.

[source,gradle]
----
hibernate {
    ...
}
----

Enhancement is configured through the `enhancement` extension.

NOTE: `hibernate {}` and `enhancement {}` are separate to allow for schema tooling capabilities to be added later.

[source,gradle]
----
hibernate {
    enhancement {
        // for illustration, enable them all
        lazyInitialization true
        dirtyTracking true
        associationManagement true
    }
}
----

The extension is of type `EnhancementSpec` which exposes the following properties:

enableLazyInitialization:: Whether to incorporate lazy loading support into the enhanced bytecode. Defaults to `true`. This setting is deprecated for removal without a replacement.  See <<BytecodeEnhancement-lazy-loading>>
enableDirtyTracking:: Whether to incorporate dirty tracking into the enhanced bytecode. Defaults to `true`. This setting is deprecated for removal without a replacement.  See <<BytecodeEnhancement-dirty-tracking>>.
enableAssociationManagement:: Whether to add bidirectional association management into the enhanced bytecode.  See <<BytecodeEnhancement-dirty-tracking-bidirectional>>.

It also exposes the following method forms:

* lazyInitialization(boolean)
* dirtyTracking(boolean)
* associationManagement(boolean)


[[tooling-gradle-modelgen]]
==== Static Metamodel Generation

Static metamodel generation can be incorporated into Gradle builds via the
annotation processor provided by the `org.hibernate.orm:hibernate-processor` artifact.  Applying
an annotation processor in Gradle is super easy -


[source,gradle]
----
dependencies {
    annotationProcessor "org.hibernate.orm:hibernate-processor:${hibernateVersion}"
}
----
