[[tooling-modelgen]]
=== Static Metamodel Generator
:root-project-dir: ../../../../../../..
:testing-project-dir: {root-project-dir}/hibernate-testing
:example-dir-model: {testing-project-dir}/src/main/java/org/hibernate/testing/orm/domain/userguide
:example-dir-metamodelgen-generated: {testing-project-dir}/target/generated/sources/annotationProcessor/java/main/org/hibernate/testing/orm/domain/userguide
:core-project-dir: {root-project-dir}/hibernate-core
:toolingTestsDir: {core-project-dir}/src/test/java/org/hibernate/orm/test/tooling

Jakarta Persistence defines a typesafe Criteria API which allows `Criteria` queries to be constructed in a
strongly-typed manner, utilizing so-called static metamodel classes.  For developers, it is important that
the task of the metamodel generation can be automated.  Hibernate Static Metamodel Generator is an annotation
processor based on https://jcp.org/en/jsr/detail?id=269[JSR_269] with the task of creating Jakarta Persistence
static metamodel classes.

See <<criteria>> for discussion of Jakarta Persistence criteria queries.

The Hibernate Static Metamodel Generator is defined by the published `org.hibernate.orm:metamodel-generator`
artifact.  As it is defined as an
https://docs.oracle.com/en/java/javase/11/tools/javac.html#GUID-082C33A5-CBCA-471A-845E-E77F79B7B049[annotation processor],
it is usable anytime `javac` is used.  See the tool-specific discussions (<<tooling-gradle,Gradle>>, <<tooling-maven,Maven>>
and <<tooling-ant,Ant>>) for details on integrating the generator into those environments.

NOTE:: The fully qualified name of the processor class is `org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor`.

[TIP]
====
The `javac` option _-proc:only_ instructs the compiler to just run the annotation processing.
You can also disable annotation processing by specifying _-proc:none_.

Run `'javac -help'` to see which other annotation processor relevant options can be specified.
====


The structure of the metamodel classes is described in the Jakarta Persistence
specification, but for completeness the definition is repeated in the following
paragraphs.  For every class in a persistence-unit, the generator will produce
a static metamodel class based on the following rules:

* For each managed class `X` in package `p`, a metamodel class `X_` is created in package `p`.
* The name of the metamodel class is derived from the name of the managed class by appending "_" to the managed class name.
* The metamodel class `X_` must be annotated with the `jakarta.persistence.StaticMetamodel` annotation.  The generation
can also be configured to add the `javax.annotation.processing.Generated` annotation.
* If class `X` extends another class `S`, where `S` is the most derived managed class extended by `X`, then
class `X_` must extend class `S_`, where `S_` is the metamodel class created for `S`.
* For every persistent singular attribute `y` declared by class `X`, where the type of `y` is `Y`,
the metamodel class must contain a declaration as follows:

 public static volatile SingularAttribute<X, Y> y;

* For every persistent plural attribute `z` declared by class `X`, where the element type of `z` is `Z`, the metamodel
class must contain a declaration as follows:

** if the collection type of `z` is `java.util.Collection`, then

 public static volatile CollectionAttribute<X, Z> z;

** if the collection type of `z` is `java.util.Set`, then

 public static volatile SetAttribute<X, Z> z;

** if the collection type of `z` is `java.util.List`, then

 public static volatile ListAttribute<X, Z> z;

** if the collection type of `z` is `java.util.Map`, then
+
 public static volatile MapAttribute<X, K, Z> z;
+
where `K` is the type of the key of the map in class `X`

* Import statements must be included for `jakarta.persistence.metamodel` types as
needed, as well as all domain model classes (i.e., `X`, `S`, `Y`, `Z`, and `K`).

As an example, consider the following domain model -

[[ex-tooling-modelgen-model]]
.`Order` and `Item` entities
====
[source, JAVA, indent=0]
----
include::{example-dir-model}/tooling/Customer.java[tags=tooling-modelgen-model]
include::{example-dir-model}/tooling/Order.java[tags=tooling-modelgen-model]
include::{example-dir-model}/tooling/Item.java[tags=tooling-modelgen-model]
----
====

Given this model, the generator will produce classes named `Customer_`, `Order_` and `Item_`.  As an example:

[[tooling-modelgen-metamodel]]
.`Order_`
====
[source, JAVA, indent=0]
----
include::{example-dir-metamodelgen-generated}/tooling/Order_.java[]
----
====

At boot-time, Hibernate will find these classes and populate them.  They can then be used in
Criteria queries for type-safe path references.  For example:

[[tooling-modelgen-usage]]
.Static Metamodel usage
====
[source, JAVA, indent=0]
----
include::{toolingTestsDir}/modelgen/ModelGenTests.java[tags=tooling-modelgen-usage]
----
====

