/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/// Community DB2 identity-column profile.
///
/// @author Steve Ebersole
public class DB2IdentityColumnSupport extends IdentityColumnSupportBase {
	public static final DB2IdentityColumnSupport INSTANCE = new DB2IdentityColumnSupport();

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public boolean supportsInsertSelectIdentity() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int jdbcTypeCode) {
		return "values identity_val_local()";
	}

	@Override
	public String getIdentityColumnString(int jdbcTypeCode) {
		return "generated by default as identity";
	}

	@Override
	public String getIdentityInsertString() {
		return "default";
	}

	@Override
	public String appendIdentitySelectToInsert(String identityColumnName, String insertString) {
		return "select " + identityColumnName + " from final table ( " + insertString + " )";
	}
}
