/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/// Community H2 identity-column profile.
///
/// @author Steve Ebersole
public class H2IdentityColumnSupport extends IdentityColumnSupportBase {
	public static final H2IdentityColumnSupport INSTANCE = new H2IdentityColumnSupport();

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentityColumnString(int jdbcTypeCode) {
		return "generated by default as identity";
	}

	@Override
	public String getIdentitySelectString(String table, String column, int jdbcTypeCode) {
		return "call identity()";
	}

	@Override
	public String getIdentityInsertString() {
		return "default";
	}
}
