/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/// Community HANA identity-column profile.
///
/// @author Steve Ebersole
public final class HANAIdentityColumnSupport extends IdentityColumnSupportBase {
	public static final HANAIdentityColumnSupport INSTANCE = new HANAIdentityColumnSupport();

	private HANAIdentityColumnSupport() {
	}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int jdbcTypeCode) {
		return "select current_identity_value() from " + table;
	}

	@Override
	public String getIdentityColumnString(int jdbcTypeCode) {
		return "generated by default as identity";
	}
}
