/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect.identity.internal;

import org.hibernate.dialect.DatabaseVersion;
import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/// Community HSQLDB identity-column profile.
///
/// @author Steve Ebersole
public final class HSQLIdentityColumnSupport extends IdentityColumnSupportBase {
	private final DatabaseVersion version;

	public HSQLIdentityColumnSupport(DatabaseVersion version) {
		this.version = version;
	}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentityColumnString(int jdbcTypeCode) {
		return "generated by default as identity (start with 1)";
	}

	@Override
	public String getIdentitySelectString(String table, String column, int jdbcTypeCode) {
		return "call identity()";
	}

	@Override
	public String getIdentityInsertString() {
		return version.isBefore( 2 ) ? "null" : "default";
	}
}
