/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;
import org.hibernate.dialect.identity.spi.IdentityValueRetrieval;

/// Community Oracle 12c identity-column profile.
///
/// @author Steve Ebersole
public final class Oracle12cIdentityColumnSupport extends IdentityColumnSupportBase {
	public static final Oracle12cIdentityColumnSupport INSTANCE = new Oracle12cIdentityColumnSupport();

	private Oracle12cIdentityColumnSupport() {
	}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentityColumnString(int jdbcTypeCode) {
		return "generated by default as identity";
	}

	@Override
	public String getIdentityInsertString() {
		return "default";
	}

	@Override
	public IdentityValueRetrieval getIdentityValueRetrieval() {
		return IdentityValueRetrieval.NAMED_GENERATED_KEYS;
	}
}
