/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/// Community PostgreSQL identity-column profile.
///
/// @author Steve Ebersole
public final class PostgreSQLIdentityColumnSupport extends IdentityColumnSupportBase {
	public static final PostgreSQLIdentityColumnSupport INSTANCE = new PostgreSQLIdentityColumnSupport();

	private PostgreSQLIdentityColumnSupport() {
	}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int jdbcTypeCode) {
		return "select currval('" + unquote( table ) + '_' + unquote( column ) + "_seq')";
	}

	@Override
	public String getIdentityColumnString(int jdbcTypeCode) {
		return "generated by default as identity";
	}

	private static String unquote(String name) {
		if ( name == null || name.isEmpty() ) {
			return name;
		}
		final char first = name.charAt( 0 );
		final char last = name.charAt( name.length() - 1 );
		return first == last && ( first == '`' || first == '"' )
				? name.substring( 1, name.length() - 1 )
				: name;
	}
}
