services:
  informix:
    image: ${DB_IMAGE_INFORMIX_14_10:-icr.io/informix/informix-developer-database:14.10.FC9W1DE@sha256:5eb0d519188d1c5d655775343974cec2063244b7a0f60b4e4dda8809ca9b376e}
    container_name: informix
    privileged: true
    ports:
      - "9088:9088"
    environment:
      LICENSE: accept
      GL_USEGLU: "1"
    volumes:
      - ../../informix/onconfig.mod:/opt/ibm/config/onconfig.mod
    healthcheck:
      test: [ "CMD-SHELL", "export INFORMIXDIR=/opt/ibm/informix INFORMIXSERVER=informix PATH=/opt/ibm/informix/bin:$$PATH && echo 'SELECT FIRST 1 tk_id FROM ph_task;' | dbaccess sysadmin > /dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 60
