/**
 * Companion classes ({@code Repo$}) that are generated by other processors for us.
 * Hibernate ORM annotation processor does not provide these, but can work with them.
 * We store the generated companions in this package. These classes contain annotated
 * methods with queries that we can genereate the repositories for (instead of doing
 * some query-by-name guessing).
 */
package ee.jakarta.tck.data;
