CREATE SCHEMA HTT
CREATE SCHEMA OTHERSCHEMA 
CREATE SCHEMA THIRDSCHEMA 
CREATE TABLE HTT.MEMBER ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
CREATE TABLE OTHERSCHEMA.ROLE ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
CREATE TABLE THIRDSCHEMA.MEMBERROLE ( MEMBERID INT NOT NULL, ROLEID INT NOT NULL, PRIMARY KEY(MEMBERID, ROLEID))
ALTER TABLE THIRDSCHEMA.MEMBERROLE ADD CONSTRAINT TOROLES FOREIGN KEY (ROLEID) REFERENCES OTHERSCHEMA.ROLE(ID)
ALTER TABLE THIRDSCHEMA.MEMBERROLE ADD CONSTRAINT TOUSERS FOREIGN KEY (MEMBERID) REFERENCES HTT.MEMBER(ID)
CREATE TABLE HTT.PLAINROLE ( ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY(ID))
CREATE TABLE HTT.PLAINMEMBERROLE ( MEMBERID INT NOT NULL, ROLEID INT NOT NULL, PRIMARY KEY(MEMBERID, ROLEID))
ALTER TABLE HTT.PLAINMEMBERROLE ADD CONSTRAINT PLAINTOROLES FOREIGN KEY (ROLEID) REFERENCES HTT.PLAINROLE(ID)
ALTER TABLE HTT.PLAINMEMBERROLE ADD CONSTRAINT PLAINTOMEMBERS FOREIGN KEY (MEMBERID) REFERENCES HTT.MEMBER(ID)