DROP TABLE HTT.PLAINMEMBERROLE
DROP TABLE HTT.PLAINROLE
DROP TABLE THIRDSCHEMA.MEMBERROLE
DROP TABLE HTT.MEMBER
DROP TABLE OTHERSCHEMA.ROLE
DROP SCHEMA OTHERSCHEMA
DROP SCHEMA THIRDSCHEMA
DROP SCHEMA HTT
