= Active question and todo list for 6.0

== TODO items

* Migrate LoadPlan to SQM/SQL AST
* related (^^) - drop Loader?  Or retrofit it to leverage JdbcSelectExecutor.
* Drop old QueryTranslator and both impls


== Open questions

* Consider managing AttributeConverter at the Attribute-level, as opposed to at the BasicType level.
	See `org.hibernate.persister.common.spi.ConvertibleDomainReference`.
* Move `org.hibernate.secure` to `org.hibernate.resource.jacc`?
* Move `org.hibernate.jmx` to `org.hibernate.resource.jmx`?
* Remove (or just deprecate for now?) org.hibernate.engine.jdbc.cursor.spi.RefCursorSupport.  IIRC we decided to
	baseline ORM 6.0 on Java 8 so no need for the reflection anymore
* Session#stream API - accepts entity to stream, operations on the stream get translated to SQL up until a forEach etc call
* Parameterized ScrollableResults signature - change signature of row access methods or add new row access methods?
* Drop `Query#iterate` support (shallow queries)?
* Drop support for loading an entity by passing the instance to populate ("optional entity instance" et al)?
* Do we want to expose some form of Returns from Query objects as a sort of "result metadata"?  This would play
	the same role that Query returning Type does now (but Type is too limiting hence its removal)
* Consider dropping `org.hibernate.cache.spi.QueryCache` in favor of direct coordination between:
** `org.hibernate.cache.spi.QueryResultsRegion`
** `org.hibernate.cache.spi.UpdateTimestampsCache`
** a new "results validation checker", something like:
+
--
	interface QueryCacheResultsValidator {
		boolean areCachedResultsValid(
				UpdateTimestampsCache timestampsCache,
				Set<Serializable> spaces,
				Long timestamp,
				SharedSessionContractImplementor session);
	}
--
* Redesign Cache SPI as per https://hibernate.atlassian.net/browse/HHH-10707?focusedCommentId=84079&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-84079
	and https://gist.github.com/sebersole/2c9ad6b77ea3477ba508c21c6ab61b8d
* Redesign `org.hibernate.cache.spi.entry.CacheEntryStructure` and friends (with better names) and make more efficient.  At the moment, to cache, we:
.. Create a "cache entry" (object creation)
.. "structure" the "cache entry" (object creation)
.. add "structured data" to the cache.
+
--
Would be more efficient to combine (a) and (b).  Both are controlled by the persister anyway
--