= 5.3 Migration Guide
:toc:

This guide discusses migration from Hibernate ORM version 5.2 to version 5.3.  For migration from
earlier versions, see any other pertinent migration guides as well.

== Background

5.3 represents a JPA 2.2 compatible version on top of 5.2


== Changes to positional query parameter handling

This really breaks down into 2 related changes:

* Support for JDBC-style parameter declarations in HQL/JPQL queries has been removed.  This feature
    has been deprecated since 4.1 and removing it made implementing the second change, so we decided
    to remove that support.  JDBC-style parameter declaration is still supported in native-queries.
* Since JPA positional parameters really behave more like named parameters (they can be repeated,
    declared in any order, etc.) Hibernate used to treat them as named parameters - it relied on
    Hibernate's JPA wrapper to interpret the JPA setParameter calls and properly handle delegating to
    the named variant.  This is actually a regression in 5.2 as it causes
    `javax.persistence.Parameter#getPosition` to report `null`.

For JDBC-style parameter declarations in native queries, we have also moved to using one-based
instead of zero-bade parameter binding to be consistent with JPA.  That can temporarily be
reverted by setting the `hibernate.query.sql.jdbc_style_params_base` setting to `true` which
reverts to expecting zero-based binding.

