= 6.3 Migration Guide
:toc:
:toclevels: 4
:docsBase: https://docs.jboss.org/hibernate/orm
:versionDocBase: {docsBase}/6.3
:userGuideBase: {versionDocBase}/userguide/html_single/Hibernate_User_Guide.html
:javadocsBase: {versionDocBase}/javadocs


This guide discusses migration to Hibernate ORM version 6.3. For migration from
earlier versions, see any other pertinent migration guides as well.

* link:{docsBase}/6.2/migration-guide/migration-guide.html[6.2 Migration guide]
* link:{docsBase}/6.1/migration-guide/migration-guide.html[6.1 Migration guide]
* link:{docsBase}/6.0/migration-guide/migration-guide.html[6.0 Migration guide]

[[data-format-changes]]
== Data format changes

[[data-format-wrapper-byte-array]]
=== Byte[] data format changes

Prior to Hibernate 6.2, a `Byte[]` in the domain model was always just blindly converted to a `byte[]`,
possibly running into a `NullPointerException` if the `Byte[]` contains a `null` array element.

To fix this, a `Byte[]` is now serialized with Java serialization to a `byte[]`, which allows handling nulls better.
This change is necessary to properly support plural basic types where the element type maps to the `Byte` Java type,
i.e. an array or collection of `Enum`.

Since the use of `Byte[]` in a domain model did not make sense so far because null elements were impossible,
it is expected that most domain models were already using `byte[]`, so the breaking change was considered to be ok.

Domain models that really used a `Byte[]` but never stored a `null`, must be migrated to `byte[]` now.

