= 7.0 Migration Guide
:toc:
:toclevels: 4
:docsBase: https://docs.jboss.org/hibernate/orm
:versionDocBase: {docsBase}/7.0
:userGuideBase: {versionDocBase}/userguide/html_single/Hibernate_User_Guide.html
:javadocsBase: {versionDocBase}/javadocs


This guide discusses migration to Hibernate ORM version 7.0. For migration from
earlier versions, see any other pertinent migration guides as well.

[[relicense]]
== Apache License

Starting with 7.0, Hibernate ORM will be licensed under the Apache License 2.0.

NOTE: While the Hibernate team still believes that our long published interpretation of LGPL
to be compatible with ASL and similar licenses, enough FUD has been spread about it to
be considered a lost cause in terms of inclusion in various projects. At this point,
it just makes sense to change - it opens up wider acceptance amongst Apache/Jakarta
projects and others.

Details can be seen at https://hibernate.atlassian.net/browse/HHH-19145.

As part of this effort, the Hibernate team reached out to the authors of
"non-trivial" contributions to request permission to relicense their
work under the Apache License.  The response was overwhelming positive, although
we never heard back from some contributors and another explicitly disagreed.
This required a few actions on our part:

* Dropping `hibernate-envers` - see https://hibernate.atlassian.net/browse/HHH-19150
* Dropping `hibernate-ucp` - see https://hibernate.atlassian.net/browse/HHH-19162
* Dropping `TeradataDialect` - see https://hibernate.atlassian.net/browse/HHH-19057


[[jpa-32]]
== Jakarta Persistence 3.2

7.0 migrates to Jakarta Persistence 3.2 which is fairly disruptive, mainly around:

* Type parameters:
  ** Affects much of the Criteria API - especially roots, joins, paths
  ** Affects much of the Graph API -
    *** `org.hibernate.graph.Graph.addAttributeNode(java.lang.String)` defines a return while
                `jakarta.persistence.Graph.addAttributeNode(java.lang.String)` does not.
* New JPA features colliding with previous Hibernate extension features:
  ** `Nulls` (JPA) v. `NullPrecedence` (Hibernate), including JPA's new `Order#getNullPrecedence()` returning `Nulls`
        colliding with Hibernate's `SqmSortSpecification#getNullPrecedence` returning `NullPrecedence`.  Hibernate's form
        was renamed to `SqmSortSpecification#getHibernateNullPrecedence` to avoid the collision.
  ** `SchemaManager` is now also a JPA contract exposed as `EntityManagerFactory#getSchemaManager` which leads to type issues for
        Hibernate's `SessionFactory#getSchemaManager`.  Hibernate's `SchemaManager` now extends the new JPA `SchemaManager`.
        But that is a bytecode incompatibility.
  ** JPA has added support in its Graph API for things Hibernate has supported for some time.  Some of those are collisions
        requiring changes to the Hibernate API.
  ** `Transaction#getTimeout`.  JPA 3.2 adds `#getTimeout` but uses `Integer` whereas Hibernate has historically used `int`.  Note that this raises the possibility of a `NullPointerException` during migration if, e.g., performing direct comparisons on the timeout value against an in (auto unboxing).

See this https://in.relation.to/2024/04/01/jakarta-persistence-3/[blog post] for a good discussion of the changes in Jakarta Persistence 3.2.


[[NamedEntityGraph]]
== @NamedEntityGraph

A new annotation (`@org.hibernate.annotations.NamedEntityGraph`) has been added to allow
specifying a named entity-graph using Hibernate's ability to parse a string representation of the graph.


[source,java]
----
@Entity
@NamedEntityGraph( graph="title, isbn, author( name, phoneNumber )" )
class Book {
	// ...
}
----


See `org.hibernate.graph.GraphParser` for details on the syntax and the
link:{user-guide-url}#fetching-strategies-dynamic-fetching-entity-graph-parsing-annotation[user guide] for additional details.



[[hibernate-models]]
== Hibernate Models

For many years Hibernate has used the Hibernate Commons Annotations (HCANN) library for handling various low-level tasks
related to understanding the structure of an application domain model, reading annotations and weaving in XML
mapping documents.

However, HCANN suffers from a number of limitations that continued to be problematic.  And given
the use of HCANN across multiple projects, doing the needed refactoring was simply not possible.

The https://github.com/hibernate/hibernate-models[Hibernate Models] project was developed to be a better alternative
to HCANN.  Hibernate Models is essentially an abstraction over reflection (`Type`, `Class`, `Member`, ...) and
annotations.  Check out its project page for complete details.

7.0 uses Hibernate Models in place of HCANN.


[[model-validation]]
== Domain Model Validations

7.0 adds many more checks about illegal use of annotations.

[[PersistentAttributeType]]
=== PersistentAttributeType

As of 7.0, Hibernate applies much better validation of an attribute specifying multiple PersistentAttributeTypes.
Jakarta Persistence 3.2 has clarified this in the specification.  E.g., the following examples are all now illegal -

[source,java]
----
@Basic
@ManyToOne
private Employee manager;
----

or

[source,java]
----
@Lob
@ManyToOne
private Employee manager;
----


[[misplaced-annotations]]
=== Misplaced Annotations

7.0 does much more in-depth checking that annotations appear in the proper place.  While previous versions
did not necessarily throw errors, in most cases these annotations were simply ignored.

For example, this code now results in an error:

[source,java]
----
@Entity
class Book {
    // specifies FIELD access, properties should not be annotated
    @Id
    Integer id;

    // previously ignored, this is an error now
    @Column(name="category")
    String getType() { ... }
}
----

[[id-generators]]
=== Identifier Generators

Starting in 7.0 it is no longer valid to combine `GenerationType#SEQUENCE` with anything other than
`@SequenceGenerator` nor `GenerationType#TABLE` with anything other than `@TableGenerator`.  Previous
versions did not validate this particularly well.


[[java-beans]]
=== JavaBean Conventions

Previous versions allowed some questionable (at best) attribute naming patterns.
For example, this property declaration is no longer allowed:

[source,java]
----
@Basic
String isDefault();
----

[[soft-delete-timestamp]]
== @SoftDelete with TIMESTAMP

Soft-delete now supports the strategy of tracking the timestamp at which the soft-delete occurred,
in addition to the previous truth-based strategies.
See the link:{user-guide-url}#soft-delete[User Guide] for details.


[[embedded-column-naming]]
== @EmbeddedColumnNaming

A long requested feature for both Hibernate and Jakarta Persistence has been the ability to
define a prefix for the names of columns associated with an embedded value.

7.0 adds support for this using the new `@EmbeddedColumnNaming` annotation.  The annotation
accepts a format pattern, so is a little more flexible than just a prefix.

Consider a typical Person / Address composition:

[source,java]
----
@Embeddable
class Address {
    String street;
	String city;
	...
}

@Entity
class Person {
	...

    @Embedded
    @EmbeddedColumnNaming("home_%")
    Address homeAddress;

    @Embedded
    @EmbeddedColumnNaming("work_%")
    Address workAddress;

}
----

This triggers Hibernate to use the column names `home_street`, `home_city`, `work_street`, ...


[[create-query]]
== Queries with implicit `select` list and no explicit result type

In previous versions, Hibernate allowed a query with no `select` list to be passed to the overload of `createQuery()` with no explicit result type parameter, for example:

[source,java]
List query =
        session.createQuery("from X, Y")
                .getResultList()

or:

[source,java]
List query =
        session.createQuery("from X join y")
                .getResultList()

The select list was inferred based on the `from` clause.

In Hibernate 6 we decided to deprecate this overload of `createQuery()`, since:

- it returns a raw type, resulting in compiler warnings in client code, and
- the second query is truly ambiguous, with no obviously intuitive interpretation.

As of Hibernate 7, the method is remains deprecated, and potentially-ambiguous queries _are no longer accepted_.
Migration paths include:

1. explicitly specify the `select` list,
2. add `X.class` or `Object[].class` as a second argument, to disambiguate the interpretation of the query, or
3. in the case where the query should return exactly one entity, explicitly assign the alias `this` to that entity.

For example, the queries above may be migrated via:

[source,java]
List<Object[]> result =
        session.createQuery("from X, Y", Object[].class)
                .getResultList()

or:

[source,java]
List<X> result =
        session.createQuery("from X join y", X.class)
                .getResultList()


[[proxy-annotation]]
== Replace `@Proxy`

Applications will need to replace usages of the removed `@Proxy` annotation.

`@Proxy#proxyClass` has no direct replacement, but was also never needed/useful.

Here we focus on `@Proxy#lazy` attribute which, again, was hardly ever useful.
By default (true), Hibernate would proxy an entity when possible and when asked for.
"Asked for" includes calls to `Session#getReference` and lazy associations.
All such cases though are already controllable by the application.

* Instead of `Session#getReference`, use `Session#find`
* Use eager association fetching, for example,
** `FetchType.EAGER` (the default for to-one associations anyway), possibly combined with `@Fetch`,
** `EntityGraph`, or a
** `@FetchProfile`.

The effect can also often be mitigated using Hibernate's bytecode-based laziness (possibly combined with `@ConcreteProxy`).


[[flush-persist]]
== Session flush and persist

The removal of `CascadeType.SAVE_UPDATE` slightly changes the persist and flush behaviour to conform with Jakarta Persistence.

Persisting a transient entity or flushing a manged entity with an associated detached entity having the association annotated with `cascade = CascadeType.ALL` or `cascade = CascadeType.PERSIST` throws now an `jakarta.persistence.EntityExistsException` if the detached entity has not been re-associated with the Session.

To re-associate the detached entity with the Session the `Session#merge` method can be used.

Consider the following model

[source,java]
----
@Entity
class Parent {
	...

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "parent", orphanRemoval = true)
	@LazyCollection(value = LazyCollectionOption.EXTRA)
	private Set<Child> children = new HashSet<>();

	public void addChild(Child child) {
		children.add( child );
		child.setParent( this );
	}
}

@Entity
class Child {
	...

	@ManyToOne
	private Parent parent;
}
----

Assuming we have `c1` as a detached `Child`, the following code will now result in `jakarta.persistence.EntityExistsException` being thrown at flush time:

[source,java]
----
Parent parent = session.get( Parent.class, parentId );
parent.addChild( c1 );
----

Instead, `c1` must first be re-associated with the Session using merge:


[source,java]
----
Parent parent = session.get( Parent.class, parentId );
Child merged = session.merge( c1 );
parent.addChild( merged );
----


[[refresh-lock-deteached]]
== Refreshing/locking detached entities

Traditionally, Hibernate allowed detached entities to be refreshed. However, Jakarta Persistence prohibits this practice and specifies that an `IllegalArgumentException` should be thrown instead. Hibernate now fully aligns with the JPA specification in this regard.

Along the same line of thought, also acquiring a lock on a detached entity is no longer allowed.

To this effect the `hibernate.allow_refresh_detached_entity`, which allowed Hibernate's legacy refresh behaviour to be invoked, has been removed.


[[auto-cascade-persist]]
== Cascading persistence for `@Id` and `@MapsId` fields

Previously Hibernate automatically enabled `cascade=PERSIST` for association fields annotated `@Id` or `@MapsId`.
This was undocumented and unexpected behavior, and arguably against the intent of the Persistence specification.

Existing code which relies on this behavior should be modified by addition of explicit `cascade=PERSIST` to the association field.


[[enum-checks]]
== Enums and Check Constraints

Hibernate previously added support for generating check constraints for enums mapped using `@Enumerated`
as part of schema generation.  7.0 adds the same capability for enums mapped using an `AttributeConverter`,
by asking the converter to convert all the enum constants on start up.

[[datetime-native]]
== Date and time types returned by native queries

In the absence of a `@SqlResultSetMapping`, previous versions of Hibernate used `java.sql` types (`Date`, `Time`, `Timestamp`) to represent date/time types returned by a native query.
In 7.0, such queries return types defined by `java.time` (`LocalDate`, `LocalTime`, `LocalDateTime`) by default.
The previous behavior may be recovered by setting `hibernate.query.native.prefer_jdbc_datetime_types` to `true`.


[[ddl-implicit-datatype-timestamp]]
== Default precision for `timestamp` on some databases

The default precision for Oracle timestamps was changed to 9, i.e. nanosecond precision.
The default precision for SQL Server timestamps was changed to 7, i.e. 100 nanosecond precision.

Note that these changes only affect DDL generation.

[[array-mapping-changes-on-db2-sap-hana-sql-server-and-sybase-ase]]
== Array mapping changes on DB2, SAP HANA, SQL Server and Sybase ASE

On DB2, SAP HANA, SQL Server and Sybase ASE, basic arrays now map to the `SqlTypes.XML_ARRAY` type code,
whereas previously, the dialect mapped arrays to `SqlTypes.VARBINARY`.
The `SqlTypes.XML_ARRAY` type uses the `xml` DDL type which enables using arrays in other features through the various XML functions.

The migration requires to read data and re-save it. Note that XML support on Sybase ASE is not enabled by default
and requires to run `sp_configure 'enable xml', 1`.

To retain backwards compatibility, configure the setting `hibernate.type.preferred_array_jdbc_type` to `VARBINARY`.

[[array-mapping-changes-on-mysql-mariadb]]
== Array mapping changes on MySQL/MariaDB

On MySQL and MariaDB, basic arrays now map to the `SqlTypes.JSON_ARRAY` type code,
whereas previously, the dialect mapped arrays to `SqlTypes.VARBINARY`.
The `SqlTypes.JSON_ARRAY` type uses the `json` DDL type which enables using arrays in other features through the various JSON functions.

The migration requires to read data and re-save it.

To retain backwards compatibility, configure the setting `hibernate.type.preferred_array_jdbc_type` to `VARBINARY`.

[[xml-format-mapper-changes]]
== XML `FormatMapper` changes

Previous versions of Hibernate ORM used an undefined/provider-specific format for serialization/deserialization of
collections, maps and byte arrays to/from XML, which was not portable.

XML `FormatMapper` implementations now use a portable format for collections, maps, and byte arrays.
This change is necessary to allow mapping basic arrays as `SqlTypes.XML_ARRAY`.

The migration requires to read data and re-save it.

To retain backwards compatibility, configure the setting `hibernate.type.xml_format_mapper.legacy_format` to `true`.

[[sf-name]]
== SessionFactory Name (and JNDI)

Hibernate defines `SessionFactory#getName` (specified via `cfg.xml` or  `hibernate.session_factory_name`) which is used to
help with (de)serializing a `SessionFactory`.  It is also, unless `hibernate.session_factory_name_is_jndi` is set to `false`,
used in biding the `SessionFactory` into JNDI.

This `SessionFactory#getName` method pre-dates Jakarta Persistence (and JPA).  It now implements `EntityManagerFactory#getName`
inherited from Jakarta Persistence, which states that this name should come from the persistence-unit name.
To align with Jakarta Persistence (the 3.2 TCK tests this), Hibernate now considers the persistence-unit name if no
`hibernate.session_factory_name` is specified.

However, because `hibernate.session_factory_name` is also a trigger to attempt to bind the SessionFactory into JNDI,
this change to consider persistence-unit name, means that each `SessionFactory` created through Jakarta Persistence now
has a name and Hibernate attempts to bind it to JNDI.

To work around this we have introduced a new `hibernate.session_factory_jndi_name` setting that can be used to explicitly
specify a name for JNDI binding.  The new behavior is as follows (assuming `hibernate.session_factory_name_is_jndi` is not explicitly configured):

* If `hibernate.session_factory_jndi_name` is specified, the name is used to bind into JNDI
* If `hibernate.session_factory_name` is specified, the name is used to bind into JNDI

Hibernate can use the persistence-unit name for binding into JNDI as well, but `hibernate.session_factory_name_is_jndi`
must be explicitly set to true.

[[configurable-generators]]
== Configurable generators

The signature of the `Configurable#configure` method changed from accepting just a `ServiceRegistry` instance to the new `GeneratorCreationContext` interface, which exposes a lot more useful information when configuring the generator itself. The old signature has been deprecated for removal, so you should migrate any custom `Configurable` generator implementation to the new one.

[[stateless-session-cache]]
== `StatelessSession` and second-level cache

Previously, stateless sessions never interacted with the second-level cache.
This reflected their original intended role in bulk processing.
With the advent of Jakarta Data and Hibernate Data Repositories, the responsibilities of `StatelessSession` have now expanded, and this behavior is no longer appropriate.

Thus, a stateless session now makes use of the second-level cache by default.
To completely bypass the second-level cache, recovering the previous behavior, call `setCacheMode(CacheMode.IGNORE)`.

It's often important to explicitly disable puts to the second-level cache in code which performs bulk processing.
Set the cache mode to `GET` or configure `jakarta.persistence.cache.storeMode` to `BYPASS`.

[[stateless-session-jdbc-batching]]
== JDBC batching with `StatelessSession`

Automatic JDBC batching has the side effect of delaying the execution of the batched operation, and this undermines the synchronous nature of operations performed through a stateless session.
In Hibernate 7, the configuration property `hibernate.jdbc.batch_size` now has no effect on a stateless session.
Automatic batching may be enabled by explicitly calling `setJdbcBatchSize()`.
However, the preferred approach is to explicitly batch operations via `insertMultiple()`, `updateMultiple()`, or `deleteMultiple()`.

[[criteria-implicit-treat]]
== Criteria API and inheritance subtypes attributes

It was previously possible to use the string version of the `jakarta.persistence.criteria.Path#get` and `jakarta.persistence.criteria.From#join` methods with names of attributes defined in an inheritance subtype of the type represented by the path expression. This was handled internally by implicitly treating the path as the subtype which defines said attribute. Since Hibernate 7.0, aligning with the JPA specification, the Criteria API will no longer allow retrieving subtype attributes this way, and it's going to require an explicit `jakarta.persistence.criteria.CriteriaBuilder#treat` to be called on the path first to downcast it to the subtype which defines the attribute.

Implicit treats are still going to be applied when an HQL query dereferences a path belonging to an inheritance subtype.

[[hbm-transform]]
== hbm.xml Transformation

Hibernate's legacy `hbm.xml` mapping schema has been deprecated for quite some time, replaced by a new `mapping.xml`
schema.  In 7.0, this `mapping.xml` is stabilized and we now offer a transformation of `hbm.xml` files into `mapping.xml` files.

This tool is available as both -

* build-time transformation (currently only offered as a Gradle plugin)
* run-time transformation, using `hibernate.transform_hbm_xml.enabled=true`

Build-time transformation is preferred.

[NOTE]
====
Initial versions of the transformation processed one file at a time.
This is now done across the entire set of `hbm.xml` files at once.
While most users will never see this change, it might impact integrations which tie-in to XML processing.
====

[[mysql-varchar]]
== Default DDL type for `char` and `Character` on MySQL

Previously, `char` and `Character` fields were, by default, mapped to `char(1)` columns by the schema export tool.
However, MySQL treats a `char(1)` containing a single space as an empty string, resulting in broken behavior for some HQL and SQL functions.
Now, `varchar(1)` is used by default.

[[unowned-order-column]]
== `@OrderColumn` in unowned `@OneToMany` associations

In an unowned (`mappedBy`) one-to-many association, an `@OrderColumn` should, in principle, also be mapped by a field of the associated entity, and the value of the order column should be determined by the value of this field, not by the position in the list.

Previously, since version 4.1, https://hibernate.atlassian.net/issues/HHH-18830[Hibernate would issue superfluous SQL `UPDATE` statements] to set the value of the order column based on the state of the unowned collection.
This was incorrect according to the JPA specification, and inconsistent with the natural semantics of Hibernate.

In Hibernate 7, these SQL `UPDATE` statements only occur if the `@OrderColumn` is _not_ also mapped by a field of the entity.

[[pools]]
== Connection pools

Since Vibur and Proxool are no longer actively developed, support for these connection pools was removed.
Use Agroal or HikariCP instead.

== Converters incompatible with annotations

JPA ``AttributeConverter``s are incompatible with the annotations `@Id`, `@Version`, `@Enumerated`, `@Embedded`, `@Temporal` and all association-mapping annotations.
Previously, any converter applied to an attribute with an incompatible annotation was simply ignored.
Hibernate now reports an error in this situation.

This includes auto-applied converters.
To suppress the error for an auto-applied converter, use `@Convert(disableConversion=true)`.

== `org.hibernate.graph` package

The `EntityGraph` API was enhanced in JPA 3.2, and made much more useful.
The incubating package `org.hibernate.graph` contains extensions to that API, which have been significantly impacted by the migration to JPA 3.2, and by the additional of new functionality.
Furthermore, some legacy operations were declared with incorrect generic type signatures (by both JPA, and by Hibernate).

This package has been significantly re-engineered, and the impact of this effort includes:

- some breaking changes to type signatures, and
- a number of deprecations of legacy operations which are now covered by JPA.

Also, a key subgraph now always refers to a `Map` key, and never to an entity id.

We encourage migration to the use of the new JPA-standard operations.

[[validator-integration-validation-mode]]
== Behaviour change for `ValidationMode.AUTO`

Hibernate ORM will not silently ignore issues with the `ValidatorFactory` configuration anymore when an auto validation mode is chosen.
In the past, with `ValidationMode.AUTO` enabled, Hibernate ORM would translate the validation mode to `ValidationMode.NONE`,
either when there were no providers available or when a provider was available,
but creating an instance of the validator factory resulted in an exception.
From now on, `ValidationMode.AUTO` will only be translated to `ValidationMode.NONE` when there are no validation providers available,
and in the case when the validation provider is available and an exception is encountered while creating an instance of the `ValidatorFactory`
this exception will be propagated to the user.

== Deprecations

* `@Comment` is deprecated in favor of the JPA 3.2 `comment` members
* `@Comment` is deprecated in favor of the JPA 3.2 `@CheckConstraint` and `check` members
* `NullPrecedence` is deprecated in favor of JPA 3.2 `Nulls`
* `@FractionalSeconds` is deprecated in favor of JPA 3.2 `secondPrecision`
* `DynamicParameterizedType` is deprecated
* `Session.get()` is deprecated in favor of `find()`
* `@Cascade` and `org.hibernate.annotations.CascadeType` are deprecated in favor of JPA `cascade` and `CascadeType`
* `org.hibernate.annotations.FlushModeType` is deprecated in favor of `QueryFlushMode`

[[cleanup]]
== Cleanup

* Annotations
** Removed `@Persister`
** Removed `@Proxy` -- see <<proxy-annotation>>
** Removed `@SelectBeforeUpdate`
** Removed `@DynamicInsert#value` and `@DynamicUpdate#value`
** Removed `@Loader`
** Removed `@Table` -> use JPA `@Table`
** Removed `@Where` and `@WhereJoinTable` -> use `@SQLRestriction` or `@SQLJoinTableRestriction`
** Removed `@OrderBy` -> use `@SQLOrder` or JPA `@OrderBy`
** Removed `@ForeignKey` -> use JPA `@ForeignKey`
** Removed `@Index` -> use JPA `@Index`
** Removed `@IndexColumn` -> use JPA `@OrderColumn`
** Removed `@GeneratorType` (and `GenerationTime`, etc)
** Removed `@LazyToOne`
** Removed `@LazyCollection`
** Replaced uses of `CacheModeType` with `CacheMode`
** Removed `@TestForIssue` (for testing purposes) -> use `org.hibernate.testing.orm.junit.JiraKey` and `org.hibernate.testing.orm.junit.JiraKeyGroup`
** Removed `@Cache.include` -> use `@Cache.includeLazy`

* Classes/interfaces
** Removed `SqmQualifiedJoin` (all joins are qualified)
** Removed `AdditionalJaxbMappingProducer` -> `AdditionalMappingContributor`
** Removed `MetadataContributor` -> `AdditionalMappingContributor`
** Removed `EmptyInterceptor` -> implement `org.hibernate.Interceptor` directly
** Removed `Session.LockRequest` -> use `LockOptions`

* Behavior
** Removed `Session.save` in favor of `Session.persist`
** Removed `Session.saveOrUpdate` in favor `persist` if the entity is transient or `merge` if the entity is detached
** Removed `Session.update` in favor of `Session.merge`
** Removed `org.hibernate.annotations.CascadeType.SAVE_UPDATE` in favor of `org.hibernate.annotations.CascadeType.PERSIST` + `org.hibernate.annotations.CascadeType.MERGE`
** Removed `Session.delete` in favor of `Session.remove`
** Removed `Session.load` in favor of `Session.find`
** Removed `org.hibernate.annotations.CascadeType.DELETE` in favor of `org.hibernate.annotations.CascadeType.REMOVE`
** Removed `Session.refresh(String entityName, Object object)` in favor of `Session.refresh(Object object)`
** Removed `Session.refresh(String entityName, Object object, LockOptions lockOptions)` in favor of `Session.refresh(Object object, LockOptions lockOptions)`
** Removed `org.hibernate.integrator.spi.Integrator.integrate(Metadata,SessionFactoryImplementor,SessionFactoryServiceRegistry)` in favor of `org.hibernate.integrator.spi.Integrator.integrate(Metadata,BootstrapContext,SessionFactoryImplementor)`
** Removed `Interceptor.onLoad(Object, Serializable, Object[] , String[] , Type[] )` in favour of `Interceptor.onLoad(Object, Object, Object[], String[], Type[] )`
** Removed `Interceptor.onFlushDirty(Object, Serializable, Object[] , Object[], String[] , Type[] )` in favour of `Interceptor.onLoad(Object, Object, Object[], Object[], String[] , Type[] )`
** Removed `Interceptor.onSave(Object, Serializable, Object[], String[], Type[])` in favour of `Interceptor.onSave(Object, Object, Object[], String[], Type[])`
** Removed `Interceptor.onDelete(Object, Serializable, Object[], String[], Type[])` in favour of `Interceptor.onDelete(Object, Serializable, Object[], String[], Type[])`
** Removed `Interceptor.onCollectionRecreate(Object, Serializable)` in favour of `Interceptor.onCollectionRecreate(Object, Object)`
** Removed `Interceptor.onCollectionRemove(Object, Serializable)` in favour of `Interceptor.onCollectionRemove(Object, Object)`
** Removed `Interceptor.onCollectionUpdate(Object, Serializable)` in favour of `Interceptor.onCollectionUpdate(Object, Object)`
** Removed `Interceptor.findDirty(Object, Serializable, Object[], Object[], String[], Type[])` in favour of `Interceptor.findDirty(Object, Object, Object[], Object[], String[], Type[])`
** Removed `Interceptor.getEntity(String, Serializable)` in favour of `Interceptor.getEntity(String, Serializable)`
** Removed `org.hibernate.metamodel.spi.MetamodelImplementor` in favor of `org.hibernate.metamodela.MappingMetmodel` or `org.hibernate.metamodel.model.domain.JpaMetamodel`
** Removed `org.hibernate.Metamodel` in favor of `org.hibernate.metamodel.model.domain.JpaMetamodel`
** Removed `NaturalIdLoadAccess.using(Map)` and `NaturalIdMultiLoadAccess.compoundValue()` in favor of `Map.of()`

* Settings
** Removed `hibernate.mapping.precedence` and friends
** Removed `hibernate.allow_refresh_detached_entity`


[[reorg]]
== Reorganize Packages (for api/spi/internal, etc)

* Reorganized the `org.hibernate.query.results` package


[[todo]]
== Todos (dev)

* Look for `todo (jpa 3.2)` comments
* Look for `todo (7.0)` comments
