= {version} Migration Guide
:toc2:
:sectanchors:
:toclevels: 4
:version: 8.0
:docsBase: https://docs.jboss.org/hibernate/orm
:versionDocBase: {docsBase}/{version}
:userGuideBase: {versionDocBase}/userguide/html_single/Hibernate_User_Guide.html
:whatsNewBase: {versionDocBase}/whats-new/whats-new.html
:javadocsBase: {versionDocBase}/javadocs
:releaseSeriesBase: https://hibernate.org/orm/releases/{version}/

This guide discusses migration to Hibernate ORM version {version}. For migration from
earlier versions, see any other pertinent migration guides as well.

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Requirements
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[requirements]]
== Requirements

See the link:{releaseSeriesBase}[website] for the list of requirements for the {version} series.


[[jpa4]
=== Jakarta Persistence 4.0

One specific requirement change that is important to call out is the move to from Jakarta Persistence version 3.2 to 4.0 which has a number of impacts, many of which are discussed below.



// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// New Features
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[new-features]]
== New Features

See the link:{releaseSeriesBase}#whats-new[website] for the list of new features in the {version} series.


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// API changes
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[api-changes]]
== Changes to API

This section describes changes to contracts (classes, interfaces, methods, etc.) which are considered https://hibernate.org/community/compatibility-policy/#api[API].


[[stateless]
=== StatelessSession

Jakarta Persistence now defines a contract for "stateless" processing, named `EntityAgent`, similar to Hibernate's `StatelessSession`.
Hibernate's `StatelessSession` now implements `EntityAgent`.
2 methods on `EntityAgent` clash with methods already defined on `StatelessSession` -

* `insert()` - `EntityAgent` defines a `void` return type, whereas Hibernate has historically returned the identifier of the inserted entity.
* `fetch()` - `EntityAgent` defines that the fetched value be returned, whereas `StatelessSession` has historically defined a `void` return type.

In both cases, `StatelessSession` has been changed to match the `EntityAgent` signatures.


[[timeout]
=== Query and Transaction Timeouts

Historically, both Hibernate and Jakarta Persistence have defined timeouts as integer values.
Confusingly, Hibernate generally used second precision while Jakarta Persistence used millisecond precision.
Starting in 3.2, Jakarta Persistence added a new `Timeout` class which helps alleviate this potential confusion.
Originally this new `Timeout` type was not exposed on any API directly, so there was no impact from an API perspective.
However, this has changed a bit in 4.0 where `Timeout` *is* now exposed on certain APIs.
This causes a signature conflict with a few of Hibernate API methods; as part of fixing those conflicts, it was decided to change all exposures of timeout in Hibernate APIs to use `Timeout` as this helps clarify these confusions.


[[graph-attr-node]
=== AttributeNode Subgraphs

As part of its support for "entity graphs", Hibernate's `org.hibernate.graph.AttributeNode` contract extends fropm the Jakarta Persistence `jakarta.persistence.AttributeNode`.
Starting in version 4.0, Jakarta Persistence has "fixed" the use of raw types for the `AttributeNode#getSubgraphs` and `AttributeNode#getKeySubgraphs` methods.
Hibernate has therefore needed to do the same in its `org.hibernate.graph.AttributeNode`.


[[criteria-join-fetch]
=== Join and Fetch in Criteria

Jakarta Persistence has changed/fixed the type signature of methods in the Criteria API which return Join and Fetch based on the String name of attributes.  This can lead to compilation issues if an application uses these methods in certain ways.



// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// SPI changes
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[spi-changes]]
== Changes to SPI

This section describes changes to contracts (classes, interfaces, methods, etc.) which are considered https://hibernate.org/community/compatibility-policy/#spi[SPI].

=== Classmate removal

The dependency on Classmate was removed, which had a minor impact on certain SPIs.
In particular, `ClassmateContext` was completely removed.

=== Raw types in JPA `Bootstrap`

Raw `Map` types were eliminated from the signatures of methods of the class
`org.hibernate.jpa.boot.spi.Bootstrap`.

[[query-memento]
=== Query Memento

Hibernate uses a number of implementations of its `NamedQueryMemento` contract to
model "named queries".  Starting in version 3.2, Jakarta Persistence added the
`TypedQueryReference` contract intended to serve the much the same goal.
Hibernate's `NamedQueryMemento` implementations were changed to extend from
`TypedQueryReference`.

In version 4.0, Jakarta Persistence has added some additional methods to
`TypedQueryReference` which now conflict with some of Hibernate's existing methods
requiring a rename.  Notably, the addition of `TypedQueryReference#getParameterTypes`
caused conflict's with Hibernate's `NamedSqmQueryMemento#getParameterTypes`.  To
address this conflict, we've renamed the `NamedSqmQueryMemento` method to
`#getAnticipatedParameterTypes`.


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Changes in Behavior
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[behavior-changes]]
== Changes in Behavior

This section describes changes in behavior that applications should be aware of.

=== Collections belonging to read-only entities

Previously, collections belonging to an entity loaded in read-only mode were not
marked as read-only and could be modified. This behavior was surprising and
significantly undermined the benefits of the read-only mode. A collection is now
set to read-only when its owning entity is read-only, and modifications to the
collection result in an error.

=== Result deduplication

In Hibernate 6.x query result lists with duplicate results were handled in an
ad hoc and inconsistent way by `getSingleResult()` and `getSingleResultOrNull()`.
As of Hibernate 7.3, these methods _always_ throw when the result list contains
more than one element (which is faithful to the documented semantics of these
methods). If automatic deduplication is required, use:

[source,java]
query.setResultListTransformer(ResultListTransformer.uniqueResultTransformer())

which collapses duplicate results according to value equality.

[[session-get]
=== Session.get

Jakarta Persistence now defines a series of overloaded `EntityHandler.get()` methods as corollaries to `EntityHandler.find()`.
These methods are defined to throw an `EntityNotFoundException` rather than return null.
This operates quite differently from the older Hibernate `Session.get()` methods which

* still returned null if no entity with that is was found
* force initialized the entity, if there was one and it was previously uninitialized.

Applications which use(d) `Session.get()` should be aware of this change in behavior.


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// XSD changes
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[behavior-changes]]
== Changes in XSD

This section describes changes in XML Schema Descriptors

[[xsd-comments]
=== Table and Column Comments

Previous versions of the `mapping.xsd` defined table and column comments (for schema export)
using XSD attributes.  This was a decision made at the time to facilitate users migrating
from `hbm.xml` mapping format.  In the intervening period, Jakarta Persistence has
also added comments to its table and column XSD types, but using dedicated element.

We now align with the Jakarta Persistence approach of using elements.  This will require
changes any `mapping.xml` documents which define table or column comments.  E.g.,

[source,xml]
----
<entity ...>
    <table ... comment="some comment"/>
</entity>
----

would need to be changed to

[source,xml]
----
<entity ...>
    <table>
         <comment>some comment</comment>
    </table>
</entity>
----



=== Migration of Spanner PostgreSQL Dialect to core

The `SpannerPostgreSQLDialect`, which was previously part of the `hibernate-community-dialects` artifact under the package name `org.hibernate.community.dialect`, has been migrated to the `hibernate-core` artifact and package name `org.hibernate.dialect`.

Users currently using the community dialect must update their dialect configuration to use `org.hibernate.dialect.SpannerPostgreSQLDialect` (or rely on Hibernate's automatic dialect resolution).

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// DDL changes
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[ddl-changes]]
== Changes to DDL generation

This section describes changes to DDL generated by the schema export tooling.
Such changes typically do not impact programs using a relational schema managed externally to Hibernate.


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Dependency changes
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[envers-migration]]
== Optional: Migrating from Hibernate Envers to core `@Audited`

NOTE: This migration is entirely optional. Hibernate Envers continues to work as before in {version}. However, if you wish to take advantage of the new core `@Audited` functionality, this section describes the steps involved.

The new core audit support provides very similar functionality to Envers with a simpler programming model: you can use standard `Session` APIs (and even HQL queries!) within a temporal session opened via `atChangeset()`, or the more specialized `AuditLog` functionality, to access the audit logs of your entities.

=== Annotation changes

[cols="2,3"]
|===
| Envers | Core

| `@org.hibernate.envers.Audited`
| `@org.hibernate.annotations.Audited`

| `@org.hibernate.envers.NotAudited`
| `@org.hibernate.annotations.Audited.Excluded`

| `@org.hibernate.envers.RevisionEntity`
| `@org.hibernate.annotations.Changelog`

| `@org.hibernate.envers.RevisionNumber`
| `@org.hibernate.annotations.Changelog.ChangesetId`

| `@org.hibernate.envers.RevisionTimestamp`
| `@org.hibernate.annotations.Changelog.Timestamp`

| `RevisionListener`
| `org.hibernate.audit.ChangesetListener` (method: `newChangeset()`)

| `EntityTrackingRevisionListener`
| `org.hibernate.audit.EntityTrackingChangesetListener`
|===

=== Map your REVINFO table

Define a `@Changelog` entity that maps to the existing `REVINFO` table (or use the built-in `DefaultChangelog`):

[source,java]
----
@Entity
@Table(name = "REVINFO")
@Changelog(listener = MyChangesetListener.class)
public class MyRevision extends ChangelogMapping { ... }
----

=== API changes

[cols="2,3"]
|===
| Envers | Core

| `AuditReader.find(Foo.class, id, rev)`
| `auditLog.find(Foo.class, id, rev)` or `sf.withOptions().atChangeset(rev).openSession().find(Foo.class, id)`

| `reader.getRevisions(Foo.class, id)`
| `auditLog.getChangesets(Foo.class, id)`

| `reader.getRevisionDate(rev)`
| `auditLog.getChangesetTimestamp(rev)`

| `reader.findRevision(RevInfo.class, rev)`
| `auditLog.findChangeset(RevInfo.class, rev)`

| `reader.createQuery().forEntitiesAtRevision(...)`
| HQL in `atChangeset()` session

| `reader.createQuery().forRevisionsOfEntity(...)`
| `auditLog.getHistory(Foo.class, id)`

| Custom `AuditQuery` criteria
| HQL with `changesetId()` / `modificationType()` functions
|===

=== Schema compatibility

No DDL changes are needed. The default `REV`/`REVTYPE` column names and encoding match between Envers and core. The `REVINFO` table rows continue the same sequence.


[[dependency-changes]]
== Changes in Dependencies

This section describes changes to dependencies used by Hibernate ORM.

