== Hibernate ORM

image:https://img.shields.io/maven-central/v/org.hibernate.orm/hibernate-core.svg?label=Maven%20Central&style=for-the-badge[Maven Central,link=https://central.sonatype.com/search?namespace=org.hibernate.orm&sort=name]
image:https://img.shields.io/jenkins/build?jobUrl=https%3A%2F%2Fci.hibernate.org%2Fjob%2Fhibernate-orm-pipeline%2Fjob%2Fmain%2F&style=for-the-badge[Build Status,link=https://ci.hibernate.org/job/hibernate-orm-pipeline/job/main/]
image:https://img.shields.io/badge/Revved%20up%20by-Develocity-06A0CE?style=for-the-badge&logo=gradle[Develocity,link=https://develocity.commonhaus.dev/scans?search.rootProjectNames=Hibernate%20ORM]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/jvm-repo-rebuild/reproducible-central/master/content/org/hibernate/orm/hibernate-core/badge.json&style=for-the-badge[Reproducible Builds,link=https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/hibernate/orm/hibernate-core/README.md]
image:https://testpilot.oracle.com/ords/testpilot/badges/github/hibernate/hibernate-orm[Oracle Test Pilot,link=https://testpilot.oracle.com/]

Hibernate ORM is a powerful object/relational mapping solution for Java, and makes it easy to develop persistence logic for applications, libraries, and frameworks.

Hibernate implements JPA, the standard API for object/relational persistence in Java, but also offers an extensive set of features and APIs which go beyond the specification.

See https://hibernate.org/orm/[Hibernate.org] for more information.

== Continuous Integration

See link:MAINTAINERS.md#ci[MAINTAINERS.md] for information about CI.

== Building from sources

The build requires at least JDK 25, and produces Java 17 bytecode.

Hibernate uses https://gradle.org[Gradle] as its build tool. See the _Gradle Primer_ section below if you are new to
Gradle.

Contributors should read the link:CONTRIBUTING.md[Contributing Guide].

See the guides for setting up https://hibernate.org/community/contribute/intellij-idea/[IntelliJ] or
https://hibernate.org/community/contribute/eclipse-ide/[Eclipse] as your development environment.

== Gradle Primer

The Gradle build tool has amazing documentation.  2 in particular that are indispensable:

* https://docs.gradle.org/current/userguide/userguide_single.html[Gradle User Guide] is a typical user guide in that
it follows a topical approach to describing all of the capabilities of Gradle.
* https://docs.gradle.org/current/dsl/index.html[Gradle DSL Guide] is unique and excellent in quickly
getting up to speed on certain aspects of Gradle.

We will cover the basics developers and contributors new to Gradle need to know to get productive quickly.

NOTE: The project defines a https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle Wrapper].
The rest of the section will assume execution through the wrapper.

=== Executing Tasks

Gradle uses the concept of build tasks (equivalent to Ant targets or Maven phases/goals). You can get a list of
available tasks via 

----
gradle tasks
----

To execute a task across all modules, simply perform that task from the root directory. Gradle will visit each
sub-project and execute that task if the sub-project defines it. To execute a task in a specific module you can
either:

. `cd` into that module directory and execute the task
. name the "task path". For example, to run the tests for the _hibernate-core_ module from the root directory
you could say `gradle hibernate-core:test`

=== Common tasks

The common tasks you might use in building Hibernate include:

* _build_ - Assembles (jars) and tests this project
* _compile_ - Performs all compilation tasks including staging resources from both main and test
* _jar_ - Generates a jar archive with all the compiled classes
* _test_ - Runs the tests
* _publishToMavenLocal_ - Installs the project jar to your local maven cache (aka ~/.m2/repository). Note that Gradle
never uses this, but it can be useful for testing your build with other local Maven-based builds.
* _clean_ - Cleans the build directory

== Testing and databases

Testing against a specific database can be achieved in 2 different ways:

=== Using the "Matrix Testing Plugin" for Gradle.

Coming later…

=== Using profiles

The Hibernate build defines several database testing _profiles_ in `local.databases.gradle`.
A profile may be activated by name using the `db` build property which can be passed either:

- as a JVM system property `-Ddb=...`, or
- as a Gradle project property `-Pdb=...`.

Examples below use the Gradle project property.

----
gradle clean build -Pdb=postgresql
----

To run a test from your IDE, you need to ensure the property expansions happen.
Use the following command:

----
gradle clean compile -Pdb=postgresql
----

__NOTE: To run tests against a JDBC driver that is not available via Maven central, add the driver to your local Maven repository (`~/.m2/repository`) or to a personal Maven repository server.__

=== Starting test databases locally as containers

If podman or docker is installed, there's no need to install any database to test Hibernate.
The script `db.sh` starts a preconfigured database which can be used for testing.

Simply run the following command:

----
./db.sh postgresql
----

Running `./db.sh` without an argument prints a list of available database configurations.

By default, `./db.sh` kills any previously started database.
To keep multiple databases running, use `--keep-orphans` or `-k`:

----
./db.sh -k postgresql
./db.sh -k mysql
----

When the database is properly started, run tests with the corresponding profile, for example, `-Pdb=postgresql` for PostgreSQL.
The system property `dbHost` configures the IP address of your docker host.

The command for running tests might look like the following:

----
./gradlew test -Pdb=postgresql "-DdbHost=192.168.99.100"
----

The following table illustrates a list of commands for various databases that can be tested locally.

|===
|Database |`db.sh` |Gradle command

|H2
|-
|`./gradlew test -Pdb=h2`

|HSQLDB
|-
|`./gradlew test -Pdb=hsqldb`

|Apache Derby
|-
|`./gradlew test -Pdb=derby`

|MySQL
|`./db.sh mysql`
|`./gradlew test -Pdb=mysql`

|MariaDB
|`./db.sh mariadb`
|`./gradlew test -Pdb=mariadb`

|PostgreSQL
|`./db.sh postgresql`
|`./gradlew test -Pdb=postgresql`

|EnterpriseDB
|`./db.sh edb`
|`./gradlew test -Pdb=edb`

|Oracle
|`./db.sh oracle`
|`./gradlew test -Pdb=oracle`

|DB2
|`./db.sh db2`
|`./gradlew test -Pdb=db2`

|SQL Server
|`./db.sh mssql`
|`./gradlew test -Pdb=mssql`

|Sybase ASE (jTDS)
|`./db.sh sybase`
|`./gradlew test -Pdb=sybase`

|Sybase ASE (jConnect)
|`./db.sh sybase`
|`./gradlew test -Pdb=sybase_jconn`

|SAP HANA
|`./db.sh hana`
|`./gradlew test -Pdb=hana`

|CockroachDB
|`./db.sh cockroachdb`
|`./gradlew test -Pdb=cockroachdb`

|TiDB
|`./db.sh tidb`
|`./gradlew test -Pdb=tidb`

|Informix
|`./db.sh informix`
|`./gradlew test -Pdb=informix`

|Spanner PostgreSQL
|`./db.sh spanner_pg`
|`./gradlew test -Pdb=spannerpgsql`
|===

To stop a container started by `docker`, use the command

[source]
----
docker stop $container_name
----

NOTE:: Substitute `podman` command for `docker` if using `podman`

E.g., to stop the mariadb container

[source]
----
docker stop mariadb
----
