hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=false
hibernate.use_sql_comments=true
hibernate.action_queue.enable_graph_implementation=true
org.hibernate.SQL=DEBUG
org.hibernate.action=DEBUG
org.hibernate.action.queue=DEBUG
