:version: 8.0
= What's New in {version}
:toc2:
:sectanchors:
:toclevels: 4
:docsBase: https://docs.jboss.org/hibernate/orm
:versionDocBase: {docsBase}/{version}
:userGuideBase: {versionDocBase}/userguide/html_single/Hibernate_User_Guide.html
:migrationGuide: {versionDocBase}/migration-guide/migration-guide.html

Describes the new features and capabilities added to Hibernate ORM in {version}.

IMPORTANT: If migrating from earlier versions, be sure to also check out the link:{migrationGuide}[Migration Guide] for discussion of impactful changes.

[[jpa4]]
== Jakarta Persistence 4.0

Support for Jakarta Persistence has been moved to version 4.0.
See https://in.relation.to/2026/01/20/JPA-4-M1/[our blog] for discussion of the changes in version 4.0.


[[graph-flushing]]
=== Graph-based Flushing

8.0 introduces graph-based flush coordination that plans insert, update, delete, and collection work using the mapped relational constraints of the domain model.  Instead of relying primarily on operation ordering heuristics, the graph queue builds a dependency model for each flush and executes work in an order that better reflects foreign keys, uniqueness constraints, optional tables, secondary tables, and other mapping relationships.

The goal is both correctness and performance: fewer special-case ordering failures, more predictable batching, and a clearer foundation for future flush-time optimizations.  The new graph approach is designed to handle complex object graphs more naturally, especially in applications with deeply related entities, mixed entity and collection changes, and database schemas where constraint ordering matters.

The new graph-based flush coordination is enabled by default, but the legacy strategy remains *_temporarily_* available by configuration using

[source,properties]
----
hibernate.flush.queue.type=legacy
----

`org.hibernate.cfg.FlushSettings` defines a number of new settings for controlling the graph-based flush coordination.


[[procedure-outputs]]
== Improvements to ProcedureCall

A number of improvements and additions have been made to
`ProcedureCall`, `ProcedureOutputs` and `Output`.


[[procedure-outputs-casting]]
=== Output Casting

Previous versions of Hibernate required explicit casting of the `Output` references.  E.g.

[source,java]
----
ProcedureCall call = session.createProcedureCall( "getRegionsAndInitiatives", Region.class);
ProcedureOutputs outputs = call.getOutputs();

List<Region> regions = ( (ResultSetOutput<Region>) outputs.getCurrent() )
        .getResultList();
----

8.0 offers method-driven casting -

[source,java]
----
ProcedureCall call = session.createProcedureCall( "getRegionsAndInitiatives");
ProcedureOutputs outputs = call.getOutputs();

List<Region> regions = outputs.getCurrent()
        .asResultSetOutput( Region.class )
        .getResultList();
----



[[procedure-outputs-mapping]]
=== ResultSet Mapping

Building on top of fixing a https://hibernate.atlassian.net/browse/HHH-9912[long-standing bug] and the improvements to <<procedure-outputs-casting,output casting>>, 8.0 adds the ability to lazily declare ResultSet mapping rather than up front during `ProcedureCall` creation.

[source,java]
----
var call = session.createProcedureCall( "getRegionsAndInitiatives");
var outputs = call.getOutputs();

List<Region> regions =  outputs.getCurrent()
        .asResultSetOutput(Region.class)
        .getResultList();

outputs.goToNext();

List<Initiative> initiatives =  outputs.getCurrent()
        .asResultSetOutput(Initiative.class)
        .getResultList();
----

[[get-ref-option]]
== getReference() by Natural Id

8.0 adds the ability to get a reference (`Session#getReference`) based on an entity's natural-id via
a new overload -

[source,java]
----
var isbn = ...;
var book = session.getReference(Book.class, isbn, NATURAL);
----

[[StatementObserver]]
== StatementObserver

8.0 introduces the new `StatementObserver` contract, allowing observation of all JDBC statements Hibernate performs.