= What's New in {version}
:toc2:
:sectanchors:
:toclevels: 4
:version: 7.4
:docsBase: https://docs.jboss.org/hibernate/orm
:versionDocBase: {docsBase}/{version}
:userGuideBase: {versionDocBase}/userguide/html_single/Hibernate_User_Guide.html
:migrationGuide: {versionDocBase}/migration-guide/migration-guide.html

Describes the new features and capabilities added to Hibernate ORM in {version}.

IMPORTANT: If migrating from earlier versions, be sure to also check out the link:{migrationGuide}[Migration Guide] for discussion of impactful changes.

[[reveng]]
== Reverse Engineering

The reverse engineering module, previously part of the standalone Hibernate Tools project, is now integrated directly into Hibernate ORM. It is available as plugins for Gradle, Maven, and Ant.

The reverse engineering plugins can generate:

- Java entity classes
- DAO classes
- `hbm.xml` mapping files
- `mapping.xml` mapping files
- `hibernate.cfg.xml` configuration files
- DDL scripts
- HTML documentation

The process is customizable via XML configuration files and custom strategy classes.

See the link:{userGuideBase}#reveng[Reverse Engineering] chapter in the User Guide for details.

[[transform-hbm]]
== HBM XML Transformation

The Maven plugin now includes a `transformHbm` goal that transforms legacy `hbm.xml` mapping files into ORM `mapping.xml` files. This does not involve reverse engineering from a database -- it converts existing HBM mappings.

See the link:{userGuideBase}#tooling-maven-transformhbm[HBM XML Transformation] section in the User Guide for details.

[[any-join]]
== Joins and join fetching for `@Any` and `@ManyToAny`

Discriminated association mappings may now:

- be used freely in HQL joins and treated joins.
- be fetched using a join.

The joining and fetching semantics for `@Any` and `@ManyToAny` are aligned with `@ManyToOne` and `@ManyToMany` respectively.

Join fetching may be requested using `join fetch` in HQL, or using an `EntityGraph`.
