[[osgi]]
== OSGi
:sourcedir: ../../../../../test/java/org/hibernate/userguide/osgi
:extrasdir: extras

=== OSGi Specification and Environment

Hibernate targets the OSGi 4.3 spec or later.
It was necessary to start with 4.3, over 4.2, due to our dependency on OSGi's `BundleWiring` for entity/mapping scanning.

Hibernate supports three types of configurations within OSGi.

. Container-Managed JPA <<osgi-managed-jpa>>
. Unmanaged JPA <<osgi-unmanaged-jpa>>
. Unmanaged Native <<osgi-unmanaged-native>>

=== hibernate-osgi

Rather than embedding OSGi capabilities into hibernate-core, and sub-modules, hibernate-osgi was created.
It's purposefully separated, isolating all OSGi dependencies.
It provides an OSGi-specific `ClassLoader` (aggregates the container's `ClassLoader` with core and `EntityManager` ``ClassLoader``s),
JPA persistence provider, `SessionFactory`/`EntityManagerFactory` bootstrapping, entities/mappings scanner, and service management.

=== features.xml

Apache Karaf environments tend to make heavy use of its "features" concept, where a feature is a set of order-specific bundles focused on a concise capability.
These features are typically defined in a `features.xml` file.
Hibernate produces and releases its own `features.xml` that defines a core `hibernate-orm`, as well as additional features for optional functionality (caching, Envers, etc.).
This is included in the binary distribution, as well as deployed to the JBoss Nexus repository (using the `org.hibernate` groupId and `hibernate-osgi` artifactId with the `karaf.xml` classifier).

Note that our features are versioned using the same ORM artifact versions they wrap.
Also, note that the features are heavily tested against Karaf 3.0.3 as a part of our PaxExam-based integration tests.
However, they'll likely work on other versions as well.

hibernate-osgi, theoretically, supports a variety of OSGi containers, such as Equinox.
In that case, please use `features.xm` as a reference for necessary bundles to activate and their correct ordering.
However, note that Karaf starts a number of bundles automatically, several of which would need to be installed manually on alternatives.

=== QuickStarts/Demos

All three configurations have a QuickStart/Demo available in the https://github.com/hibernate/hibernate-demos[hibernate-demos] project:

[[osgi-managed-jpa]]
=== Container-Managed JPA

The Enterprise OSGi specification includes container-managed JPA.
The container is responsible for discovering persistence units in bundles and automatically creating the `EntityManagerFactory` (one `EntityManagerFactory` per `PersistenceUnit`).
It uses the JPA provider (hibernate-osgi) that has registered itself with the OSGi `PersistenceProvider` service.

=== Enterprise OSGi JPA Container

In order to utilize container-managed JPA, an Enterprise OSGi JPA container must be active in the runtime.
In Karaf, this means Aries JPA, which is included out-of-the-box (simply activate the `jpa` and `transaction` features).
Originally, we intended to include those dependencies within our own `features.xml`.
However, after guidance from the Karaf and Aries teams, it was pulled out.
This allows Hibernate OSGi to be portable and not be directly tied to Aries versions, instead of having the user choose which to use.

That being said, the QuickStart/Demo projects include a sample https://github.com/hibernate/hibernate-demos/tree/master/hibernate-orm/osgi/managed-jpa/features.xml[features.xml]
showing which features need to be activated in Karaf in order to support this environment.
As mentioned, use this purely as a reference!

=== persistence.xml

Similar to any other JPA setup, your bundle must include a `persistence.xml` file. This is typically located in `META-INF`.

=== DataSource

Typical Enterprise OSGi JPA usage includes a `DataSource` installed in the container.
Your bundle's `persistence.xml` calls out the `DataSource` through JNDI.
For example, you could install the following H2 `DataSource`.
You can deploy the `DataSource` manually (Karaf has a `deploy` dir), or through a "blueprint bundle" (`blueprint:file:/[PATH]/datasource-h2.xml`).

.datasource-h2.xml
====
[source,xml]
----
include::{extrasdir}/datasource-h2.xml[]
----
====

That `DataSource` is then used by your `persistence.xml` persistence-unit. The following works in Karaf, but the names may need tweaked in alternative containers.

.META-INF/persistence.xml
====
[source,xml]
----
<jta-data-source>osgi:service/javax.sql.DataSource/(osgi.jndi.service.name=jdbc/h2ds)</jta-data-source>
----
====

=== Bundle Package Imports

Your bundle's manifest will need to import, at a minimum:

* `javax.persistence`
* `org.hibernate.proxy` and `javassist.util.proxy`, due to Hibernate's ability to return proxies for lazy initialization (Javassist enhancement occurs on the entity's `ClassLoader` during runtime).

=== Obtaining an EntityManger

The easiest, and most supported, method of obtaining an `EntityManager` utilizes OSGi's `OSGI-INF/blueprint/blueprint.xml` in your bundle.
The container takes the name of your persistence unit, then automatically injects an `EntityManager` instance into your given bean attribute.

.OSGI-INF/blueprint/blueprint.xml
====
[source,xml]
----
include::{extrasdir}/blueprint.xml[]
----
====

[[osgi-unmanaged-jpa]]
=== Unmanaged JPA

Hibernate also supports the use of JPA, unmanaged by the OSGi container.
The client bundle is responsible for managing the `EntityManagerFactory` and `EntityManager`s.

=== persistence.xml

Similar to any other JPA setup, your bundle must include a `persistence.xml` file. This is typically located in `META-INF`.

=== Bundle Package Imports

Your bundle's manifest will need to import, at a minimum:

* `javax.persistence`
* `org.hibernate.proxy` and `javassist.util.proxy`, due to Hibernate's ability to return proxies for lazy initialization (Javassist enhancement occurs on the entity's `ClassLoader` during runtime)
* JDBC driver package (example: `org.h2`)
* `org.osgi.framework`, necessary to discover the `EntityManagerFactory` (described below)

=== Obtaining an EntityMangerFactory

`hibernate-osgi` registers an OSGi service, using the JPA `PersistenceProvider` interface name, that bootstraps and creates an `EntityManagerFactory` specific for OSGi environments.

[IMPORTANT]
====
It is VITAL that your `EntityManagerFactory` be obtained through the service, rather than creating it manually.
The service handles the OSGi `ClassLoader`, discovered extension points, scanning, etc.
Manually creating an `EntityManagerFactory` is guaranteed to NOT work during runtime!
====

[[osgi-discover-EntityManagerFactory]]
.Discover/Use `EntityManagerFactory`
====
[source,java]
----
include::{sourcedir}/jpa/HibernateUtil.java[tag=osgi-discover-EntityManagerFactory, indent=0]
----
====

[[osgi-unmanaged-native]]
=== Unmanaged Native

Native Hibernate use is also supported. The client bundle is responsible for managing the ``SessionFactory`` and ``Session``s.

=== Bundle Package Imports

Your bundle's manifest will need to import, at a minimum:

* `javax.persistence`
* `org.hibernate.proxy` and `javassist.util.proxy`, due to Hibernate's ability to return proxies for lazy initialization (Javassist enhancement occurs on the entity's `ClassLoader` during runtime)
* JDBC driver package (example: `org.h2`)
* `org.osgi.framework`, necessary to discover the `SessionFactory` (described below)
* `org.hibernate.*` packages, as necessary (ex: cfg, criterion, service, etc.)

=== Obtaining a SessionFactory

`hibernate-osgi` registers an OSGi service, using the `SessionFactory` interface name, that bootstraps and creates a `SessionFactory` specific for OSGi environments.

[IMPORTANT]
====
It is VITAL that your `SessionFactory` be obtained through the service, rather than creating it manually. The service handles the OSGi `ClassLoader`, discovered extension points, scanning, etc.
Manually creating a `SessionFactory` is guaranteed to NOT work during runtime!
====

[[osgi-discover-SessionFactory]]
.Discover/Use `SessionFactory`
====
[source,java]
----
include::{sourcedir}/_native/HibernateUtil.java[tag=osgi-discover-SessionFactory, indent=0]
----
====

=== Optional Modules

The https://github.com/hibernate/hibernate-demos/tree/master/hibernate-orm/osgi/unmanaged-native[unmanaged-native] demo project displays the use of optional Hibernate modules.
Each module adds additional dependency bundles that must first be activated, either manually or through an additional feature.
As of ORM 4.2, Envers is fully supported.
Support for C3P0, Proxool, EhCache, and Infinispan were added in 4.3. However, none of their 3rd party libraries currently work in OSGi (lots of `ClassLoader` problems, etc.).
We're tracking the issues in JIRA.

=== Extension Points

Multiple contracts exist to allow applications to integrate with and extend Hibernate capabilities.
Most apps utilize JDK services to provide their implementations.
`hibernate-osgi` supports the same extensions through OSGi services.
Implement and register them in any of the three configurations.
`hibernate-osgi` will discover and integrate them during `EntityManagerFactory`/`SessionFactory` bootstrapping. Supported extension points are as follows.
The specified interface should be used during service registration.

`org.hibernate.integrator.spi.Integrator`:: (as of 4.2)
`org.hibernate.boot.registry.selector.StrategyRegistrationProvider`:: (as of 4.3)
`org.hibernate.boot.model.TypeContributor`:: (as of 4.3)
JTA's:: `javax.transaction.TransactionManager` and `javax.transaction.UserTransaction` (as of 4.2). However, these are typically provided by the OSGi container.

The easiest way to register extension point implementations is through a `blueprint.xml` file.
Add `OSGI-INF/blueprint/blueprint.xml` to your classpath. Envers' blueprint is a great example:

.Example extension point registrations in blueprint.xml
====
[source,xml]
----
include::{extrasdir}/extension_point_blueprint.xml[]
----
====

Extension points can also be registered programmatically with `BundleContext#registerService`, typically within your `BundleActivator#start`.

=== Caveats

* Technically, multiple persistence units are supported by Enterprise OSGi JPA and unmanaged Hibernate JPA use.
  However, we cannot currently support this in OSGi.
  In Hibernate 4, only one instance of the OSGi-specific `ClassLoader` is used per Hibernate bundle, mainly due to heavy use of static TCCL utilities.
  We hope to support one OSGi `ClassLoader` per persistence unit in Hibernate 5.
* Scanning is supported to find non-explicitly listed entities and mappings.
  However, they MUST be in the same bundle as your persistence unit (fairly typical anyway).
  Our OSGi `ClassLoader` only considers the "requesting bundle" (hence the requirement on using services to create `EntityManagerFactory`/`SessionFactory`), rather than attempting to scan all available bundles.
  This is primarily for versioning considerations, collision protection, etc.
* Some containers (ex: Aries) always return true for `PersistenceUnitInfo#excludeUnlistedClasses`, even if your `persistence.xml` explicitly has `exclude-unlisted-classes` set to `false`.
  They claim it's to protect JPA providers from having to implement scanning ("we handle it for you"), even though we still want to support it in many cases.
  The workaround is to set `hibernate.archive.autodetection` to, for example, `hbm,class`.
  This tells hibernate to ignore the `excludeUnlistedClasses` value and scan for `*.hbm.xml` and entities regardless.
* Scanning does not currently support annotated packages on `package-info.java`.
* Currently, Hibernate OSGi is primarily tested using Apache Karaf and Apache Aries JPA. Additional testing is needed with Equinox, Gemini, and other container providers.
* Hibernate ORM has many dependencies that do not currently provide OSGi manifests. The QuickStart tutorials make heavy use of 3rd party bundles (SpringSource, ServiceMix) or the `wrap:...` operator.


