/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.orm.tooling.dialectprovider.internal;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/// Gradle-independent generator for the Dialect test-kit JUnit bridge.
///
/// @author Steve Ebersole
public final class ContractTestGenerator {
	private static final String GENERATED_PACKAGE = "org.hibernate.dialect.testing.generated";
	private static final String GENERATED_CLASS = "GeneratedDialectProviderContractTest";

	private ContractTestGenerator() {
	}

	public static void generate(Path outputDirectory, List<String> profiles) throws IOException {
		final Set<String> unique = new LinkedHashSet<>();
		for ( String profile : profiles ) {
			if ( profile == null || profile.isBlank() ) {
				throw new IllegalArgumentException( "Dialect contract profile class names must not be blank" );
			}
			if ( !unique.add( profile.trim() ) ) {
				throw new IllegalArgumentException( "Duplicate Dialect contract profile class " + profile.trim() );
			}
		}
		final Path packageDirectory = outputDirectory.resolve( GENERATED_PACKAGE.replace( '.', '/' ) );
		final Path sourceFile = packageDirectory.resolve( GENERATED_CLASS + ".java" );
		if ( unique.isEmpty() ) {
			Files.deleteIfExists( sourceFile );
			return;
		}
		Files.createDirectories( packageDirectory );
		Files.writeString( sourceFile, source( unique ), StandardCharsets.UTF_8 );
	}

	private static String source(Set<String> profiles) {
		final StringBuilder source = new StringBuilder();
		source.append( "package " ).append( GENERATED_PACKAGE ).append( ";\n\n" )
				.append( "import java.lang.reflect.Constructor;\n" )
				.append( "import java.lang.reflect.InvocationTargetException;\n" )
				.append( "import java.lang.reflect.Modifier;\n" )
				.append( "import java.util.stream.Stream;\n\n" )
				.append( "import org.hibernate.dialect.testing.DialectTestKit;\n" )
				.append( "import org.hibernate.dialect.testing.spi.DialectContractProfile;\n" )
				.append( "import org.junit.jupiter.api.DynamicNode;\n" )
				.append( "import org.junit.jupiter.api.TestFactory;\n\n" )
				.append( "/// Generated by `org.hibernate.orm.dialect-provider`.\n" )
				.append( "///\n" )
				.append( "/// @author Steve Ebersole\n" )
				.append( "public final class " ).append( GENERATED_CLASS ).append( " {\n" )
				.append( "\t@TestFactory\n" )
				.append( "\tStream<DynamicNode> dialectProviderContracts() {\n" )
				.append( "\t\treturn Stream.of(\n" );
		int index = 0;
		for ( String profile : profiles ) {
			if ( index++ > 0 ) {
				source.append( ",\n" );
			}
			source.append( "\t\t\t\tinstantiate(\"" ).append( profile ).append( "\")" );
		}
		return source.append( "\n\t\t).map(DialectTestKit::contractTests);\n\t}\n\n" )
				.append( "\tprivate static DialectContractProfile instantiate(String className) {\n" )
				.append( "\t\tfinal Class<?> candidate;\n" )
				.append( "\t\ttry {\n" )
				.append( "\t\t\tcandidate = Class.forName(className);\n" )
				.append( "\t\t}\n" )
				.append( "\t\tcatch (ClassNotFoundException e) {\n" )
				.append( "\t\t\tthrow invalid(className, \"was not found on the dialectProviderTest runtime classpath\", e);\n" )
				.append( "\t\t}\n" )
				.append( "\t\tif (!Modifier.isPublic(candidate.getModifiers())) {\n" )
				.append( "\t\t\tthrow invalid(className, \"must be public\", null);\n" )
				.append( "\t\t}\n" )
				.append( "\t\tif (!DialectContractProfile.class.isAssignableFrom(candidate)) {\n" )
				.append( "\t\t\tthrow invalid(className, \"must implement DialectContractProfile\", null);\n" )
				.append( "\t\t}\n" )
				.append( "\t\tif (Modifier.isAbstract(candidate.getModifiers())) {\n" )
				.append( "\t\t\tthrow invalid(className, \"must be concrete\", null);\n" )
				.append( "\t\t}\n" )
				.append( "\t\tfinal Constructor<?> constructor;\n" )
				.append( "\t\ttry {\n" )
				.append( "\t\t\tconstructor = candidate.getConstructor();\n" )
				.append( "\t\t}\n" )
				.append( "\t\tcatch (NoSuchMethodException e) {\n" )
				.append( "\t\t\tthrow invalid(className, \"must declare an accessible public no-argument constructor\", e);\n" )
				.append( "\t\t}\n" )
				.append( "\t\ttry {\n" )
				.append( "\t\t\treturn (DialectContractProfile) constructor.newInstance();\n" )
				.append( "\t\t}\n" )
				.append( "\t\tcatch (InstantiationException | IllegalAccessException e) {\n" )
				.append( "\t\t\tthrow invalid(className, \"could not be constructed through its public no-argument constructor\", e);\n" )
				.append( "\t\t}\n" )
				.append( "\t\tcatch (InvocationTargetException e) {\n" )
				.append( "\t\t\tthrow invalid(className, \"constructor failed\", e.getCause());\n" )
				.append( "\t\t}\n" )
				.append( "\t}\n\n" )
				.append( "\tprivate static IllegalArgumentException invalid(String className, String requirement, Throwable cause) {\n" )
				.append( "\t\treturn new IllegalArgumentException(\"Configured Dialect contract profile \" + className + \" \" + requirement, cause);\n" )
				.append( "\t}\n" )
				.append( "}\n" )
				.toString();
	}
}
