include::{shared-attributes-dir}/common-attributes.adoc[]
include::{shared-attributes-dir}/url-attributes.adoc[]
include::{shared-attributes-dir}/filesystem-attributes.adoc[]
include::{shared-attributes-dir}/renderer-attributes.adoc[]

= Topical Guides
:toc:

Hibernate documentation is organized into several guides that cover specific topics.  This guide provides links to
all the documentation to give some direction on where to look for information.

[TIP]
====
See the link:{doc-migration-guide-url}[Migration Guide] for details about migration to Hibernate {majorMinorVersion}.
====


[[usage-guides]]
== Usage Guides

Hibernate publishes multiple usage guides -

link:{doc-quick-start-url}[Quick Start]::
    Tutorial style guide for quickly getting started with Hibernate.
link:{doc-introduction-url}[Introduction to Hibernate]::
    High-level look at the most used Hibernate features.
link:{doc-query-language-url}[Guide to the Hibernate Query Language]::
    Discussion of the Hibernate Query Language.
link:{doc-user-guide-url}[User Guide]::
    Detailed discussion of all features of Hibernate.  More of a reference manual.


[[logging]]
== Logging

The link:{doc-logging-url}[Logging Guide] discusses logging in Hibernate.


[[tooling]]
== Tooling

See the link:{doc-user-guide-url}#tooling[Tooling Guide] for information on:

* Bytecode enhancement
* Static Metamodel Generation
* Gradle, Maven, and Ant plugins
* Schema management


== Integrator Guides
* The <<registries/ServiceRegistries.adoc#registries-guide,Service Registries Guide>> discusses Hibernate Service and ServiceRegistry contracts.
* Others coming soon


[[support]]
== Compatibility and Support

Compatibility is defined as ...

Support is defined as ...

By default, all parts of Hibernate are considered supported and follow the general backwards compatibility https://hibernate.org/community/compatibility-policy/[policy].
Various things influence the levels of support and backwards compatibility to expect in regard to parts of Hibernate.

[[support-internal]]
=== Internal

Internal parts of Hibernate are simply that - internal implementation details that are not supported for use by applications.
Use of internal contracts should be avoided as they are not supported and could be removed or changed at any time.

Contracts considered internal are defined in one of 2 ways:

1. The Java class (interface, etc.) is defined under a package named `internal`, either directly or as a sub-package
2. Through the use of the `@Internal` annotation.

See the definitive set of link:{report-internals-url}[internals].


[[support-incubating]]
=== Incubating

Incubating contracts are generally new contracts which are still being actively designed, similar to
"tech preview" features.
Such contracts are subject to change and should be used with that understanding.

See the definitive set of link:{report-incubating-url}[incubations].

[[support-deprecation]]
=== Deprecations

1. `@Deprecated`
2. `@Remove`

See the definitive set of link:{report-deprecation-url}[deprecations].


