services:
  mysql:
    image: ${MYSQL_IMAGE:-docker.io/library/mysql:9.7@sha256:f0ef1d92fa650fcfa5b85f1d82bb1a56a6dd579bf256b8f8f2a5a0b1b61c8b0b}
    container_name: mysql
    environment:
      MYSQL_USER: hibernate_orm_test
      MYSQL_PASSWORD: hibernate_orm_test
      MYSQL_ROOT_PASSWORD: hibernate_orm_test
      MYSQL_DATABASE: hibernate_orm_test
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_as_cs
      - --log-bin-trust-function-creators=1
      - --lower_case_table_names=2
      - --innodb_native_foreign_keys
      - --init-connect=SET character_set_client='utf8mb4';SET character_set_results='utf8mb4';SET character_set_connection='utf8mb4';SET collation_connection='utf8mb4_0900_as_cs';
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-phibernate_orm_test"]
      interval: 5s
      timeout: 5s
      retries: 12
