services:
  spanner:
    image: ${SPANNER_EMULATOR:-gcr.io/cloud-spanner-emulator/emulator:1.5.52@sha256:350fa0e504aff363c386a237ef4755f3332deca6f6aa3335664c5b8245495e9c}
    container_name: ${SPANNER_CONTAINER_NAME:-spanner}
    ports:
      - "${SPANNER_GRPC_PORT:-9011}:9010"
      - "${SPANNER_REST_PORT:-9021}:9020"
  spanner-healthcheck:
    # Sidecar: spanner emulator image has no tools, so we use UBI to run the healthcheck:
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:3868cb764020427548832b43b69a9bfc5854442529ef78a1f0db169e7ba6479c
    container_name: ${SPANNER_CONTAINER_NAME:-spanner}_healthcheck
    depends_on:
      spanner:
        condition: service_started
    entrypoint: [ "tail", "-f", "/dev/null" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://spanner:9020/v1/projects/test-project/instanceConfigs || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
