[[pagination]]
== Pagination and dynamic sorting

An <<find-method,automatic>> or <<query-method,annotated>> query method may have additional parameters which specify:

- additional sorting criteria, and/or
- a limit and offset restricting the results which are actually returned to the client.

Before we see this, let's see how we can refer to a field of an entity in a completely typesafe way.

=== The static metamodel

You might already be familiar with the Jakarta Persistence static metamodel.
For an entity class `Book`, the class `Book_` exposes objects representing the persistent fields of `Book`, for example, `Book_.title` represents the field `title`.
This class is generated by `HibernateProcessor` at compilation time.

Jakarta Data has its own static metamodel, which is different to the Jakarta Persistence metamodel, but conceptually very similar. Instead of `Book_`, the Jakarta Data static metamodel for `Book` is exposed by the class `_Book`.

[TIP]
====
The Jakarta Persistence static metamodel is most commonly used together with the Criteria Query API or the `EntityGraph` facility.
Even though these APIs aren't part of the programming model of Jakarta Data, you can still use them from a `default` method of a repository by <<resource-accessor-method,calling the `StatelessSession`>> directly.
====

Let's see how the static metamodel is useful, by considering a simple example.

It's perfectly possible to obtain an instance of `Sort` by passing the name of a field:

[source,java]
----
var sort = Sort.asc("title");
----

Unfortunately, since this is in regular code, and not in an annotation, the field name `"title"` cannot be validated at compile time.

A much better solution is to use the static metamodel to obtain an instance of `Sort`.

[source,java]
----
var sort = _Book.title.asc();
----

The static metamodel also declares constants containing the names of persistent fields.
For example, `_Book.TITLE` evaluates to the string `"title"`.

[TIP]
====
These constants are sometimes used as annotation values.

[source,java]
----
@Find
@OrderBy(_Book.TITLE)
@OrderBy(_Book.ISBN)
List<Book> books(@Pattern String title, Year yearPublished);
----

This example looks superficially more typesafe.
But since Hibernate Data Repositories already validates the content of the `@OrderBy` annotation at compile time, it's not really better.
====

=== Dynamic sorting

Dynamic sorting criteria are expressed using the types `Sort` and `Order`:

- an instance of `Sort` represents a single criterion for sorting query results, and
- an instance of `Order` packages multiple ``Sort``s together.

A query method may accept an instance of `Sort`.

[source,java]
----
@Find
List<Book> books(@Pattern String title, Year yearPublished,
                 Sort<Book> sort);
----

This method might be called as follows:

[source,java]
----
var books =
        library.books(pattern, year,
                      _Book.title.ascIgnoreCase());
----

Alternatively the method may accept an instance of `Order`.

[source,java]
----
@Find
List<Book> books(@Pattern String title, Year yearPublished,
                 Order<Book> order);
----

The method might now be called like this:

[source,java]
----
var books =
       library.books(pattern, year,
                     Order.of(_Book.title.ascIgnoreCase(),
                              _Book.isbn.asc());
----

Dynamic sorting criteria may be combined with static criteria.

[source,java]
----
@Find
@OrderBy("title")
List<Book> books(@Pattern String title, Year yearPublished,
                 Sort<Book> sort);
----

We're not convinced this is very useful in practice.

=== Limits

A `Limit` is the simplest way to express a subrange of query results.
It specifies:

- `maxResults`, the maximum number of results to be returned from the database server to the client, and,
- optionally, `startAt`, an offset from the very first result.

These values map directly the familiar `setMaxResults()` and `setFirstResults()` of the Jakarta Persistence `Query` interface.

[source,java]
----
@Find
@OrderBy(_Book.TITLE)
List<Book> books(@Pattern String title, Year yearPublished,
                 Limit limit);
----
[source,java]
----
var books =
        library.books(pattern, year,
                      Limit.of(MAX_RESULTS));
----

A more sophisticated approach is provided by `PageRequest`.

=== Offset-based pagination

A `PageRequest` is superficially similar to a `Limit`, except that it's specified in terms of:

- a page `size`, and
- a numbered `page`.

We can use a `PageRequest` just like a `Limit`.

[source,java]
----
@Find
@OrderBy("title")
@OrderBy("isbn")
List<Book> books(@Pattern String title, Year yearPublished,
                 PageRequest pageRequest);
----
[source,java]
----
var books =
        library.books(pattern, year,
                      PageRequest.ofSize(PAGE_SIZE));
----

[CAUTION]
====
Query results should be totally ordered when a repository method is used for pagination.
The easiest way to be sure that you have a well-defined total order is to specify the identifier of the entity as the last element of the order.
For this reason, we specified `@OrderBy("isbn")` in the previous example.
====

However, a repository method which accepts a `PageRequest` may return a `Page` instead of a `List`, making it easier to implement pagination.

[source,java]
----
@Find
@OrderBy("title")
@OrderBy("isbn")
Page<Book> books(@Pattern String title, Year yearPublished,
                 PageRequest pageRequest);
----
[source,java]
----
var page =
        library.books(pattern, year,
                      PageRequest.ofSize(PAGE_SIZE));
var books = page.content();
long totalPages = page.totalPages();
// ...
while (page.hasNext()) {
    page = library.books(pattern, year,
                         page.nextPageRequest().withoutTotal());
    books = page.content();
    // ...
}
----

Pagination may be combined with dynamic sorting.

[source,java]
----
@Find
Page<Book> books(@Pattern String title, Year yearPublished,
                 PageRequest pageRequest, Order<Book> order);
----

[WARNING]
=====
It's important to pass the same arguments to query parameters, and the same sorting criteria, with each page request!
The repository is stateless: it doesn't remember the values passed on the previous page request.
=====

A repository method with return type `Page` uses SQL offset and limit to implement pagination.
We'll refer to this as _offset-based pagination_.
A problem with this approach is that it's quite vulnerable to missed or duplicate results when the database is modified between page requests.
Therefore, Jakarta Data offers an alternative solution, which we'll call _key-based pagination_.

=== Key-based pagination

In key-based pagination, the query results must be totally ordered by a unique key of the result set.
The SQL offset is replaced with a restriction on the unique key, appended to the `where` clause of the query:

- a request for the _next_ page of query results uses the key value of the _last_ result on the current page to restrict the results, or
- a request for the _previous_ page of query results uses the key value of the _first_ result on the current page to restrict the results.


[WARNING]
====
For key-based pagination, it's _essential_ that the query has a total order.
====

From our point of view as users of Jakarta Data, key-based pagination works almost exactly like offset-based pagination.
The difference is that we must declare our repository method to return `CursoredPage`.

[source,java]
----
@Find
@OrderBy("title")
@OrderBy("isbn")
CursoredPage<Book> books(@Pattern String title, Year yearPublished,
                 PageRequest pageRequest);
----

On the other hand, with key-based pagination, Hibernate must do some work under the covers rewriting our query.

[CAUTION]
====
Key-based pagination goes some way to protect us from skipped or duplicate results.
The cost is that page numbers can lose synchronization with the query result set during navigation.
This isn't usually a problem, but it's something to be aware of.
====

****
Direct API support for key-based pagination originated in the work of Hibernate team member Christian Beikov back in 2015 in the Blaze-Persistence framework.
It was adopted from there by the Jakarta Data specification, and is now even available in Hibernate ORM via the link:{doc-javadoc-url}org/hibernate/query/KeyedPage.html[`KeyedPage`]/link:{doc-javadoc-url}org/hibernate/query/KeyedResultList.html[`KeyedResultList`] API.
****

=== Advanced control over querying

For more advanced usage, an automatic or annotated query method may be declared to return `jakarta.persistence.Query`, `jakarta.persistence.TypedQuery`, link:{doc-javadoc-url}org/hibernate/query/Query.html[`org.hibernate.query.Query`], or link:{doc-javadoc-url}org/hibernate/query/SelectionQuery.html[`org.hibernate.query.SelectionQuery`].

[source,java]
----
@Find
SelectionQuery<Book> booksQuery(@Pattern String title, Year yearPublished);

default List<Book> booksQuery(String title, Year yearPublished) {
    return books(title, yearPublished)
            .enableFetchProfile(_Book.PROFILE_WITH_AUTHORS);
            .setReadOnly(true)
            .setTimeout(QUERY_TIMEOUT)
            .getResultList();
}
----

This allows for direct control over query execution, without loss of typesafety.