[[pagination]]
== Pagination and dynamic sorting

An <<find-method,automatic>> or <<query-method,annotated>> query method may have additional parameters which specify:

- additional sorting criteria, and/or
- a limit and offset restricting the results which are actually returned to the client.

Before we see this, let's see how we can refer to a field of an entity in a completely typesafe way.

=== The static metamodel

You might already be familiar with the Jakarta Persistence static metamodel.
For an entity class `Book`, the class `Book_` exposes objects representing the persistent fields of `Book`, for example, `Book_.title` represents the field `title`.
This class is generated by `HibernateProcessor` at compilation time.

Jakarta Data has its own static metamodel, which is different to the Jakarta Persistence metamodel, but conceptually very similar. Instead of `Book_`, the Jakarta Data static metamodel for `Book` is exposed by the class `_Book`.

[TIP]
====
The Jakarta Persistence static metamodel is most commonly used together with the Criteria Query API or the `EntityGraph` facility.
Even though these APIs aren't part of the programming model of Jakarta Data, you can still use them from a `default` method of a repository by <<resource-accessor-method,calling the `StatelessSession`>> directly.
====

Let's see how the static metamodel is useful, by considering a simple example.

It's perfectly possible to obtain an instance of `Sort` by passing the name of a field:

[source,java]
----
var sort = Sort.asc("title");
----

Unfortunately, since this is in regular code, and not in an annotation, the field name `"title"` cannot be validated at compile time.

A much better solution is to use the static metamodel to obtain an instance of `Sort`.

[source,java]
----
var sort = _Book.title.asc();
----

The static metamodel also declares constants containing the names of persistent fields.
For example, `_Book.TITLE` evaluates to the string `"title"`.

[TIP]
====
These constants are sometimes used as annotation values.

[source,java]
----
@Find
@OrderBy(_Book.TITLE)
@OrderBy(_Book.ISBN)
List<Book> books(@Pattern String title, Year yearPublished);
----

This example looks superficially more typesafe.
But since Hibernate Data Repositories already validates the content of the `@OrderBy` annotation at compile time, it's not really better.
====

=== Dynamic sorting

Dynamic sorting criteria are expressed using the types `Sort` and `Order`:

- an instance of `Sort` represents a single criterion for sorting query results, and
- an instance of `Order` packages multiple ``Sort``s together.

A query method may accept an instance of `Sort`.

[source,java]
----
@Find
List<Book> books(@Pattern String title, Year yearPublished,
                 Sort<Book> sort);
----

This method might be called as follows:

[source,java]
----
var books =
        library.books(pattern, year,
                      _Book.title.ascIgnoreCase());
----

Alternatively the method may accept an instance of `Order`.

[source,java]
----
@Find
List<Book> books(@Pattern String title, Year yearPublished,
                 Order<Book> order);
----

The method might now be called like this:

[source,java]
----
var books =
       library.books(pattern, year,
                     Order.of(_Book.title.ascIgnoreCase(),
                              _Book.isbn.asc());
----

Dynamic sorting criteria may be combined with static criteria.

[source,java]
----
@Find
@OrderBy("title")
List<Book> books(@Pattern String title, Year yearPublished,
                 Sort<Book> sort);
----

We're not convinced this is very useful in practice.

=== Limits

A `Limit` is the simplest way to express a subrange of query results.
It specifies:

- `maxResults`, the maximum number of results to be returned from the database server to the client, and,
- optionally, `startAt`, an offset from the very first result.

These values map directly the familiar `setMaxResults()` and `setFirstResults()` of the Jakarta Persistence `Query` interface.

[source,java]
----
@Find
@OrderBy(_Book.TITLE)
List<Book> books(@Pattern String title, Year yearPublished,
                 Limit limit);
----
[source,java]
----
var books =
        library.books(pattern, year,
                      Limit.of(MAX_RESULTS));
----

A more sophisticated approach is provided by `PageRequest`.

=== Pagination