[[reactive-repositories]]
== Reactive repositories

Hibernate Data Repositories provides repositories backed by https://hibernate.org/reactive/[Hibernate Reactive] for use in reactive programming.
The methods of a reactive repository are non-blocking, and so every operation returns a reactive stream.

[NOTE]
====
Jakarta Data 1.0 does not define a way to write repositories for use in reactive programming, but the spec was written to accommodate such extensions.
This capability is being written into Data 1.1 under the more general category of _asynchronous repositories_.
====

In Hibernate Data Repositories we use https://smallrye.io/smallrye-mutiny/[Mutiny] to work with reactive streams.

[CAUTION]
====
A future version of Hibernate Data Repositories will also allow the use of `CompletionStage` from `java.util.concurrent`.
Asynchronous repositories based on Mutiny are unlikely to ever be portable to other implementations of Jakarta Data.
====

In our opinion, Mutiny is a _much_ more comfortable API than `CompletionStage`.

[TIP]
The documentation for Hibernate Reactive contains a https://hibernate.org/reactive/documentation/3.0/reference/html_single/#_apis_for_chaining_reactive_operations[comparison table] that's useful if you're more familiar with `CompletionStage`.


=== Defining a reactive repository

In the following code example we notice the two requirements for a reactive repository in Hibernate Data Repositories:

1. there must be a resource accessor method returning the underlying `Mutiny.StatelessSession` from Hibernate Reactive, and
2. the return type of every other operation is `Uni`, a reactive stream type defined by Mutiny.

For example, a `@Find` method which would return `Book` in a regular Jakarta Data repository must return `Uni<Book>` in a reactive repository.
Similarly, lifecycle methods usually return `Uni<Void>` instead of `void`.

[source,java]
----
@Repository
interface Library {

    Mutiny.StatelessSession session();

    @Find
    Uni<Book> book(String isbn);

    @Insert
    Uni<Void> add(Book book);

    @Find
    Uni<List<Book>> books(@By("isbn") String[] ibsns);
}
----

It's _not_ possible to mix blocking and non-blocking operations in the same repository interface.

IMPORTANT: Depending on how you're managing the stateless session, you might need to declare the resource accessor method with the type `Uni<Mutiny.StatelessSession>`.

=== Obtaining a reactive repository

To make use of our reactive repository, we'll need to bootstrap Hibernate Reactive and obtain a `Mutiny.SessionFactory`.
For example, if we have a persistence unit named `example` in our `persistence.xml` file, we can obtain a `SessionFactory` like this:

[source,java]
----
Mutiny.SessionFactory factory =
        createEntityManagerFactory("example")
                .unwrap(Mutiny.SessionFactory.class);
----

Please refer to the https://hibernate.org/reactive/documentation/[documentation for Hibernate Reactive] for more information on this topic.

TIP: In Quarkus, this step is unnecessary, and you can let Quarkus manage and inject the reactive `SessionFactory`.

Once we have the `SessionFactory`, we can easily obtain a `Mutiny.StatelessSession`, and use it to instantiate our repository:

[source,java]
----
factory.withStatelessTransaction(session -> {
    Library library = new Library_(session);
    ...
})
----

TIP: An even better approach is to make a `@RequestScoped` instance of `Mutiny.StatelessSession` or `Uni<Mutiny.StatelessSession>` available for injection by CDI.
Then the `Library` repository itself may be directly injected, and you won't have to worry about managing the stateless session in application program code.
This is a little bit tricky to get working perfectly, so hopefully by the time you're reading this, there will already be a built-in implementation in Quarkus.

// TIP: In Quarkus, all this is unnecessary, and you can directly inject the `Library`.

=== Calling a reactive repository

To actually make use of a reactive repository, you'll need to be familiar with the programming model of reactive streams.
For this, we refer you to the Mutiny documentation, and to the documentation for Hibernate Reactive, which goes over some gotchas.

The most important thing to understand is that a code fragment like the following does _not_ result in any immediate interaction with the database:

[source,java]
----
Uni<Void> uni =
        factory.withStatelessTransaction(session -> {
            Library library = new Library_(session);
            return library.book("9781932394153");
        })
        .invoke(book -> out.println(book.title))
        .replaceWithVoid();
----

This code does no more than construct a reactive stream.
We can execute the stream blockingly by calling `uni.await().indefinitely()`, but that's not something we would ever do in real code.
Instead, what we usually do is simply return the stream, allowing it to be executed in a non-blocking way.