/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.community.dialect;

import org.hibernate.boot.Metadata;
import org.hibernate.boot.model.relational.SqlStringGenerationContext;
import org.hibernate.dialect.Dialect;
import org.hibernate.mapping.Column;
import org.hibernate.tool.schema.internal.ColumnValue;
import org.hibernate.mapping.Index;
import org.hibernate.mapping.PrimaryKey;
import org.hibernate.mapping.Table;
import org.hibernate.mapping.UniqueKey;
import org.hibernate.tool.schema.internal.StandardTableExporter;

import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

public class SpannerPostgreSQLTableExporter extends StandardTableExporter {

	public SpannerPostgreSQLTableExporter(Dialect dialect) {
		super( dialect );
	}

	@Override
	public String[] getSqlCreateStrings(Table table, Metadata metadata, SqlStringGenerationContext context) {
		// Spanner mandates that primary key should be present in all the tables. For element collection tables,
		// there will be no primary key. In order to fix the problem, we randomly generate the ID column
		// with BIT_REVERSED_POSITIVE sequence
		if ( !table.hasPrimaryKey() && !table.getForeignKeyCollection().isEmpty() ) {
			Column column = getAutoGeneratedPrimaryKeyColumn( table, metadata );
			table.addColumn( column );

			PrimaryKey primaryKey = new PrimaryKey( table );
			primaryKey.addColumn( column );

			table.setPrimaryKey( primaryKey );
		}

		return super.getSqlCreateStrings( table, metadata, context );
	}

	@Override
	public String[] getSqlDropStrings(Table table, Metadata metadata, SqlStringGenerationContext context) {
		// Spanner requires the indexes to be dropped before dropping the table
		List<String> sqlDropIndexStrings = new ArrayList<>();
		for ( Index index : table.getIndexes().values() ) {
			sqlDropIndexStrings.add( sqlDropIndexString(index.getName()) );
		}
		// Spanner requires all the unique indexes to be dropped before dropping the tables
		for ( UniqueKey uniqueKey : table.getUniqueKeys().values() ) {
			sqlDropIndexStrings.add( sqlDropIndexString(uniqueKey.getName()) );
		}
		for ( Column column : table.getColumns() ) {
			if ( column.isUnique() ) {
				sqlDropIndexStrings.add( sqlDropIndexString(column.getUniqueKeyName()) );
			}
		}
		String[] sqlDropStrings = super.getSqlDropStrings( table, metadata, context );
		return Stream.concat( sqlDropIndexStrings.stream(), Stream.of( sqlDropStrings ) )
				.toArray( String[]::new );
	}

	private String sqlDropIndexString(String indexName) {
		return "drop index if exists " + indexName;
	}

	private Column getAutoGeneratedPrimaryKeyColumn(Table table, Metadata metadata) {
		Column column = new Column( "rowid" );
		column.setSqlTypeCode( Types.BIGINT );
		column.setNullable( false );
		column.setSqlType( "bigint" );
		column.setOptions( "hidden" );
		column.setIdentity( true );
		column.setValue( new ColumnValue( metadata.getDatabase(), table, column, metadata.getDatabase().getTypeConfiguration().getBasicTypeForJavaType( Long.class ) ) );
		return column;
	}
}
