/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later
 * See the lgpl.txt file in the root directory or http://www.gnu.org/licenses/lgpl-2.1.html
 */
package org.hibernate.sql.ast.produce.metamodel.spi;

import org.hibernate.metamodel.model.domain.spi.EntityTypeImplementor;

/**
 * Access to "source" information about the TableGroup to be built - a set of
 * parameters indicating information to encode into the TableGroup.
 * <p/>
 * This information varies depending on the particular source (HQL, loading, etc).
 *
 * @author Steve Ebersole
 */
public interface TableGroupInfoSource {
	/**
	 * The unique identifier (uid) for the table group generated by Hibernate.
	 */
	String getUniqueIdentifier();

	/**
	 * Access to the "identification variable" (alias) as defined in the source.
	 * Should never be {@code null}; if a particular source reference defines no
	 * identification variable the implementor should use a generated one.
	 */
	String getIdentificationVariable();

	/**
	 * The specific entity subclass to be used (for filtering).
	 */
	EntityTypeImplementor getIntrinsicSubclassEntityMetadata();
}
