/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later
 * See the lgpl.txt file in the root directory or http://www.gnu.org/licenses/lgpl-2.1.html
 */
package org.hibernate.sql.ast.produce.metamodel.spi;

import org.hibernate.metamodel.model.domain.spi.EntityDescriptor;

/**
 * Access to "source" information about the TableGroup to be built - a set of
 * parameters indicating information to encode into the TableGroup.
 * <p/>
 * This information varies depending on the particular source (HQL, loading, etc).
 *
 * @author Steve Ebersole
 *
 * @apiNote The point of this contract was to isolate the different sources
 * (HQL, NativeQuery, etc) of SQL AST trees, especially around producing
 * TableGroups and NavigableReferences ({@link NavigableReferenceInfo}).  Not
 * happy with the definition of these contracts as-is - they were done in haste
 * just to get "something working"; but they should be revisited.
 *
 * todo (6.0) : revisit these ^^
 */
public interface TableGroupInfoSource {

	/**
	 * The unique identifier (uid) for the table group generated by Hibernate.
	 */
	String getUniqueIdentifier();

	/**
	 * Access to the "identification variable" (alias) as defined in the source.
	 * Should never be {@code null}; if a particular source reference defines no
	 * identification variable the implementor should use a generated one.
	 */
	String getIdentificationVariable();

	/**
	 * The specific entity subclass to be used (for filtering).
	 */
	EntityDescriptor getIntrinsicSubclassEntityMetadata();
}
