/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity;

import org.hibernate.MappingException;

/**
 * Identity column support for Spanner.
 */
public class SpannerIdentityColumnSupport extends IdentityColumnSupportImpl {
	public static final SpannerIdentityColumnSupport INSTANCE = new SpannerIdentityColumnSupport();

	private SpannerIdentityColumnSupport() {}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int type) throws MappingException {
		throw new MappingException(
				getClass().getName() + " does not support selecting the last generated identity value");
	}

	@Override
	public String getIdentityColumnString(int type) {
		return "GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)";
	}
}
