CREATE TABLE MY_RETURN (RETURN_ID VARCHAR(20) NOT NULL, CONSTRAINT PK_MY_RETURN PRIMARY KEY (RETURN_ID))
CREATE TABLE MY_RETURN_HISTORY (ID VARCHAR(20) NOT NULL, MY_RETURN_REF VARCHAR(20), CONSTRAINT PK_MY_RETURN_HISTORY PRIMARY KEY (ID), CONSTRAINT FK_MY_RETURN_HISTORY_ID FOREIGN KEY (MY_RETURN_REF) REFERENCES MY_RETURN(RETURN_ID))		
