/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.property.access.internal;

import java.lang.invoke.MethodHandles;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Member;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.ClassFileVersion;
import net.bytebuddy.NamingStrategy;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.dynamic.scaffold.TypeValidation;
import net.bytebuddy.dynamic.scaffold.subclass.ConstructorStrategy;
import net.bytebuddy.implementation.Implementation;
import net.bytebuddy.jar.asm.Opcodes;

import net.bytebuddy.jar.asm.Type;
import org.hibernate.AssertionFailure;
import org.hibernate.HibernateException;
import org.hibernate.bytecode.enhance.internal.bytebuddy.BridgeMembersClassInfo;
import org.hibernate.bytecode.enhance.internal.bytebuddy.DelegatingAccessorMember;
import org.hibernate.bytecode.enhance.internal.bytebuddy.DelegateConstructorAppender;
import org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImplConstants;
import org.hibernate.bytecode.enhance.internal.bytebuddy.ForeignPackageMember;
import org.hibernate.bytecode.enhance.internal.bytebuddy.GetFieldOnArgument;
import org.hibernate.bytecode.enhance.internal.bytebuddy.GetPropertyValues;
import org.hibernate.bytecode.enhance.internal.bytebuddy.SetFieldOnArgument;
import org.hibernate.bytecode.enhance.internal.bytebuddy.SetPropertyValues;
import org.hibernate.models.accessor.HibernateAccessorFactory;
import org.hibernate.models.accessor.HibernateAccessorInstantiator;
import org.hibernate.models.accessor.HibernateAccessorMultiValueReader;
import org.hibernate.models.accessor.HibernateAccessorMultiValueWriter;
import org.hibernate.models.accessor.MultiValueAccessorGenerationException;
import org.hibernate.models.accessor.HibernateAccessorValueReader;
import org.hibernate.models.accessor.HibernateAccessorValueWriter;
import org.hibernate.models.accessor.bytebuddy.HibernateAccessorByteBuddyFactory;
import org.hibernate.models.accessor.spi.CrossClassLoaderLookupBridge;

import org.hibernate.models.accessor.spi.HibernateAccessorBytecodeDumper;
import org.hibernate.models.accessor.spi.HibernateAccessorConfiguration;

import static net.bytebuddy.matcher.ElementMatchers.named;
import static org.hibernate.internal.util.StringHelper.decapitalize;

/**
 * ORM-specific delegating factory that wraps a delegate {@link HibernateAccessorFactory}
 * (typically ByteBuddy-based) for individual accessor methods and provides its own
 * multi-value accessor implementations with ORM enhancement logic.
 *
 * <p>Individual accessors ({@code valueReader}, {@code valueWriter}, {@code instantiator})
 * delegate directly to the underlying factory for optimized bytecode-generated access.
 *
 * <p>Multi-value accessors ({@code multiValueReader}, {@code multiValueWriter}) generate
 * bytecode with direct field/method access and ORM enhancement logic (dirty tracking,
 * lazy-attribute interception, composite owner wiring). The generated bytecode uses
 * direct GETFIELD/PUTFIELD or INVOKEVIRTUAL with boxing/unboxing for primitives.
 */
public class OrmHibernateAccessorFactory implements HibernateAccessorFactory {

	private static final String BRIDGE_GETTER_SUFFIX = "$HibernateAccessorGetterBridge";
	private static final String BRIDGE_SETTER_SUFFIX = "$HibernateAccessorSetterBridge";

	/**
	 * Lookup used for loading bridge classes via {@link ClassLoadingStrategy.UsingLookup}.
	 * Bridge classes are regular (non-hidden) classes loaded into the superclass's classloader
	 * so they can access non-public members in the superclass's package.
	 */
	private static final MethodHandles.Lookup BRIDGE_LOOKUP = MethodHandles.lookup();

	private final HibernateAccessorFactory delegate;
	private final CrossClassLoaderLookupBridge lookupBridge;
	private final HibernateAccessorBytecodeDumper bytecodeDumper;

	// Lazy-initialized for bytecode generation
	private volatile ByteBuddy byteBuddy;
	private volatile EnhancerImplConstants constants;

	public OrmHibernateAccessorFactory(MethodHandles.Lookup lookup, Map<String, Object> configurationValues) {
		final var accessFactoryConfiguration = new HibernateAccessorConfiguration(
				lookup,
				configurationValues
		);
		this.delegate = HibernateAccessorByteBuddyFactory.factory( accessFactoryConfiguration );
		this.lookupBridge = new CrossClassLoaderLookupBridge( lookup, OrmBridgeClassGenerator::generate );
		this.bytecodeDumper = new HibernateAccessorBytecodeDumper( accessFactoryConfiguration );
	}

	@Override
	public <T> HibernateAccessorInstantiator<T> instantiator(Constructor<T> constructor) {
		return delegate.instantiator( constructor );
	}

	@Override
	public HibernateAccessorValueReader<?> valueReader(Field field) {
		return delegate.valueReader( field );
	}

	@Override
	public HibernateAccessorValueReader<?> valueReader(Method method) {
		return delegate.valueReader( method );
	}

	@Override
	public HibernateAccessorValueWriter valueWriter(Field field) {
		return delegate.valueWriter( field );
	}

	@Override
	public HibernateAccessorValueWriter valueWriter(Method setter) {
		return delegate.valueWriter( setter );
	}

	@Override
	public HibernateAccessorMultiValueReader multiValueReader(Class<?> declaringClass, Member... members) {
		// Final fields cannot be written by a different class (even nestmates),
		// so bail out early to fall back to per-property access — matching the
		// old ReflectionOptimizer behavior that returned null for final fields.
		for ( Member member : members ) {
			if ( member instanceof Field field && Modifier.isFinal( field.getModifiers() ) ) {
				throw new MultiValueAccessorGenerationException(
						"Cannot generate multi-value reader for final field: " + field
				);
			}
		}
		final String[] propertyNames = derivePropertyNames( members );
		final Member[] getters = members.clone(); // just for "safety reasons" so we don't mutate the input parameters
		// Private members on superclasses can't be accessed even via bridge classes
		// (only nestmates can access private members). Delegate to single-value readers.
		final var delegates = resolvePrivateSuperclassGetters( declaringClass, getters );
		// For remaining non-public (package-private/protected) members on superclasses,
		// generate bridge classes in the superclass's package.
		ensureInitialized();
		final Class<?> superClass = determineBridgeSuperClass( declaringClass, propertyNames, getters, true );
		final boolean hasDelegates = delegates != null;
		DynamicType.Builder<?> builder = byteBuddy
				.with( namingStrategyFor( declaringClass ) )
				.subclass( superClass, hasDelegates
						? ConstructorStrategy.Default.NO_CONSTRUCTORS
						: ConstructorStrategy.Default.DEFAULT_CONSTRUCTOR )
				.implement( HibernateAccessorMultiValueReader.class );
		if ( hasDelegates ) {
			builder = addDelegateFields( builder, delegates.length, HibernateAccessorValueReader.class );
		}
		final byte[] classBytes = builder
				.method( named( "get" ) )
				.intercept( new Implementation.Simple(
						new GetPropertyValues( declaringClass, propertyNames, getters, constants )
				) )
				.make()
				.getBytes();
		dumpClassBytes( declaringClass, "Reader", classBytes );
		return loadHiddenClass( declaringClass, classBytes, HibernateAccessorMultiValueReader.class, delegates );
	}

	@Override
	public HibernateAccessorMultiValueWriter multiValueWriter(Class<?> declaringClass, Member... members) {
		// Final fields cannot be written by a different class (even nestmates),
		// so bail out early to fall back to per-property access — matching the
		// old ReflectionOptimizer behavior that returned null for final fields.
		for ( Member member : members ) {
			if ( member instanceof Field field && Modifier.isFinal( field.getModifiers() ) ) {
				throw new MultiValueAccessorGenerationException(
						"Cannot generate multi-value writer for final field: " + field
				);
			}
		}
		final String[] propertyNames = derivePropertyNames( members );
		final Member[] setters = members.clone(); // just for "safety reasons" so we don't mutate the input parameters
		// Private members on superclasses can't be accessed even via bridge classes.
		// Delegate to single-value writers.
		final var delegates = resolvePrivateSuperclassSetters( declaringClass, setters );
		// For remaining non-public (package-private/protected) members on superclasses,
		// generate bridge classes in the superclass's package.
		ensureInitialized();
		final Class<?> superClass = determineBridgeSuperClass( declaringClass, propertyNames, setters, false );
		final boolean hasDelegates = delegates != null;
		DynamicType.Builder<?> builder = byteBuddy
				.with( namingStrategyFor( declaringClass ) )
				.subclass( superClass, hasDelegates
						? ConstructorStrategy.Default.NO_CONSTRUCTORS
						: ConstructorStrategy.Default.DEFAULT_CONSTRUCTOR )
				.implement( HibernateAccessorMultiValueWriter.class );
		if ( hasDelegates ) {
			builder = addDelegateFields( builder, delegates.length, HibernateAccessorValueWriter.class );
		}
		final byte[] classBytes = builder
				.method( named( "set" ) )
				.intercept( new Implementation.Simple(
						new SetPropertyValues( declaringClass, propertyNames, setters, constants )
				) )
				.make()
				.getBytes();
		dumpClassBytes( declaringClass, "Writer", classBytes );
		return loadHiddenClass( declaringClass, classBytes, HibernateAccessorMultiValueWriter.class, delegates );
	}

	/**
	 * Creates a naming strategy that places the generated class in the same package
	 * as the declaring class. This is required because {@code defineHiddenClass}
	 * requires the hidden class to be in the same package as the lookup class.
	 */
	private static NamingStrategy namingStrategyFor(Class<?> declaringClass) {
		return new NamingStrategy.SuffixingRandom(
				"HibernateAccessor",
				new NamingStrategy.Suffixing.BaseNameResolver.ForFixedValue( declaringClass.getName() )
		);
	}

	/**
	 * Derives property names from the member array. For a {@link Field}, the property
	 * name is the field name. For a getter/setter {@link Method}, the name is derived by
	 * stripping the "get"/"is"/"set" prefix and decapitalizing per JavaBeans conventions.
	 */
	private static String[] derivePropertyNames(Member[] members) {
		final String[] names = new String[members.length];
		for ( int i = 0; i < members.length; i++ ) {
			final Member member = members[i];
			if ( member instanceof Field field ) {
				names[i] = field.getName();
			}
			else if ( member instanceof Method method ) {
				names[i] = propertyNameFromMethod( method );
			}
			else {
				throw new IllegalArgumentException( "Unsupported member type: " + member.getClass().getName() );
			}
		}
		return names;
	}

	/**
	 * Derives the JavaBeans property name from a getter method.
	 * Strips the "get" or "is" prefix and decapitalizes the remainder
	 * following standard JavaBeans conventions.
	 */
	private static String propertyNameFromMethod(Method method) {
		final String methodName = method.getName();
		if ( (methodName.startsWith( "get" ) || methodName.startsWith( "set" ))
			&& methodName.length() > 3 ) {
			return decapitalize( methodName.substring( 3 ) );
		}
		else if ( methodName.startsWith( "is" ) && methodName.length() > 2 ) {
			return decapitalize( methodName.substring( 2 ) );
		}
		// Fall back to the raw method name (e.g. record component accessors)
		return methodName;
	}

	/**
	 * Replaces private members declared on superclasses with delegating single-value
	 * readers. Private members can only be accessed by the declaring class itself or
	 * its nestmates, so the generated multi-value accessor (which is neither) delegates
	 * to a {@link HibernateAccessorValueReader} that uses reflection.
	 *
	 * @param declaringClass the entity class
	 * @param members the getter member array — modified in place
	 * @return the created delegate readers, or {@code null} if none were needed
	 */
	private @Nullable HibernateAccessorValueReader<?>[] resolvePrivateSuperclassGetters(
			Class<?> declaringClass,
			Member[] members) {
		List<HibernateAccessorValueReader<?>> delegates = null;
		for ( int i = 0; i < members.length; i++ ) {
			final Member member = members[i];
			if ( Modifier.isPrivate( member.getModifiers() ) && member.getDeclaringClass() != declaringClass ) {
				if ( delegates == null ) {
					delegates = new ArrayList<>();
				}
				final int delegateIndex = delegates.size();
				if ( member instanceof Field field ) {
					delegates.add( valueReader( field ) );
				}
				else if ( member instanceof Method method ) {
					delegates.add( valueReader( method ) );
				}
				members[i] = new DelegatingAccessorMember( member, "delegate$" + delegateIndex );
			}
		}
		return delegates != null
				? delegates.toArray( new HibernateAccessorValueReader<?>[0] )
				: null;
	}

	/**
	 * Replaces private members declared on superclasses with delegating single-value
	 * writers. See {@link #resolvePrivateSuperclassGetters} for rationale.
	 *
	 * @param declaringClass the entity class
	 * @param setterMembers the setter member array — modified in place
	 * @return the created delegate writers, or {@code null} if none were needed
	 */
	private @Nullable HibernateAccessorValueWriter[] resolvePrivateSuperclassSetters(
			Class<?> declaringClass,
			Member[] setterMembers) {
		List<HibernateAccessorValueWriter> delegates = null;
		for ( int i = 0; i < setterMembers.length; i++ ) {
			final Member member = setterMembers[i];
			if ( Modifier.isPrivate( member.getModifiers() ) && member.getDeclaringClass() != declaringClass ) {
				if ( delegates == null ) {
					delegates = new ArrayList<>();
				}
				final int delegateIndex = delegates.size();
				if ( member instanceof Field field ) {
					delegates.add( valueWriter( field ) );
				}
				else if ( member instanceof Method method ) {
					delegates.add( valueWriter( method ) );
				}
				setterMembers[i] = new DelegatingAccessorMember( member, "delegate$" + delegateIndex );
			}
		}
		return delegates != null
				? delegates.toArray( new HibernateAccessorValueWriter[0] )
				: null;
	}

	/**
	 * Generates bridge classes for non-public members declared on superclasses of
	 * {@code declaringClass}. Bridge classes are loaded as regular (non-hidden) classes
	 * in the superclass's package, giving them access to non-public members. Each bridge
	 * class declares {@code protected static} accessor methods that the generated hidden
	 * accessor class can call (since it extends the bridge class).
	 *
	 * <p>The {@code members} array is modified in place: members that require bridge
	 * access are replaced with {@link ForeignPackageMember} wrappers, which
	 * {@link GetPropertyValues} and {@link SetPropertyValues} recognize and handle
	 * by emitting {@code INVOKESTATIC} calls to the bridge methods instead of
	 * direct {@code GETFIELD}/{@code PUTFIELD}.
	 *
	 * @param declaringClass the entity class for which the accessor is being generated
	 * @param propertyNames the property names corresponding to members
	 * @param members the member array (fields or methods) — modified in place
	 * @param forGetter {@code true} to generate {@code get_} bridge methods (for readers),
	 *                  {@code false} to generate {@code set_} bridge methods (for writers)
	 * @return the bridge superclass to use as the superclass of the generated accessor,
	 *         or {@code Object.class} if no bridges are needed
	 */
	private Class<?> determineBridgeSuperClass(
			Class<?> declaringClass,
			String[] propertyNames,
			Member[] members,
			boolean forGetter) {
		if ( declaringClass.isInterface() ) {
			return Object.class;
		}

		final List<BridgeMembersClassInfo> bridgeInfos = collectBridgeMembers( declaringClass, members, propertyNames );
		if ( bridgeInfos.isEmpty() ) {
			return Object.class;
		}

		final String suffix = forGetter ? BRIDGE_GETTER_SUFFIX : BRIDGE_SETTER_SUFFIX;
		Class<?> superClass = Object.class;
		for ( int i = bridgeInfos.size() - 1; i >= 0; i-- ) {
			final BridgeMembersClassInfo info = bridgeInfos.get( i );
			final Class<?> prevSuperClass = superClass;
			final String className = info.getClazz().getName() + suffix + info.encodeName();

			superClass = forGetter ? loadBridgeClassGetter( className, prevSuperClass, info )
					: loadBridgeClassSetter( className, prevSuperClass, info );

			// Wrap bridged members with ForeignPackageMember so that the bytecode
			// appenders emit INVOKESTATIC calls to the bridge methods
			for ( int j = 0; j < members.length; j++ ) {
				if ( info.containsGetter( members[j] ) && !Modifier.isPublic( members[j].getModifiers() ) ) {
					members[j] = new ForeignPackageMember( superClass, members[j] );
				}
			}
		}

		return superClass;
	}

	/**
	 * Walks the superclass hierarchy of {@code declaringClass} and collects information
	 * about non-public, non-private members that need bridge access. Private members are
	 * handled separately by {@link #resolvePrivateSuperclassGetters} /
	 * {@link #resolvePrivateSuperclassSetters} since bridge classes cannot access private
	 * members (only nestmates can). This method collects only package-private and protected
	 * members which bridge classes CAN access (being in the same package as the declaring
	 * superclass).
	 */
	private static List<BridgeMembersClassInfo> collectBridgeMembers(
			Class<?> declaringClass,
			Member[] members,
			String[] propertyNames) {
		final List<BridgeMembersClassInfo> result = new ArrayList<>();
		Class<?> c = declaringClass.getSuperclass();
		while ( c != null && c != Object.class ) {
			final BridgeMembersClassInfo info = new BridgeMembersClassInfo( c );
			for ( int i = 0; i < members.length; i++ ) {
				final Member member = members[i];
				if ( member.getDeclaringClass() == c
						&& !Modifier.isPublic( member.getModifiers() )
						&& !Modifier.isPrivate( member.getModifiers() ) ) {
					info.addGetter( member );
					info.addSetter( member );
					info.addProperty( propertyNames[i] );
				}
			}
			if ( !info.propertyNamesIsEmpty() ) {
				result.add( info );
			}
			c = c.getSuperclass();
		}
		return result;
	}

	private Class<?> loadBridgeClassGetter(
			String className,
			Class<?> superClass,
			BridgeMembersClassInfo info
	) {
		return loadBridgeClass( info.getClazz(), className, superClass, info.gettersIterable(), new GetterBridgeBuilder( info ) );
	}

	private Class<?> loadBridgeClassSetter(
			String className,
			Class<?> superClass,
			BridgeMembersClassInfo info
	) {
		return loadBridgeClass( info.getClazz(), className, superClass, info.gettersIterable(), new SetterBridgeBuilder( info ) );
	}

	/**
	 * Generates and loads a bridge class in the {@code referenceClass}'s package.
	 * The bridge class extends {@code superClass} and declares {@code protected static}
	 * methods for accessing non-public members. If the class has already been loaded
	 * (by a previous call for the same entity hierarchy), the cached class is returned.
	 *
	 * @param referenceClass the superclass whose package the bridge belongs in
	 * @param className the deterministic fully-qualified name for the bridge class
	 * @param superClass the superclass for the bridge class (previous bridge in chain, or Object)
	 * @return the loaded bridge class
	 */
	private Class<?> loadBridgeClass(
			Class<?> referenceClass,
			String className,
			Class<?> superClass,
			Iterable<Member> memberIterable,
			BiFunction<DynamicType.Builder<?>, Member, DynamicType.Builder<?>> builderFunc
	) {
		// Check if the class is already loaded (deterministic naming enables caching)
		try {
			final Class<?> result = referenceClass.getClassLoader().loadClass( className );
			if ( result.getClassLoader() == referenceClass.getClassLoader() ) {
				return result;
			}
		}
		catch (ClassNotFoundException e) {
			// Not loaded yet — generate it
		}

		DynamicType.Builder<?> builder = byteBuddy
				.with( new FixedNamingStrategy( className ) )
				.subclass( superClass );

		for ( Member member : memberIterable ) {
			if ( !Modifier.isPublic( member.getModifiers() ) ) {
				builder = builderFunc.apply( builder, member );
			}
		}

		try {
			return builder.make()
					.load(
							referenceClass.getClassLoader(),
							ClassLoadingStrategy.UsingLookup.of(
									MethodHandles.privateLookupIn( referenceClass, BRIDGE_LOOKUP )
							)
					)
					.getLoaded();
		}
		catch (LinkageError e) {
			// Race condition: another thread may have loaded the class concurrently
			try {
				return referenceClass.getClassLoader().loadClass( className );
			}
			catch (ClassNotFoundException ex) {
				throw new HibernateException(
						"Failed to load or generate bridge class '" + className + "'", e
				);
			}
		}
		catch (IllegalAccessException e) {
			throw new HibernateException(
					"Failed to generate bridge class '" + className
					+ "' (it might be due to the Java module system preventing Hibernate ORM"
					+ " from defining a bridge class in the same package"
					+ " — in this case, the class should be opened and exported to Hibernate ORM)",
					e
			);
		}
	}

	/**
	 * A naming strategy that always returns a fixed class name, used for bridge
	 * classes whose names must be deterministic for classloader-level caching.
	 */
	private static class FixedNamingStrategy extends NamingStrategy.AbstractBase {
		private final String className;

		FixedNamingStrategy(String className) {
			this.className = className;
		}

		@Override
		protected String name(TypeDescription typeDescription) {
			return className;
		}
	}

	private void ensureInitialized() {
		if ( byteBuddy == null ) {
			synchronized ( this ) {
				if ( byteBuddy == null ) {
					constants = new EnhancerImplConstants();
					byteBuddy = new ByteBuddy( ClassFileVersion.ofThisVm( ClassFileVersion.JAVA_V17 ) )
							.with( TypeValidation.DISABLED );
				}
			}
		}
	}

	private void dumpClassBytes(Class<?> declaringClass, String suffix, byte[] bytes) {
		bytecodeDumper.dump( Type.getInternalName( declaringClass ) + "$HibernateAccessor" + suffix, bytes );
	}

	/**
	 * Adds {@code delegate$N} instance fields and a constructor that accepts
	 * a typed array parameter and stores each element into the corresponding field.
	 * Callers must use {@link ConstructorStrategy.Default#NO_CONSTRUCTORS} when
	 * building the class so that no default no-arg constructor is generated.
	 */
	private static DynamicType.Builder<?> addDelegateFields(
			DynamicType.Builder<?> builder,
			int count,
			Class<?> fieldType) {
		final Class<?> arrayType = fieldType.arrayType();
		for ( int i = 0; i < count; i++ ) {
			builder = builder.defineField(
					"delegate$" + i,
					fieldType,
					Opcodes.ACC_PRIVATE | Opcodes.ACC_FINAL
			);
		}
		return builder
				.defineConstructor( Opcodes.ACC_PUBLIC )
				.withParameter( arrayType )
				.intercept( new Implementation.Simple( new DelegateConstructorAppender( count, fieldType ) ) );
	}

	/**
	 * Loads bytecode as a hidden class that is a nestmate of the declaring class,
	 * giving it access to the declaring class's private members.
	 * Uses {@link CrossClassLoaderLookupBridge} to obtain a full-privilege lookup
	 * even when the declaring class is in a different classloader or module.
	 */
	private <T, D> T loadHiddenClass(
			Class<?> declaringClass,
			byte[] bytes,
			Class<T> type,
			@Nullable D[] delegates) {
		try {
			final MethodHandles.Lookup targetLookup = lookupBridge.resolve( declaringClass );
			final MethodHandles.Lookup hiddenLookup = targetLookup
					.defineHiddenClass( bytes, true, MethodHandles.Lookup.ClassOption.NESTMATE );
			final Class<?> hiddenClass = hiddenLookup.lookupClass();
			if ( delegates != null ) {
				return type.cast(
						hiddenClass.getDeclaredConstructor( delegates.getClass() )
								.newInstance( (Object) delegates )
				);
			}
			else {
				return type.cast( hiddenClass.getDeclaredConstructor().newInstance() );
			}
		}
		catch (Exception e) {
			throw new HibernateException(
					"Failed to create multi-value accessor for " + declaringClass.getName(), e
			);
		}
	}

	private record GetterBridgeBuilder(BridgeMembersClassInfo info)
			implements BiFunction<DynamicType.Builder<?>, Member, DynamicType.Builder<?>> {

		@Override
		public DynamicType.Builder<?> apply(DynamicType.Builder<?> builder, Member member) {
			final Class<?> type = resolveGetterType( member );
			return builder.defineMethod(
							"get_" + member.getName(),
							TypeDescription.Generic.OfNonGenericType.ForLoadedType.of( type ),
							Opcodes.ACC_PROTECTED | Opcodes.ACC_STATIC
					)
					.withParameter( info.getClazz() )
					.intercept( new Implementation.Simple( new GetFieldOnArgument( member ) ) );
		}

		private @Nonnull Class<?> resolveGetterType(Member member) {
			final Class<?> type;
			if ( member instanceof Field field ) {
				type = field.getType();
			}
			else if ( member instanceof Method method ) {
				type = method.getReturnType();
			}
			else {
				throw new AssertionFailure( "Unexpected member: " + member );
			}
			return type;
		}
	}

	private record SetterBridgeBuilder(BridgeMembersClassInfo info)
			implements BiFunction<DynamicType.Builder<?>, Member, DynamicType.Builder<?>> {

		@Override
		public DynamicType.Builder<?> apply(DynamicType.Builder<?> builder, Member member) {
			final Class<?> type = resolveSetterType( member );
			return builder.defineMethod(
							"set_" + member.getName(),
							TypeDescription.Generic.VOID,
							Opcodes.ACC_PROTECTED | Opcodes.ACC_STATIC
					)
					.withParameter( info.getClazz() )
					.withParameter( type )
					.intercept( new Implementation.Simple( new SetFieldOnArgument( member ) ) );
		}

		private @Nonnull Class<?> resolveSetterType(Member member) {
			final Class<?> type;
			if ( member instanceof Field field ) {
				type = field.getType();
			}
			else if ( member instanceof Method method ) {
				type = method.getParameterTypes()[0];
			}
			else {
				throw new AssertionFailure( "Unexpected member: " + member );
			}
			return type;
		}
	}
}
