[[configuration]]
== Configuration and boostrap

We would love to make this section short.
Unfortunately, there are several distinct ways to configure and bootstrap Hibernate, and we're going to have to describe at least two of them in detail.

The four basic ways to obtain an instance of Hibernate are:

- using the standard JPA-defined operation `Persistence.createEntityManagerFactory()`,
- using the `Configuration` class to construct a `SessionFactory`,
- using the more complex APIs defined in `org.hibernate.boot`, or
- in a container environment like WildFly or Quarkus, by letting the container take care of the bootstrap process and of injecting the `SessionFactory` or `EntityManagerFactory`.

The first option is the commonly chosen when portability between JPA implementations is important.
When it's not important, the second option adds some flexibility and saves a typecast.

The third option is targeted primarily toward framework integrators and is outside the scope of this document.

The fourth option is extremely popular, since every major Java application server and microservice framework comes with built-in support for Hibernate.
Such container environments also typically feature facilities to automatically manage the lifecycle of an `EntityManager` or `Session` and its association with container-managed transactions.
To learn how to configure Hibernate in such a container environment, you'll need to refer to the documentation of your chosen container.

[[configuration-jpa]]
=== Configuration using JPA
