Chapter 5. Collections
======================

http://www.hibernate.org[*Hibernate.org*]http://hibernate.org/Documentation/DocumentationOverview[*Community
Documentation*]

* link:ch04.html[*Prev*]
* link:ch06.html[*Next*]

Chapter 5. Collections
~~~~~~~~~~~~~~~~~~~~~~

*Table of Contents*

link:ch05.html#collections-synopsis[5.1. Collections as a value type]

link:ch05.html#collections-value[5.2. Collections of value types]

link:ch05.html#collections-entity[5.3. Collections of entities]

link:ch05.html#collections-list[5.4. List - index]

link:ch05.html#collections-map[5.5. Map - key]

link:ch05.html#collections-bag[5.6. Bags]

link:ch05.html#collections-array[5.7. Arrays]

link:ch05.html#collections-as-basic[5.8. Collections as basic value
type]

5.1. Collections as a value type
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

discussions of what it means for them to be value types - lifecycle,
opt-locking

Collections have the usual behavior of value types. They are
automatically persisted when referenced by a persistent object and are
automatically deleted when unreferenced. If a collection is passed from
one persistent object to another, its elements might be moved from one
table to another. Two entities cannot share a reference to the same
collection instance.

Collection attributes do not support null value semantics; Hibernate
does not distinguish between a null collection reference and an empty
collection.

It is important that collections be defined using the appropriate Java
Collections Framework interface rather than a specific implementation.
From a theoretical perspective, this just follows good design
principles. From a practical perspective, Hibernate (really all
persistence providers) will use their own collection implementations
which conform to the Java Collections Framework interfaces.

5.2. Collections of value types
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

collection of values - elements can be of any value type except for
collections (in fact even compositions as the element cannot contain
collections) * basics * compositions

5.3. Collections of entities
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* one-to-many * many-to-many

5.4. List - index
~~~~~~~~~~~~~~~~~

todo : discuss mapping list index

5.5. Map - key
~~~~~~~~~~~~~~

todo : discuss mapping map key

5.6. Bags
~~~~~~~~~

todo : discuss mapping bags and idbags

5.7. Arrays
~~~~~~~~~~~

todo : discuss mapping arrays

5.8. Collections as basic value type
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Notice how all the previous examples explicitly mark the collection
attribute as either ElementCollection, OneToMany or ManyToMany.
Collections not marked as such, or collections explicitly maked with
@Basic are treated as JPA basic values. Meaning there value is stored
into a single column in the containing table.

This is sometimes beneficial. Consider a use-case such as a VARCHAR
column that represents a delimited list or set of Strings.

*Example 5.1. Delimited set of tags*

----------------------------------------------------------------------------------------------
@Entity
public static class Post {
    @Id
    public Integer id;
    @Basic
    @Type( type = "delimited_strings" )
    Set<String> tags;
}


public static class DelimitedStringsType extends AbstractSingleColumnStandardBasicType<Set> {
    public DelimitedStringsType() {
        super(
                VarcharTypeDescriptor.INSTANCE,
                new DelimitedStringsJavaTypeDescriptor()
        );
    }

    @Override
    public String getName() {
        return "delimited_strings";
    }
}

public static class DelimitedStringsJavaTypeDescriptor extends AbstractTypeDescriptor<Set> {
    public DelimitedStringsJavaTypeDescriptor() {
        super(
                Set.class,
                new MutableMutabilityPlan<Set>() {
                    @Override
                    protected Set deepCopyNotNull(Set value) {
                        Set<String> copy = new HashSet<String>();
                        copy.addAll( value );
                        return copy;
                    }
                }
        );
    }

    @Override
    public String toString(Set value) {
        return null;
    }

    @Override
    public Set fromString(String string) {
        return null;
    }

    @Override
    public <X> X unwrap(Set value, Class<X> type, WrapperOptions options) {
        return null;
    }

    @Override
    public <X> Set wrap(X value, WrapperOptions options) {
        return null;
    }
}
----------------------------------------------------------------------------------------------

 +

See the _Hibernate Integrations Guide_ for more details on developing
custom value type mappings. Without the special type mapping above the
"set of tags" would have simply been marshalled using serialization.

'''''

link:legalnotice.html[]

* link:ch04.html[**Prev**Chapter 4. Compositions]
* link:#[*Up*]
* link:index.html[*Home*]
* link:ch06.html[**Next**Chapter 6. Identifiers]
