CREATE TABLE MASTER ( ID CHAR NOT NULL, NAME VARCHAR(20), OTHERNAME VARCHAR(20), PRIMARY KEY (ID) )
CREATE TABLE UNIQUEMASTER ( ID CHAR NOT NULL, NAME VARCHAR(20), OTHERNAME VARCHAR(20), PRIMARY KEY (ID), CONSTRAINT O1 UNIQUE (NAME), CONSTRAINT O2 UNIQUE (OTHERNAME) )
