package org.hibernate.test.annotations.formula;

import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.cfg.Environment;
import org.hibernate.criterion.Order;
import org.hibernate.testing.junit4.BaseCoreFunctionalTestCase;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

/**
 * Test that the queries generated by {@link org.hibernate.annotations.Formula} properly ignore type names when escaping identifiers.
 * <p/>
 * Created by Michael Hum on 17/07/2015.
 */
public class FormulaWithColumnTypesTest extends BaseCoreFunctionalTestCase {

    @Override
    protected void configure(Configuration configuration) {
        configuration.setProperty( Environment.DIALECT, ExtendedOracleDialect.class.getName());
    }

    @Test
    public void testFormulaAnnotationWithTypeNames() {

        Session session = openSession();
        Transaction transaction = session.beginTransaction();

        DisplayItem displayItem20 = new DisplayItem();
        displayItem20.setDisplayCode("20");

        DisplayItem displayItem03 = new DisplayItem();
        displayItem03.setDisplayCode("03");

        DisplayItem displayItem100 = new DisplayItem();
        displayItem100.setDisplayCode("100");

        session.persist(displayItem20);
        session.persist(displayItem03);
        session.persist(displayItem100);

        transaction.commit();
        session.close();

        // 1. Default sorting by display code natural ordering (resulting in 3-100-20).
        session = openSession();
        transaction = session.beginTransaction();

        List displayItems = session.createCriteria(DisplayItem.class)
                .addOrder(Order.asc("displayCode"))
                .list();

        assertNotNull(displayItems);
        assertEquals(displayItems.size(), 3);
        assertEquals("03", ((DisplayItem) displayItems.get(0)).getDisplayCode());
        assertEquals("100", ((DisplayItem) displayItems.get(1)).getDisplayCode());
        assertEquals("20", ((DisplayItem) displayItems.get(2)).getDisplayCode());
        transaction.commit();
        session.close();


        // 2. Sorting by the casted type (resulting in 3-20-100).
        session = openSession();
        transaction = session.beginTransaction();

        List displayItemsSortedByInteger = session.createCriteria(DisplayItem.class)
                .addOrder(Order.asc("displayCodeAsInteger"))
                .list();

        assertNotNull(displayItemsSortedByInteger);
        assertEquals(displayItemsSortedByInteger.size(), 3);
        assertEquals("03", ((DisplayItem) displayItemsSortedByInteger.get(0)).getDisplayCode());
        assertEquals("20", ((DisplayItem) displayItemsSortedByInteger.get(1)).getDisplayCode());
        assertEquals("100", ((DisplayItem) displayItemsSortedByInteger.get(2)).getDisplayCode());
        transaction.commit();
        session.close();
    }

    @Override
    public Class<?>[] getAnnotatedClasses() {
        return new Class<?>[] { DisplayItem.class };
    }

}
