ALTER TABLE PROJECT DROP CONSTRAINT PROJECT_MANAGER
DROP TABLE WORKS_ON
DROP TABLE EMPLOYEE
DROP TABLE PROJECT
DROP TABLE ADDRESS_PERSON
DROP TABLE PERSON
DROP TABLE ADDRESS_MULTI_PERSON
DROP TABLE MULTI_PERSON