package org.hibernate.processor.spi;

import jakarta.annotation.Nullable;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;

import org.hibernate.Incubating;
import org.hibernate.service.JavaServiceLoadable;

/**
 * SPI allowing a framework built on top of Hibernate (for example Quarkus) to
 * customize the code generated by {@link org.hibernate.processor.HibernateProcessor}
 * without the processor having to know anything about that framework.
 * <p>
 * An implementation is discovered with {@link java.util.ServiceLoader}, using the
 * class loader of this interface, by listing its fully qualified class name in
 * {@code META-INF/services/org.hibernate.processor.spi.HibernateProcessorExtension}.
 * At most one implementation may be registered: finding several is reported as a compilation
 * error, since which one would be used is not deterministic. When none is found,
 * {@link org.hibernate.processor.internal.DefaultHibernateProcessorExtension}, which does nothing, is used instead.
 * <p>
 * A single instance is created each time the processor is initialized, and
 * {@link #init(ProcessingEnvironment)} is called once on it before any other method.
 *
 * @see AnnotationMetaEntityContext
 * @see SessionSetup
 */
@Incubating(since = "8.0", group = "processor-extension")
@JavaServiceLoadable
public interface HibernateProcessorExtension {

	/**
	 * Called once, when the processor is initialized and before any other method of this
	 * interface. This is the place to detect which framework libraries are present on the
	 * compilation classpath, for example via
	 * {@link ProcessingEnvironment#getElementUtils() getElementUtils()}.{@code getPackageElement(...)}.
	 *
	 * @param processingEnvironment the environment of the running annotation processor
	 */
	void init(ProcessingEnvironment processingEnvironment);

	/**
	 * The qualifier annotation to place on the session injected into the constructor of a generated
	 * repository, for example to select a persistence unit, as in {@code @PersistenceUnit("name")}.
	 * <p>
	 * The extension is responsible for deciding if there is a qualifier, and which one, with all the
	 * context it needs about the repository being generated. It returns the whole annotation as source
	 * code, and should use {@code context.metamodel().importType(...)} to refer to the type of the
	 * annotation so that it is imported.
	 *
	 * @param dataStore the name of the data store, given by the {@code dataStore} member of the Jakarta
	 * Data {@code @Repository} annotation of the repository, or {@code null} if there is none
	 * @param context gives access to the repository being generated
	 * @return the annotation, for example {@code "@PersistenceUnit(\"name\")"}, or {@code null} for none
	 */
	@Nullable String sessionQualifier(@Nullable String dataStore, AnnotationMetaEntityContext context);

	/**
	 * Whether the session of a Jakarta Data repository is injected by the container into the constructor
	 * of the generated class, which is then annotated {@code @Inject}.
	 * <p>
	 * When this returns {@code false}, which is the default, the generated class instead gets a no-argument
	 * constructor, for the container to instantiate it, and the session is obtained with Jakarta Persistence
	 * resource injection, because that is incompatible with constructor injection. The constructor taking the
	 * session is then only meant for direct instantiation, for example in tests.
	 * <p>
	 * This is independent of {@link #sessionQualifier(String, AnnotationMetaEntityContext)}: a qualifier
	 * is only used for the constructor which takes the session.
	 *
	 * @param context gives access to the repository being generated
	 */
	boolean usesConstructorInjection(AnnotationMetaEntityContext context);

	/**
	 * Whether the given type is an entity, or entity base class, with framework-specific
	 * behavior, such as a Panache entity.
	 * <p>
	 * For a type annotated {@code @Entity} for which this returns {@code true},
	 * {@link #addRepositoryMembers(TypeElement, AnnotationMetaEntityContext)} is called
	 * when its metamodel is generated. Such types are also searched for session getter methods,
	 * even though entities normally are not.
	 *
	 * @param type the type being processed
	 * @return {@code true} if the type is handled by this extension
	 */
	boolean isExtensionEntity(TypeElement type);

	/**
	 * Whether the given type is a framework-specific repository, such as a Panache repository.
	 * <p>
	 * A type for which this returns {@code true} is treated as a repository even if none of its
	 * methods carries an annotation that would make it one.
	 *
	 * @param type the type being processed
	 * @return {@code true} if the type is a repository handled by this extension
	 */
	boolean isExtensionRepository(TypeElement type);

	/**
	 * Called while the metamodel of an {@code @Entity} for which
	 * {@link #isExtensionEntity(TypeElement)} returned {@code true} is built, so that the
	 * extension can add members to it, such as static accessors for default repositories
	 * and the nested repository types they return. It is not called when generating the
	 * Jakarta Data static metamodel.
	 *
	 * @param element the entity type
	 * @param context gives access to the metamodel being built
	 */
	void addRepositoryMembers(TypeElement element, AnnotationMetaEntityContext context);

	/**
	 * Called for each type for which a repository implementation may be generated, to let the
	 * extension decide how the repository obtains its session.
	 * <p>
	 * Returning {@code null} lets the processor apply its standard behavior: use the session
	 * getter method if there is one, and otherwise inject an {@code EntityAgent} into Jakarta Data
	 * repositories. Returning a {@link SessionSetup} overrides that behavior. In that case the
	 * extension is responsible for registering whatever is needed to get the session, typically
	 * with {@link AnnotationMetaEntityContext#addRepositoryConstructor(String, String)} or
	 * {@link AnnotationMetaEntityContext#setSessionGetter(String)}.
	 *
	 * @param element the repository or entity type being processed
	 * @param getter the session getter method declared by the type or its supertypes,
	 * or {@code null} if it has none
	 * @param context gives access to the metamodel being built
	 * @return how the session is obtained, or {@code null} to use the default behavior
	 */
	@Nullable SessionSetup setupRepositorySession(
			TypeElement element,
			@Nullable ExecutableElement getter,
			AnnotationMetaEntityContext context);
}
