/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.orm.test.schemaupdate.manytomany;

import java.util.EnumSet;

import org.hibernate.orm.test.schemaupdate.BaseSchemaUnitTestCase;
import org.hibernate.tool.schema.TargetType;

import org.hibernate.testing.TestForIssue;
import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

/**
 * @author Andrea Boriero
 */
public class ForeignKeyNameTest extends BaseSchemaUnitTestCase {

	@Override
	protected boolean createSqlScriptTempOutputFile() {
		return true;
	}

	@Override
	protected boolean dropSchemaAfterTest() {
		return false;
	}

	@Override
	protected String[] getHmbMappingFiles() {
		return new String[]{"schemaupdate/manytomany/UserGroup.hbm.xml"};
	}

	@Test
	@TestForIssue(jiraKey = "HHH-10247")
	public void testJoinedSubclassForeignKeyNameIsNotAutoGeneratedWhenProvided() throws Exception {
		createSchemaExport()
				.setDelimiter( ";" )
				.setFormat( true )
				.create( EnumSet.of( TargetType.SCRIPT ) );

		String fileContent = getSqlScriptOutputFileContent();
		assertThat( fileContent.toLowerCase().contains( "fk_user_group" ), is( true ) );
		assertThat( fileContent.toLowerCase().contains( "fk_group_user" ), is( true ) );
	}
}
