/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.orm.test.schemaupdate.manytomany;

import org.hamcrest.MatcherAssert;
import org.hibernate.testing.orm.junit.DomainModel;
import org.hibernate.testing.orm.junit.DomainModelScope;
import org.hibernate.testing.orm.junit.JiraKey;
import org.hibernate.testing.orm.junit.ServiceRegistry;
import org.hibernate.testing.orm.junit.Setting;
import org.hibernate.tool.hbm2ddl.SchemaExport;
import org.hibernate.tool.schema.TargetType;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.nio.file.Files;
import java.util.EnumSet;

import static org.hamcrest.core.Is.is;
import static org.hibernate.cfg.SchemaToolingSettings.HBM2DDL_AUTO;

/**
 * @author Andrea Boriero
 */
@SuppressWarnings("JUnitMalformedDeclaration")
@ServiceRegistry(settings = @Setting(name = HBM2DDL_AUTO, value = "none"))
@DomainModel(xmlMappings = "org/hibernate/orm/test/schemaupdate/manytomany/UserGroup.hbm.xml")
public class ForeignKeyNameTest {

	@Test
	@JiraKey(value = "HHH-10247")
	public void testJoinedSubclassForeignKeyNameIsNotAutoGeneratedWhenProvided(
			DomainModelScope modelScope,
			@TempDir File tmpDir) throws Exception {
		final var scriptFile = new File( tmpDir, "script.sql" );

		final var metadata = modelScope.getDomainModel();
		metadata.orderColumns( false );
		metadata.validate();

		new SchemaExport()
				.setOutputFile( scriptFile.getAbsolutePath() )
				.setDelimiter( ";" )
				.setFormat( true )
				.create( EnumSet.of( TargetType.SCRIPT ), metadata );

		String fileContent = new String( Files.readAllBytes( scriptFile.toPath() ) );
		MatcherAssert.assertThat( fileContent.toLowerCase().contains( "fk_user_group" ), is( true ) );
		MatcherAssert.assertThat( fileContent.toLowerCase().contains( "fk_group_user" ), is( true ) );
	}
}
