/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.testing;

import java.util.Objects;

import org.hibernate.Incubating;
import org.hibernate.SPI;
import org.hibernate.dialect.Dialect;
import org.hibernate.dialect.testing.internal.DialectTestContextAccess;

import static org.hibernate.SPI.Role.USE;

/// A thread-confined, database-free context for inspecting SQL generated by one
/// Dialect profile.
///
/// Close the context when the provider test is complete. Operations after
/// [#close] fail with [IllegalStateException].
///
/// @author Steve Ebersole
/// @since 8.0
@Incubating
@SPI(USE)
public final class DialectTestContext implements AutoCloseable {
	private final DialectTestContextAccess access;

	DialectTestContext(DialectTestContextAccess access) {
		this.access = Objects.requireNonNull( access, "access" );
	}

	/// The fresh Dialect owned by this context.
	public Dialect getDialect() {
		return access.getDialect();
	}

	/// Translate simple HQL using default request options.
	public SqlGenerationResult translate(String hql) {
		return translate( SqlGenerationRequest.hql( hql ) );
	}

	/// Translate HQL through Hibernate's SQM and SQL AST pipelines.
	public SqlGenerationResult translate(SqlGenerationRequest request) {
		return access.translate( Objects.requireNonNull( request, "request" ) );
	}

	/// Generate create and drop commands for the fixed mapping model.
	public SchemaGenerationResult generateSchema() {
		return access.generateSchema();
	}

	@Override
	public void close() {
		access.close();
	}
}
