CREATE SCHEMA "cat.cat"
CREATE TABLE "cat.cat"."cat.master" (ID INT NOT NULL, TT INT, CONSTRAINT MASTER_PK PRIMARY KEY (ID))
CREATE TABLE "cat.cat"."cat.child" (CHILDID INT NOT NULL, MASTERREF INT, CONSTRAINT CHILD_PK PRIMARY KEY (CHILDID), CONSTRAINT MASTERREF_FK FOREIGN KEY (MASTERREF) references "cat.cat"."cat.master"(ID))