/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.orm.test.id;

import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.generator.BeforeExecutionGenerator;
import org.hibernate.generator.EventType;
import org.hibernate.id.IdentityGenerator;

import org.hibernate.testing.orm.junit.DomainModel;
import org.hibernate.testing.orm.junit.JiraKey;
import org.hibernate.testing.orm.junit.SessionFactory;
import org.hibernate.testing.orm.junit.SessionFactoryScope;
import org.junit.jupiter.api.Test;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Test for HHH-20567: PropertyValueException when using a mixed-timing generator
 * with @Version field and manually assigned IDs.
 *
 * A mixed-timing generator can either auto-generate IDs (when ID is null) or
 * use manually assigned IDs (when ID is set). When the entity has a @Version field
 * and the ID is manually assigned, Hibernate should treat it as transient, not detached.
 */
@DomainModel(
		annotatedClasses = {
				MixedTimingGeneratorWithVersionTest.Item.class
		}
)
@SessionFactory
@JiraKey("HHH-20567")
public class MixedTimingGeneratorWithVersionTest {

	@Test
	public void testAutoGeneratedId(SessionFactoryScope scope) {
		scope.inTransaction(
				session -> {
					Item item = new Item();
					item.setName("Auto Generated Item");
					// ID is null, so generator will use DB IDENTITY
					session.persist(item);
					session.flush();

					assertNotNull(item.getId(), "ID should be auto-generated");
					assertEquals(0L, item.getVersion(), "Version should be initialized to 0");
				}
		);
	}

	@Test
	public void testManuallyAssignedId(SessionFactoryScope scope) {
		scope.inTransaction(
				session -> {
					Item item = new Item();
					item.setId(500);  // Manually assign ID
					item.setName("Manual Item");
					// Version is NOT set - should be initialized by Hibernate

					// This should NOT throw PropertyValueException
					// The entity is transient (new), not detached
					session.persist(item);
					session.flush();

					assertEquals(500, item.getId(), "ID should be the manually assigned value");
					assertEquals(0L, item.getVersion(), "Version should be initialized to 0");
				}
		);

		// Verify the item was persisted correctly
		scope.inTransaction(
				session -> {
					Item item = session.find(Item.class, 500);
					assertNotNull(item, "Item should be found in database");
					assertEquals("Manual Item", item.getName());
					assertEquals(0L, item.getVersion());
				}
		);
	}


	@Entity(name = "Item")
	@Table(name = "MIXED_TIMING_ITEMS")
	public static class Item {
		@Id
		@org.hibernate.annotations.GenericGenerator(type = MixedTimingGenerator.class)
		private Integer id;

		private String name;

		@Version
		private Long version;

		public Integer getId() {
			return id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public Long getVersion() {
			return version;
		}

		public void setVersion(Long version) {
			this.version = version;
		}
	}

	/**
	 * Custom ID generator implementing the mixed-timing pattern.
	 * Returns true for auto-generated IDs (null) and false for manually assigned IDs.
	 */
	public static class MixedTimingGenerator extends IdentityGenerator implements BeforeExecutionGenerator {

		@Override
		public boolean generatedOnExecution() {
			return true; // class-level: registers as mixed-timing
		}

		@Override
		public boolean generatedOnExecution(Object entity, SharedSessionContractImplementor session) {
			Object id = session.getEntityPersister(null, entity).getIdentifier(entity, session);
			return id == null; // true → DB IDENTITY, false → use assigned id
		}

		@Override
		public Object generate(SharedSessionContractImplementor session, Object entity,
							Object currentValue, EventType eventType) {
			return session.getEntityPersister(null, entity).getIdentifier(entity, session);
		}
	}
}
