/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.boot.jaxb.hbm.transform;

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import org.hibernate.boot.jaxb.hbm.spi.EntityInfo;
import org.hibernate.boot.jaxb.hbm.spi.JaxbHbmCompositeAttributeType;
import org.hibernate.boot.jaxb.hbm.spi.JaxbHbmDiscriminatorSubclassEntityType;
import org.hibernate.boot.jaxb.hbm.spi.JaxbHbmHibernateMapping;
import org.hibernate.boot.jaxb.hbm.spi.JaxbHbmJoinedSubclassEntityType;
import org.hibernate.boot.jaxb.hbm.spi.JaxbHbmRootEntityType;
import org.hibernate.boot.jaxb.hbm.spi.JaxbHbmUnionSubclassEntityType;
import org.hibernate.boot.jaxb.mapping.spi.JaxbEmbeddableImpl;
import org.hibernate.boot.jaxb.mapping.spi.JaxbEntityImpl;
import org.hibernate.boot.jaxb.mapping.spi.JaxbEntityMappingsImpl;
import org.hibernate.boot.jaxb.spi.Binding;

import static org.hibernate.internal.util.StringHelper.isNotEmpty;

import static org.hibernate.internal.util.collections.CollectionHelper.arrayList;

/**
 * @author Steve Ebersole
 */
public class XmlPreprocessor {

	public static List<Binding<JaxbEntityMappingsImpl>> preprocessHbmXml(
			List<Binding<JaxbHbmHibernateMapping>> hbmXmlBindings,
			TransformationState transformationState) {
		final List<Binding<JaxbEntityMappingsImpl>> mappingBindings =
				arrayList( hbmXmlBindings.size() );
		hbmXmlBindings.forEach( hbmXmlBinding ->
				preProcessHbmXml( hbmXmlBinding, mappingBindings, transformationState ) );
		return mappingBindings;
	}

	private static void preProcessHbmXml(
			Binding<JaxbHbmHibernateMapping> hbmXmlBinding,
			List<Binding<JaxbEntityMappingsImpl>> mappingBindings,
			TransformationState transformationState) {
		final var hbmRoot = hbmXmlBinding.getRoot();
		final var mappingRoot = new JaxbEntityMappingsImpl();
		transformationState.getJaxbRootMap().put( hbmRoot, mappingRoot );

		final var origin = hbmXmlBinding.getOrigin();
		mappingRoot.setDescription( String.format(
				Locale.ROOT,
				"Generated by Hibernate HbmXmlTransformer from %s (%s)",
				origin.getName(),
				origin.getType()
		) );
		mappingBindings.add( new Binding<>( mappingRoot, origin ) );

		final Set<String> seenEmbeddableClasses = new HashSet<>();

		hbmRoot.getTypedef().forEach( hbmTypeDef ->
				transformationState.getTypeDefMap().put( hbmTypeDef.getName(), hbmTypeDef ) );

		hbmRoot.getClazz().forEach( hbmRootEntity ->
				preProcessRooEntity( hbmRootEntity, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );

		hbmRoot.getSubclass().forEach( hbmSubclass ->
				preProcessSubclass( hbmSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );

		hbmRoot.getJoinedSubclass().forEach( hbmSubclass ->
				preProcessJoinedSubclass( hbmSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );

		hbmRoot.getUnionSubclass().forEach( hbmSubclass ->
				preProcessUnionSubclass( hbmSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );
	}

	private static void preProcessRooEntity(
			JaxbHbmRootEntityType hbmRootEntity,
			JaxbHbmHibernateMapping hbmRoot,
			JaxbEntityMappingsImpl mappingRoot,
			TransformationState transformationState,
			Set<String> seenEmbeddableClasses) {
		final var mappingEntity = new JaxbEntityImpl();
		mappingRoot.getEntities().add( mappingEntity );
		commonEntityPreprocessing( hbmRootEntity, hbmRoot, mappingRoot, transformationState, mappingEntity, seenEmbeddableClasses );

		hbmRootEntity.getSubclass().forEach( hbmSubclass ->
				preProcessSubclass( hbmSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );

		hbmRootEntity.getJoinedSubclass().forEach( hbmSubclass ->
				preProcessJoinedSubclass( hbmSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );

		hbmRootEntity.getUnionSubclass().forEach( hbmSubclass ->
				preProcessUnionSubclass( hbmSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );
	}

	private static void commonEntityPreprocessing(
			EntityInfo hbmEntity,
			JaxbHbmHibernateMapping hbmRoot,
			JaxbEntityMappingsImpl mappingRoot,
			TransformationState transformationState,
			JaxbEntityImpl mappingEntity,
			Set<String> seenEmbeddableClasses) {
		// apply some basic info to the mapping.xsd entity
		TransformationHelper.transfer( hbmEntity::getEntityName, mappingEntity::setName );
		TransformationHelper.transfer( hbmEntity::getName, mappingEntity::setClazz );

		final String entityName = TransformationHelper.determineEntityName( hbmEntity, hbmRoot );
		transformationState.getEntityToHbmXmlMap().put( entityName, hbmRoot );
		transformationState.getEntityToMappingXmlMap().put( entityName, mappingRoot );
		transformationState.getHbmEntityByName().put( entityName, hbmEntity );
		transformationState.getMappingEntityByName().put( entityName, mappingEntity );

		//noinspection unchecked
		collectComponentTypes( hbmEntity.getAttributes(), mappingRoot, seenEmbeddableClasses );
	}

	private static void collectComponentTypes(List<Serializable> attributes, JaxbEntityMappingsImpl mappingRoot,
			Set<String> seenEmbeddableClasses) {
		for ( Object attribute : attributes ) {
			if ( attribute instanceof JaxbHbmCompositeAttributeType compositeAttribute ) {
				final String className = compositeAttribute.getClazz();
				if ( isNotEmpty( className ) && seenEmbeddableClasses.add( className ) ) {
					final var embeddable = new JaxbEmbeddableImpl();
					embeddable.setClazz( className );
					mappingRoot.getEmbeddables().add( embeddable );
				}
				collectComponentTypes( compositeAttribute.getAttributes(), mappingRoot, seenEmbeddableClasses );
			}
		}
	}

	private static void preProcessSubclass(
			JaxbHbmDiscriminatorSubclassEntityType hbmSubclass,
			JaxbHbmHibernateMapping hbmRoot,
			JaxbEntityMappingsImpl mappingRoot,
			TransformationState transformationState,
			Set<String> seenEmbeddableClasses) {
		final var mappingEntity = new JaxbEntityImpl();
		mappingRoot.getEntities().add( mappingEntity );
		commonEntityPreprocessing( hbmSubclass, hbmRoot, mappingRoot, transformationState, mappingEntity, seenEmbeddableClasses );
		hbmSubclass.getSubclass().forEach( hbmSubclassSubclass ->
				preProcessSubclass( hbmSubclassSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );
	}

	private static void preProcessJoinedSubclass(
			JaxbHbmJoinedSubclassEntityType hbmSubclass,
			JaxbHbmHibernateMapping hbmRoot,
			JaxbEntityMappingsImpl mappingRoot,
			TransformationState transformationState,
			Set<String> seenEmbeddableClasses) {
		final var mappingEntity = new JaxbEntityImpl();
		mappingRoot.getEntities().add( mappingEntity );
		commonEntityPreprocessing( hbmSubclass, hbmRoot, mappingRoot, transformationState, mappingEntity, seenEmbeddableClasses );
		hbmSubclass.getJoinedSubclass().forEach( hbmSubclassSubclass ->
				preProcessJoinedSubclass( hbmSubclassSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );
	}

	private static void preProcessUnionSubclass(
			JaxbHbmUnionSubclassEntityType hbmSubclass,
			JaxbHbmHibernateMapping hbmRoot,
			JaxbEntityMappingsImpl mappingRoot,
			TransformationState transformationState,
			Set<String> seenEmbeddableClasses) {
		final var mappingEntity = new JaxbEntityImpl();
		mappingRoot.getEntities().add( mappingEntity );
		commonEntityPreprocessing( hbmSubclass, hbmRoot, mappingRoot, transformationState, mappingEntity, seenEmbeddableClasses );
		hbmSubclass.getUnionSubclass().forEach( hbmSubclassSubclass ->
				preProcessUnionSubclass( hbmSubclassSubclass, hbmRoot, mappingRoot, transformationState, seenEmbeddableClasses ) );
	}
}
