############################################################################
# Hibernate Tools, Tooling for your Hibernate Projects                     #
#                                                                          #
# Copyright 2004-2025 Red Hat, Inc.                                        #
#                                                                          #
# Licensed under the Apache License, Version 2.0 (the "License");          #
# you may not use this file except in compliance with the License.         #
# You may obtain a copy of the License at                                  #
#                                                                          #
#     http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                          #
# Unless required by applicable law or agreed to in writing, software      #
# distributed under the License is distributed on an "AS IS" basis,        #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
# See the License for the specific language governing permissions and      #
# limitations under the License.                                           #
############################################################################
CREATE TABLE "orders" ( "ordId" INT generated by default as identity (start with 1) NOT NULL, "ordDesc" VARCHAR(10), "ordVersion" TINYINT DEFAULT 0 NOT NULL, PRIMARY KEY ("ordId"))
CREATE TABLE "orderItems" ( "oiId" INT generated by default as identity (start with 1) NOT NULL, "oiOrdId" INT NOT NULL, "oiDesc" VARCHAR(10), "oiVersion" TINYINT DEFAULT 0 NOT NULL, PRIMARY KEY ("oiId"))
ALTER TABLE "orderItems" ADD CONSTRAINT "orderorderitemfk" FOREIGN KEY ("oiOrdId") REFERENCES "orders" ("ordId") ON DELETE CASCADE ON UPDATE CASCADE
CREATE TABLE "dummy" ( "duId" INT generated by default as identity (start with 1) NOT NULL, "duVersion" TINYINT DEFAULT 0 NOT NULL, PRIMARY KEY ("duId"))