CREATE TABLE MASTER (ID CHAR NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID))
CREATE TABLE CHILD  (CHILDID CHAR NOT NULL, MASTERREF CHAR, PRIMARY key (CHILDID), FOREIGN KEY (MASTERREF) REFERENCES MASTER(ID))		
