services:
  tidb:
    image: ${TIDB_IMAGE:-docker.io/pingcap/tidb:v8.5.7@sha256:07d9116fad581d6c93d49a789a944995b499dbc284f5d981750de045e67d9e06}
    container_name: tidb
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:10080/status || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15
  mysql-client:
    image: docker.io/library/mysql:9.7@sha256:ae269281abffe401d65f04cb54d45a069a495b8174b9c0a815e502fed7fa0370
    entrypoint: [ "/bin/sh", "-c" ]
    depends_on:
      tidb:
        condition: service_healthy
    command:
      - |
        mysql -h tidb -P 4000 -uroot -e "$TIDB_DB_SETUP"
        echo "Setup complete. Keeping container alive for Compose..."
        tail -f /dev/null
