= Type System

The Hibernate "type system" is multi-layered....


== JavaTypeDescriptor

At the lowest level we have `JavaTypeDescriptor` which describes information about Java types
(`Class`).  This level makes no distinctions based about the nature of the type.  E.g. it does
not understand that `Person` is an entity.


== Domain type system (JPA/SQM)

The JPA type system is an "unmapped" model, meaning that it has no mapping information -
no references to tables, columns, etc.  The base contract for Hibernate's extension to the
JPA model is `org.hibernate.metamodel.model.domain.DomainType`.

Hibernate's Semantic Query Model (SQM) is defined in terms of these JPA type extensions,
through the `org.hibernate.query.sqm.SqmExpressable` contract allowing parts of the application's
domain model to be used as part of an SQM tree.


[plantuml,SqmTypeSystem,png]
.Domain (JPA/SQM) type system
....
@startuml
skinparam handwritten true

interface DomainType
interface SimpleDomainType
interface BasicDomainType
interface AnyMappingDomainType
interface ManagedDomainType
interface EmbeddableDomainType
interface IdentifiableDomainType
interface EntityDomainType
interface MappedSuperclassDomainType

interface SqmExpressable
interface SqmPathSource
interface PersistentAttribute
interface SingularPersistentAttribute
interface PluralPersistentAttribute

DomainType <|-- SimpleDomainType
SimpleDomainType <|-- BasicDomainType
SimpleDomainType <|-- AnyMappingDomainType
SimpleDomainType <|-- ManagedDomainType
ManagedDomainType <|-- EmbeddableDomainType
ManagedDomainType <|-- IdentifiableDomainType
IdentifiableDomainType <|-- MappedSuperclassDomainType
IdentifiableDomainType <|-- EntityDomainType

SqmExpressable <|-- DomainType
SqmExpressable <|-- SqmPathSource

SqmPathSource <|-- EntityDomainType
SqmPathSource <|-- PersistentAttribute

PersistentAttribute <|-- SingularPersistentAttribute
PersistentAttribute <|-- PluralPersistentAttribute

@enduml
....



== Mapping model

TBC...

[plantuml,SqmTypeSystem,png]
.Mapping type system
....
@startuml
skinparam handwritten true

interface ValueMapping
interface BasicType
interface ModelPart
interface ModelPartContainer

ValueMapping <|-- BasicType
ValueMapping <|-- ModelPart
ModelPartContainer <|-- EntityMapping
ModelPartContainer <|-- EmbeddableMapping
ModelPart <|-- EmbeddableMapping
ModelPart <|-- AttributeMapping
ModelPart <|-- EntityIdentifierMapping
ModelPart <|-- EntityVersionMapping
ModelPart <|-- EntityDiscriminatorMapping


@enduml
....

[source,JAVA]
----
interface ValueMapping {
	Type getMappingType();
	<X> X getCapability(Class<X> capabilityType);
	...
}

interface ModelPart extends ValueMapping {
	<T> DomainResult<T> createDomainResult(...);
	void applySqlSelections(...);
	...
}

interface ModelPartContainer extends ValueMapping {
    void visitSubMappings(Consumer<ModelPart> action);
    ModelPart findSubPart(String name);
    ModelPart resolveSubPart(String path);
}

interface EntityMapping extends ModelPartContainer {
    default EntityPersister getEntityPersister() {
    	return getCapability( EntityPersister.class );
    }

    default EntityIdentifierMapping getIdentifierMapping() {
    	return getCapability( EntityIdentifierMapping.class );
    }

    default EntityVersionMapping getVersionMapping() {
    	return getCapability( EntityVersionMapping.class );
    }

    default EntityDiscriminatorMapping getDiscriminatorMapping() {
    	return getCapability( EntityDiscriminatorMapping.class );
    }

    ...
}

interface EmbeddableMapping extends ModelPart, ModelPartContainer {
	...
}
----


`org.hibernate.metamodel.model.mapping` contract corollaries in `org.hibernate.persister.walking`:

EntityMapping::EntityDefinition
EmbeddableMapping::CompositionDefinition
AttributeMapping::AttributeDefinition
EntityIdentifierMapping::EntityIdentifierDefinition
