== 6.0 Alpha2 announcement

We are excited to announce the release of 6.0 Final.  6.0 is now considered stable and ready for
production use.

=== Synopsis

The main design goal for 6.0 is to improve the performance of Hibernate's interactions with JDBC.  High-load performance
testing showed that Hibernate's approach of reading values from the ResultSet by name to be the a big obstacle to scaling
through-put.  6.0 is essentially about converting Hibernate to read-by-name to read-by-position.  That seemingly
minor change has major implications however.


This obviously affects the actual calls to ResultSet (resolving name to position).  But it also has
implications on the SQL generated; since we do not need the selection alias to read back the selection, we no longer
render the alias which, combined with other SQL generation improvements reduces the size of the query string sent to the
database which help better optimize sending the query "across the wire" as well as the database optimizer's ability to
parse the query (smaller strings parse faster).


=== Type system

6.0 required some pretty major changes to a few Hibernate contracts, especially Hibernate's "type system", to account
for read-by-position rather than read-by-name.

Alpha1 contains the initial proposal for handling various "basic value" customizations including `BasicType`,
`UserType`, `@SqlType`, `@SqlTypeDescriptor`, `@SqlTypeRegistration`, `@JavaTypeDescriptor`, `@JavaTypeRegistration`.

The descriptors for managed-types and collections have also changed significantly.  See `RuntimeModelDescriptorFactory`
and `RuntimeModelDescriptorClassResolver`

Supported:

basic values:: fully supported
embeddable values:: fully supported
one-to-one:: supported (see note about "non-aggregated composite identifiers")
many-to-one:: fully supported
one-to-many:: supported except:
* adding values to an existing collection
* removing values from an existing collection
* non-bidirectional mappings using a join table works, not using a join table does not
many-to-many:: partial support
any:: not yet supported
many-to-any:: not yet supported


Known limitations:
* extra-lazy collection fetching is, for the most part, not yet implemented
* "non-aggregated composite identifiers" (`@IdClass`) are not yet supported
* post-insert identifier generation (IDENTITY, etc) not yet implemented
* inheritance is not yet implemented (limited support for discriminator-based)
* support for `@SQLInsert`, `@SQLDelete`, etc not yet implemented


See the `design/type-customization.adoc` document in the root of the project.  It
describes how to customize Hibernate's type system and how Hibernate maps values
to the database.  This document will eventually become a chapter in the user guide.



=== Queries

Hibernate now uses Antlr v4 for interpreting HQL queries.  Antlr v4 is significantly faster than Antlr v2, which
is what Hibernate has been using up through (and including) 5.x.

We also cleaned up and refactored the grammars to perform better.

Quite a few new HQL language features are planned for 6.0.  Alpha1  includes the following:

* Nested dynamic-instantiations - use dynamic-instantiation as an argument to another dynamic-instantiation.  E.g. `select new DTO( a.id, new AnotherDTO( a.name, .... ), ... ) ...`
* Expanded literal type support using JDBC escape-like syntax.  E.g. `where e.startTime < {ts '1999-01-01 00:00:00.0'}`
* Better support for custom query functions.  Better, but different - suppliers of custom functions will need to update to the new signatures designed to work with an AST

Note also that Hibernate's legacy `org.hibernate.Criteria` support has been removed.  `Query#iterate`
has also been removed.

Known limitations:
* support for criteria queries not not yet implemented
* support for native queries not not yet implemented


=== Artifacts

Notice we have moved all Hibernate ORM artifacts to a new groupdId - from `org.hibernate` to `org.hibernate.orm`

relocated::`hibernate-envers` has been folded into the `hibernate-core` module to provide better integration - easier
and more powerful for users.
disabled:: The following artifacts are temporarily disabled
* `hibernate-spatial`
* `hibernate-ehcache`
* `hibernate-infinispan`
* `hibernate-jcache`
removed:: we have removed the following artifacts:
* `hibernate-entitymanager` - JPA support has been part of `hibernate-core` since 5.0
* `hibernate-java8` - Java 8 support (Instant, etc) has been part of `hibernate-core` since 4.3(?)
* `hibernate-envers` - Support for Envers is made part of `hibernate-core` as of 6.0



=== More information

See the user guide and migration guide for more information

Gitter, IRC, ...


=== Next step

The plan for Alpha2 includes:

* Inheritance
* Complete association mapping support
* Criteria
