package org.hibernate.testing.sqlparser;

public class Column {

	public Name name;
	public String type;
	public int length;
	public int decimals;
	public boolean notNull;
	public Object check;
	public boolean generatedByDefaultAsIdentity;

	/**
	 * {@inheritDoc}
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder( name.toString() );
		builder.append( ' ' ).append( type );
		if ( length > 0 ) {
			builder.append( "( " ).append( length );
			if ( decimals > 0 ) {
				builder.append( ", " ).append( decimals );
			}
			builder.append( " )" );
		}
		if ( generatedByDefaultAsIdentity ) {
			builder.append( " GENERATED BY DEFAULT AS IDENTITY" );
		}
		if ( notNull ) {
			builder.append( " NOT NULL" );
		}
		if ( check != null ) {
			builder.append( " CHECK " ).append( check );
		}
		return builder.toString();
	}
}
