/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.annotations;

/**
 * Specifies the source of a generated {@link java.sql.Timestamp}.
 * <p>
 * Timestamps are generated by calling methods of
 * {@link org.hibernate.type.descriptor.java.VersionJavaType}.
 *
 * @see Source
 *
 * @author Hardy Ferentschik
 */
public enum SourceType {
	/**
	 * The virtual machine {@linkplain java.time.Clock#instant()
	 * current instance} is the source of the generated timestamp.
	 */
	VM,

	/**
	 * The database {@code current_timestamp} function (or equivalent)
	 * is the source of the generated timestamp.
	 */
	DB;

	/**
	 * The corresponding {@link org.hibernate.type.BasicType} name.
	 *
	 * @return The corresponding type name.
	 */
	public String typeName() {
		return this == SourceType.DB ? "dbtimestamp" : "timestamp";
	}
}
