services:
  oracle:
    image: ${DB_IMAGE_ORACLE_23:-docker.io/gvenzl/oracle-free:23@sha256:e2763af84ecc345d48e4e3fe7999d0b7bb57885b6e0166051acd5f62e27eb605}
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: Oracle18
    cap_add:
      - NET_RAW
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 60
    shm_size: 1g
