/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.tool.ant.GenericExport;

import org.hibernate.tool.ant.test.utils.AntUtil;
import org.hibernate.tool.ant.test.utils.FileUtil;
import org.hibernate.tool.ant.test.utils.JdbcUtil;
import org.hibernate.tool.ant.test.utils.ResourceUtil;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class TestCase {

	@TempDir
	public File outputFolder = new File("output");

	private File destinationDir = null;
	private File resourcesDir = null;

	@BeforeEach
	public void setUp() {
		destinationDir = new File(outputFolder, "destination");
		assertTrue(destinationDir.mkdir());
		resourcesDir = new File(outputFolder, "resources");
		assertTrue(resourcesDir.mkdir());
		JdbcUtil.createDatabase(this);
	}

	@AfterEach
	public void tearDown() {
		JdbcUtil.dropDatabase(this);
	}

	@Test
	public void testGenericExport() {

		String[] resources = new String[] {"build.xml", "TopDown.hbm.xml", "generic-class.ftl"};
		ResourceUtil.createResources(this, resources, resourcesDir);
		File buildFile = new File(resourcesDir, "build.xml");
		ResourceUtil.createResources(this, new String[] { "/hibernate.properties" }, resourcesDir);

		AntUtil.Project project = AntUtil.createProject(buildFile);
		project.setProperty("destinationDir", destinationDir.getAbsolutePath());
		project.setProperty("resourcesDir", resourcesDir.getAbsolutePath());

		File xTopDownJava = new File(destinationDir, "Xorg/hibernate/tool/hbm2x/ant/TopDown.java");
		assertFalse(xTopDownJava.exists());

		File topDownJava = new File(destinationDir, "org/hibernate/tool/hbm2x/ant/TopDown.java");
		assertFalse(topDownJava.exists());

		File topDownQuote = new File(destinationDir, "org/hibernate/tool/hbm2x/ant/TopDown.quote");
		assertFalse(topDownQuote.exists());

		File topDownPojo = new File(destinationDir, "org/hibernate/tool/hbm2x/ant/TopDown.pojo");
		assertFalse(topDownPojo.exists());

		project.executeTarget("testGenericExport");

		assertTrue(xTopDownJava.exists());
		assertTrue( FileUtil
				.findFirstString("TopDown", xTopDownJava)
				.contains("TopDown generated by hbm2java"));

		assertTrue(topDownJava.exists());
		assertTrue(FileUtil
				.findFirstString("TopDown", topDownJava)
				.contains("TopDown generated by hbm2java"));

		assertTrue(topDownQuote.exists());
		assertTrue(FileUtil
				.findFirstString("TopDown", topDownQuote)
				.contains("pojo=TopDown"));

		assertTrue(topDownPojo.exists());
		assertTrue(FileUtil
				.findFirstString("TopDown", topDownPojo)
				.contains("TopDown generated by hbm2java"));
	}


}
