/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.orm.test.schemaupdate.inheritance;

import java.io.File;
import java.util.EnumSet;

import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.spi.MetadataImplementor;
import org.hibernate.orm.test.schemaupdate.BaseSchemaUnitTestCase;
import org.hibernate.tool.schema.TargetType;

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

/**
 * @author Andrea Boriero
 */
public class ForeignKeySubclassNameTest extends BaseSchemaUnitTestCase {

	@Override
	protected boolean createSqlScriptTempOutputFile() {
		return true;
	}

	@Override
	protected boolean dropSchemaAfterTest() {
		return false;
	}

	@Override
	protected String[] getHmbMappingFiles() {
		return new String[] {
				"schemaupdate/inheritance/Payment.hbm.xml"
		};
	}
	@Test
	public void testSubclassForeignKeyNameIsNotAutoGeneratedWhenProvided() throws Exception {
		createSchemaUpdate()
				.setHaltOnError( true )
				.setDelimiter( ";" )
				.setFormat( true )
				.execute( EnumSet.of( TargetType.SCRIPT ) );

		final String fileContent = getSqlScriptOutputFileContent();
		assertThat( fileContent.toLowerCase().contains( "fk_cc_pay" ), is( true ) );
	}
}
