services:
  cockroach:
    image: ${DB_IMAGE_COCKROACHDB_23_2:-cockroachdb/cockroach:v23.2.28@sha256:ce30fa656269cec938c951fc1cb313de1c476c1eed4fe8eab77ec52c81f0ed01}
    container_name: cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command:
      - start-single-node
      - --insecure
      - --store=type=mem,size=0.25
      - --advertise-addr=localhost
      - |
        --log=sinks:
          stderr:
            channels: all
            filter: ERROR
            redact: false
            exit-on-error: true
    deploy:
      resources:
        limits:
          memory: 6g
    healthcheck:
      test: ["CMD-SHELL", "./cockroach sql --insecure -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
