services:
  cockroach:
    image: ${DB_IMAGE_COCKROACHDB_24_3:-cockroachdb/cockroach:v24.3.3@sha256:cb96e5cba54fa1b876d83736a1eb2c3455ae25e13711dc1b6ce463db51395f5c}
    container_name: cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command:
      - start-single-node
      - --insecure
      - --store=type=mem,size=0.25
      - --advertise-addr=localhost
      - |
        --log=sinks:
          stderr:
            channels: all
            filter: ERROR
            redact: false
            exit-on-error: true
    deploy:
      resources:
        limits:
          memory: 6g
    healthcheck:
      test: ["CMD-SHELL", "./cockroach sql --insecure -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
