services:
  mysql:
    image: ${DB_IMAGE_MYSQL_9_2:-docker.io/library/mysql:9.2@sha256:0596fa224cdf3b3355ce3ddbfd7ce77be27ec9e51841dfc5d2e1c8b81eea69d2}
    container_name: mysql
    environment:
      MYSQL_USER: hibernate_orm_test
      MYSQL_PASSWORD: hibernate_orm_test
      MYSQL_ROOT_PASSWORD: hibernate_orm_test
      MYSQL_DATABASE: hibernate_orm_test
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_as_cs
      - --log-bin-trust-function-creators=1
      - --lower_case_table_names=2
      - --init-connect=SET character_set_client='utf8mb4';SET character_set_results='utf8mb4';SET character_set_connection='utf8mb4';SET collation_connection='utf8mb4_0900_as_cs';
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-phibernate_orm_test"]
      interval: 5s
      timeout: 5s
      retries: 12
