services:
  mariadb:
    image: ${MARIADB_IMAGE:-docker.io/library/mariadb:13.0@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d}
    container_name: mariadb
    environment:
      MARIADB_USER: hibernate_orm_test
      MARIADB_PASSWORD: hibernate_orm_test
      MARIADB_DATABASE: hibernate_orm_test
      MARIADB_ROOT_PASSWORD: hibernate_orm_test
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
      - --lower_case_table_names=2
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 10
