/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.collection.spi;

import org.hibernate.Incubating;

/// A row identifier for an identifier-bag's collectio-id which is generated by
/// collection pre-insert processing after the delta has been frozen.
///
/// @param collection The collection which owns the identifier
/// @param entryPosition The current entry position used to obtain the identifier
///
/// @see org.hibernate.annotations.CollectionId
///
/// @since 8.0
/// @author Steve Ebersole
@Incubating
public record DeferredCollectionIdentifier(
		PersistentCollection<?> collection,
		int entryPosition) {

	/// Resolve the generated identifier after collection pre-insert processing.
	public Object resolve() {
		final Object identifier = collection.getIdentifier( null, entryPosition );
		if ( identifier == null ) {
			throw new IllegalStateException( "Collection row identifier has not been generated" );
		}
		return identifier;
	}
}
