= Hibernate ORM Gradle Plugin

A Gradle plugin for introducing Hibernate tasks and capabilities into a build.


== Set up

[source,groovy]
----
plugins {
  id("org.hibernate.orm") version "<version-to-use>"
}

// HibernateOrmSpec
hibernate {
    ...
}
----


== DSL

The `hibernate` DSL extension is the main entry into configuring the plugin

[source,groovy]
----
hibernate {
}
----

It defines configuration options:

useSameVersion:: Specifies whether to have the plugin inject an `implementation` dependency on `hibernate-core`, implicitly using
    the same version as the plugin.  The default is true.  If you'd prefer to use a different version, set this to false and define
    the dependency on `hibernate-core` as you normally would.
sourceSet:: The source-set containing the project's domain model.  Only one source-set is supported, although all languages (Java, Kotlin, etc)
    within that source-set are considered.

It additionally defines 2 nested DSL extensions related to:

* <<enhance>>
* <<hbm-xml>>


[[enhance]]
== Bytecode Enhancement

The plugin can perform build-time enhancement of the domain classes.  This is controlled
by the `enhancement` portion of the `hibernate` DSL extension.

To enable enhancement, reference the DSL extension:

[source,groovy]
----
hibernate {
    enhancement {
    }
}
----

Enhancement has a few options to control what enhancements take place. These are the defaults:

[source,groovy]
----
hibernate {
    enhancement {
        enableLazyInitialization = true
        enableDirtyTracking = true
        enableAssociationManagement = false
        enableExtendedEnhancement = false
    }
}
----

All options are deprecated for removal.

[[hbm-xml]]
== Legacy `hbm.xml` Transformation

Gradle Task Example
```
//build.gradle

import org.hibernate.orm.tooling.gradle.misc.TransformHbmXmlTask

plugins {
    ...
    id("org.hibernate.orm") version "6.6.40.Final" // replace version as appropriate
}

tasks.register("transformHbmXml", TransformHbmXmlTask) { 
    source = fileTree("path/to/your/xml/mappings") {
        include "**/*.hbm.xml"
    }
    it.renaming.get().prefix.set("transformed-") // Prefix to apply to the generated orm.xml files
    it.renaming.get().suffix.set("-transformed") // Suffix to apply to the generated orm.xml files
    it.renaming.get().extension.set("orm.xml")
    outputDirectory = project.layout.buildDirectory.dir("generated/orm")
}
```
More coming soon...
