/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.orm.test.tool.schemaupdate.inheritance;

import java.util.EnumSet;

import org.hibernate.orm.test.tool.BaseSchemaUnitTestCase;
import org.hibernate.tool.schema.TargetType;


import org.hibernate.testing.junit5.schema.SchemaScope;
import org.hibernate.testing.junit5.schema.SchemaTest;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.Is.is;

/**
 * @author Andrea Boriero
 */
public class ForeignKeySubclassNameTest extends BaseSchemaUnitTestCase {

	@Override
	protected boolean createSqlScriptTempOutputFile() {
		return true;
	}

	@Override
	protected boolean dropSchemaAfterTest() {
		return false;
	}

	@Override
	protected String[] getHmbMappingFiles() {
		return new String[] {
				"tool/schemaupdate/inheritance/Payment.hbm.xml"
		};
	}

	@SchemaTest
	public void testSubclassForeignKeyNameIsNotAutoGeneratedWhenProvided(SchemaScope schemaScope) throws Exception {
		schemaScope.withSchemaUpdate( schemaUpdate ->
								  schemaUpdate
										  .setHaltOnError( true )
										  .setDelimiter( ";" )
										  .setFormat( true )
										  .execute( EnumSet.of( TargetType.SCRIPT ) ) );

		final String fileContent = getSqlScriptOutputFileContent();
		assertThat( fileContent.toLowerCase().contains( "fk_cc_pay" ), is( true ) );
	}
}
