/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/**
 * @author Andrea Boriero
 */
public class H2IdentityColumnSupport extends IdentityColumnSupportBase {

	public static final H2IdentityColumnSupport INSTANCE = new H2IdentityColumnSupport();

	protected H2IdentityColumnSupport() {
	}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentityColumnString(int type) {
		// not null is implicit
		return "generated by default as identity";
	}

	@Override
	public String getIdentitySelectString(String table, String column, int type) {
		return "call identity()";
	}

	@Override
	public String getIdentityInsertString() {
		return "default";
	}

}
