/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity.internal;

import org.hibernate.MappingException;
import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

public class HANAIdentityColumnSupport extends IdentityColumnSupportBase {

	public static final HANAIdentityColumnSupport INSTANCE = new HANAIdentityColumnSupport();

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int type) throws MappingException {
		return "select current_identity_value() from " + table;
	}

	@Override
	public String getIdentityColumnString(int type) {
		// implicitly start with 1 increment by 1
		return "generated by default as identity";
	}

}
