/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity.internal;

import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;
import org.hibernate.dialect.identity.spi.IdentityValueRetrieval;

/**
 * @author Andrea Boriero
 */
public class Oracle12cIdentityColumnSupport extends IdentityColumnSupportBase {

	public static final Oracle12cIdentityColumnSupport INSTANCE = new Oracle12cIdentityColumnSupport();

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentityColumnString(int type) {
		return "generated by default as identity";
	}

	@Override
	public IdentityValueRetrieval getIdentityValueRetrieval() {
		return IdentityValueRetrieval.NAMED_GENERATED_KEYS;
	}

	@Override
	public String getIdentityInsertString() {
		return "default";
	}
}
