/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.dialect.identity.internal;

import org.hibernate.MappingException;
import org.hibernate.dialect.identity.spi.IdentityColumnSupportBase;

/**
 * Identity column support for Spanner.
 */
public class SpannerIdentityColumnSupport extends IdentityColumnSupportBase {
	public static final SpannerIdentityColumnSupport INSTANCE = new SpannerIdentityColumnSupport();

	private SpannerIdentityColumnSupport() {}

	@Override
	public boolean supportsIdentityColumns() {
		return true;
	}

	@Override
	public String getIdentitySelectString(String table, String column, int type) throws MappingException {
		throw new MappingException(
				getClass().getName() + " does not support selecting the last generated identity value");
	}

	@Override
	public String getIdentityColumnString(int type) {
		return "not null generated by default as identity (bit_reversed_positive)";
	}
}
