services:
  db2spatial:
    image: ${DB_IMAGE_DB2_SPATIAL:-docker.io/ibmcom/db2:11.5.5.0@sha256:9577b5f306efdbc2792297275b8331059d0818eb70700d8106d986da2908d45c}
    container_name: db2spatial
    privileged: true
    ports:
      - "50000:50000"
    environment:
      DB2INSTANCE: orm_test
      DB2INST1_PASSWORD: orm_test
      DBNAME: orm_test
      LICENSE: accept
      AUTOCONFIG: "false"
      ARCHIVE_LOGS: "false"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
    volumes:
      - ../../build-config/db2_spatial/ewkt.sql:/conf/ewkt.sql
    shm_size: 2g
    healthcheck:
      test: ["CMD-SHELL", "su - orm_test -c 'source ~/sqllib/db2profile && db2 connect to orm_test && db2 connect reset'"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 200s
