= Post-release Steps

Whether releasing <<./manual-release-process.adoc>>[manually] or via the <<./jenkins-release-process.adoc>>[Jenkins job],
there are a number of "post" release steps that need to be performed...

1. Complete release process on https://oss.sonatype.org/[OSSRH]
2. Write release announcement blog post (see http://in.relation.to/README/[Blog site instructions])
3. Write release descriptor as part of the https://github.com/hibernate/hibernate.org[website]
.. If this is the first release in a new family/series, some additional steps are required:
... Create a directory `_data/projects/orm/releases/${family_name}` and create a file named `series.yml`.  E.g. for 4.3.0.Final you'd be adding _data/projects/orm/releases/4.3/series.yml
... Create a directory `orm/releases/${family_name}` and create a file named `index.adoc`.  E.g. for 4.3.0.Final you'd be adding orm/releases/4.3/index.adoc
... Create a directory `orm/documentation/${family_name}` and create a file named `index.adoc`.  E.g. for 4.3.0.Final you'd be adding orm/documentation/4.3/index.adoc
... If this new series is to support a new JPA release, also be sure to update `orm/releases/index.adoc`
.. Create a release-specific yml file in `_data/projects/orm/releases/${family_name}`.  E.g. for 4.3.0.Final you'd add _data/projects/orm/releases/4.3/4.3.0.Final.yml
.. Add/update the XSD descriptor(s)
4. Announce the release
.. on the hibernate-dev and hibernate-announce mailing lists
.. on Twitter (use hibernate account not the dev one)
.. on https://discourse.hibernate.org/[forums]
5. Possibly update "current" symlink on the documentation server - only for a new minor or major release
