= ORM Releases
:toc:

== Where is the information

If you're looking for information about how to release Hibernate ORM, see link:../MAINTAINERS.md[MAINTAINERS.md]

If you're looking for information about how releases are implemented technically, read on.

== How it works

Releases are triggered as a link:../ci/release/Jenkinsfile[Jenkins pipeline].
Hibernate ORM also publishes SNAPSHOT releases using an automated link:../ci/snapshot-publish.Jenkinsfile[Jenkins pipeline],
which is triggered on a merge to the main branch. This job requires no user interactions.

When a release job is started,
the job coordinates with the unified Hibernate https://github.com/hibernate/hibernate-release-scripts[release scripts] in a number of stages and steps,
calling tasks on this module's link:./release.gradle[Gradle script] and leveraging link:../jreleaser.yml[JReleaser configuration].

NOTE: Snapshot releases are not relying on JReleaser but on built-in Gradle publish plugin. See the link:../ci/snapshot-publish.Jenkinsfile[Jenkinsfile].

At a high-level, this process:

* builds and verifies the individual modules
* produces artifacts and publishes them
* tags the release
* updates the website

This process has a number of "outputs"...


=== Release Artifacts (jar)

Release artifacts are published to https://central.sonatype.com/[Maven Central].  For each module, we publish:

* The "main" jar
* The sources jar
* The javadoc jar


=== Gradle Plugin

The Gradle plugin gets published to Gradle's https://plugins.gradle.org/[Plugin Portal].

See https://plugins.gradle.org/plugin/org.hibernate.orm


=== Documentation

All documentation for the release is generated, assembled and then published to the https://docs.hibernate.org/orm/[documentation server].

