[[collections]]
=== Collections
:root-project-dir: ../../../../../../..
:core-project-dir: {root-project-dir}/hibernate-core
:core-test-base: {core-project-dir}/src/test/java
:example-dir-collection: {core-test-base}/org/hibernate/orm/test/mapping/collections
:docs-base: https://docs.jboss.org/hibernate/orm/{majorMinorVersion}
:javadoc-base: {docs-base}/javadocs
:java-javadoc-base: https://docs.oracle.com/en/java/javase/11/docs/api/java.base
:extrasdir: extras/collections

Hibernate supports mapping collections (`java.util.Collection` and `java.util.Map` subtypes)
in a variety of ways.

Hibernate even allows mapping a collection as `@Basic`, but that should generally be avoided.
See <<collections-as-basic>> for details of such a mapping.

This section is limited to discussing `@ElementCollection`, `@OneToMany` and `@ManyToMany`.


[IMPORTANT]
====
Two entities cannot share a reference to the same collection instance.

Collection-valued properties do not support null value semantics.

Collections cannot be nested, meaning Hibernate does not support mapping `List<List<?>>`, for example.

Embeddables which are used as a collection element, Map value or Map key may not themselves define collections
====


[[collections-semantics]]
==== Collection Semantics

The semantics of a collection describes how to handle the collection, including

* the collection subtype to use - `java.util.List`, `java.util.Set`, `java.util.SortedSet`, etc.
* how to access elements of the collection
* how to create instances of the collection - both "raw" and "<<collection-wrapper,wrapper>>" forms.


Hibernate supports the following semantics:

ARRAY:: Object and primitive arrays.  See <<collections-array>>.
BAG:: A collection that may contain duplicate entries and has no defined ordering.  See <<collections-bag>>.
ID_BAG:: A bag that defines a per-element identifier to uniquely identify elements in the collection.  See <<collections-bag>>.
LIST:: Follows the semantics defined by `java.util.List`.  See <<collections-list>>.
SET:: Follows the semantics defined by `java.util.Set`.  See <<collections-set>>.
ORDERED_SET:: A set that is ordered by a SQL fragment defined on its mapping.  See <<collections-set>>.
SORTED_SET:: A set that is sorted according to a `Comparator` defined on its mapping.  See <<collections-set>>.
MAP:: Follows the semantics defined by `java.util.Map`.  See <<collections-map>>.
ORDERED_MAP:: A map that is ordered by keys according to a SQL fragment defined on its mapping.  See <<collections-map>>.
SORTED_MAP:: A map that is sorted by keys according to a `Comparator` defined on its mapping.  See <<collections-map>>.

By default, Hibernate interprets the defined type of the plural attribute and makes an
interpretation as to which classification it fits in to, using the following checks:

1. if an array -> ARRAY
2. if a `List` -> LIST
3. if a `SortedSet` -> SORTED_SET
4. if a `Set` -> SET
5. if a `SortedMap` -> SORTED_MAP
6. if a `Map` -> MAP
7. else `Collection` -> BAG



[[collection-list]]
==== Mapping Lists

`java.util.List` defines a collection of ordered, non-unique elements.


[[collection-list-ex]]
.Basic List Mapping
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/list/EntityWithList.java[tags=collections-list-ex]
----
====

Contrary to natural expectations, the ordering of a list is by default not maintained.
To maintain the order, it is necessary to explicitly use the `jakarta.persistence.OrderColumn` annotation.

[[NOTE]]
====
Starting in 6.0, Hibernate allows to configure the default semantics of `List` without `@OrderColumn`
via the `hibernate.mapping.default_list_semantics` setting.
To switch to the more natural LIST semantics with an implicit order-column, set the setting to `LIST`.
Beware that default LIST semantics only affects owned collection mappings.
Unowned mappings like `@ManyToMany(mappedBy = "...")` and `@OneToMany(mappedBy = "...")` do not retain the element
order by default, and explicitly annotating `@OrderColumn` for `@ManyToMany(mappedBy = "...")` mappings is illegal.

To retain the order of elements of a `@OneToMany(mappedBy = "...")` the `@OrderColumn` annotation must be applied
explicitly. In addition to that, it is important that both sides of the relationship, the `@OneToMany(mappedBy = "...")`
and the `@ManyToOne`, must be kept in sync. Otherwise, the element position will not be updated accordingly.

The default column name that stores the index is derived from the attribute name, by suffixing `_ORDER`.
====

[[collection-list-ordercolumn-ex]]
.@OrderColumn
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/list/EntityWithOrderColumnList.java[tags=collections-list-ordercolumn-ex]
----
====

Now, a column named `name_index` will be used.

Hibernate stores index values into the order-column based on the element's position in the list
with no adjustment.  The element at `names[0]` is stored with `name_index=0` and so on.  That is to say
that the list index is considered 0-based just as list indexes themselves are 0-based.  Some legacy
schemas might map the position as 1-based, or any base really.  Hibernate also defines support for such
cases using its `@ListIndexBase` annotation.

[[collection-list-indexbase-ex]]
.@ListIndexBase
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/list/EntityWithIndexBasedList.java[tags=collections-list-indexbase-ex]
----
====






[[collections-set]]
==== Mapping Sets

`java.util.Set` defines a collection of unique, though unordered elements.  Hibernate supports
mapping sets according to the requirements of the `java.util.Set`.

[[collection-set-ex]]
.Basic Set Mapping
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/set/EntityWithSet.java[tags=collections-set-ex]
----
====

Hibernate also has the ability to map sorted and ordered sets.  A sorted set orders its
elements in memory via an associated `Comparator`; an ordered set is ordered via
SQL when the set is loaded.

TIP:: An ordered set does not perform any sorting in-memory.  If an element is added
after the collection is loaded, the collection would need to be refreshed to re-order
the elements.  For this reason, ordered sets are not recommended - if the application
needs ordering of the set elements, a sorted set should be preferred.  For this reason,
it is not covered in the User Guide.  See the javadocs for `jakarta.persistence.OrderBy`
or `org.hibernate.annotations.SQLOrder` for details.

There are 2 options for sorting a set - naturally or using an explicit comparator.

A set is naturally sorted using the natural sort comparator for its elements.  Generally
this implies that the element type is `Comparable`.  E.g.



[[collection-sortedset-natural-ex]]
.@SortNatural
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/Name.java[tags=collections-name-ex]

include::{example-dir-collection}/classification/set/EntityWithNaturallySortedSet.java[tags=collections-sortedset-natural-ex]
----
====

Because `Name` is defined as `Comparable`, its `#compare` method will be used to sort the elements in this
set.

But Hibernate also allows sorting based on a specific `Comparator` implementation.  Here, e.g., we map
the `Names` as sorted by a `NameComparator`:

[[collection-sortedset-comparator-ex]]
.@SortComparator
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/NameComparator.java[tags=collections-name-comparator-ex]

include::{example-dir-collection}/classification/set/EntityWithSortedSet.java[tags=collections-sortedset-comparator-ex]
----
====

Here, instead of `Name#compare` being use for the sorting, the explicit `NameComparator` will be used
instead.






[[collections-map]]
==== Mapping Maps

A `java.util.Map` is a collection of key/value pairs.

[[collection-map-ex]]
.Simple MAP mapping
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/map/EntityWithMap.java[tags=collections-map-ex]
----
====

Hibernate has the ability to map sorted and ordered maps - the ordering and sorting applies
to the Map key.  As we saw with Sets, the use of ordered Maps is generally discouraged.

Maps may be sorted naturally -

[[collection-sortedmap-natural-ex]]
.Naturally sorted MAP mapping
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/map/EntityWithNaturallySortedMap.java[tags=example]
----
====

or via a Comparator -

[[collection-sortedmap-ex]]
.Comparator sorted MAP mapping
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/map/EntityWithSortedMap.java[tags=example]
----
====



[[collections-bag]]
==== Mapping Collections

Without any other mapping influencers, `java.util.Collection` is interpreted using BAG
semantics which means a collection that may contain duplicate entries and has no defined
ordering.

[NOTE]
====
Jakarta Persistence does not define support for BAG (nor ID_BAG) classification per-se.  The
specification does allow mapping of `java.util.Collection` attributes, but how such attributes
are handled is largely undefined.
====

[[collection-bag-ex]]
.Simple BAG mapping
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/bag/EntityWithBagAsCollection.java[tags=collections-bag-ex]
----
====

Some apps map BAG collections using `java.util.List` instead.  Hibernate provides 2 ways to handle
lists as bags.  First an explicit annotation

[[collection-bag-list-ex]]
.@Bag
====
[source, java, indent=0]
----
include::{example-dir-collection}/classification/bag/EntityWithBagAsList.java[tags=collections-bag-list-ex]
----
====

Specifically, the usage of `@Bag` forces the classification as BAG.  Even though the `names` attribute is defined
as `List`, Hibernate will treat it using the BAG semantics.

Additionally, as discussed in <<collection-list>>, the `hibernate.mapping.default_list_semantics` setting
is available to have Hibernate interpret a `List` with no `@OrderColumn` and no `@ListIndexBase` as a BAG.


An ID_BAG is similar to a BAG, except that it maps a generated, per-row identifier into the collection
table.  `@CollectionId` is the annotation to configure this identifier.

For details about defining an id-bad identifier, see the Javadocs for:

* link:{javadoc-base}/org/hibernate/annotations/CollectionId.html[@CollectionId]
* link:{javadoc-base}/org/hibernate/annotations/CollectionIdJavaClass.html[@CollectionIdJavaClass]
* link:{javadoc-base}/org/hibernate/annotations/CollectionIdJavaType.html[@CollectionIdJavaType]
* link:{javadoc-base}/org/hibernate/annotations/CollectionIdJdbcType.html[@CollectionIdJdbcType]
* link:{javadoc-base}/org/hibernate/annotations/CollectionIdJdbcTypeCode.html[@CollectionIdJdbcTypeCode]
* link:{javadoc-base}/org/hibernate/annotations/CollectionIdType.html[@CollectionIdType]


// todo (6.0) - finish




[[collections-array]]
==== Mapping Arrays

Hibernate is able to map Object and primitive arrays as collections.  Mapping an array is essentially
the same as mapping a <<collection-list,list>>.

There is a major limitation of mapping arrays to be aware of - the array cannot be lazy using
<<collection-wrapper,wrappers>>.  It can, however, be lazy via <<BytecodeEnhancement, bytecode enhancement>>
of its owner.

Note that Jakarta Persistence does not define support for arrays as plural attributes; according to the specification,
these would be mapped as binary data.






[[collections-elemental]]
==== @ElementCollection

Element collections may contain values of either basic or embeddable types.  They have a similar
lifecycle to basic/embedded attributes in that their persistence is completely managed as part of
the owner - they are created when referenced from an owner and automatically deleted when
unreferenced.  The specifics of how this lifecycle manifests in terms of database calls depends
on the <<collections-semantics,semantics>> of the mapping.

This section will discuss these lifecycle aspects using the example of mapping a collection
of phone numbers.  The examples use embeddable values, but the same aspects apply to collections
of basic values as well.

The embeddable used in the examples is a `PhoneNumber` -

[[ex-collection-elemental]]
.PhoneNumber
====
[source,java]
----
include::{example-dir-collection}/nature/elemental/Phone.java[tags=ex-collection-elemental-model,indent=0]
----
====


First, a BAG mapping -

[[ex-collection-elemental-bag]]
.Elemental BAG mapping
====
[source,java]
----
include::{example-dir-collection}/nature/elemental/ElementalBagTest.java[tags=ex-collection-elemental-model,indent=0]
----
====


[[ex-collection-elemental-bag-lifecycle]]
.Elemental BAG lifecycle
====
[source,java]
----
include::{example-dir-collection}/nature/elemental/ElementalBagTest.java[tags=ex-collection-elemental-lifecycle,indent=0]
----

[source,sql]
----
include::{extrasdir}/elemental-bag-lifecycle-example.sql[]
----
====


// todo (6.0) - finish









[[collection-nature-entity]]
===== Collections of entities

If value type collections can only form a one-to-many association between an owner entity and multiple basic or embeddable types,
entity collections can represent both <<chapters/domain/associations.adoc#associations-one-to-many,@OneToMany>> and <<chapters/domain/associations.adoc#associations-many-to-many,@ManyToMany>> associations.

From a relational database perspective, associations are defined by the foreign key side (the child-side).
With value type collections, only the entity can control the association (the parent-side), but for a collection of entities, both sides of the association are managed by the persistence context.

For this reason, entity collections can be devised into two main categories: unidirectional and bidirectional associations.
Unidirectional associations are very similar to value type collections since only the parent side controls this relationship.
Bidirectional associations are more tricky since, even if sides need to be in-sync at all times, only one side is responsible for managing the association.
A bidirectional association has an _owning_ side and an _inverse (mappedBy)_ side.

// todo (6.0) - finish







[[collection-type-ann]]
==== @CollectionType

The `@CollectionType` annotation provides the ability to use a custom
link:{javadoc-base}/org/hibernate/usertype/UserCollectionType.html[`UserCollectionType`]
implementation to influence how the collection for a plural attribute behaves.

As an example, consider a requirement for a collection with the semantics of a "unique list" - a
cross between the ordered-ness of a `List` and the uniqueness of a `Set`.  First the entity:


[[collection-type-ann-ex]]
.@CollectionType
====
[source, java, indent=0]
----
include::{example-dir-collection}/semantics/TheEntityWithUniqueList.java[tags=ex-collections-custom-type-model]
----
====

The mapping says to use the `UniqueListType` class for the mapping of the plural attribute.

[[collection-type-usertype-ex]]
.UniqueListType
====
[source, java, indent=0]
----
include::{example-dir-collection}/semantics/UniqueListType.java[tags=collections-custom-type-ex]
----
====

Most custom `UserCollectionType` implementations will want their own `PersistentCollection` implementation.

[[collection-type-usertype-wrapper-ex]]
.UniqueListWrapper
====
[source, java, indent=0]
----
include::{example-dir-collection}/semantics/UniqueListWrapper.java[tags=collections-custom-semantics-ex]
----
====

`UniqueListWrapper` is the `PersistentCollection` implementation for the "unique list" semantic.  See <<collection-wrapper>> for more details.



[[collection-type-reg-ann]]
==== @CollectionTypeRegistration

For cases where an application wants to apply the same custom type to all
plural attributes of a given classification, Hibernate also provides the
`@CollectionTypeRegistration`:

[[collection-type-usertype-registration-ex]]
.UniqueListType Registration
====
[source, java, indent=0]
----
include::{example-dir-collection}/semantics/TheEntityWithUniqueListRegistration.java[tags=ex-collections-custom-type-model]
----
====

This example behaves exactly as in <<collection-type-ann-ex>>.


[[collection-wrapper]]
==== Wrappers

As mentioned in <<collections-semantics>>, Hibernate provides its own implementations
of the Java collection types.  These are called wrappers as they wrap an underlying
collection and provide support for things like lazy loading, queueing add/remove
operations while detached, etc.  Hibernate defines the following `PersistentCollection`
implementations for each of its collection classifications -

* `PersistentArrayHolder`
* `PersistentBag`
* `PersistentIdentifierBag`
* `PersistentList`
* `PersistentMap`
* `PersistentSet`
* `PersistentSortedMap`
* `PersistentSortedSet`

ORDERED_SET uses `PersistentSet` for its wrapper and ORDERED_MAP uses `PersistentMap`.

The collections they wrap are called "raw" collections, which are generally the standard
Java implementations (`java.util.ArrayList`, etc)







[NOTE]
----
Original content below
----


[[collections-entity]]

[[collections-bag]]
==== Bags

Bags are unordered lists, and we can have unidirectional bags or bidirectional ones.

[[collections-unidirectional-bag]]
===== Unidirectional bags

The unidirectional bag is mapped using a single `@OneToMany` annotation on the parent side of the association.
Behind the scenes, Hibernate requires an association table to manage the parent-child relationship, as we can see in the following example:

[[collections-unidirectional-bag-example]]
.Unidirectional bag
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalBagTest.java[tags=collections-unidirectional-bag-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-unidirectional-bag-example.sql[]
----
====

[NOTE]
====
Because both the parent and the child sides are entities, the persistence context manages each entity separately.

The cascading mechanism allows you to propagate an entity state transition from a parent entity to its children.
====

By marking the parent side with the `CascadeType.ALL` attribute, the unidirectional association lifecycle becomes very similar to that of a value type collection.

[[collections-unidirectional-bag-lifecycle-example]]
.Unidirectional bag lifecycle
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalBagTest.java[tags=collections-unidirectional-bag-lifecycle-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-unidirectional-bag-lifecycle-example.sql[]
----
====

In the example above, once the parent entity is persisted, the child entities are going to be persisted as well.

[NOTE]
====
Just like value type collections, unidirectional bags are not as efficient when it comes to modifying the collection structure (removing or reshuffling elements).

Because the parent-side cannot uniquely identify each individual child, Hibernate deletes all link table rows associated with the parent entity and re-adds the remaining ones that are found in the current collection state.
====

[[collections-bidirectional-bag]]
===== Bidirectional bags

The bidirectional bag is the most common type of entity collection.
The `@ManyToOne` side is the owning side of the bidirectional bag association, while the `@OneToMany` is the _inverse_ side, being marked with the `mappedBy` attribute.

[[collections-bidirectional-bag-example]]
.Bidirectional bag
====
[source,java]
----
include::{example-dir-collection}/BidirectionalBagTest.java[tags=collections-bidirectional-bag-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-bidirectional-bag-example.sql[]
----
====

[[collections-bidirectional-bag-lifecycle-example]]
.Bidirectional bag lifecycle
====
[source,java]
----
include::{example-dir-collection}/BidirectionalBagTest.java[tags=collections-bidirectional-bag-lifecycle-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-bidirectional-bag-lifecycle-example.sql[]
----
====

[[collections-bidirectional-bag-orphan-removal-example]]
.Bidirectional bag with orphan removal
====
[source,java]
----
include::{example-dir-collection}/BidirectionalBagOrphanRemovalTest.java[tags=collections-bidirectional-bag-orphan-removal-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-bidirectional-bag-orphan-removal-example.sql[]
----
====

When rerunning the previous example, the child will get removed because the parent-side propagates the removal upon dissociating the child entity reference.

[[collections-list]]
==== Ordered Lists

Although they use the `List` interface on the Java side, bags don't retain element order.
To preserve the collection element order, there are two possibilities:

`@OrderBy`:: the collection is ordered upon retrieval using a child entity property
`@OrderColumn`:: the collection uses a dedicated order column in the collection link table

[[collections-unidirectional-ordered-list]]
===== Unidirectional ordered lists

When using the `@OrderBy` annotation, the mapping looks as follows:

[[collections-unidirectional-ordered-list-order-by-example]]
.Unidirectional `@OrderBy` list
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalOrderedByListTest.java[tags=collections-unidirectional-ordered-list-order-by-example,indent=0]
----
====

The database mapping is the same as with the <<collections-unidirectional-bag>> example, so it won't be repeated.
Upon fetching the collection, Hibernate generates the following select statement:

[[collections-unidirectional-ordered-list-order-by-select-example]]
.Unidirectional `@OrderBy` list select statement
====
[source,sql]
----
include::{extrasdir}/collections-unidirectional-ordered-list-order-by-select-example.sql[]
----
====

The child table column is used to order the list elements.

[NOTE]
====
The `@OrderBy` annotation can take multiple entity properties, and each property can take an ordering direction too (e.g. `@OrderBy("name ASC, type DESC")`).

If no property is specified (e.g. `@OrderBy`), the primary key of the child entity table is used for ordering.
====

Another ordering option is to use the `@OrderColumn` annotation:

[[collections-unidirectional-ordered-list-order-column-example]]
.Unidirectional `@OrderColumn` list
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalOrderColumnListTest.java[tags=collections-unidirectional-ordered-list-order-column-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-unidirectional-ordered-list-order-column-example.sql[]
----
====

This time, the link table takes the `order_id` column and uses it to materialize the collection element order.
When fetching the list, the following select query is executed:

[[collections-unidirectional-ordered-list-order-column-select-example]]
.Unidirectional `@OrderColumn` list select statement
====
[source,sql]
----
include::{extrasdir}/collections-unidirectional-ordered-list-order-column-select-example.sql[]
----
====

With the `order_id` column in place, Hibernate can order the list in-memory after it's being fetched from the database.

[[collections-bidirectional-ordered-list]]
===== Bidirectional ordered lists

The mapping is similar with the <<collections-bidirectional-bag>> example, just that the parent side is going to be annotated with either `@OrderBy` or `@OrderColumn`.

[[collections-bidirectional-ordered-list-order-by-example]]
.Bidirectional `@OrderBy` list
====
[source,java]
----
include::{example-dir-collection}/BidirectionalOrderByListTest.java[tags=collections-bidirectional-ordered-list-order-by-example,indent=0]
----
====

Just like with the unidirectional `@OrderBy` list, the `number` column is used to order the statement on the SQL level.

When using the `@OrderColumn` annotation, the `order_id` column is going to be embedded in the child table:

[[collections-bidirectional-ordered-list-order-column-example]]
.Bidirectional `@OrderColumn` list
====
[source,java]
----
include::{example-dir-collection}/BidirectionalOrderColumnListTest.java[tags=collections-bidirectional-ordered-list-order-column-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-bidirectional-ordered-list-order-column-example.sql[]
----
====

When fetching the collection, Hibernate will use the fetched ordered columns to sort the elements according to the `@OrderColumn` mapping.

[[collections-customizing-ordered-list-ordinal]]
===== Customizing ordered list ordinal

You can customize the ordinal of the underlying ordered list by using the https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/ListIndexBase.html[`@ListIndexBase`] annotation.

[[collections-customizing-ordered-list-ordinal-mapping-example]]
.`@ListIndexBase` mapping example
====
[source,java]
----
include::{example-dir-collection}/OrderColumnListIndexBaseTest.java[tags=collections-customizing-ordered-list-ordinal-mapping-example,indent=0]
----
====

When inserting two `Phone` records, Hibernate is going to start the List index from 100 this time.

[[collections-customizing-ordered-list-ordinal-persist-example]]
.`@ListIndexBase` persist example
====
[source,java]
----
include::{example-dir-collection}/OrderColumnListIndexBaseTest.java[tags=collections-customizing-ordered-list-ordinal-persist-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-customizing-ordered-list-ordinal-persist-example.sql[]
----
====

[[collections-customizing-ordered-by-sql-clause]]
===== Customizing ORDER BY SQL clause

While the Jakarta Persistence
{jpaJavadocUrlPrefix}OrderBy.html[`@OrderBy`] annotation allows you to specify the entity attributes used for sorting
when fetching the current annotated collection, the Hibernate specific
https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/OrderBy.html[`@OrderBy`] annotation is used to specify a *SQL* clause instead.

In the following example, the `@OrderBy` annotation uses the `CHAR_LENGTH` SQL function to order the `Article` entities
by the number of characters of the `name` attribute.

[[collections-customizing-ordered-by-sql-clause-mapping-example]]
.`@OrderBy` mapping example
====
[source,java]
----
include::{example-dir-collection}/OrderedBySQLTest.java[tags=collections-customizing-ordered-by-sql-clause-mapping-example,indent=0]
----
====

When fetching the `articles` collection, Hibernate uses the ORDER BY SQL clause provided by the mapping:

[[collections-customizing-ordered-by-sql-clause-fetching-example]]
.`@OrderBy` fetching example
====
[source,java]
----
include::{example-dir-collection}/OrderedBySQLTest.java[tags=collections-customizing-ordered-by-sql-clause-fetching-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-customizing-ordered-by-sql-clause-fetching-example.sql[]
----
====

[[collections-set]]
==== Sets

Sets are collections that don't allow duplicate entries and Hibernate supports both the unordered `Set` and the natural-ordering `SortedSet`.

[[collections-unidirectional-set]]
===== Unidirectional sets

The unidirectional set uses a link table to hold the parent-child associations and the entity mapping looks as follows:

[[collections-unidirectional-set-example]]
.Unidirectional set
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalSetTest.java[tags=collections-unidirectional-set-example,indent=0]
----
====

The unidirectional set lifecycle is similar to that of the <<collections-unidirectional-bag>>, so it can be omitted.
The only difference is that `Set` doesn't allow duplicates, but this constraint is enforced by the Java object contract rather than the database mapping.

[NOTE]
====
When using Sets, it's very important to supply proper equals/hashCode implementations for child entities.

In the absence of a custom equals/hashCode implementation logic, Hibernate will use the default Java reference-based object equality which might render unexpected results when mixing detached and managed object instances.
====

[[collections-bidirectional-set]]
===== Bidirectional sets

Just like bidirectional bags, the bidirectional set doesn't use a link table, and the child table has a foreign key referencing the parent table primary key.
The lifecycle is just like with bidirectional bags except for the duplicates which are filtered out.

[[collections-bidirectional-set-example]]
.Bidirectional set
====
[source,java]
----
include::{example-dir-collection}/BidirectionalSetTest.java[tags=collections-bidirectional-set-example,indent=0]
----
====

[[collections-sorted-set]]
==== Sorted sets

For sorted sets, the entity mapping must use the `SortedSet` interface instead.
According to the `SortedSet` contract, all elements must implement the `Comparable` interface and therefore provide the sorting logic.

[[collections-unidirectional-sorted-set]]
===== Unidirectional sorted sets

A `SortedSet` that relies on the natural sorting order given by the child element `Comparable` implementation logic might be annotated with the `@SortNatural` Hibernate annotation.

[[collections-unidirectional-sorted-set-natural-comparator-example]]
.Unidirectional natural sorted set
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalSortedSetTest.java[tags=collections-unidirectional-sorted-set-natural-comparator-example,indent=0]
----
====

The lifecycle and the database mapping are identical to the <<collections-unidirectional-bag>>, so they are intentionally omitted.

To provide a custom sorting logic, Hibernate also provides a `@SortComparator` annotation:

[[collections-unidirectional-sorted-set-custom-comparator-example]]
.Unidirectional custom comparator sorted set
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalComparatorSortedSetTest.java[tags=collections-unidirectional-sorted-set-custom-comparator-example,indent=0]
----
====

[[collections-bidirectional-sorted-set]]
===== Bidirectional sorted sets

The `@SortNatural` and `@SortComparator` work the same for bidirectional sorted sets too:

[[collections-bidirectional-sorted-set-example]]
.Bidirectional natural sorted set
====
[source,java]
----
include::{example-dir-collection}/BidirectionalSortedSetTest.java[tags=collections-bidirectional-sorted-set-example,indent=0]

include::{example-dir-collection}/UnidirectionalComparatorSortedSetTest.java[lines=75..77,indent=0]
----
====

[NOTE]
====
Before v6, `@SortNatural` must be used if collection element's natural ordering is relied upon for sorting.
Starting from v6, we can omit `@SortNatural` as it will take effect by default.
====

[[collections-map]]
==== Maps

A `java.util.Map` is a ternary association because it requires a parent entity, a map key, and a value.
An entity can either be a map key or a map value, depending on the mapping.
Hibernate allows using the following map keys:

`MapKeyColumn`:: for value type maps, the map key is a column in the link table that defines the grouping logic
`MapKey`:: the map key is either the primary key or another property of the entity stored as a map entry value
`MapKeyEnumerated`:: the map key is an `Enum` of the target child entity
`MapKeyTemporal`:: the map key is a `Date` or a `Calendar` of the target child entity
`MapKeyJoinColumn`:: the map key is an entity mapped as an association in the child entity that's stored as a map entry key

[[collections-map-value-type]]
===== Value type maps

A map of value type must use the `@ElementCollection` annotation, just like value type lists, bags or sets.

[[collections-map-value-type-entity-key-example]]
.Value type map with an entity as a map key
====
[source,java]
----
include::{example-dir-collection}/ElementCollectionMapTest.java[tags=collections-map-value-type-entity-key-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-value-type-entity-key-example.sql[]
----
====

Adding entries to the map generates the following SQL statements:

[[collections-map-value-type-entity-key-add-example]]
.Adding value type map entries
====
[source,java]
----
include::{example-dir-collection}/ElementCollectionMapTest.java[tags=collections-map-value-type-entity-key-add-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-value-type-entity-key-add-example.sql[]
----
====

[[collections-map-custom-key-type]]
===== Maps with a custom key type

Hibernate defines the
https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/MapKeyType.html[`@MapKeyType`] annotation
which you can use to customize the `Map` key type.

Considering you have the following tables in your database:

[source,sql]
----
include::{extrasdir}/collections-map-custom-key-type-sql-example.sql[]
----

The `call_register` records the call history for every `person`.
The `call_timestamp_epoch` column stores the phone call timestamp as a Unix timestamp since the Unix epoch.

[NOTE]
====
The `@MapKeyColumn` annotation is used to define the table column holding the key while the `@Column` mapping gives the value of the `java.util.Map` in question.
====

Since we want to map all the calls by their associated `java.util.Date`, not by their timestamp since epoch which is a number, the entity mapping looks as follows:

[[collections-map-custom-key-type-mapping-example]]
.`@MapKeyType` mapping example
====
[source,java]
----
include::{example-dir-collection}/MapKeyTypeTest.java[tags=collections-map-custom-key-type-mapping-example,indent=0]
----
====


[[collections-map-key-class]]
===== Maps having an interface type as the key

Considering you have the following `PhoneNumber` interface with an implementation given by the `MobilePhone` class type:

[[collections-map-key-class-type-mapping-example]]
.`PhoneNumber` interface and the `MobilePhone` class type
====
[source,java]
----
include::{example-dir-collection}/MapKeyClassTest.java[tags=collections-map-key-class-type-mapping-example,indent=0]
----
====

If you want to use the `PhoneNumber` interface as a `java.util.Map` key, then you need to supply the
{jpaJavadocUrlPrefix}MapKeyClass.html[`@MapKeyClass`] annotation as well.

[[collections-map-key-class-mapping-example]]
.`@MapKeyClass` mapping example
====
[source,java]
----
include::{example-dir-collection}/MapKeyClassTest.java[tags=collections-map-key-class-mapping-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-key-class-mapping-example.sql[]
----
====

When inserting a `Person` with a `callRegister` containing 2 `MobilePhone` references,
Hibernate generates the following SQL statements:

[[collections-map-key-class-persist-example]]
.`@MapKeyClass` persist example
====
[source,java]
----
include::{example-dir-collection}/MapKeyClassTest.java[tags=collections-map-key-class-persist-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-key-class-persist-example.sql[]
----
====

When fetching a `Person` and accessing the `callRegister` `Map`,
Hibernate generates the following SQL statements:

[[collections-map-key-class-fetch-example]]
.`@MapKeyClass` fetch example
====
[source,java]
----
include::{example-dir-collection}/MapKeyClassTest.java[tags=collections-map-key-class-fetch-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-key-class-fetch-example.sql[]
----
====

[[collections-map-unidirectional]]
===== Unidirectional maps

A unidirectional map exposes a parent-child association from the parent-side only.

The following example shows a unidirectional map which also uses a `@MapKeyTemporal` annotation.
The map key is a timestamp, and it's taken from the child entity table.

[NOTE]
====
The `@MapKey` annotation is used to define the entity attribute used as a key of the `java.util.Map` in question.
====

[[collections-map-unidirectional-example]]
.Unidirectional Map
====
[source,java]
----
include::{example-dir-collection}/UnidirectionalMapTest.java[tags=collections-map-unidirectional-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-unidirectional-example.sql[]
----
====

[[collections-map-bidirectional]]
===== Bidirectional maps

Like most bidirectional associations, this relationship is owned by the child-side while the parent is the inverse side and can propagate its own state transitions to the child entities.

In the following example, you can see that `@MapKeyEnumerated` was used so that the `Phone` enumeration becomes the map key.

[[collections-map-bidirectional-example]]
.Bidirectional Map
====
[source,java]
----
include::{example-dir-collection}/BidirectionalMapTest.java[tags=collections-map-bidirectional-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-map-bidirectional-example.sql[]
----
====

[[collections-array]]
==== Arrays

When discussing arrays, it is important to understand the distinction between SQL array types and Java arrays that are mapped as part of the application's domain model.

Not all databases implement the SQL-99 ARRAY type and, for this reason,
the SQL type used by Hibernate for arrays varies depending on the database support.

NOTE: It is impossible for Hibernate to offer lazy-loading for arrays of entities and, for this reason,
it is strongly recommended to map a "collection" of entities using a List or Set rather than an array.

[[collections-array-as-basic]]
==== [[collections-array-binary]] Arrays as basic value type

By default, Hibernate will choose a type for the array based on `Dialect.getPreferredSqlTypeCodeForArray()`.
Prior to Hibernate 6.1, the default was to always use the BINARY type, as supported by the current `Dialect`,
but now, Hibernate will leverage the native array data types if possible.

[[collections-array-binary-example]] To force the BINARY type, the persistent attribute has to be annotated with `@JdbcTypeCode(SqlTypes.VARBINARY)`.

[[collections-array-as-basic-example]]
.Arrays stored as SQL array
====
[source,java]
----
include::{example-dir-collection}/ArrayTest.java[tags=collections-array-as-basic-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-array-as-basic-example.sql[]
----
====

[[collections-as-basic]]
==== Collections as basic value type

Notice how all the previous examples explicitly mark the collection attribute as either `@ElementCollection`,
`@OneToMany` or `@ManyToMany`.

Attributes of collection or array type without any of those annotations are considered basic types and by
default mapped like basic arrays as depicted in the <<collections-array-as-basic,previous section>>.

[[collections-as-basic-example]]
.Collections stored as SQL array
====
[source,java]
----
include::{example-dir-collection}/CollectionTest.java[tags=collections-as-basic-example,indent=0]
----

[source,sql]
----
include::{extrasdir}/collections-array-as-basic-example.sql[]
----
====

Prior to Hibernate 6.1, it was common to use an <<basic-jpa-convert,AttributeConverter>> to map the elements
into e.g. a comma separated list which is still a viable option. Just note that it is not required anymore.

[[ex-collections-comma-delimited-list]]
.Comma delimited collection
====
[source,java]
----
include::{example-dir-collection}/asbasic/CommaDelimitedStringsConverter.java[tags=ex-csv-converter,indent=0]

include::{example-dir-collection}/asbasic/CommaDelimitedStringsConverterTests.java[tags=ex-csv-converter-model,indent=0]
----
====


