[[collections]]
=== Collections
:sourcedir: extras

[[collections-synopsis]]
==== Collections as a value type

TODO: discussions of what it means for them to be value types - lifecycle, opt-locking

Collections have the usual behavior of value types.
They are automatically persisted when referenced by a persistent object and are automatically deleted when unreferenced.
If a collection is passed from one persistent object to another, its elements might be moved from one table to another.
Two entities cannot share a reference to the same collection instance.

[IMPORTANT]
====
Collection attributes do not support null value semantics because Hibernate does not distinguish between a null collection reference and an empty collection.

It is important that collections be defined using the appropriate Java Collections Framework interface rather than a specific implementation.
From a theoretical perspective, this just follows good design principles.
From a practical perspective, Hibernate (like other persistence providers) will use their own collection implementations which conform to the Java Collections Framework interfaces.
====

[[collections-value]]
==== Collections of value types

TODO : collection of values - elements can be of any value type except for collections (in fact even embeddables as the element cannot contain collections) * basics * embeddables

[[collections-entity]]
==== Collections of entities

TODO : one-to-many * many-to-many


[[collections-list]]
==== List - index

TODO : discuss mapping list index

[[collections-map]]
==== Map - key

TODO : discuss mapping map key

[[collections-bag]]
==== Bags

TODO : discuss mapping bags and idbags

[[collections-array]]
==== Arrays

TODO : discuss mapping arrays

[[collections-as-basic]]
==== Collections as basic value type

Notice how all the previous examples explicitly mark the collection attribute as either `ElementCollection`, `OneToMany` or `ManyToMany`.

TODO : Collections not marked as such, or collections explicitly marked with @Basic are treated as JPA basic values. Meaning there value is stored into a single column in the containing table.

TODO : This is sometimes beneficial. Consider a use-case such as a VARCHAR column that represents a delimited list or set of Strings.

.Delimited set of tags
====
[source,java]
----
include::{sourcedir}/collection/DelimitedStringTagsExample.java[]
----
====

See the Hibernate Integrations Guide for more details on developing custom value type mappings.
Without the special type mapping above the "set of tags" would have simply been marshalled using serialization.
