[[embeddables]]
=== Embeddable values
:root-project-dir: ../../../../../../..
:core-project-dir: {root-project-dir}/hibernate-core
:core-test-base: {root-project-dir}/hibernate-core/src/test/java
:example-dir-emeddable: {core-test-base}/org/hibernate/orm/test/mapping/embeddable
:example-dir-embeddableinstantiator: {core-test-base}/org/hibernate/orm/test/mapping/embeddable/strategy/instantiator
:example-dir-compositeusertype: {core-test-base}/org/hibernate/orm/test/mapping/embeddable/strategy/usertype
:extrasdir: extras

Historically Hibernate called these components.
Jakarta Persistence calls them embeddables.
Either way, the concept is the same: a composition of values.

For example, we might have a `Publisher` class that is a composition of `name` and `country`,
or a `Location` class that is a composition of `country` and `city`.

.Usage of the word _embeddable_
[NOTE]
====
To avoid any confusion with the annotation that marks a given embeddable type, the annotation will be further referred to as `@Embeddable`.

Throughout this chapter and thereafter, for brevity sake, embeddable types may also be referred to as _embeddable_.
====

[[embeddable-type-mapping-example]]
.Embeddable type example
====
[source,java]
----
include::{example-dir-emeddable}/NestedEmbeddableTest.java[tag=embeddable-type-mapping-example, indent=0]
----
====

An embeddable type is another form of a value type, and its lifecycle is bound to a parent entity type, therefore inheriting the attribute access from its parent (for details on attribute access, see <<chapters/domain/entity.adoc#access-embeddable-types,Access strategies>>).

Embeddable types can be made up of basic values as well as associations, with the caveat that, when used as collection elements, they cannot define collections themselves.

==== Component / Embedded

Most often, embeddable types are used to group multiple basic type mappings and reuse them across several entities.

[[simple-embeddable-type-mapping-example]]
.Simple Embeddable
====
[source,java]
----
include::{example-dir-emeddable}/SimpleEmbeddableTest.java[tag=embeddable-type-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/embeddable/simple-embeddable-type-mapping-example.sql[]
----
====

[NOTE]
====
Jakarta Persistence defines two terms for working with an embeddable type: `@Embeddable` and `@Embedded`.

`@Embeddable` is used to describe the mapping type itself (e.g. `Publisher`).

`@Embedded` is for referencing a given embeddable type (e.g. `book.publisher`).
====

So, the embeddable type is represented by the `Publisher` class and
the parent entity makes use of it through the `book#publisher` object composition.

The composed values are mapped to the same table as the parent table.
Composition is part of good object-oriented data modeling (idiomatic Java).
In fact, that table could also be mapped by the following entity type instead.

[[alternative-to-embeddable-type-mapping-example]]
.Alternative to embeddable type composition
====
[source,java]
----
include::{example-dir-emeddable}/SimpleEmbeddableEquivalentTest.java[tag=embeddable-type-mapping-example, indent=0]
----
====

The composition form is certainly more object-oriented, and that becomes more evident as we work with multiple embeddable types.

[[embeddable-override]]
==== Overriding Embeddable types

Although from an object-oriented perspective, it's much more convenient to work with embeddable types, when we reuse the same
embeddable multiple times on the same class, the Jakarta Persistence specification requires to set the associated column names explicitly.

This requirement is due to how object properties are mapped to database columns.
By default, Jakarta Persistence expects a database column having the same name with its associated object property.
When including multiple embeddables, the implicit name-based mapping rule doesn't work anymore because multiple object
properties could end-up being mapped to the same database column.

When an embeddable type is used multiple times, Jakarta Persistence defines the `@AttributeOverride`
and `@AssociationOverride` annotations to handle this scenario to override the default column names defined
by the Embeddable.

NOTE: See <<embeddable-multiple-namingstrategy>> for an alternative to using `@AttributeOverride` and `@AssociationOverride`

Considering you have the following `Publisher` embeddable type
which defines a `@ManyToOne` association with the `Country` entity:

[[embeddable-type-association-mapping-example]]
.Embeddable type with a `@ManyToOne` association
====
[source,java]
----
include::{example-dir-emeddable}/EmbeddableOverrideTest.java[tag=embeddable-type-association-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/embeddable/embeddable-type-association-mapping-example.sql[]
----
====

Now, if you have a `Book` entity which declares two `Publisher` embeddable types for the ebook and paperback versions,
you cannot use the default `Publisher` embeddable mapping since there will be a conflict between the two embeddable column mappings.

Therefore, the `Book` entity needs to override the embeddable type mappings for each `Publisher` attribute:

[[embeddable-type-override-mapping-example]]
.Overriding embeddable type attributes
====
[source,java]
----
include::{example-dir-emeddable}/EmbeddableOverrideTest.java[tag=embeddable-type-override-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/embeddable/embeddable-type-override-mapping-example.sql[]
----
====

[[embeddable-column-naming]]
==== @EmbeddedColumnNaming

The most common use case for `@AttributeOverride` in relation to an embeddable is to rename the associated columns.

Consider a typical embeddable mapping -

[[embeddable-column-naming-example-model]]
.Typical embeddable mapping
====
[source,java]
----
@Entity
class Person {
	// ...
    @Embedded
    Address homeAddress;
    @Embedded
    Address workAddress;
}

@Embeddable
class Address {
	String street;
	String city;
	// ...
}
----
====

In strict Jakarta Persistence sense, this will lead to a bootstrapping error because
Jakarta Persistence requires that the implicit names for the columns for both of the
embedded `Address` mappings to be based on the attribute names from the embeddable -
`street`, `city`, etc.  However, that will lead to duplicate column names here.

The strict compliance way to accomplish this would be a tedious use of the `@AttributeOverride` annotation
as <<embeddable-override,discussed previously>>.

Since this is such a common pattern, Hibernate offers a much simpler solution through its `@EmbeddedColumnNaming` annotation
which allows to "patternize" the column naming -

[[embeddable-column-naming-example-basic]]
.Simple `@EmbeddedColumnNaming` example
====
[source,java]
----
@Entity
class Person {
	// ...
    @Embedded
    @EmbeddedColumnNaming("home_%s")
    Address homeAddress;
    @Embedded
    @EmbeddedColumnNaming("work_%s")
    Address workAddress;
}
----
====

This mapping produces implicit column names `home_street`, `home_city`, `work_street`, `work_city`, etc.

`@EmbeddedColumnNaming` also works in nested usages and plays nicely with explicit column names.

[[embeddable-column-naming-example-column]]
.Explicit @Column example
====
[source,java]
----
@Entity
class Person {
	// ...
    @Embedded
	@EmbeddedColumnNaming("home_%s")
    Address homeAddress;
    @Embedded
    @EmbeddedColumnNaming("work_%s")
    Address workAddress;
}

@Embeddable
class Address {
	String street;
	String city;
    @Embedded
    private ZipPlus zip;
	// ...
}

@Embeddable
public static class ZipPlus {
    @Column(name="zip_code")
    private String code;
    @Column(name="zip_plus4")
    private String plus4;
}
----
====

This will produce implicit column names `home_street`, `home_city`, `home_zip_code`, `home_zip_plus4`, ...


When `@EmbeddedColumnNaming` is used withing nested embeddables, the affect will be cumulative.
Given the following model:

[[embeddable-column-naming-example-cumulative]]
.Cumulative @EmbeddedColumnNaming example
====
[source,java]
----
@Entity
class Person {
	// ...
    @Embedded
	@EmbeddedColumnNaming("home_%s")
    Address homeAddress;
    @Embedded
    @EmbeddedColumnNaming("work_%s")
    Address workAddress;
}

@Embeddable
class Address {
	String street;
	String city;
    @Embedded
    @EmbeddedColumnNaming("zip_%s")
    private ZipPlus zip;
	// ...
}

@Embeddable
public static class ZipPlus {
    private String code;
    private String plus4;
}
----
====

Here we will end up with the columns `home_street`, `home_city`, `home_zip_code`, `home_zip_plus4`, ...



[[embeddable-collections]]
==== Collections of embeddable types

Collections of embeddable types are specifically valued collections (as embeddable types are value types).
Value collections are covered in detail in <<chapters/domain/collections.adoc#collections-value,Collections of value types>>.

[[embeddable-mapkey]]
==== Embeddable type as a Map key

Embeddable types can also be used as `Map` keys.
This topic is converted in detail in <<chapters/domain/collections.adoc#collections-map,Map - key>>.

[[embeddable-identifier]]
==== Embeddable type as identifier

Embeddable types can also be used as entity type identifiers.
This usage is covered in detail in <<chapters/domain/identifiers.adoc#identifiers-composite,Composite identifiers>>.

[IMPORTANT]
====
Embeddable types that are used as collection entries, map keys or entity type identifiers cannot include their own collection mappings.
====


[[embeddable-Target]]
==== `@TargetEmbeddable` mapping

The https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/TargetEmbeddable.html[`@TargetEmbeddable`] annotation is used to specify the implementation class of an embeddable-valued mapping when the declared type is a non-concrete type (interface, etc).

As an example, consider an `@Embedded` attribute (`City.coordinates`) whose declared type (`Coordinates`) is an interface.  However, Hibernate needs to know about the concrete type to use, which is `GPS` in this case.  The `@TargetEmbeddable` annotation is used to provide this information.

[[embeddable-Target-example]]
.Embedded mapping example
====
[source, java, indent=0]
----
include::{example-dir-emeddable}/TargetEmbeddableOnEmbeddedTest.java[tags=embeddable-Target-example]
----
====

The mapping works just like any embeddable-valued mapping at this point, with Hibernate using `GPS` "under the covers":


[[embeddable-Target-fetching-example]]
.Usage example
====
[source, java, indent=0]
----
include::{example-dir-emeddable}/TargetEmbeddableOnEmbeddedTest.java[tags=embeddable-Target-fetching-example]
----
====

For `@Embedded` and `@EmbeddedId` cases, `@TargetEmbeddable` may be specified on the member's declared type instead of the member itself:

[[embeddable-Target-example2]]
.Interface mapping example
====
[source, java, indent=0]
----
include::{example-dir-emeddable}/TargetEmbeddableOnInterfaceTest.java[tags=embeddable-Target-example2]
----
====


[[embeddable-Parent]]
==== `@Parent` mapping

The Hibernate-specific `@Parent` annotation allows you to reference the owner entity from within an embeddable.

[[embeddable-Parent-example]]
.`@Parent` mapping usage
====
[source, java, indent=0]
----
include::{example-dir-emeddable}/ParentTest.java[tags=embeddable-Parent-example]
----
====

Assuming we have persisted the following `City` entity:

[[embeddable-Parent-persist-example]]
.`@Parent` persist example
====
[source, java, indent=0]
----
include::{example-dir-emeddable}/ParentTest.java[tags=embeddable-Parent-persist-example]
----
====

When fetching the `City` entity, the `city` property of the embeddable type acts as a back reference to the owning parent entity:

[[embeddable-Parent-fetching-example]]
.`@Parent` fetching example
====
[source, java, indent=0]
----
include::{example-dir-emeddable}/ParentTest.java[tags=embeddable-Parent-fetching-example]
----
====

Therefore, the `@Parent` annotation is used to define the association between an embeddable type and the owning entity.


[[embeddable-instantiator]]
==== Custom instantiation

Jakarta Persistence requires embeddable classes to follow Java Bean conventions.  Part of this is the
definition of a non-arg constructor.  However, not all value compositions applications might map as embeddable
values follow Java Bean conventions - e.g. a struct or Java 15 record.

Hibernate allows the use of a custom instantiator for creating the embeddable instances through the
`org.hibernate.metamodel.spi.EmbeddableInstantiator` contract.  For example, consider the following
embeddable:

[[embeddable-instantiator-embeddable-ex]]
.`EmbeddableInstantiator` - Embeddable
====
[source, java, indent=0]
----
include::{example-dir-embeddableinstantiator}/embedded/Name.java[tags=embeddable-instantiator-embeddable]
----
====

Here, `Name` only allows use of the constructor accepting its state.  Because this class does not follow Java Bean
conventions, in terms of constructor, a custom strategy for instantiation is needed.

[[embeddable-instantiator-impl-ex]]
.`EmbeddableInstantiator` - Implementation
====
[source, java, indent=0]
----
include::{example-dir-embeddableinstantiator}/embedded/NameInstantiator.java[tags=embeddable-instantiator-impl]
----
====

There are a few ways to specify the custom instantiator.  The `@org.hibernate.annotations.EmbeddableInstantiator`
annotation can be used on the embedded attribute:

[[embeddable-instantiator-property-ex]]
.`@EmbeddableInstantiator` on attribute
====
[source, java, indent=0]
----
include::{example-dir-embeddableinstantiator}/embedded/Person.java[tags=embeddable-instantiator-property]
----
====

`@EmbeddableInstantiator` may also be specified on the embeddable class:

[[embeddable-instantiator-class-ex]]
.`@EmbeddableInstantiator` on class
====
[source, java, indent=0]
----
include::{example-dir-embeddableinstantiator}/embeddable/Name.java[tags=embeddable-instantiator-class]

include::{example-dir-embeddableinstantiator}/embeddable/Person.java[tags=embeddable-instantiator-class]
----
====


Lastly, `@org.hibernate.annotations.EmbeddableInstantiatorRegistration` may be used, which is useful
when the application developer does not control the embeddable to be able to apply the instantiator
on the <<embeddable-instantiator-class-ex,embeddable>>.

[[embeddable-instantiator-registration-ex]]
.`@EmbeddableInstantiatorRegistration`
====
[source, java, indent=0]
----
include::{example-dir-embeddableinstantiator}/registered/Person.java[tags=embeddable-instantiator-registration]
----
====




[[embeddable-mapping-custom]]
==== Custom type mapping

Another approach is to supply the implementation of the `org.hibernate.usertype.CompositeUserType` contract using `@CompositeType`,
which is an extension to the `org.hibernate.metamodel.spi.EmbeddableInstantiator` contract.

There are also corresponding, specialized forms of `@CompositeType` for specific model parts:

* When mapping a Map, `@CompositeType` describes the Map value while `@MapKeyCompositeType` describes the Map key
* For collection mappings, `@CompositeType` describes the elements

For example, consider the following custom type:

[[embeddable-usertype-domain-ex]]
.`CompositeUserType` - Domain type
====
[source, java, indent=0]
----
include::{example-dir-compositeusertype}/embedded/Name.java[tags=embeddable-usertype-domain]
----
====

Here, `Name` only allows use of the constructor accepting its state.  Because this class does not follow Java Bean
conventions, a custom user type for instantiation and state access is needed.

[[embeddable-usertype-impl-ex]]
.`CompositeUserType` - Implementation
====
[source, java, indent=0]
----
include::{example-dir-compositeusertype}/embedded/NameCompositeUserType.java[tags=embeddable-usertype-impl]
----
====

A composite user type needs an embeddable mapper class, which represents the embeddable mapping structure of the type
i.e. the way the type would look like if you had the option to write a custom `@Embeddable` class.

In addition to the instantiation logic, a composite user type also has to provide a way to decompose the returned type
into the individual components/properties of the embeddable mapper class through `getPropertyValue`.
The property index, just like in the `instantiate` method, is based on the alphabetical order of the attribute names
of the embeddable mapper class.

The composite user type also needs to provide methods to handle the mutability, equals, hashCode and the cache
serialization and deserialization of the returned type.

There are a few ways to specify the composite user type.  The `@org.hibernate.annotations.CompositeType`
annotation can be used on the embedded and element collection attributes:

[[embeddable-usertype-property-ex]]
.`@CompositeType` on attribute
====
[source, java, indent=0]
----
include::{example-dir-compositeusertype}/embedded/Person.java[tags=embeddable-usertype-property]
----
====

Or `@org.hibernate.annotations.CompositeTypeRegistration` may be used, which is useful
when the application developer wants to apply the composite user type for all domain type uses.

[[embeddable-usertype-registration-ex]]
.`@CompositeTypeRegistration`
====
[source, java, indent=0]
----
include::{example-dir-compositeusertype}/registered/Person.java[tags=embeddable-usertype-registration]
----
====




[[embeddable-multiple-namingstrategy]]
==== Embeddables and ImplicitNamingStrategy

[IMPORTANT]
====
The `ImplicitNamingStrategyComponentPathImpl` is a Hibernate-specific feature.
Users concerned with Jakarta Persistence provider portability should instead prefer explicit column naming with `@AttributeOverride`.
====

Hibernate naming strategies are covered in detail in <<chapters/domain/naming.adoc#naming,Naming>>.
However, for the purposes of this discussion, Hibernate has the capability to interpret implicit column names in a way that is safe for use with multiple embeddable types.

[[embeddable-multiple-namingstrategy-entity-mapping]]
.Implicit multiple embeddable type mapping
====
[source,java]
----
include::{example-dir-emeddable}/EmbeddableImplicitOverrideTest.java[tag=embeddable-multiple-namingstrategy-entity-mapping, indent=0]
----
====

To make it work, you need to use the `ImplicitNamingStrategyComponentPathImpl` naming strategy.

[[embeddable-multiple-ImplicitNamingStrategyComponentPathImpl]]
.Enabling implicit embeddable type mapping using the component path naming strategy
====
[source,java]
----
include::{example-dir-emeddable}/EmbeddableImplicitOverrideTest.java[tag=embeddable-multiple-ImplicitNamingStrategyComponentPathImpl, indent=0]
----
====

Now the "path" to attributes are used in the implicit column naming:

[source,sql]
----
include::{extrasdir}/embeddable/embeddable-multiple-namingstrategy-entity-mapping.sql[]
----

You could even develop your own naming strategy to do other types of implicit naming strategies.

[[embeddable-mapping-aggregate]]
==== Aggregate embeddable mapping

An embeddable mapping is usually just a way to encapsulate columns of a table into a Java type,
but as of Hibernate 6.2, it is also possible to map embeddable types as SQL aggregate types.

Currently, there are three possible SQL aggregate types which can be specified by annotating one of the following
annotations on a persistent attribute:

* `@Struct` - maps to a named SQL object type
* `@JdbcTypeCode(SqlTypes.JSON)` - maps to the SQL type JSON
* `@JdbcTypeCode(SqlTypes.SQLXML)` - maps to the SQL type XML

Any read or assignment (in an update statement) expression for an attribute of such an embeddable
will resolve to the proper SQL expression to access/update the attribute of the SQL type.

Since object, JSON and XML types are not supported equally on all databases, beware that not every mapping will work on all databases.
The following table outlines the current support for the different aggregate types:

|===
|Database |Struct |JSON |XML

|PostgreSQL
|Yes
|Yes
|Yes

|Oracle
|Yes
|Yes
|Yes

|MySQL/MariaDB
|No
|Yes
|No

|DB2
|Yes
|Yes
|Yes

|SQL Server
|No https://hibernate.atlassian.net/browse/HHH-16158[(not yet)]
|Yes
|Yes

|Sybase ASE
|No
|No
|Yes

|H2
|No
|Yes
|No

|CockroachDB
|No
|Yes
|No

|SAP HANA
|No
|Yes
|Yes
|===

Also note that embeddable types that are used in array aggregate mappings do not support association mappings.

===== `@Struct` aggregate embeddable mapping

The `@Struct` annotation can be placed on either the persistent attribute, or the embeddable type,
and requires the specification of a name i.e. the name of the SQL object type that it maps to.

The following example mapping, maps the `EmbeddableAggregate` type to the SQL object type `structType`:

.Mapping embeddable as SQL object type on persistent attribute level
====
[source,java]
----
include::{example-dir-emeddable}/StructEmbeddableTest.java[tag=embeddable-struct-type-mapping-example, indent=0]
----
====

The schema generation will by default emit DDL for that object type, which looks something along the lines of

====
[source,sql]
----
create type structType as (
    ...
)
create table StructHolder as (
    id bigint not null primary key,
    aggregate structType
)
----
====

The name and the nullability of the column can be refined through applying a `@Column` on the persistent attribute.

One very important thing to note is that the order of columns in the DDL definition of a type must match the order that Hibernate expects.
By default, the order of columns is based on the alphabetical ordering of the embeddable type attribute names.

Consider the following class:

====
[source,java]
----
@Embeddable
@Struct(name = "myStruct")
public class MyStruct {
	@Column(name = "b")
	String attr1;
	@Column(name = "a")
	String attr2;
}
----
====

The expected ordering of columns will be `(b,a)`, because the name `attr1` comes before `attr2` in alphabetical ordering.
This example aims at showing the importance of the persistent attribute name.

Defining the embeddable type as Java record instead of a class can force a particular ordering through the definition of canonical constructor.

====
[source,java]
----
@Embeddable
@Struct(name = "myStruct")
public record MyStruct (
	@Column(name = "a")
	String attr2,
	@Column(name = "b")
	String attr1
) {}
----
====

In this particular example, the expected ordering of columns will be `(a,b)`, because the canonical constructor of the record
defines a specific ordering of persistent attributes, which Hibernate makes use of for `@Struct` mappings.

It is not necessary to switch to Java records to configure the order though.
The `@Struct` annotation allows specifying the order through the `attributes` member,
an array of attribute names that the embeddable type declares, which defines the order in columns appear in the SQL object type.

The same ordering as with the Java record can be achieved this way:

====
[source,java]
----
@Embeddable
@Struct(name = "myStruct", attributes = {"attr2", "attr1"})
public class MyStruct {
	@Column(name = "b")
	String attr1;
	@Column(name = "a")
	String attr2;
}
----
====

===== JSON/XML aggregate embeddable mapping

The `@JdbcTypeCode` annotation for JSON and XML mappings can only be placed on the persistent attribute.

The following example mapping, maps the `EmbeddableAggregate` type to the JSON SQL type:

.Mapping embeddable as JSON
====
[source,java]
----
include::{example-dir-emeddable}/JsonEmbeddableTest.java[tag=embeddable-json-type-mapping-example, indent=0]
----
====

The schema generation will by default emit DDL that ensures the constraints of the embeddable type are respected, which looks something along the lines of

====
[source,sql]
----
create table JsonHolder as (
    id bigint not null primary key,
    aggregate json,
    check (json_value(aggregate, '$.attribute1') is not null)
)
----
====

Again, the name and the nullability of the `aggregate` column can be refined through applying a `@Column` on the persistent attribute.

[[embeddable-mapping-aggregate-collections]]
==== Embeddable mappings containing collections

Mapping <<chapters/domain/collections.adoc#collections,collections>> inside an `@Embeddable` value is supported in most cases. There are a couple exceptions:

* If the values of an <<chapters/domain/collections.adoc#collections-elemental,@ElementCollection>> is of embeddable type, that embeddable cannot contain nested collections;
* Explicitly selecting an embeddable that contains collections in a query is currently not supported (we wouldn't be able to correctly initialize the collection since its owning entity instance would be missing from the Persistence Context).