[[embeddables]]
=== Embeddable values
:rootProjectDir: ../../../../../../..
:sourcedir: ../../../../../test/java/org/hibernate/userguide/mapping/embeddable
:coreProjectDir: {rootProjectDir}/hibernate-core
:coreTestSrcDir: {rootProjectDir}/hibernate-core/src/test/java
:instantiatorTestDir: {coreTestSrcDir}/org/hibernate/orm/test/mapping/embeddable/strategy/instantiator
:usertypeTestDir: {coreTestSrcDir}/org/hibernate/orm/test/mapping/embeddable/strategy/usertype
:extrasdir: extras

Historically Hibernate called these components.
Jakarta Persistence calls them embeddables.
Either way, the concept is the same: a composition of values.

For example, we might have a `Publisher` class that is a composition of `name` and `country`,
or a `Location` class that is a composition of `country` and `city`.

.Usage of the word _embeddable_
[NOTE]
====
To avoid any confusion with the annotation that marks a given embeddable type, the annotation will be further referred to as `@Embeddable`.

Throughout this chapter and thereafter, for brevity sake, embeddable types may also be referred to as _embeddable_.
====

[[embeddable-type-mapping-example]]
.Embeddable type example
====
[source,java]
----
include::{sourcedir}/NestedEmbeddableTest.java[tag=embeddable-type-mapping-example, indent=0]
----
====

An embeddable type is another form of a value type, and its lifecycle is bound to a parent entity type, therefore inheriting the attribute access from its parent (for details on attribute access, see <<chapters/domain/entity.adoc#access-embeddable-types,Access strategies>>).

Embeddable types can be made up of basic values as well as associations, with the caveat that, when used as collection elements, they cannot define collections themselves.

==== Component / Embedded

Most often, embeddable types are used to group multiple basic type mappings and reuse them across several entities.

[[simple-embeddable-type-mapping-example]]
.Simple Embeddable
====
[source,java]
----
include::{sourcedir}/SimpleEmbeddableTest.java[tag=embeddable-type-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/embeddable/simple-embeddable-type-mapping-example.sql[]
----
====

[NOTE]
====
Jakarta Persistence defines two terms for working with an embeddable type: `@Embeddable` and `@Embedded`.

`@Embeddable` is used to describe the mapping type itself (e.g. `Publisher`).

`@Embedded` is for referencing a given embeddable type (e.g. `book.publisher`).
====

So, the embeddable type is represented by the `Publisher` class and
the parent entity makes use of it through the `book#publisher` object composition.

The composed values are mapped to the same table as the parent table.
Composition is part of good object-oriented data modeling (idiomatic Java).
In fact, that table could also be mapped by the following entity type instead.

[[alternative-to-embeddable-type-mapping-example]]
.Alternative to embeddable type composition
====
[source,java]
----
include::{sourcedir}/SimpleEmbeddableEquivalentTest.java[tag=embeddable-type-mapping-example, indent=0]
----
====

The composition form is certainly more object-oriented, and that becomes more evident as we work with multiple embeddable types.

[[embeddable-override]]
==== Overriding Embeddable types

Although from an object-oriented perspective, it's much more convenient to work with embeddable types, when we reuse the same
embeddable multiple times on the same class, the Jakarta Persistence specification requires to set the associated column names explicitly.

This requirement is due to how object properties are mapped to database columns.
By default, Jakarta Persistence expects a database column having the same name with its associated object property.
When including multiple embeddables, the implicit name-based mapping rule doesn't work anymore because multiple object
properties could end-up being mapped to the same database column.

When an embeddable type is used multiple times, Jakarta Persistence defines the `@AttributeOverride`
and `@AssociationOverride` annotations to handle this scenario to override the default column names defined
by the Embeddable.

NOTE: See <<embeddable-multiple-namingstrategy>> for an alternative to using `@AttributeOverride` and `@AssociationOverride`

Considering you have the following `Publisher` embeddable type
which defines a `@ManyToOne` association with the `Country` entity:

[[embeddable-type-association-mapping-example]]
.Embeddable type with a `@ManyToOne` association
====
[source,java]
----
include::{sourcedir}/EmbeddableOverrideTest.java[tag=embeddable-type-association-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/embeddable/embeddable-type-association-mapping-example.sql[]
----
====

Now, if you have a `Book` entity which declares two `Publisher` embeddable types for the ebook and paperback versions,
you cannot use the default `Publisher` embeddable mapping since there will be a conflict between the two embeddable column mappings.

Therefore, the `Book` entity needs to override the embeddable type mappings for each `Publisher` attribute:

[[embeddable-type-override-mapping-example]]
.Overriding embeddable type attributes
====
[source,java]
----
include::{sourcedir}/EmbeddableOverrideTest.java[tag=embeddable-type-override-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/embeddable/embeddable-type-override-mapping-example.sql[]
----
====


[[embeddable-collections]]
==== Collections of embeddable types

Collections of embeddable types are specifically valued collections (as embeddable types are value types).
Value collections are covered in detail in <<chapters/domain/collections.adoc#collections-value,Collections of value types>>.

[[embeddable-mapkey]]
==== Embeddable type as a Map key

Embeddable types can also be used as `Map` keys.
This topic is converted in detail in <<chapters/domain/collections.adoc#collections-map,Map - key>>.

[[embeddable-identifier]]
==== Embeddable type as identifier

Embeddable types can also be used as entity type identifiers.
This usage is covered in detail in <<chapters/domain/identifiers.adoc#identifiers-composite,Composite identifiers>>.

[IMPORTANT]
====
Embeddable types that are used as collection entries, map keys or entity type identifiers cannot include their own collection mappings.
====

[[embeddable-Target]]
==== `@Target` mapping

The https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/Target.html[`@Target`] annotation is used to specify the implementation class of a given association that is mapped via an interface.
The
{jpaJavadocUrlPrefix}ManyToOne.html[`@ManyToOne`],
{jpaJavadocUrlPrefix}OneToOne.html[`@OneToOne`],
{jpaJavadocUrlPrefix}OneToMany.html[`@OneToMany`], and
{jpaJavadocUrlPrefix}ManyToMany.html[`@ManyToMany`]
feature a {jpaJavadocUrlPrefix}ManyToOne.html#targetEntity--[`targetEntity`] attribute to specify the actual class of the entity association when an interface is used for the mapping.

The {jpaJavadocUrlPrefix}ElementCollection.html[`@ElementCollection`] association has a {jpaJavadocUrlPrefix}ElementCollection.html#targetClass--[`targetClass`] attribute for the same purpose.

However, for simple embeddable types, there is no such construct and so you need to use the Hibernate-specific `@Target` annotation instead.

[[embeddable-Target-example]]
.`@Target` mapping usage
====
[source, JAVA, indent=0]
----
include::{sourcedir}/TargetTest.java[tags=embeddable-Target-example]
----
====

The `coordinates` embeddable type is mapped as the `Coordinates` interface.
However, Hibernate needs to know the actual implementation tye, which is `GPS` in this case,
hence the `@Target` annotation is used to provide this information.

Assuming we have persisted the following `City` entity:

[[embeddable-Target-persist-example]]
.`@Target` persist example
====
[source, JAVA, indent=0]
----
include::{sourcedir}/TargetTest.java[tags=embeddable-Target-persist-example]
----
====

When fetching the `City` entity, the `coordinates` property is mapped by the `@Target` expression:

[[embeddable-Target-fetching-example]]
.`@Target` fetching example
====
[source, JAVA, indent=0]
----
include::{sourcedir}/TargetTest.java[tags=embeddable-Target-fetching-example]
----

[source, SQL, indent=0]
----
include::{extrasdir}/embeddable/embeddable-Target-fetching-example.sql[]
----
====

Therefore, the `@Target` annotation is used to define a custom join association between the parent-child association.

[[embeddable-Parent]]
==== `@Parent` mapping

The Hibernate-specific `@Parent` annotation allows you to reference the owner entity from within an embeddable.

[[embeddable-Parent-example]]
.`@Parent` mapping usage
====
[source, JAVA, indent=0]
----
include::{sourcedir}/ParentTest.java[tags=embeddable-Parent-example]
----
====

Assuming we have persisted the following `City` entity:

[[embeddable-Parent-persist-example]]
.`@Parent` persist example
====
[source, JAVA, indent=0]
----
include::{sourcedir}/ParentTest.java[tags=embeddable-Parent-persist-example]
----
====

When fetching the `City` entity, the `city` property of the embeddable type acts as a back reference to the owning parent entity:

[[embeddable-Parent-fetching-example]]
.`@Parent` fetching example
====
[source, JAVA, indent=0]
----
include::{sourcedir}/ParentTest.java[tags=embeddable-Parent-fetching-example]
----
====

Therefore, the `@Parent` annotation is used to define the association between an embeddable type and the owning entity.


[[embeddable-instantiator]]
==== Custom instantiation

Jakarta Persistence requires embeddable classes to follow Java Bean conventions.  Part of this is the
definition of a non-arg constructor.  However, not all value compositions applications might map as embeddable
values follow Java Bean conventions - e.g. a struct or Java 15 record.

Hibernate allows the use of a custom instantiator for creating the embeddable instances through the
`org.hibernate.metamodel.spi.EmbeddableInstantiator` contract.  For example, consider the following
embeddable:

[[embeddable-instantiator-embeddable-ex]]
.`EmbeddableInstantiator` - Embeddable
====
[source, JAVA, indent=0]
----
include::{instantiatorTestDir}/embedded/Name.java[tags=embeddable-instantiator-embeddable]
----
====

Here, `Name` only allows use of the constructor accepting its state.  Because this class does not follow Java Bean
conventions, in terms of constructor, a custom strategy for instantiation is needed.

[[embeddable-instantiator-impl-ex]]
.`EmbeddableInstantiator` - Implementation
====
[source, JAVA, indent=0]
----
include::{instantiatorTestDir}/embedded/NameInstantiator.java[tags=embeddable-instantiator-impl]
----
====

There are a few ways to specify the custom instantiator.  The `@org.hibernate.annotations.EmbeddableInstantiator`
annotation can be used on the embedded attribute:

[[embeddable-instantiator-property-ex]]
.`@EmbeddableInstantiator` on attribute
====
[source, JAVA, indent=0]
----
include::{instantiatorTestDir}/embedded/Person.java[tags=embeddable-instantiator-property]
----
====

`@EmbeddableInstantiator` may also be specified on the embeddable class:

[[embeddable-instantiator-class-ex]]
.`@EmbeddableInstantiator` on class
====
[source, JAVA, indent=0]
----
include::{instantiatorTestDir}/embeddable/Person.java[tags=embeddable-instantiator-class]
----
====


Lastly, `@org.hibernate.annotations.EmbeddableInstantiatorRegistration` may be used, which is useful
when the application developer does not control the embeddable to be able to apply the instantiator
on the <<embeddable-instantiator-class-ex,embeddable>>.

[[embeddable-instantiator-registration-ex]]
.`@EmbeddableInstantiatorRegistration`
====
[source, JAVA, indent=0]
----
include::{instantiatorTestDir}/registered/Person.java[tags=embeddable-instantiator-registration]
----
====




[[embeddable-mapping-custom]]
==== Custom type mapping

Another approach is to supply the implementation of the `org.hibernate.usertype.CompositeUserType` contract using `@CompositeType`,
which is an extension to the `org.hibernate.metamodel.spi.EmbeddableInstantiator` contract.

There are also corresponding, specialized forms of `@CompositeType` for specific model parts:

* When mapping a Map, `@CompositeType` describes the Map value while `@MapKeyCompositeType` describes the Map key
* For collection mappings, `@CompositeType` describes the elements

For example, consider the following custom type:

[[embeddable-usertype-domain-ex]]
.`CompositeUserType` - Domain type
====
[source, JAVA, indent=0]
----
include::{usertypeTestDir}/embedded/Name.java[tags=embeddable-usertype-domain]
----
====

Here, `Name` only allows use of the constructor accepting its state.  Because this class does not follow Java Bean
conventions, a custom user type for instantiation and state access is needed.

[[embeddable-usertype-impl-ex]]
.`CompositeUserType` - Implementation
====
[source, JAVA, indent=0]
----
include::{usertypeTestDir}/embedded/NameCompositeUserType.java[tags=embeddable-usertype-impl]
----
====

A composite user type needs an embeddable mapper class, which represents the embeddable mapping structure of the type
i.e. the way the type would look like if you had the option to write a custom `@Embeddable` class.

In addition to the instantiation logic, a composite user type also has to provide a way to decompose the returned type
into the individual components/properties of the embeddable mapper class through `getPropertyValue`.
The property index, just like in the `instantiate` method, is based on the alphabetical order of the attribute names
of the embeddable mapper class.

The composite user type also needs to provide methods to handle the mutability, equals, hashCode and the cache
serialization and deserialization of the returned type.

There are a few ways to specify the composite user type.  The `@org.hibernate.annotations.CompositeType`
annotation can be used on the embedded and element collection attributes:

[[embeddable-usertype-property-ex]]
.`@CompositeType` on attribute
====
[source, JAVA, indent=0]
----
include::{usertypeTestDir}/embedded/Person.java[tags=embeddable-usertype-property]
----
====

Or `@org.hibernate.annotations.CompositeTypeRegistration` may be used, which is useful
when the application developer wants to apply the composite user type for all domain type uses.

[[embeddable-usertype-registration-ex]]
.`@CompositeTypeRegistration`
====
[source, JAVA, indent=0]
----
include::{usertypeTestDir}/registered/Person.java[tags=embeddable-usertype-registration]
----
====




[[embeddable-multiple-namingstrategy]]
==== Embeddables and ImplicitNamingStrategy

[IMPORTANT]
====
The `ImplicitNamingStrategyComponentPathImpl` is a Hibernate-specific feature.
Users concerned with Jakarta Persistence provider portability should instead prefer explicit column naming with `@AttributeOverride`.
====

Hibernate naming strategies are covered in detail in <<chapters/domain/naming.adoc#naming,Naming>>.
However, for the purposes of this discussion, Hibernate has the capability to interpret implicit column names in a way that is safe for use with multiple embeddable types.

[[embeddable-multiple-namingstrategy-entity-mapping]]
.Implicit multiple embeddable type mapping
====
[source,java]
----
include::{sourcedir}/EmbeddableImplicitOverrideTest.java[tag=embeddable-multiple-namingstrategy-entity-mapping, indent=0]
----
====

To make it work, you need to use the `ImplicitNamingStrategyComponentPathImpl` naming strategy.

[[embeddable-multiple-ImplicitNamingStrategyComponentPathImpl]]
.Enabling implicit embeddable type mapping using the component path naming strategy
====
[source,java]
----
include::{sourcedir}/EmbeddableImplicitOverrideTest.java[tag=embeddable-multiple-ImplicitNamingStrategyComponentPathImpl, indent=0]
----
====

Now the "path" to attributes are used in the implicit column naming:

[source,sql]
----
include::{extrasdir}/embeddable/embeddable-multiple-namingstrategy-entity-mapping.sql[]
----

You could even develop your own naming strategy to do other types of implicit naming strategies.