[[entity]]
=== Entity types
:core-project-dir: {root-project-dir}/hibernate-core
:core-test-base: {core-project-dir}/src/test/java/org/hibernate/orm/test
:example-dir-mapping: {core-test-base}/mapping
:example-dir-proxy: {core-test-base}/proxy
:example-dir-persister: {core-test-base}/persister
:extrasdir: extras

.Usage of the word _entity_
[NOTE]
====
The entity type describes the mapping between the actual persistable domain model object and a database table row.
To avoid any confusion with the annotation that marks a given entity type, the annotation will be further referred to as `@Entity`.

Throughout this chapter and thereafter, entity types will be simply referred to as _entity_.
====

[[entity-pojo]]
==== POJO Models

Section _2.1 The Entity Class_ of the _Java Persistence 2.1 specification_ defines its requirements for an entity class.
Applications that wish to remain portable across Jakarta Persistence providers should adhere to these requirements:

> - The entity class must be annotated with the `@Entity` annotation or declared as an `entity` in its XML descriptor.
>
> - The entity class must be a top-level class or a static inner class.
> An enum, record, or interface may not be designated as an entity.
>
> - The entity class must have a `public` or `protected` constructor with no parameters, which is called by the persistence provider runtime to instantiate the entity.
>
> - The entity class must be non-`final`. Every method and persistent instance variable of the entity class must also be non-`final`.
>
> An entity might be an abstract class, or it might be a concrete class.
> An entity may extend a non-entity class, or it may extend another entity class.
> A non-entity class may extend an entity class.
>
> The persistent state of an entity is represented by instance variables, which may correspond to JavaBeans properties.
> An instance variable may be directly accessed only within the methods of the entity, by the entity instance itself.
> An instance variable of an entity must _not_ be directly accessed by a client of the entity.
> The state of the entity is available to clients only through the methods of the entity--that is, via accessor (getter/setter) methods, or via other business methods.

Hibernate, however, is not as strict in its requirements. Differences from the list above include:

- Fields may be declared `final`.

- The constructor with no parameters may be declared with package visibility, or, when the <<chapters/pc/BytecodeEnhancement.adoc#BytecodeEnhancement,bytecode enhancer>> is used, it may be omitted completely.

- Final classes and classes with final methods are tolerated but not recommended unless the bytecode enhancer is used.


Let's look at each requirement in detail.

[[entity-pojo-final]]
==== Prefer non-final classes

A central feature of Hibernate is the ability to lazily load entity state via _proxies_.
This feature depends on:

- the entity class being non-`final` (or implementing an interface that declares the external operations of the entity), and
- the non-`private` methods and accessor methods being non-`final`.

Hibernate _can_ persist a `final` entity class that does not implement any interface, but it is then not able to use proxies for lazily fetching to-one associations to that entity type, limiting options for performance tuning.

The bytecode enhancer automatically makes any entity class non-`final`, along with all its methods.

[[entity-pojo-constructor]]
==== Implement a no-argument constructor

The entity class should have a constructor with no parameters.
Both Hibernate and Jakarta Persistence require this.
Hibernate allows the constructor to be declared with `public`, `protected`, or package visibility.

The bytecode enhancer automatically adds a constructor with no parameters if it is missing.

[[entity-pojo-accessors]]
==== Declare getters and setters for persistent attributes

Strictly speaking, neither Jakarta Persistence nor Hibernate require accessor methods for a persistent field.
However, direct access to a field of an entity from outside the entity instance itself is extremely dangerous and can easily expose the application program to uninitialized/unfetched state.
All external access to fields of an entity should go through methods or accessor methods of the entity class.

Therefore, it's a good idea to declare fields as `private`.

[[entity-pojo-identifier]]
==== Providing identifier attribute(s)

[IMPORTANT]
====
Historically, providing identifier attributes was considered optional.

However, not defining identifier attributes on the entity should be considered a deprecated feature that will be removed in an upcoming release.
====

The identifier attribute does not necessarily need to be mapped to the column(s) that physically define the primary key.
However, it should map to column(s) that can uniquely identify each row.

[NOTE]
====
We recommend that you declare consistently-named identifier attributes on persistent classes and that you use a wrapper (i.e., non-primitive) type (e.g. `Long` or `Integer`).
====

The placement of the `@Id` annotation marks the <<chapters/domain/access.adoc#access,persistence state access strategy>>.

[[entity-pojo-identifier-mapping-example]]
.Identifier mapping
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-identifier-mapping-example, indent=0]
----
====

Hibernate offers multiple identifier generation strategies, see the <<chapters/domain/identifiers.adoc#identifiers,Identifier Generators>> chapter for more about this topic.

[[entity-pojo-mapping]]
==== Mapping the entity

The main piece in mapping the entity is the {jpaJavadocUrlPrefix}Entity.html[`jakarta.persistence.Entity`] annotation.

The `@Entity` annotation defines just the {jpaJavadocUrlPrefix}Entity.html#name--[`name`] attribute which is used to give a specific entity name for use in JPQL queries.

By default, if the name attribute of the `@Entity` annotation is missing, the unqualified name of the entity class itself will be used as the entity name.

[IMPORTANT]
====
Because the entity name is given by the unqualified name of the class, Hibernate does not allow registering multiple entities with the same name even if the entity classes reside in different packages.

Without imposing this restriction, Hibernate would not know which entity class is referenced in a JPQL query if the unqualified entity name is associated with more then one entity classes.
====

In the following example, the entity name (e.g. `Book`) is given by the unqualified name of the entity class name.

[[entity-pojo-mapping-implicit-name-example]]
.`@Entity` mapping with an implicit name
====
[source,java]
----
include::{example-dir-mapping}/identifier/Book.java[tag=entity-pojo-mapping-implicit-name-example, indent=0]
----
====

However, the entity name can also be set explicitly as illustrated by the following example.

[[entity-pojo-mapping-example]]
.`@Entity` mapping with an explicit name
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-mapping-example, indent=0]
----
====

An entity models a database table.
The identifier uniquely identifies each row in that table.
By default, the name of the table is assumed to be the same as the name of the entity.
To explicitly give the name of the table or to specify other information about the table, we would use the `jakarta.persistence.Table` annotation.

[[entity-pojo-table-mapping-example]]
.Simple `@Entity` with `@Table`
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTableTest.java[tag=entity-pojo-table-mapping-example, indent=0]
----
====

[[mapping-entity-table-catalog]]
===== Mapping the catalog of the associated table

Without specifying the catalog of the associated database table a given entity is mapped to, Hibernate will use the default catalog associated with the current database connection.

However, if your database hosts multiple catalogs, you can specify the catalog where a given table is located using the `catalog` attribute of the Jakarta Persistence {jpaJavadocUrlPrefix}Table.html[`@Table`] annotation.

Let's assume we are using MySQL and want to map a `Book` entity to the `book` table located in the `public` catalog
which looks as follows.

[[mapping-post-table-catalog-mysql-example]]
.The `book` table located in the `public` catalog
====
[source,sql]
----
include::{extrasdir}/entity/mapping-post-table-catalog-mysql-example.sql[]
----
====

Now, to map the `Book` entity to the `book` table in the `public` catalog we can use the `catalog` attribute of the `@Table` Jakarta Persistence annotation.

[[mapping-entity-table-catalog-mysql-example]]
.Specifying the database catalog using the `@Table` annotation
====
[source,java]
----
include::{example-dir-mapping}/identifier/EntityTableCatalogTest.java[tag=mapping-entity-table-catalog-mysql-example, indent=0]
----
====

[[mapping-entity-table-schema]]
===== Mapping the schema of the associated table

Without specifying the schema of the associated database table a given entity is mapped to, Hibernate will use the default schema associated with the current database connection.

However, if your database supports schemas, you can specify the schema where a given table is located using the `schema` attribute of the Jakarta Persistence {jpaJavadocUrlPrefix}Table.html[`@Table`] annotation.

Let's assume we are using PostgreSQL and want to map a `Book` entity to the `book` table located in the `library` schema
which looks as follows.

[[mapping-post-table-schema-postgresql-example]]
.The `book` table located in the `library` schema
====
[source,sql]
----
include::{extrasdir}/entity/mapping-post-table-schema-postgresql-example.sql[]
----
====

Now, to map the `Book` entity to the `book` table in the `library` schema we can use the `schema` attribute of the `@Table` Jakarta Persistence annotation.

[[mapping-entity-table-catalog-postgresql-example]]
.Specifying the database schema using the `@Table` annotation
====
[source,java]
----
include::{example-dir-mapping}/identifier/EntityTableSchemaTest.java[tag=mapping-entity-table-schema-postgresql-example, indent=0]
----
====

[IMPORTANT]
====
The `schema` attribute of the `@Table` annotation works only if the underlying database supports schemas (e.g. PostgreSQL).

Therefore, if you're using MySQL or MariaDB, which do not support schemas natively (schemas being just an alias for catalog), you need to use the
`catalog` attribute, and not the `schema` one.
====

[[mapping-model-pojo-equalshashcode]]
==== Implementing `equals()` and `hashCode()`

[NOTE]
====
Much of the discussion in this section deals with the relation of an entity to a Hibernate Session, whether the entity is managed, transient or detached.
If you are unfamiliar with these topics, they are explained in the <<chapters/pc/PersistenceContext.adoc#pc,Persistence Context>> chapter.
====

Whether to implement `equals()` and `hashCode()` methods in your domain model, let alone how to implement them, is a surprisingly tricky discussion when it comes to ORM.

There is really just one absolute case: a class that acts as an identifier must implement equals/hashCode based on the id value(s).
Generally, this is pertinent for user-defined classes used as composite identifiers.
Beyond this one very specific use case and few others we will discuss below, you may want to consider not implementing equals/hashCode altogether.

So what's all the fuss? Normally, most Java objects provide a built-in `equals()` and `hashCode()` based on the object's identity, so each new object will be different from all others.
This is generally what you want in ordinary Java programming.
Conceptually, however, this starts to break down when you start to think about the possibility of multiple instances of a class representing the same data.

This is, in fact, exactly the case when dealing with data coming from a database.
Every time we load a specific `Person` from the database we would naturally get a unique instance.
Hibernate, however, works hard to make sure that does not happen within a given `Session`.
In fact, Hibernate guarantees equivalence of persistent identity (database row) and Java identity inside a particular session scope.
So if we ask a Hibernate `Session` to load that specific Person multiple times we will actually get back the same __instance__:

[[entity-pojo-identity-scope-example]]
.Scope of identity
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-identity-scope-example, indent=0]
----
====

Consider we have a `Library` parent entity which contains a `java.util.Set` of `Book` entities:

[[entity-pojo-set-mapping-example]]
.Library entity mapping
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-set-mapping-example, indent=0]
----
====

[[entity-pojo-set-identity-scope-example]]
.Set usage with Session-scoped identity
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-set-identity-scope-example, indent=0]
----
====

However, the semantic changes when we mix instances loaded from different Sessions:

[[entity-pojo-multi-session-identity-scope-example]]
.Mixed Sessions
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-multi-session-identity-scope-example, indent=0]
----

[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-multi-session-set-identity-scope-example, indent=0]
----
====

Specifically, the outcome in this last example will depend on whether the `Book` class
implemented equals/hashCode, and, if so, how.

If the `Book` class did not override the default equals/hashCode,
then the two `Book` object references are not going to be equal since their references are different.

Consider yet another case:

[[entity-pojo-transient-set-identity-scope-example]]
.Sets with transient entities
====
[source,java]
----
include::{example-dir-mapping}/identifier/SimpleEntityTest.java[tag=entity-pojo-transient-set-identity-scope-example, indent=0]
----
====

In cases where you will be dealing with entities outside of a Session (whether they be transient or detached),
especially in cases where you will be using them in Java collections,
you should consider implementing equals/hashCode.

A common initial approach is to use the entity's identifier attribute as the basis for equals/hashCode calculations:

[[entity-pojo-naive-equals-hashcode-example]]
.Naive equals/hashCode implementation
====
[source,java]
----
include::{example-dir-mapping}/identifier/NaiveEqualsHashCodeEntityTest.java[tag=entity-pojo-naive-equals-hashcode-example, indent=0]
----
====

It turns out that this still breaks when adding transient instance of `Book` to a set as we saw in the last example:

[[entity-pojo-naive-equals-hashcode-persist-example]]
.Auto-generated identifiers with Sets and naive equals/hashCode
====
[source,java]
----
include::{example-dir-mapping}/identifier/NaiveEqualsHashCodeEntityTest.java[tag=entity-pojo-naive-equals-hashcode-persist-example, indent=0]
----
====

The issue here is a conflict between the use of the generated identifier, the contract of `Set`, and the equals/hashCode implementations.
`Set` says that the equals/hashCode value for an object should not change while the object is part of the `Set`.
But that is exactly what happened here because the equals/hasCode are based on the (generated) id, which was not set until the Jakarta Persistence transaction is committed.

Note that this is just a concern when using generated identifiers.
If you are using assigned identifiers this will not be a problem, assuming the identifier value is assigned prior to adding to the `Set`.

Another option is to force the identifier to be generated and set prior to adding to the `Set`:

[[entity-pojo-naive-equals-hashcode-persist-force-flush-example]]
.Forcing the flush before adding to the Set
====
[source,java]
----
include::{example-dir-mapping}/identifier/NaiveEqualsHashCodeEntityTest.java[tag=entity-pojo-naive-equals-hashcode-persist-force-flush-example, indent=0]
----
====

But this is often not feasible.

The final approach is to use a "better" equals/hashCode implementation, making use of a natural-id or business-key.

[[entity-pojo-natural-id-equals-hashcode-example]]
.Natural Id equals/hashCode
====
[source,java]
----
include::{example-dir-mapping}/identifier/NaturalIdEqualsHashCodeEntityTest.java[tag=entity-pojo-natural-id-equals-hashcode-example, indent=0]
----
====

This time, when adding a `Book` to the `Library` `Set`, you can retrieve the `Book` even after it's being persisted:

[[entity-pojo-natural-id-equals-hashcode-persist-example]]
.Natural Id equals/hashCode persist example
====
[source,java]
----
include::{example-dir-mapping}/identifier/NaturalIdEqualsHashCodeEntityTest.java[tag=entity-pojo-natural-id-equals-hashcode-persist-example, indent=0]
----
====

As you can see the question of equals/hashCode is not trivial, nor is there a one-size-fits-all solution.

[TIP]
====
Although using a natural-id is best for `equals` and `hashCode`, sometimes you only have the entity identifier that provides a unique constraint.

It's possible to use the entity identifier for equality check, but it needs a workaround:

- you need to provide a constant value for `hashCode` so that the hash code value does not change before and after the entity is flushed.
- you need to compare the entity identifier equality only for non-transient entities.
====

For details on mapping the identifier, see the <<chapters/domain/identifiers.adoc#identifiers,Identifiers>> chapter.

[[entity-sql-query-mapping]]
==== Mapping the entity to a SQL query

You can map an entity to a SQL query using the https://docs.hibernate.org/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/Subselect.html[`@Subselect`] annotation.

[[mapping-Subselect-example]]
.`@Subselect` entity mapping
====
[source,java]
----
include::{example-dir-mapping}/basic/SubselectTest.java[tag=mapping-Subselect-example,indent=0]
----
====

In the example above, the `Account` entity does not retain any balance since every account operation is registered as an `AccountTransaction`.
To find the `Account` balance, we need to query the `AccountSummary` which shares the same identifier with the `Account` entity.

However, the `AccountSummary` is not mapped to a physical table, but to an SQL query.

So, if we have the following `AccountTransaction` record, the `AccountSummary` balance will match the proper amount of money in this `Account`.

[[mapping-Subselect-entity-find-example]]
.Finding a `@Subselect` entity
====
[source,java]
----
include::{example-dir-mapping}/basic/SubselectTest.java[tag=mapping-Subselect-entity-find-example,indent=0]
----
====

[NOTE]
====
The underlying `@Subselect` SQL query supports standard Hibernate placeholders ( see <<chapters/query/native/Native.adoc#sql-global-catalog-schema,Catalog and schema in SQL queries>> ).
Global settings can be overridden using the `schema` or `catalog` attributes of the `@Table` annotation.
====

If we add a new `AccountTransaction` entity and refresh the `AccountSummary` entity, the balance is updated accordingly:

[[mapping-Subselect-refresh-find-example]]
.Refreshing a `@Subselect` entity
====
[source,java]
----
include::{example-dir-mapping}/basic/SubselectTest.java[tag=mapping-Subselect-entity-refresh-example,indent=0]
----
====

[TIP]
====
The goal of the `@Synchronize` annotation in the `AccountSummary` entity mapping is to instruct Hibernate which database tables are needed by the
underlying `@Subselect` SQL query. This is because, unlike JPQL and HQL queries, Hibernate cannot parse the underlying native SQL query.

With the `@Synchronize` annotation in place,
when executing an HQL or JPQL which selects from the `AccountSummary` entity,
Hibernate will trigger a Persistence Context flush if there are pending `Account`, `Client` or `AccountTransaction` entity state transitions.
====

[[concrete-proxy]]
==== Create proxies that resolve their inheritance subtype

When working with lazy associations or entity references for types that define and inheritance hierarchy Hibernate often creates proxies starting from the root class, with no information about the actual subtype that's referenced by the lazy instance. This can be a problem when using `instanceof` to check the type of said lazy entity references or when trying to cast to the concrete subtype.

The https://docs.hibernate.org/orm/{majorMinorVersion}/javadocs/org/hibernate/annotations/ConcreteProxy.html[`@ConcreteProxy`] annotation can be used on an entity hierarchy root mapping to specify that Hibernate should always try to resolve the actual subtype corresponding to the proxy instance created. This effectively means that proxies for that entity hierarchy will always be created from the correct subclass, allowing to preserve laziness and enable using type checks and casts.

[[entity-concrete-proxy-mapping]]
.Root entity class annotated with `@ConcreteProxy`
====
[source,java]
----
include::{example-dir-proxy}/concrete/ConcreteProxyTest.java[tag=entity-concrete-proxy-mapping,indent=0]
----
====

In the following example we load the parent's lazy association and resolve to the concrete `SingleSubChild1` type:

[[entity-concrete-proxy-find]]
.Loading parent entity with lazy association
====
[source,java]
----
include::{example-dir-proxy}/concrete/ConcreteProxyTest.java[tag=entity-concrete-proxy-find,indent=0]
----

[source,sql]
----
include::{extrasdir}/entity/entity-concrete-proxy-find.sql[]
----
====

IMPORTANT: This added functionality does not come free: in order to determine the concrete type to use when creating the Proxy instance, Hibernate might need to access the association target's table(s) to discover the actual subtype corresponding to a specific identifier value.

The concrete type will be determined:

* With *single table* inheritance, the discriminator column value will be left joined when fetching associations or simply read from the entity table when getting references.
* When using *joined* inheritance, all subtype tables will need to be left joined to determine the concrete type. Note however that when using an explicit discriminator column, the behavior is the same as for single-table inheritance.
* Finally, for *table-per-class* inheritance, all subtype tables will need to be (union) queried to determine the concrete type.

In the following example, you can see how Hibernate issues a query to resolve the concrete proxy type for an entity reference:

[[entity-concrete-proxy-reference]]
.Resolving the concrete proxy type for `getReference()`:
====
[source,java]
----
include::{example-dir-proxy}/concrete/ConcreteProxyTest.java[tag=entity-concrete-proxy-reference,indent=0]
----

[source,sql]
----
include::{extrasdir}/entity/entity-concrete-proxy-reference.sql[]
----
====
