[[identifiers]]
=== Identifiers
:root-project-dir: ../../../../../../..
:core-project-dir: {root-project-dir}/hibernate-core
:core-test-base: {core-project-dir}/src/test/java/org/hibernate/orm/test
:example-dir-identifier: {core-test-base}/mapping/identifier
:example-dir-associations: {core-test-base}/associations
:jpaJavadocUrl: https://javadoc.io/doc/jakarta.persistence/jakarta.persistence-api/latest/jakarta.persistence
:extrasdir: extras

Identifiers model the primary key of an entity. They are used to uniquely identify each specific entity.

Hibernate and Jakarta Persistence both make the following assumptions about the corresponding database column(s):

`UNIQUE`:: The values must uniquely identify each row.
`NOT NULL`:: The values cannot be null. For composite ids, no part can
be null.
`IMMUTABLE`:: The values, once inserted, can never be changed.  In cases where the values for the PK you have
chosen will be updated, Hibernate recommends mapping the mutable value as a natural id, and use a surrogate id
for the PK.  See <<chapters/domain/natural_id.adoc#naturalid,Natural Ids>>.

[NOTE]
====
Technically the identifier does not have to map to the column(s) physically defined as the table primary key.
They just need to map to column(s) that uniquely identify each row.
However, this documentation will continue to use the terms identifier and primary key interchangeably.
====

Every entity must define an identifier. For entity inheritance hierarchies, the identifier must be defined just on the entity that is the root of the hierarchy.

An identifier may be <<identifiers-simple,simple>> or <<identifiers-composite,composite>>.

[[identifiers-simple]]
==== Simple identifiers

Simple identifiers map to a single basic attribute, and are denoted using the `jakarta.persistence.Id` annotation.

According to Jakarta Persistence, only the following types are portably supported for use as identifier attribute types:

* any Java primitive type
* any primitive wrapper type
* `java.lang.String`
* `java.util.Date` (`TemporalType#DATE`)
* `java.sql.Date`
* `java.math.BigDecimal`
* `java.math.BigInteger`

Hibernate, however, supports a more broad set of types to be used for identifiers (`UUID`, e.g.).


[[identifiers-simple-assigned]]
===== Assigned identifiers

Values for simple identifiers can be assigned, which simply means that the application itself will
assign the value to the identifier attribute prior to persisting the entity.

[[identifiers-simple-assigned-mapping-example]]
.Simple assigned entity identifier
====
[source,java]
----
include::{example-dir-identifier}/AssignedIdentifierTest.java[tag=identifiers-simple-assigned-mapping-example, indent=0]
----
====


[[identifiers-simple-generated]]
===== Generated identifiers

Values for simple identifiers can be generated. To denote that an identifier attribute is generated, it is
annotated with `jakarta.persistence.GeneratedValue`

[[identifiers-simple-generated-mapping-example]]
.Simple generated identifier
====
[source,java]
----
include::{example-dir-identifier}/GeneratedIdentifierTest.java[tag=identifiers-simple-generated-mapping-example, indent=0]
----
====

When an entity with an identifier defined as generated is persisted, Hibernate will generate the value based on
an associated generation strategy.  Identifier value generations strategies are discussed in detail in the
<<identifiers-generators>> section.

[NOTE]
====
While Hibernate supports almost any valid basic type be used for generated identifier values,
Jakarta Persistence restricts the allowable types to just integer types.
====


[[identifiers-composite]]
==== Composite identifiers

Composite identifiers correspond to one or more persistent attributes.
Here are the rules governing composite identifiers, as defined by the Jakarta Persistence specification:

* The composite identifier must be represented by a "primary key class".
The primary key class may be defined using the `jakarta.persistence.EmbeddedId` annotation (see <<identifiers-composite-aggregated>>),
or defined using the `jakarta.persistence.IdClass` annotation (see <<identifiers-composite-nonaggregated>>).
* The primary key class must be public and must have a public no-arg constructor.
* The primary key class must be serializable.
* The primary key class must define equals and hashCode methods, consistent with equality for the underlying database types to which the primary key is mapped.

[NOTE]
====
The restriction that a composite identifier has to be represented by a "primary key class" (e.g. `@EmbeddedId` or `@IdClass`) is only
Jakarta Persistence-specific.

Hibernate does allow composite identifiers to be defined without a "primary key class" via multiple `@Id` attributes, although that
is generally considered poor design.
====

The attributes making up the composition can be either basic, composite or `@ManyToOne`.  Note especially that collection and one-to-one
are never appropriate.


[[identifiers-composite-aggregated]]
==== Composite identifiers with `@EmbeddedId`

Modeling a composite identifier using an EmbeddedId simply means defining an embeddable to be a composition for the attributes making up
the identifier, and then exposing an attribute of that embeddable type on the entity.

[[identifiers-basic-embeddedid-mapping-example]]
.Basic `@EmbeddedId`
====
[source,java]
----
include::{example-dir-identifier}/EmbeddedIdTest.java[tag=identifiers-basic-embeddedid-mapping-example, indent=0]
----
====

As mentioned before, EmbeddedIds can even contain `@ManyToOne` attributes:

[[identifiers-basic-embeddedid-manytoone-mapping-example]]
.`@EmbeddedId` with `@ManyToOne`
====
[source,java]
----
include::{example-dir-identifier}/EmbeddedIdManyToOneTest.java[tag=identifiers-basic-embeddedid-manytoone-mapping-example, indent=0]
----
====

[NOTE]
====
Hibernate supports directly modeling `@ManyToOne` associations in the Primary Key class, whether `@EmbeddedId` or `@IdClass`.

However, that is not portably supported by the Jakarta Persistence specification.
In Jakarta Persistence terms, one would use "derived identifiers". For more details, see <<identifiers-derived>>.
====

[[identifiers-composite-nonaggregated]]
==== Composite identifiers with `@IdClass`

Modeling a composite identifier using an IdClass differs from using an EmbeddedId in that the entity defines each individual
attribute making up the composition.  The IdClass is used as the representation of the identifier for load-by-id operations.

[[identifiers-basic-idclass-mapping-example]]
.Basic `@IdClass`
====
[source,java]
----
include::{example-dir-identifier}/IdClassTest.java[tag=identifiers-basic-idclass-mapping-example, indent=0]
----
====

Non-aggregated composite identifiers can also contain ManyToOne attributes as we saw with aggregated mappings, though still non-portably.

[[identifiers-basic-idclass-manytoone-mapping-example]]
.IdClass with `@ManyToOne`
====
[source,java]
----
include::{example-dir-identifier}/IdClassManyToOneTest.java[tag=identifiers-basic-idclass-manytoone-mapping-example, indent=0]
----
====

With non-aggregated composite identifiers, Hibernate also supports "partial" generation of the composite values.

[[identifiers-basic-idclass-generatedvalue-mapping-example]]
.`@IdClass` with partial identifier generation using `@GeneratedValue`
====
[source,java]
----
include::{example-dir-identifier}/IdClassGeneratedValueTest.java[tag=identifiers-basic-idclass-generatedvalue-mapping-example, indent=0]
----
====

[NOTE]
====
This feature which allows auto-generated values in composite identifiers exists because of a highly questionable interpretation
of the Jakarta Persistence specification made by the SpecJ committee.

Hibernate does not feel that Jakarta Persistence defines support for this, but added the feature simply to be usable in SpecJ
benchmarks.  Use of this feature may or may not be portable from a Jakarta Persistence perspective.
====

[[identifiers-composite-associations]]
==== Composite identifiers with associations

Hibernate allows defining a composite identifier out of entity associations.
In the following example, the `Book` entity identifier is formed of two `@ManyToOne` associations.

[[identifiers-composite-id-mapping-example]]
.Composite identifiers with associations
====
[source,java]
----
include::{example-dir-identifier}/IdManyToOneTest.java[tag=identifiers-composite-id-mapping-example, indent=0]
----
====

Although the mapping is much simpler than using an `@EmbeddedId` or an `@IdClass`, there's no separation between the entity instance and the actual identifier.
To query this entity, an instance of the entity itself must be supplied to the persistence context.

[[identifiers-composite-id-fetching-example]]
.Fetching with composite identifiers
====
[source,java]
----
include::{example-dir-identifier}/IdManyToOneTest.java[tag=identifiers-composite-id-fetching-example, indent=0]
----
====

[[identifiers-composite-generated]]
==== Composite identifiers with generated properties

When using composite identifiers, the underlying identifier properties must be manually assigned by the user.

Automatically generated properties are not supported to be used to generate the value of an underlying property that makes the composite identifier.

Therefore, you cannot use any of the automatic property generator described by the <<chapters/domain/basic_types.adoc#mapping-generated, generated properties section>> like `@Generated`, `@CreationTimestamp` or `@ValueGenerationType` or database-generated values.

Nevertheless, you can still generate the identifier properties prior to constructing the composite identifier, as illustrated by the following examples.

Assuming we have the following `EventId` composite identifier and an `Event` entity which uses the aforementioned composite identifier.

[[identifiers-composite-generated-mapping-example]]
.The Event entity and EventId composite identifier
====
[source,java]
----
include::{example-dir-identifier}/composite/Event.java[tag=identifiers-composite-generated-mapping-example, indent=0]
----

[source,java]
----
include::{example-dir-identifier}/composite/EventId.java[tag=identifiers-composite-generated-mapping-example, indent=0]
----
====

[[identifiers-composite-generated-in-memory]]
===== In-memory generated composite identifier properties

If you want to generate the composite identifier properties in-memory,
you need to do that as follows:

[[identifiers-composite-generated-in-memory-example]]
.In-memory generated composite identifier properties example
====
[source,java]
----
include::{example-dir-identifier}/composite/EmbeddedIdInMemoryGeneratedValueTest.java[tag=identifiers-composite-generated-in-memory-example, indent=0]
----
====

Notice that the `createdOn` property of the `EventId` composite identifier was generated by the data access code and assigned to the
identifier prior to persisting the `Event` entity.

[[identifiers-composite-generated-database]]
===== Database generated composite identifier properties

If you want to generate the composite identifier properties using a database function or stored procedure,
you could to do it as illustrated by the following example.

[[identifiers-composite-generated-database-example]]
.Database generated composite identifier properties example
====
[source,java]
----
include::{example-dir-identifier}/composite/EmbeddedIdDatabaseGeneratedValueTest.java[tag=identifiers-composite-generated-database-example, indent=0]
----
====

Notice that the `createdOn` property of the `EventId` composite identifier was generated by calling the `CURRENT_TIMESTAMP` database function,
and we assigned it to the composite identifier prior to persisting the `Event` entity.


[[identifiers-generators]]
==== Generated identifier values

Hibernate supports identifier value generation across a number of different types.
Remember that Jakarta Persistence portably defines identifier value generation just for integer types.

[NOTE]
====
You can also auto-generate values for non-identifier attributes. For more details, see the <<chapters/domain/basic_types.adoc#mapping-generated,Generated properties>> section.
====


Identifier value generation is indicated using the `jakarta.persistence.GeneratedValue` annotation.
The most important piece of information here is the specified `jakarta.persistence.GenerationType` which indicates how values will be generated.

`AUTO` (the default):: Indicates that the persistence provider (Hibernate) should choose an appropriate generation strategy. See <<identifiers-generators-auto>>.
`IDENTITY`:: Indicates that database IDENTITY columns will be used for primary key value generation. See <<identifiers-generators-identity>>.
`SEQUENCE`:: Indicates that database sequence should be used for obtaining primary key values. See <<identifiers-generators-sequence>>.
`TABLE`:: Indicates that a database table should be used for obtaining primary key values. See <<identifiers-generators-table>>.
`UUID`:::Indicates that UUID generation should be used.  See <<identifiers-generators-uuid>>

[[identifiers-generators-auto]]
==== Interpreting AUTO

How a persistence provider interprets the AUTO generation type is left up to the provider.

The default behavior is to look at the Java type of the identifier attribute, plus what the underlying database supports.

If the identifier type is UUID, Hibernate is going to use a <<identifiers-generators-uuid, UUID generator>>.

If the identifier type is numeric (e.g. `Long`, `Integer`), then Hibernate will use its `SequenceStyleGenerator` which
resolves to a SEQUENCE generation if the underlying database supports sequences and a table-based generation otherwise.


[[identifiers-generators-sequence]]
==== Using sequences

For implementing database sequence-based identifier value generation Hibernate makes use of its
`org.hibernate.id.enhanced.SequenceStyleGenerator` id generator.  It is important to note that `SequenceStyleGenerator`
is capable of working against databases that do not support sequences by transparently switching to a table as the
underlying backing, which gives Hibernate a huge degree of portability across databases while still maintaining consistent
id generation behavior (versus say choosing between SEQUENCE and IDENTITY).


[[identifiers-generators-sequence-unnamed]]
.Implicit sequence
====
[source,java]
----
include::{example-dir-identifier}/SequenceGeneratorUnnamedTest.java[tag=identifiers-generators-sequence-mapping-example, indent=0]
----
====

Notice that the mapping does not specify the name of the sequence to use.  In such cases, Hibernate will assume a
sequence name based on the name of the table to which the entity is mapped.  Here, since the entity is mapped to
a table named `product`, Hibernate will use a sequence named `product_seq`.

[NOTE]
====
When using `@Subselect` mappings, using the "table name" is not valid so Hibernate falls back to using the entity
name as the base along with the `_seq` suffix.
====


To specify the sequence name explicitly, the simplest form is to specify `@GeneratedValue#generator`.


[[identifiers-generators-sequence-named]]
.Named sequence
====
[source,java]
----
include::{example-dir-identifier}/SequenceGeneratorAnnotationNameTest.java[tag=identifiers-generators-sequence-mapping-example, indent=0]
----
====

For this mapping, Hibernate will use `explicit_product_sequence` as the name of the sequence.

For more advanced configuration, Jakarta Persistence defines the `@SequenceGenerator` annotation.

[[identifiers-generators-sequence-gen-simple]]
.Simple @SequenceGenerator
====
[source,java]
----
include::{example-dir-identifier}/SequenceGeneratorNamedTest.java[tag=identifiers-generators-sequence-mapping-example, indent=0]
----
====

This is simply a more verbose form of the mapping in <<identifiers-generators-sequence-named>>.
However, the `jakarta.persistence.SequenceGenerator` annotation allows you to specify additional
configurations as well.

[[identifiers-generators-sequence-configured]]
.Sequence configuration
====
[source,java]
----
include::{example-dir-identifier}/SequenceGeneratorConfiguredTest.java[tag=identifiers-generators-sequence-mapping-example, indent=0]
----
====

Again the mapping specifies `explicit_product_sequence` as the physical sequence name, but it also specifies an
explicit allocation-size ("increment by").


[[identifiers-generators-identity]]
==== Using IDENTITY columns

For implementing identifier value generation based on IDENTITY columns,
Hibernate makes use of its `org.hibernate.id.IdentityGenerator` id generator which expects the identifier to be generated by INSERT into the table.
IdentityGenerator understands 3 different ways that the INSERT-generated value might be retrieved:

* If Hibernate believes the JDBC environment supports `java.sql.Statement#getGeneratedKeys`, then that approach will be used for extracting the IDENTITY generated keys.
* Otherwise, if `Dialect#supportsInsertSelectIdentity` reports true, Hibernate will use the Dialect specific INSERT+SELECT statement syntax.
* Otherwise, Hibernate will expect that the database supports some form of asking for the most recently inserted IDENTITY value via a separate SQL command as indicated by `Dialect#getIdentitySelectString`.

[IMPORTANT]
====
It is important to realize that using IDENTITY columns imposes a runtime behavior where the entity
row *must* be physically inserted prior to the identifier value being known.

This can mess up extended persistence contexts (long conversations).
Because of the runtime imposition/inconsistency, Hibernate suggests other forms of identifier value generation
be used (e.g. SEQUENCE) with extended contexts.

In Hibernate 5.3, Hibernate attempts to delay the insert of entities if the flush-mode does not equal `AUTO`.
This was slightly problematic for entities that used `IDENTITY` or `SEQUENCE` generated identifiers that were
also involved in some form of association with another entity in the same transaction.

In Hibernate 5.4, Hibernate attempts to remedy the problem using an algorithm to decide if the insert should
be delayed or if it requires immediate insertion.  We wanted to restore the behavior prior to 5.3 only for
very specific use cases where it made sense.

Entity mappings can sometimes be complex and it is possible a corner case was overlooked.  Hibernate offers a
way to completely disable the 5.3 behavior in the event problems occur with `DelayedPostInsertIdentifier`.  To
enable the legacy behavior, set `hibernate.id.disable_delayed_identity_inserts=true`.

This configuration option is meant to act as a _temporary_ fix and bridge the gap between the changes in this
behavior across Hibernate 5.x releases.  If this configuration setting is necessary for a mapping, please open
a JIRA and report the mapping so that the algorithm can be reviewed.
====


[NOTE]
====
There is yet another important runtime impact of choosing IDENTITY generation: Hibernate will not be able to batch INSERT statements for the entities using the IDENTITY generation.

The importance of this depends on the application-specific use cases.
If the application is not usually creating many new instances of a given entity type using the IDENTITY generator, then this limitation will be less important since batching would not have been very helpful anyway.
====

[[identifiers-generators-table]]
==== Using the table identifier generator

Hibernate achieves table-based identifier generation based on its `org.hibernate.id.enhanced.TableGenerator` which defines a table capable of holding multiple named value segments for any number of entities.


The basic idea is that a given table-generator table (`hibernate_sequences` for example) can hold multiple segments of identifier generation values.

[[identifiers-generators-table-unnamed-mapping-example]]
.Unnamed table generator
====
[source,java]
----
include::{example-dir-identifier}/TableGeneratorUnnamedTest.java[tag=identifiers-generators-table-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/id/identifiers-generators-table-unnamed-mapping-example.sql[]
----
====

If no table name is given Hibernate assumes an implicit name of `hibernate_sequences`.

Additionally, because no `jakarta.persistence.TableGenerator#pkColumnValue` is specified,
Hibernate will use the default segment (`sequence_name='default'`) from the hibernate_sequences table.

However, you can configure the table identifier generator using the {jpaJavadocUrl}/TableGenerator.html[`@TableGenerator`] annotation.

[[identifiers-generators-table-configured-mapping-example]]
.Configured table generator
====
[source,java]
----
include::{example-dir-identifier}/TableGeneratorConfiguredTest.java[tag=identifiers-generators-table-mapping-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/id/identifiers-generators-table-configured-mapping-example.sql[]
----
====

Now, when inserting 3 `Product` entities, Hibernate generates the following statements:

[[identifiers-generators-table-configured-persist-example]]
.Configured table generator persist example
====
[source,java]
----
include::{example-dir-identifier}/TableGeneratorConfiguredTest.java[tag=identifiers-generators-table-persist-example, indent=0]
----

[source,sql]
----
include::{extrasdir}/id/identifiers-generators-table-configured-persist-example.sql[]
----
====

[[identifiers-generators-uuid]]
==== Using UUID generation

Hibernate offers 2 flavors of support for UUID generation -

1. using `org.hibernate.id.uuid.UuidGenerator`, which can be configured using the `org.hibernate.annotations.UuidGenerator` annotation.
2. using `org.hibernate.id.UUIDGenerator`, which can be configured using the `@GenericGenerator` annotation.  Note that this approach is deprecated.

For legacy reasons, `org.hibernate.id.UUIDGenerator` is used when the generator is implicit (or explicitly requested via `@GenericGenerator`).

[NOTE]
====
Future versions of Hibernate will drop support for `org.hibernate.id.UUIDGenerator` and the following 3 examples
will then use `org.hibernate.id.uuid.UuidGenerator`.
====

[[example-identifiers-generators-uuid-implicit]]
.Implicit UUID generation
====
[source,java]
----
include::{example-dir-identifier}/uuid/implicit/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

[[example-identifiers-generators-uuid-implicit2]]
.Another example of implicit UUID generation
====
[source,java]
----
include::{example-dir-identifier}/uuid/implicit2/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

[[example-identifiers-generators-uuid-implicit3]]
.Implicit UUID generation with String
====
[source,java]
----
include::{example-dir-identifier}/uuid/implicit3/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

The second approach, using `org.hibernate.id.uuid.UuidGenerator`, is much more flexible and usable
because it builds on top of the <<identifiers-generators-IdGeneratorType,@IdGeneratorType>> support.

To use (and optionally configure) this strategy, use the `org.hibernate.annotations.UuidGenerator` annotation.

By default, Hibernate uses a random (IETF RFC 4122 version 4) generation.

[[example-identifiers-generators-uuid-random]]
.Random UUID generation
====
[source,java]
----
include::{example-dir-identifier}/uuid/random/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

[[example-identifiers-generators-uuid-random2]]
.Random UUID generation, with explicit style
====
[source,java]
----
include::{example-dir-identifier}/uuid/random2/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

[[example-identifiers-generators-uuid-random3]]
.Random UUID generation, with String
====
[source,java]
----
include::{example-dir-identifier}/uuid/random3/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

Hibernate also comes with simplified support for a time-based (IETF RFC 4122 version 1, variant2) generation.

[[example-identifiers-generators-uuid-time]]
.Time-based UUID generation
====
[source,java]
----
include::{example-dir-identifier}/uuid/time/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

[[example-identifiers-generators-uuid-time2]]
.Time-based UUID generation using String
====
[source,java]
----
include::{example-dir-identifier}/uuid/time2/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

For even more flexibility, Hibernate also offers the ability to plug in custom algorithms for creating the UUID value
by specifying an implementation of `org.hibernate.id.uuid.UuidValueGenerator`.

[[example-identifiers-generators-uuid-custom]]
.Custom UUID generation
====
[source,java]
----
include::{example-dir-identifier}/uuid/custom/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====

[[example-identifiers-generators-uuid-custom2]]
.Custom UUID generation using String
====
[source,java]
----
include::{example-dir-identifier}/uuid/custom2/Book.java[tag=example-identifiers-generators-uuid-implicit, indent=0]
----
====


[[identifiers-generators-optimizer]]
==== Optimizers

Most of the Hibernate generators that separately obtain identifier values from database structures support the use of pluggable optimizers.
Optimizers help manage the number of times Hibernate has to talk to the database in order to generate identifier values.
For example, with no optimizer applied to a sequence-generator, every time the application asked Hibernate to generate an identifier it would need to grab the next sequence value from the database.
But if we can minimize the number of times we need to communicate with the database here, the application will be able to perform better,
which is, in fact, the role of these optimizers.

none:: No optimization is performed. We communicate with the database each and every time an identifier value is needed from the generator.

pooled-lo:: The pooled-lo optimizer works on the principle that the increment-value is encoded into the database table/sequence structure.
In sequence-terms, this means that the sequence is defined with a greater-than-1 increment size.
+
For example, consider a brand new sequence defined as `create sequence m_sequence start with 1 increment by 20`.
This sequence essentially defines a "pool" of 20 usable id values each and every time we ask it for its next-value.
The pooled-lo optimizer interprets the next-value as the low end of that pool.
+
So when we first ask it for next-value, we'd get 1.
We then assume that the valid pool would be the values from 1-20 inclusive.
+
The next call to the sequence would result in 21, which would define 21-40 as the valid range. And so on.
The "lo" part of the name indicates that the value from the database table/sequence is interpreted as the pool lo(w) end.

pooled:: Just like pooled-lo, except that here the value from the table/sequence is interpreted as the high end of the value pool.

hilo; legacy-hilo:: Define a custom algorithm for generating pools of values based on a single value from a table or sequence.
+
These optimizers are not recommended for use. They are maintained (and mentioned) here simply for use by legacy applications that used these strategies previously.

[NOTE]
====
Applications can also implement and use their own optimizer strategies, as defined by the `org.hibernate.id.enhanced.Optimizer` contract.
====

[[identifiers-generators-IdGeneratorType]]
==== Using `@IdGeneratorType`

`@IdGeneratorType` is a meta-annotation that allows the creation of custom annotations that support simple, concise
and type-safe definition and configuration of custom `org.hibernate.id.IdentifierGenerator` implementations.

[[identifiers-IdGeneratorType-example]]
.@IdGeneratorType
====
[source,java]
----
include::{core-test-base}/id/custom/CustomSequenceGenerator.java[tag=identifiers-IdGeneratorType-example, indent=0]

include::{core-test-base}/id/custom/Sequence.java[tag=identifiers-IdGeneratorType-example, indent=0]
----
====

The example illustrates using `@IdGeneratorType` to define a custom sequence-based annotation `@Sequence`
to apply and configure a custom `IdentifierGenerator` implementation `CustomSequenceGenerator`.

Notice the `CustomSequenceGenerator` constructor.  Custom generator defined through `@IdGeneratorType`
receive the following arguments:

1. The configuration annotation - here, `@Sequence`.  This is the type-safety aspect, rather than
relying on untyped configuration properties in a Map, etc.
2. The `Member` to which annotation was applied.  This allows access to the Java type of the identifier
attribute, etc.
3. `CustomIdGeneratorCreationContext` is a "parameter object" providing access to things often useful
for identifier generators.



[[identifiers-generators-GenericGenerator]]
==== Using `@GenericGenerator`

[TIP]
====
`@GenericGenerator` is generally considered deprecated in favor of <<identifiers-generators-IdGeneratorType,@IdGeneratorType>>
====

`@GenericGenerator` allows integration of any Hibernate `org.hibernate.id.IdentifierGenerator` implementation, including any of the specific ones discussed here and any custom ones.

[[identifiers-generators-pooled-lo-optimizer-mapping-example]]
.Pooled-lo optimizer mapping using `@GenericGenerator` mapping
====
[source, JAVA, indent=0]
----
include::{example-dir-identifier}/PooledOptimizerTest.java[tag=identifiers-generators-pooled-lo-optimizer-mapping-example]
----
====

Now, when saving 5 `Person` entities and flushing the Persistence Context after every 3 entities:

[[identifiers-generators-pooled-lo-optimizer-persist-example]]
.Pooled-lo optimizer mapping using `@GenericGenerator` mapping
====
[source, JAVA, indent=0]
----
include::{example-dir-identifier}/PooledOptimizerTest.java[tag=identifiers-generators-pooled-lo-optimizer-persist-example]
----

[source, SQL, indent=0]
----
include::{extrasdir}/id/identifiers-generators-pooled-lo-optimizer-persist-example.sql[]
----
====

As you can see from the list of generated SQL statements, you can insert 3 entities with just one database sequence call.
This way, the pooled and the pooled-lo optimizers allow you to reduce the number of database round trips, therefore reducing the overall transaction response time.

[[identifiers-derived]]
==== Derived Identifiers

Java Persistence 2.0 added support for derived identifiers which allow an entity to borrow the identifier from a many-to-one or one-to-one association.

[[identifiers-derived-mapsid]]
.Derived identifier with `@MapsId`
====
[source,java]
----
include::{example-dir-associations}/OneToOneMapsIdTest.java[tag=identifiers-derived-mapsid, indent=0]
----
====

In the example above, the `PersonDetails` entity uses the `id` column for both the entity identifier and for the one-to-one association to the `Person` entity.
The value of the `PersonDetails` entity identifier is "derived" from the identifier of its parent `Person` entity.

[[identifiers-derived-mapsid-persist-example]]
.Derived identifier with `@MapsId` persist example
====
[source,java]
----
include::{example-dir-associations}/OneToOneMapsIdTest.java[tag=identifiers-derived-mapsid-persist-example, indent=0]
----
====

The `@MapsId` annotation can also reference columns from an `@EmbeddedId` identifier as well.

The previous example can also be mapped using `@PrimaryKeyJoinColumn`.

[[identifiers-derived-primarykeyjoincolumn]]
.Derived identifier `@PrimaryKeyJoinColumn`
====
[source,java]
----
include::{example-dir-associations}/OneToOnePrimaryKeyJoinColumnTest.java[tag=identifiers-derived-primarykeyjoincolumn, indent=0]
----
====

[NOTE]
====
Unlike `@MapsId`, the application developer is responsible for ensuring that the entity identifier and the many-to-one (or one-to-one) association are in sync, as you can see in the `PersonDetails#setPerson` method.
====

[[identifiers-rowid]]
==== @RowId

If you annotate a given entity with the `@RowId` annotation and the underlying database supports fetching a record by ROWID (e.g. Oracle),
then Hibernate can use the `ROWID` pseudo-column for CRUD operations.

[[identifiers-rowid-mapping]]
.`@RowId` entity mapping
====
[source, JAVA, indent=0]
----
include::{example-dir-identifier}/RowIdTest.java[tag=identifiers-rowid-mapping]
----
====

Now, when fetching an entity and modifying it, Hibernate uses the `ROWID` pseudo-column for the UPDATE SQL statement.

[[identifiers-rowid-example]]
.`@RowId` example
====
[source, JAVA, indent=0]
----
include::{example-dir-identifier}/RowIdTest.java[tag=identifiers-rowid-example]
----

[source, SQL, indent=0]
----
include::{extrasdir}/id/identifiers-rowid-example.sql[]
----
====
