[[entity-inheritance]]
=== Inheritance
:sourcedir: extras

Although relational database systems don't provide inheritance, Hibernate can leverage this object-oriented trait onto domain model entities.
There are several strategies to achieve inheritance:

MappedSuperclass:: Inheritance is implemented in domain model only and the database doesn't reflect it at all. See <<entity-inheritance-mapped-superclass>>.
Single table:: The domain model class hierarchy is materialized into a single table which contains entities belonging to different class types. See <<entity-inheritance-single-table>>.
Joined table:: The base class has a table of its own. Each subclasses goes to its own table too and fetching a subclass entity requires a join with the parent table as well. See <<entity-inheritance-joined-table>>.
Table per class:: Each subclass has a its own table containing both the subclass as well as the base class properties. See <<entity-inheritance-table-per-class>>.

[[entity-inheritance-mapped-superclass]]
==== MappedSuperclass

In the following domain model class hierarchy, a 'DebitAccount' and a 'CreditAccount' share the same 'Account' base class.

image:images/domain/inheritance/inheritance_class_diagram.svg[Inheritance class diagram]

When using `MappedSuperclass`, the inheritance is visible in the domain model only.
Each database table contains both the base class and the subclass properties.

.`@MappedSuperclass` inheritance
====
[source,java]
----
include::{sourcedir}/inheritance/MappedSuperclass.java[]
----

[source,sql]
----
include::{sourcedir}/inheritance/MappedSuperclass.sql[]
----
====

[NOTE]
====
Because the `@MappedSuperclass` inheritance model is not mirrored at database level,
it's not therefore possible to query entities by their base class (like it's the case with all the other inheritance strategies).
====

[[entity-inheritance-single-table]]
==== Single table

TODO

[[entity-inheritance-joined-table]]
==== Joined table

TODO

[[entity-inheritance-table-per-class]]
==== Table per class

TODO