[[criteria]]
== Criteria
:sourcedir: extras

Criteria queries offer a type-safe alternative to HQL, JPQL and
native-sql queries.

[IMPORTANT]
====
Hibernate offers an older, legacy `org.hibernate.Criteria` API which
should be considered deprecated. No feature development will target
those APIs. Eventually, Hibernate-specific criteria features will be
ported as extensions to the JPA
`javax.persistence.criteria.CriteriaQuery`. For details on the
`org.hibernate.Criteria` API, see <<appendices/Legacy_Criteria.adoc#appendix-legacy-criteria, Legacy Hibernate Criteria Queries>>.

This chapter will focus on the JPA APIs for declaring type-safe criteria
queries.
====

Criteria queries are a programmatic, type-safe way to express a query.
They are type-safe in terms of using interfaces and classes to represent
various structural parts of a query such as the query itself, or the
select clause, or an order-by, etc. They can also be type-safe in terms
of referencing attributes as we will see in a bit. Users of the older
Hibernate `org.hibernate.Criteria` query API will recognize the general
approach, though we believe the JPA API to be superior as it represents
a clean look at the lessons learned from that API.

Criteria queries are essentially an object graph, where each part of the
graph represents an increasing (as we navigate down this graph) more
atomic part of query. The first step in performing a criteria query is
building this graph. The javax.persistence.criteria.CriteriaBuilder
interface is the first thing with which you need to become acquainted to
begin using criteria queries. Its role is that of a factory for all the
individual pieces of the criteria. You obtain a
javax.persistence.criteria.CriteriaBuilder instance by calling the
getCriteriaBuilder method of either
javax.persistence.EntityManagerFactory or
javax.persistence.EntityManager.

The next step is to obtain a javax.persistence.criteria.CriteriaQuery.
This is accomplished using one of the 3 methods on
javax.persistence.criteria.CriteriaBuilder for this purpose:

====
[source,java]
----
include::{sourcedir}/CriteriaBuilder_query_creation_snippet.java[]
----
====

Each serves a different purpose depending on the expected type of the
query results.

[NOTE]
====
Chapter 6 Criteria API of the JPA Specification already contains a
decent amount of reference material pertaining to the various parts of a
criteria query. So rather than duplicate all that content here, lets
instead look at some of the more widely anticipated usages of the API.
====

[[querycriteria-typedquery]]
=== Typed criteria queries

The type of the criteria query (aka the <T>) indicates the expected
types in the query result. This might be an entity, an Integer, or any
other object.

[[querycriteria-typedquery-entity]]
=== Selecting an entity

This is probably the most common form of query. The application wants to
select entity instances.

.Selecting the root entity
====
[source,java]
----
include::{sourcedir}/select_root_entity_example.java[]
----
====

The example uses [method]+createQuery+ passing in the [class]+Person+ class reference as the results of the query will be Person objects.

[NOTE]
====
The call to the CriteriaQuery.select method in this example is
unnecessary because _personRoot_ will be the implied selection since we
have only a single query root. It was done here only for completeness of
an example.

The _Person_.eyeColor_ reference is an example of the static form of JPA
metamodel reference. We will use that form exclusively in this chapter.
See the documentation for the Hibernate JPA Metamodel Generator for
additional details on the JPA static metamodel.
====

[[querycriteria-typedquery-expression]]
=== Selecting an expression

The simplest form of selecting an expression is selecting a particular
attribute from an entity. But this expression might also represent an
aggregation, a mathematical operation, etc.

.Selecting an attribute
====
[source,java]
----
include::{sourcedir}/select_attribute_example.java[]
----
====

In this example, the query is typed as `java.lang.Integer` because that
is the anticipated type of the results (the type of the Person#age
attribute is `java.lang.Integer`). Because a query might contain
multiple references to the Person entity, attribute references always
need to be qualified. This is accomplished by the Root#get method call.

[[querycriteria-typedquery-multiselect]]
=== Selecting multiple values

There are actually a few different ways to select multiple values using
criteria queries. We will explore 2 options here, but an alternative
recommended approach is to use tuples as described in
<<querycriteria-tuple>>. Or consider a wrapper query;
see <<querycriteria-typedquery-construct>> for details.

[[ex-criteria-typedquery-array]]
.Selecting an array
====
[source,java]
----
include::{sourcedir}/select_multiple_values_array.java[]
----
====

Technically this is classified as a typed query, but you can see from
handling the results that this is sort of misleading. Anyway, the
expected result type here is an array.

The example then uses the array method of
javax.persistence.criteria.CriteriaBuilder which explicitly combines
individual selections into a
javax.persistence.criteria.CompoundSelection.

[[ex-criteria-typedquery-array2]]
.Selecting an array (2)
====
[source,java]
----
include::{sourcedir}/select_multiple_values_array2.java[]
----
====

Just as we saw in <<ex-criteria-typedquery-array>> we
have a typed criteria query returning an Object array. Both queries are
functionally equivalent. This second example uses the multiselect method
which behaves slightly differently based on the type given when the
criteria query was first built, but in this case it says to select and
return an __Object[]__.

[[querycriteria-typedquery-construct]]
=== Selecting a wrapper

Another alternative to
<<querycriteria-typedquery-multiselect>> is to instead
select an object that will ``wrap'' the multiple values. Going back to
the example query there, rather than returning an array of _[Person#id,
Person#age]_ instead declare a class that holds these values and instead
return that.

.Selecting an wrapper
====
[source,java]
----
include::{sourcedir}/select_wrapper.java[]
----
====

First we see the simple definition of the wrapper object we will be
using to wrap our result values. Specifically notice the constructor and
its argument types. Since we will be returning `PersonWrapper` objects,
we use `PersonWrapper` as the type of our criteria query.

This example illustrates the use of the
javax.persistence.criteria.CriteriaBuilder method construct which is
used to build a wrapper expression. For every row in the result we are
saying we would like a _PersonWrapper_ instantiated with the remaining
arguments by the matching constructor. This wrapper expression is then
passed as the select.

[[querycriteria-tuple]]
=== Tuple criteria queries

A better approach to
<<querycriteria-typedquery-multiselect>> is to use
either a wrapper (which we just saw in
<<querycriteria-typedquery-construct>>) or using the
javax.persistence.Tuple contract.

.Selecting a tuple
====
[source,java]
----
include::{sourcedir}/select_tuple.java[]
----
====

This example illustrates accessing the query results through the
javax.persistence.Tuple interface. The example uses the explicit
createTupleQuery of javax.persistence.criteria.CriteriaBuilder. An
alternate approach is to use createQuery passing `Tuple.class`.

Again we see the use of the multiselect method, just like in
<<ex-criteria-typedquery-array2>>. The difference here
is that the type of the javax.persistence.criteria.CriteriaQuery was
defined as javax.persistence.Tuple so the compound selections in this
case are interpreted to be the tuple elements.

The javax.persistence.Tuple contract provides 3 forms of access to the
underlying elements:

typed::
  The <<ex-criteria-typedquery-tuple>> example
  illustrates this form of access in the `tuple.get( idPath )` and
  `tuple.get( agePath )` calls. This allows typed access to the
  underlying tuple values based on the `javax.persistence.TupleElement`
  expressions used to build the criteria.
positional::
  Allows access to the underlying tuple values based on the position.
  The simple _Object get(int position)_ form is very similar to the
  access illustrated in
  <<ex-criteria-typedquery-array>> and
  <<ex-criteria-typedquery-array2>>. The _<X> X get(int
  position, Class<X> type_ form allows typed positional access, but
  based on the explicitly supplied type which the tuple value must be
  type-assignable to.
aliased::
  Allows access to the underlying tuple values based an (optionally)
  assigned alias. The example query did not apply an alias. An alias
  would be applied via the alias method on
  `javax.persistence.criteria.Selection`. Just like `positional` access,
  there is both a typed (__Object get(String alias)__) and an untyped
  (__<X> X get(String alias, Class<X> type__ form.

[[querycriteria-from]]
=== FROM clause

====
A CriteriaQuery object defines a query over one or more entity,
embeddable, or basic abstract schema types. The root objects of the
query are entities, from which the other types are reached by
navigation.

— JPA Specification, section 6.5.2 Query Roots, pg 262
====

[NOTE]
====
All the individual parts of the FROM clause (roots, joins, paths)
implement the javax.persistence.criteria.From interface.
====

[[querycriteria-from-root]]
=== Roots

Roots define the basis from which all joins, paths and attributes are
available in the query. A root is always an entity type. Roots are
defined and added to the criteria by the overloaded from methods on
javax.persistence.criteria.CriteriaQuery:

====
[source,java]
----
include::{sourcedir}/from_root_methods.java[]
----
====

.Adding a root
====
[source,java]
----
include::{sourcedir}/from_root_example.java[]
----
====

Criteria queries may define multiple roots, the effect of which is to
create a cartesian product between the newly added root and the others.
Here is an example matching all single men and all single women:

[[querycriteria-from-join]]
=== Joins

Joins allow navigation from other javax.persistence.criteria.From to
either association or embedded attributes. Joins are created by the
numerous overloaded join methods of the javax.persistence.criteria.From
interface

.Example with Embedded and ManyToOne
====
[source,java]
----
include::{sourcedir}/from_join_example_embedded_and_many2one.java[]
----
====

[[querycriteria-from-fetch]]
=== Fetches

Just like in HQL and JPQL, criteria queries can specify that associated
data be fetched along with the owner. Fetches are created by the
numerous overloaded fetch methods of the javax.persistence.criteria.From
interface.

.Example with Embedded and ManyToOne
====
[source,java]
----
include::{sourcedir}/from_fetch_example_embedded_and_many2one.java[]
----
====

[NOTE]
====
Technically speaking, embedded attributes are always fetched with their
owner. However in order to define the fetching of _Address#country_ we
needed a javax.persistence.criteria.Fetch for its parent path.
====

.Example with Collections
====
[source,java]
----
include::{sourcedir}/from_fetch_example_plural.java[]
----
====

[[querycriteria-path]]
=== Path expressions

[NOTE]
====
Roots, joins and fetches are themselves paths as well.
====

[[querycriteria-param]]
=== Using parameters

.Using parameters
====
[source,java]
----
include::{sourcedir}/parameter_example.java[]
----
====

Use the parameter method of javax.persistence.criteria.CriteriaBuilder
to obtain a parameter reference. Then use the parameter reference to
bind the parameter value to the javax.persistence.Query