[[introduction]]
== Introduction

Hibernate is an _Object/Relational Mapping_ (ORM) solution for programs written in Java and other JVM languages.
It lets us map Java classes to database tables, and fields of the Java classes to columns of the tables, and then
takes over the most tedious work involved in executing SQL statements against the database. Hibernate typically
eliminates upward of 90% of the work involved in common persistence-related programming tasks.

However, unlike some other persistence solutions, Hibernate doesn't attempt to hide the relational model, nor take
away the power of SQL as a query language. On the contrary, Hibernate centers the relational data, makes it visible
to Java in a natural and typesafe object-oriented form, and offers an extremely powerful SQL-like query language for
working with the data in Java.

[NOTE]
Hibernate may not be the best solution for data-centric applications where business logic is implemented in stored
procedures. Hibernate is most useful for programs with an object-oriented domain model and business logic in a
Java-based _middle tier_.

[[resources]]
.Resources
****
A strong background in SQL is not required to use Hibernate, at least not at first, but a basic understanding of the
concepts is important.
An understanding of _data modeling_ principles is especially important.
Good starting points include:

- https://www.agiledata.org/essays/dataModeling101.html[Data Modeling 101], and
- https://en.wikipedia.org/wiki/Data_modeling[Wikipedia].

If you're completely new to database access in Java, a decent overview of various technologies and options and how they
fit together may be found at:

- https://www.marcobehler.com/guides/a-guide-to-accessing-databases-in-java[Java & Databases: An Overview of Libraries & APIs].

This guide will help you get up and running with Hibernate itself.
But the best way to start learning Hibernate properly is the _Introduction to Hibernate 6_, available at
https://hibernate.org/orm/documentation[the same place you got this document].

[TIP]
====
Of course, the other essential resource will be the documentation for your RDBMS, and especially the guide to the dialect
of SQL provided by your database.
====
****

[[obtaining]]
=== Obtaining Hibernate

We may obtain any Hibernate module we need just by declaring a dependency on the module in our Maven or Gradle build.
We're certainly going to need `hibernate-core`, so we'll go ahead and declare a dependency on `org.hibernate.orm:hibernate-core`.

In Gradle we would have:

[source,groovy]
----
implementation 'org.hibernate.orm:hibernate-core:6.3.0.Final'
----

Or in Maven:

[source,xml]
----
<dependency>
    <groupId>org.hibernate.org</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>6.3.0.Final</version>
</dependency>
----

[[modules]]
=== Modules belonging to Hibernate ORM

Hibernate ORM is an umbrella project containing the following modules:

[cols="40m,~"]
.API-oriented modules
|===
|hibernate-core| The core object/relational mapping engine
|hibernate-envers| Entity versioning and auditing
|hibernate-spatial| Support for spatial/GIS data types
|hibernate-jpamodelgen| An annotation processor that generates a JPA-compliant metamodel
|===

[cols="40m,~"]
.Integration-oriented modules
|===
|hibernate-agroal| Support for https://agroal.github.io/[Agroal] connection pooling
|hibernate-c3p0| Support for https://www.mchange.com/projects/c3p0/[C3P0] connection pooling
|hibernate-hikaricp| Support for https://github.com/brettwooldridge/HikariCP/[HikariCP] connection pooling
|hibernate-vibur| Support for https://www.vibur.org/[Vibur DBCP] connection pooling
|hibernate-proxool| Support for https://proxool.sourceforge.net/[Proxool] connection pooling
|hibernate-jcache| Integration with https://jcp.org/en/jsr/detail?id=107$$[JCache], allowing any compliant implementation as a second-level cache provider
|hibernate-community-dialects| Additional community-supported SQL dialects
|hibernate-graalvm| Experimental extension to make it easier to compile applications as a https://www.graalvm.org/[GraalVM] native image
|hibernate-micrometer| Integration with https://micrometer.io[Micrometer] metrics
|===

[cols="40m,~"]
.Testing-oriented modules
|===
|hibernate-testing| A framework for testing Hibernate ORM functionality
|hibernate-integrationtest-java-modules| Integration tests for running Hibernate ORM in the Java module path
|===

These artifacts are published under the Maven group id `org.hibernate.orm`.

[NOTE]
There's more to Hibernate than the modules belonging to the ORM project: Hibernate Search, Hibernate Reactive, Hibernate Validator, and more.

