[[preface]]

[preface]
== Preface

Hibernate is an _Object/Relational Mapping_ (ORM) solution for programs written in Java and other JVM languages.
It lets us map Java classes to database tables, and fields of the Java classes to columns of the tables, and then
takes over the most tedious work involved in executing SQL statements against the database. Hibernate typically
eliminates upward of 90% of the work involved in common persistence-related programming tasks.

However, unlike some other persistence solutions, Hibernate doesn't attempt to hide the relational model, nor take
away the power of SQL as a query language. On the contrary, Hibernate centers the relational data, makes it visible
to Java in a natural and typesafe object-oriented form, and offers an extremely powerful SQL-like query language for
working with the data in Java.

[NOTE]
Hibernate may not be the best solution for data-centric applications where business logic is implemented in stored
procedures. Hibernate is most useful for programs with an object-oriented domain model and business logic in a
Java-based _middle tier_.

A strong background in SQL is not required to use Hibernate, at least not at first, but a basic understanding of the
concepts is important.
An understanding of _data modeling_ principles is especially important.
Good starting points include:

- https://www.agiledata.org/essays/dataModeling101.html[Data Modeling 101], and
- https://en.wikipedia.org/wiki/Data_modeling[Wikipedia].

If you're completely new to database access in Java, a decent overview of various technologies and options and how they
fit together may be found at:

- https://www.marcobehler.com/guides/a-guide-to-accessing-databases-in-java[Java & Databases: An Overview of Libraries & APIs].

This guide will help you get up and running with Hibernate itself.
But the best way to start learning Hibernate properly is the _Introduction to Hibernate 6_, available at
https://hibernate.org/orm/documentation[the same place you got this document].
