[[tutorial_envers]]
== Tutorial Using Envers

.Objectives
- [*] Annotate an entity as historical
- [*] Configure Envers
- [*] Use the Envers APIs to view and analyze historical data

****
This tutorial is located within the download bundle under `envers/`.
****

[[hibernate-gsg-tutorial-envers-config]]
=== persistence.xml

This file is unchanged from <<hibernate-gsg-tutorial-jpa-config,what we had before>>.

[[hibernate-gsg-tutorial-envers-entity]]
=== The annotated entity Java class

The entity class is also almost identical to what we had <<hibernate-gsg-tutorial-annotations-entity,previously>>.
The major difference is the addition of the annotation `@org.hibernate.envers.Audited`, which tells Envers to automatically track changes to this entity.

[[hibernate-gsg-tutorial-envers-test]]
=== Example code

The code saves some entities, makes a change to one of the entities and then uses the Envers API to pull back the
initial revision as well as the updated revision.  A revision refers to a historical snapshot of an entity.


[[hibernate-gsg-tutorial-envers-test-api]]
.Using the `org.hibernate.envers.AuditReader`
[source, java]
----
public void testBasicUsage() {
    ...
    AuditReader reader = AuditReaderFactory.get( entityManager );   <1>
    Event firstRevision = reader.find( Event.class, 2L, 1 );        <2>
    ...
    Event secondRevision = reader.find( Event.class, 2L, 2 );       <3>
    ...
}
----
<1> An `org.hibernate.envers.AuditReader` is obtained from the `org.hibernate.envers.AuditReaderFactory` which wraps the JPA `EntityManager`.
<2> The `find` method retrieves specific revisions of the entity. The first call retrieves revision number 1 of the `Event` with id 2.
<3> Later, the second call asks for revision number 2 of the `Event` with id 2.


[[hibernate-gsg-tutorial-envers-further]]
=== Take it further!

.Practice Exercises
- [*] Provide a custom revision entity to additionally capture who made the changes.
- [*] Write a query to retrieve only historical data which meets some criteria. Use the _User Guide_ to see how
Envers queries are constructed.
- [*] Experiment with auditing entities which have various forms of relationships (many-to-one, many-to-many, etc).  Try
retrieving historical versions (revisions) of such entities and navigating the object tree.

// force the break