= AccessType
:toc:

The JPA `javax.persistence.AccessType` enum actually represents 3 related concepts:

. Determining which fields/methods constitute a persistent attribute.
. Indicating where to look for mapping annotations for each persistent attribute.
. How the attribute (its value) is accessed at runtime

Unfortunately the JPA specification is not overly clear about how the AccessType value defines the
answers to these 3 questions in all cases.  Often that is left up to each provider to decide.  So here we will
discuss how Hibernate answers the 3 AccessType-related questions in different situations.  By default, Hibernate
tries to keep the explanation for how it answers these questions simple.  AccessType defines 2 possible values: FIELD
and PROPERTY.

For Hibernate, PROPERTY access means that:

. A persistent attribute is identified by its JavaBeans-style getter and setter on a Class
. The mapping annotations for the persistent attribute are located on the Class getter method
. At runtime we access the persistent attribute's value via the getter/setter methods.

IMPORTANT: Placing annotations on setters is NEVER appropriate.


FIELD access means that:

. A persistent attribute is identified by its Class field
. The mapping annotations for the persistent attribute are located on the Class field
. At runtime we access the persistent attribute's value directly via the field.


== Implicit (hierarchy) access type

The implicit access type for an entity hierarchy defines how access type is defined when there is no explicitly
defined AccessType.  To determine implicit hierarchy access type, Hibernate looks for the annotation marking the
identifier for the entity hierarchy (either @Id or @EmbeddedId).  The placement (field or getter) defines the implicit
access type for the hierarchy.  Let's look at an example:


[[hierarchy-level-field]]
.Hierarchy-level FIELD access
====
[source, JAVA]
----
@Entity
public class Document {
    @Id
    private Integer id;
    private String title;
    @Lob
    private Clob content;

    @Transient
    private int hashCode;
}

@Entity
public class PublishedDocument extends Document {
    private String isbn;
    @Temporal(DATE)
    private Date publishDate;
}
----
====

Here we have implicit hierarchy-level field access because of the placement of @Id on a field, which means:

. We look at the declared fields for each class to determine its persistent attributes.  For the `Document` class,
	that means we have 3 fields that would be considered persistent attributes: `id`, `title`, and `content`; for
	`PublishedDocument` we have 2: `isbn` and `publishDate`.  Given field "access type", to indicate that a particular
	field is not persistent, the field would be annotated with the `javax.persistence.Transient` annotation; here we
	see an example of that for the `hashCode` field.
. We use the annotations attached to those fields as the mapping annotations for the persistent attribute it indicates.
	Annotations on the getter associated with that field (if one/any) are ignored (although we do try to log warnings
	in such cases).
. In terms of runtime access, Hibernate will use direct field access (via reflection) to get and set attribute values
	using `java.lang.reflection.Field`.


Implicit property access works similarly:

[[hierarchy-level-property]]
.Hierarchy-level PROPERTY access
====
[source, JAVA]
----
@Entity
public class Document {
    private Integer id;
    private String title;
    private Clob content;

    @Id
    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    @Lob
    public Clob getContent() { return content; }
    public void setContent(Clob content) { this.content = content; }
}

@Entity
public class PublishedDocument extends Document {
    private String isbn;
    private Date publishDate;

    public String getIsbn() { return isbn; }
    public void setIsbn(String isbn) { this.isbn = isbn; }

    @Temporal(DATE)
    public Date getPublishDate() { return publishDate; }
    public void setPublishDate(Date publishDate) { this.publishDate = publishDate; }
}
----
====

In this case, we have implicit hierarchy-level property access because of the placement of @Id on the getter,
which here means:

. We look at the declared methods for each class looking for JavaBean-style getters to determine the persistent
	attributes for that class.  For the `Document` class, we have 3 getters that would indicate persistent attributes:
	`getId()`, `getTitle()` and `getContent()`; for `PublishedDocument` we have 2: `getIsbn()` and `getPublishDate()`.
	The "attribute name" is taken following JavaBean-conventions.  To indicate that a getter does is not indicate a
	persistent attribute, the getter would be annotated with the `javax.persistence.Transient` annotation.
. We use the annotations attached to those getter methods as the mapping annotations for the persistent attribute
	it indicates.  Annotations on the field associated with that getter (if one/any) are ignored (although, again, we do
	try to log warnings in such cases).
. In terms of runtime access, Hibernate will use getter/setter access (via reflection) to get and set attribute values
	using `java.lang.reflection.Method`.


== Explicit access type

Access type may also be explicitly indicate via the `javax.persistence.Access` annotation, which can be applied to
either a class or attribute.


=== Class-level

Annotating a class (`MappedSuperclass`, `Entity`, or `Embeddable`) applies the indicated access type to the class,
although not its superclass nor subclasses.  Let's go back to the <<hierarchy-level-field,first example>> where we saw
implicit hierarchy-level field access.  But lets instead use `javax.persistence.Access` and see what affect that has:


[[class-level-property]]
.Class-level PROPERTY access
====
[source, JAVA]
----
@Entity
public class Document {
    @Id
    private Integer id;
    private String title;
    @Lob
    private Clob content;
}

@Entity
@Access(PROPERTY)
public class PublishedDocument extends Document {
    private String isbn;
    private Date publishDate;

    public String getIsbn() { return isbn; }
    public void setIsbn(String isbn) { this.isbn = isbn; }

    @Temporal(DATE)
    public Date getPublishDate() { return publishDate; }
    public void setPublishDate(Date publishDate) { this.publishDate = publishDate; }
}
----
====

The hierarchy still has an implicit field access type.  The `Document` class implicitly uses field access as the
hierarchy default.  The `PublishedDocument` class however overrides that to say that it uses property access.  This
class-level `javax.persistence.Access` override is only in effect for that class; if another entity extended from
`PublishedClass` and did not specify a `javax.persistence.Access`, that entity subclass would use field access
as the hierarchy default.  But in terms of the `PublishedDocument` class, it has the same effect we saw in the
<<hierarchy-level-property,second example>>:

. We look at the declared methods for `PublishedDocument` to determine the persistent attributes, here:
	`getIsbn()` and `getPublishDate()`.
. We use the annotations attached to those getter methods as the mapping annotations.
. We will use getter/setter runtime access.


Similarly, the explicit class-level access type can be set to FIELD:

[[class-level-field]]
.Class-level FIELD access
====
[source, JAVA]
----
@Entity
public class Document {
    private Integer id;
    private String title;
    private Clob content;

    @Id
    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    @Lob
    public Clob getContent() { return content; }
    public void setContent(Clob content) { this.content = content; }
}

@Entity
@Access(PROPERTY)
public class PublishedDocument extends Document {
    private String isbn;
    @Temporal(DATE)
    private Date publishDate;
}
----
====


=== Attribute-level


JPA also says that access type can be explicitly specified on an individual attribute...






== Extensions

As discussed above, whether defined implicitly or explicitly, the notion of access type controls:

. identifying persistent attributes
. locating each persistent attribute's mapping information
. runtime access to each persistent attribute.

Regardless of implicit/explicit the following are always true:

* FIELD access always indicates runtime access via direct field access
* PROPERTY access always indicates runtime access via getter/setter

In terms of default behavior:

* Given FIELD access, all mapping annotations are expected to be placed on the corresponding class field
* Given PROPERTY access, all mapping annotations are expected to be placed on the corresponding class getter method


That being said, Hibernate offers a number of extensions that affect these statements...


=== PropertyAccessor

Thus far we have focused on FIELD and PROPERTY runtime access because those are the strategies defined by JPA.
Hibernate, however, has a more open-ended strategy for runtime access defined by the
`org.hibernate.property.PropertyAccessor`.

NOTE: Hibernate's use of the phrase "property" here pre-dates JPA.  Think of "property accessor" as "attribute accessor".

`org.hibernate.property.PropertyAccessor` essentially defines contract for extracting (`org.hibernate.property.Getter`)
and injecting (`org.hibernate.property.Setter`) attribute values at runtime.  To specify a custom runtime access
strategy, simply use the `org.hibernate.annotations.AttributeAccessor` annotation:

[[custom-accessor]]
.Custom PropertyAccessor
====
[source, JAVA]
----
@Entity
public class Document {
    ...

    @Id
    @AttributeAccessor( "com.acme.CustomHibernateIdPropertyAccessor" )
    public Integer getId() { return id; }
    ...
}
----
====

`org.hibernate.annotations.AttributeAccessor` can also be specified at the class-level to apply to all attributes
for the annotated class.


=== PersistentAttributeMemberResolver

The `org.hibernate.metamodel.spi.PersistentAttributeMemberResolver` contract allows swapping the manner in
which Hibernate decides which fields/methods constitute a persistent attribute.  The information described above is
in accordance with the standard, default resolver :
`org.hibernate.metamodel.spi.StandardPersistentAttributeMemberResolver`.  This standard implementation follows the
JPA very closely in not allowing certain things, although it always warns or throws an exception when ignoring or
not allowing things.

Hibernate ships with another resolver implementation : `org.hibernate.metamodel.spi.LenientPersistentAttributeMemberResolver`
As its name implies, it aims at being more lenient that what is mandated by JPA specification.

TODO : discuss specific leniencies

To specify alternate PersistentAttributeMemberResolver to use (whether a Hibernate-provided one or a custom one), use
the `org.hibernate.metamodel.MetadataBuilder.with(PersistentAttributeMemberResolver)` method.