services:
  spanner:
    image: ${SPANNER_EMULATOR:-gcr.io/cloud-spanner-emulator/emulator:1.5.53@sha256:2c3a9be05e1f36476ec2d07dae0544e1c91c46bc170c22807436f11c496f5f06}
    container_name: ${SPANNER_CONTAINER_NAME:-spanner}
    ports:
      - "${SPANNER_GRPC_PORT:-9011}:9010"
      - "${SPANNER_REST_PORT:-9021}:9020"
  spanner-healthcheck:
    # Sidecar: spanner emulator image has no tools, so we use UBI to run the healthcheck:
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:12db9874bd753eb98b1ab3d840e75de5d6842ac0604fbd68c012adefe97140be
    container_name: ${SPANNER_CONTAINER_NAME:-spanner}_healthcheck
    depends_on:
      spanner:
        condition: service_started
    entrypoint: [ "tail", "-f", "/dev/null" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://spanner:9020/v1/projects/test-project/instanceConfigs || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
