services:
  spanner:
    image: ${SPANNER_EMULATOR:-gcr.io/cloud-spanner-emulator/emulator:1.5.55@sha256:ad54472fe7b161b9214f7f816f304b649a4779e348229c375ac067f5ed5a6422}
    container_name: ${SPANNER_CONTAINER_NAME:-spanner}
    ports:
      - "${SPANNER_GRPC_PORT:-9011}:9010"
      - "${SPANNER_REST_PORT:-9021}:9020"
  spanner-healthcheck:
    # Sidecar: spanner emulator image has no tools, so we use UBI to run the healthcheck:
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:062c52ff973065752b0965787649db2bcf551a6c727a00e95a3eb42cebadbdab
    container_name: ${SPANNER_CONTAINER_NAME:-spanner}_healthcheck
    depends_on:
      spanner:
        condition: service_started
    entrypoint: [ "tail", "-f", "/dev/null" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://spanner:9020/v1/projects/test-project/instanceConfigs || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
