services:
  cockroach:
    image: ${COCKROACHDB_IMAGE:-cockroachdb/cockroach:v26.1.4@sha256:66082934e823505f0f171eafd397b35396f3a7dba588225a01b2434eb4b53e77}
    container_name: cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command:
      - start-single-node
      - --insecure
      - --store=type=mem,size=0.25
      - --advertise-addr=localhost
      - |
        --log=sinks:
          stderr:
            channels: all
            filter: ERROR
            redact: false
            exit-on-error: true
    deploy:
      resources:
        limits:
          memory: 6g
    healthcheck:
      test: ["CMD-SHELL", "./cockroach sql --insecure -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
