[[bootstrap]]
== Bootstrap

:asciidoc-dir: ../../..
include::{asciidoc-dir}/shared/common-attributes.adoc[]

:core-project-dir: {root-project-dir}/hibernate-core
:core-test-base: {core-project-dir}/src/test/java/org/hibernate/orm/test
:example-dir-boot: {core-test-base}/bootstrap
:example-dir-boot-spi: {core-test-base}/bootstrap/spi
:example-dir-boot-jpa: {core-test-base}/jpa/boot
:extrasdir: extras

The term bootstrapping refers to initializing and starting a software component.
In Hibernate, we are specifically talking about the process of building a fully functional `SessionFactory` instance
(or `EntityManagerFactory` instance, for Jakarta Persistence).

[TIP]
====
In this chapter, we will discuss on a number of specific configuration settings.  Be sure to check out the
<<appendices/SettingsReference.adoc#settings>> section as well for documentation of each available setting.
====

Hibernate supports both <<#bootstrap-native,native>> and <<#bootstrap-standardized,standardized>> approaches for
bootstrapping the `SessionFactory` / `EntityManagerFactory`.


[[bootstrap-standardized]]
=== Standardized Bootstrapping

Jakarta Persistence defines two standardized bootstrap approaches depending on the environment into which the application is deployed
and on how the application intends to access the `EntityManager` instances from an `EntityManagerFactory`.

It uses the terms _EE_ and _SE_ for these two approaches, but those terms are very misleading in this context.
What Jakarta Persistence calls _EE_ bootstrapping implies the existence of a container (EE, OSGi, etc.) that will manage and inject the persistence context on behalf of the application.
What it calls _SE_ bootstrapping is everything else.
We will use the terms <<#bootstrap-standardized-container,container>> and <<#bootstrap-standardized-app,application>> bootstrapping in this guide.

[NOTE]
====
If you would like additional details on accessing and using `EntityManager` instances, sections 7.6 and 7.7 of the Jakarta Persistence specification cover container-managed and application-managed `EntityManagers`, respectively.
====


[[bootstrap-standardized-container]]
==== Container Bootstrapping

For compliant container-bootstrapping, the container will build an `EntityManagerFactory` for each persistent-unit defined in the `META-INF/persistence.xml` configuration file
and make that available to the application for injection via the `jakarta.persistence.PersistenceUnit` annotation or via JNDI lookup.

In these container environments, an `EntityManager` may be dependency injected via `@PersistenceContext`.  In most
cases, the lifecycle of such an injected `EntityManager` is managed by the container.

Consider the following `META-INF/persistence.xml` file:

[[example-bootstrap-standardized-persistence-xml]]
.META-INF/persistence.xml file
====
[source, XML, indent=0]
----
include::{extrasdir}/persistence.xml[]
----
====

We can inject the `EntityManagerFactory` -

[[bootstrap-jpa-compliant-PersistenceUnit-configurable-example]]
.Injecting a specific `EntityManagerFactory`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=bootstrap-jpa-compliant-PersistenceUnit-configurable-example]
----
====

Because there is only one `<persistence-unit/>` defined, we can also omit the name and inject the "default" `EntityManagerFactory` -

[[bootstrap-jpa-compliant-PersistenceUnit-example]]
.Injecting the default `EntityManagerFactory`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=bootstrap-jpa-compliant-PersistenceUnit-example]
----
====

See the documentation of your container for additional details.



[[bootstrap-standardized-app]]
==== Application Bootstrapping

Jakarta Persistence also allows for the application itself to manage bootstrapping the `EntityManagerFactory` reference it needs.
This is achieved through `jakarta.persistence.Persistence` or `jakarta.persistence.PersistenceConfiguration`.

The traditional way an application builds an `EntityManagerFactory` itself is to use `jakarta.persistence.Persistence`
and either -

* a `peristence.xml` file
* manually passing a `Map` of settings

[[example-bootstrap-jpa-compliant-EntityManagerFactory]]
.Application bootstrapped `EntityManagerFactory`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=bootstrap-jpa-compliant-EntityManagerFactory-example]
----
====


Jakarta Persistence 3.2 also introduced a new way for applications to build the `EntityManagerFactory` itself using
`jakarta.persistence.PersistenceConfiguration` which offers a more type-safe approach.


[[example-bootstrap-standard-PersistenceConfiguration]]
.Using PersistenceConfiguration
====
[source, java, indent=0]
----
include::{example-dir-boot-jpa}/PersistenceConfigurationTests.java[tags=example-bootstrap-standard-PersistenceConfiguration]
----
====

Hibernate offers an extension to `jakarta.persistence.PersistenceConfiguration` named `org.hibernate.jpa.HibernatePersistenceConfiguration`
which exposes additional conveniences.

[[example-bootstrap-standard-HibernatePersistenceConfiguration]]
.Using HibernatePersistenceConfiguration
====
[source, java, indent=0]
----
include::{example-dir-boot-jpa}/PersistenceConfigurationTests.java[tags=example-bootstrap-standard-HibernatePersistenceConfiguration]
----
====

[[bootstrap-standardized-integrations]]
==== Standardized Bootstrapping and Integrations

When performing standardized Jakarta Persistence bootstrapping, Hibernate still uses its <<#bootstrap-native,native>> under the covers.
Therefore, all extension/integration points discussed in that section are also available.
It is especially useful in such cases that the integrations are discoverable as Java services.


[[bootstrap-native]]
=== Native Bootstrapping

Hibernate exposes its own approaches for bootstrapping a `SessionFactory` -

* a <<bootstrap-native-simple,simplified>> approach using `Configuration`
* more controlled <<bootstrap-native-builders,builder-style>> approach


[[bootstrap-native-simple]]
==== Native Bootstrapping: Simple

`org.hibernate.cfg.Configuration` provides a simple API for bootstrapping a Hibernate `SessionFactory`.
It is a collection of settings and mappings, thrown together, and used to build the `SessionFactory`.

[NOTE]
====
Even simplified bootstrapping uses the <<bootstrap-native-builders,builder-style>> approach under the covers, so the
integration points discussed there are still available.
====

You can obtain the `Configuration` by instantiating it directly.
You then specify mapping metadata (XML mapping documents, annotated classes) that describe your applications object model and its mapping to a SQL database.

[source,java]
----
Configuration cfg = new Configuration()
    // addResource does a classpath resource lookup
    .addResource( "Item.hbm.xml" )
    .addResource( "Bid.hbm.xml" )

    // calls addResource using "/org/hibernate/auction/User.hbm.xml"
    .addClass( org.hibernate.auction.User.class )

    // parses Address class for mapping annotations
    .addAnnotatedClass( Address.class )

    // reads package-level (package-info.class) annotations in the named package
    .addPackage( "org.hibernate.auction" )

    .setProperty( "hibernate.dialect", "org.hibernate.dialect.H2Dialect" )
    .setProperty( "hibernate.connection.datasource", "java:comp/env/jdbc/test" )
    .setProperty( "hibernate.order_updates", "true" );
----

There are other ways to specify Configuration information, including:

* Place a file named hibernate.properties in a root directory of the classpath
* Pass an instance of java.util.Properties to `Configuration#setProperties`
* Via a `hibernate.cfg.xml` file
* System properties using Java `-Dproperty=value`





[[bootstrap-native-builders]]
==== Native Bootstrapping: Builder-style

Bootstrapping a `SessionFactory` may also be achieved using a number of builders.  This approach is broken down into 3 course phases.

First, a `ServiceRegistry` is built, which represents the various services that will be available.
An example of such a service is `ConnectionProvider` which Hibernate uses to obtain JDBC Connections.
See <<bootstrap-native-builders-registry>>.

Next, a `Metadata` is built, which represents the application's mapping information (entities, embeddables, generators, etc).
See <<bootstrap-native-builders-metadata>>.

And finally, the `SessionFactory` is built.
See <<bootstrap-native-builders-sessionfactory>>.


While "more complex", these builders represents the actual process Hibernate goes through to build a `SessionFactory`.
And more importantly, illustrate the various integration points in this bootstrap process.

[NOTE]
====
Notice that a `ServiceRegistry` can be passed at a number of points in this bootstrapping process.
The suggested approach is to build a `StandardServiceRegistry` yourself and pass that along to the `MetadataSources` constructor.
From there, `MetadataBuilder`, `Metadata`, `SessionFactoryBuilder`, and `SessionFactory` will all pick up that same `StandardServiceRegistry`.
====



[[bootstrap-native-builders-registry]]
===== Building the ServiceRegistry

As mentioned earlier, Hibernate needs a `ServiceRegistry` holding the services Hibernate will need during bootstrap and at run time.

Actually, there are 2 types of registries which are important here.

First is the `org.hibernate.boot.registry.BootstrapServiceRegistry` which contains 3 important services:

`org.hibernate.boot.registry.classloading.spi.ClassLoaderService`:: which controls how Hibernate interacts with ``ClassLoader``s.
`org.hibernate.integrator.spi.IntegratorService`:: which controls the management and discovery of `org.hibernate.integrator.spi.Integrator` instances.
`org.hibernate.boot.registry.selector.spi.StrategySelector`:: which controls how Hibernate resolves implementations of various strategy contracts.
This is a very powerful service, but a full discussion of it is beyond the scope of this guide.

[NOTE]
====
If you are ok with the default behavior of Hibernate in regard to these `BootstrapServiceRegistry` services
(which is quite often the case, especially in stand-alone environments), then explicitly building the `BootstrapServiceRegistry` is
not needed.
====

If you wish to alter how the `BootstrapServiceRegistry` is built, that is controlled through the `org.hibernate.boot.registry.BootstrapServiceRegistryBuilder`:

[[example-bootstrap-native-BootstrapServiceRegistry]]
.Controlling `BootstrapServiceRegistry` building
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-BootstrapServiceRegistry]
----
====

The second registry is the `org.hibernate.boot.registry.StandardServiceRegistry`.
You will almost always need to configure this registry, which is done through `org.hibernate.boot.registry.StandardServiceRegistryBuilder`:

[[example-bootstrap-native-StandardServiceRegistryBuilder]]
.Building a `BootstrapServiceRegistryBuilder`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-StandardServiceRegistryBuilder]
----
====

See the `StandardServiceRegistryBuilder` link:{doc-javadoc-url}/org/hibernate/boot/registry/StandardServiceRegistryBuilder.html[Javadocs] for more details.


The main integration point in this process is `org.hibernate.service.spi.ServiceContributor`, usually provided
as a Java service, which allows contributing custom Hibernate services.



[[bootstrap-native-builders-metadata]]
===== Building the Metadata

To build the `Metadata` reference, we first construct a `MetadataSources` which allows specifying the different sources for mapping information.
This mapping information might be in the form of XML, annotations or both.

[[example-bootstrap-native-MetadataSources]]
.Building a `MetadataSources`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-MetadataSources]
----
====

Also, all methods on `MetadataSources` offer fluent-style call chaining -

[[bootstrap-native-metadata-source-example]]
.Configuring a `MetadataSources` with method chaining
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-MetadataSources-chained]
----
====

`MetadataSources` has many other methods as well. Explore its API and link:{doc-javadoc-url}/org/hibernate/boot/MetadataSources.html[Javadocs] for more information.

Once we have the sources of mapping information defined, we need to build the `Metadata` object.

If you have specified everything as settings, or you are ok with the default behavior, you can simply call link:{doc-javadoc-url}/org/hibernate/boot/MetadataSources.html#buildMetadata--[`MetadataSources#buildMetadata`].

[[example-bootstrap-native-Metadata-no-builder]]
.Using `MetadataSources#buildMetadata`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-Metadata-no-builder]
----
====


Optionally, we can obtain a `MetadataBuilder` from `MetadataSources` which can be used to configure the interpretation of the mapping information.

[[example-bootstrap-native-MetadataBuilder]]
.Using `MetadataBuilder`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-Metadata-using-builder]
----
====


There are a few integration points, usually provided as Java services, that hook into this part of bootstrapping -

* `org.hibernate.boot.model.TypeContributor` which allows contributing custom types such as Java type descriptors, JDBC type descriptors, etc.
* `org.hibernate.boot.spi.MetadataSourcesContributor` which allows access to `MetadataSources` to contribute additional sources.
* `org.hibernate.boot.spi.AdditionalMappingContributor` which, like `MetadataSourcesContributor`, allows contributing additional sources.
* `org.hibernate.boot.spi.MetadataBuilderInitializer` which allows for configuration of `MetadataBuilder`




[[bootstrap-native-builders-sessionfactory]]
===== Building the SessionFactory

Once we have `Metadata`, we can build the `SessionFactory`.

If all configuration has been done by settings, or if you are ok with the default behavior, you can simply call
link:{doc-javadoc-url}/org/hibernate/boot/Metadata.html#buildSessionFactory--[`Metadata#buildSessionFactory`].

[[example-bootstrap-native-SessionFactory-no-builder]]
.Using `SessionFactoryBuilder`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-SessionFactory-no-builder]
----
====

Or a `SessionFactoryBuilder`, obtained from `Metadata`, may be used to configure the `SessionFactory` creation.

[[example-bootstrap-native-SessionFactoryBuilder]]
.Using `SessionFactoryBuilder`
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=example-bootstrap-native-SessionFactory-using-builder]
----
====

The main integration point here is `org.hibernate.integrator.spi.Integrator`, usually provided
as a Java service, which allows contributing custom Hibernate services.

A common use case for `Integrator`, for example, is to hook in custom event listeners -

[[example-bootstrap-event-listener-registration]]
.Configuring an event listener
====
[source, java, indent=0]
----
include::{example-dir-boot}/BootstrapTest.java[tags=bootstrap-event-listener-registration-example]
----
====
