[[pc]]
== Persistence Contexts
:sourcedir: extras

Both the `org.hibernate.Session` API and `javax.persistence.EntityManager` API represent a context for dealing with persistent data.
This concept is called a `persistence context`.
Persistent data has a state in relation to both a persistence context and the underlying database.

`transient`:: the entity has just been instantiated and is not associated with a persistence context.
It has no persistent representation in the database and typically no identifier value has been assigned (unless the _assigned_ generator was used).
`managed`, or `persistent`:: the entity has an associated identifier and is associated with a persistence context.
It may or may not physically exist in the database yet.
`detached`:: the entity has an associated identifier, but is no longer associated with a persistence context (usually because the persistence context was closed or the instance was evicted from the context)
`removed`:: the entity has an associated identifier and is associated with a persistence context, however it is scheduled for removal from the database.

Much of the `org.hibernate.Session` and `javax.persistence.EntityManager` methods deal with moving entities between these states.

=== Accessing Hibernate APIs from JPA

JPA defines an incredibly useful method to allow applications access to the APIs of the underlying provider.

.Accessing Hibernate APIs from JPA
====
[source,java]
----
include::{sourcedir}/UnwrapWithEM.java[]
----
====

include::BytecodeEnhancement.adoc[]

=== Making entities persistent

Once you've created a new entity instance (using the standard `new` operator) it is in `new` state.
You can make it persistent by associating it to either a `org.hibernate.Session` or `javax.persistence.EntityManager`.

.Example of making an entity persistent
====
[source,java]
----
include::{sourcedir}/MakingPersistentWithSession.java[]
----

[source,java]
----
include::{sourcedir}/MakingPersistentWithEM.java[]
----
====

`org.hibernate.Session` also has a method named persist which follows the exact semantic defined in the JPA specification for the persist method.
It is this `org.hibernate.Session` method to which the Hibernate `javax.persistence.EntityManager` implementation delegates.

If the `DomesticCat` entity type has a generated identifier, the value is associated to the instance when the save or persist is called.
If the identifier is not automatically generated, the manually assigned (usually natural) key value has to be set on the instance before the save or persist methods are called.

=== Deleting entities

Entities can also be deleted.

.Example of deleting an entity
====
[source,java]
----
include::{sourcedir}/DeletingWithSession.java[]
----

[source,java]
----
include::{sourcedir}/DeletingWithEM.java[]
----
====

[NOTE]
====
Hibernate itself can handle deleting detached state.
JPA, however, disallows it.
The implication here is that the entity instance passed to the `org.hibernate.Session` delete method can be either in managed or detached state,
while the entity instance passed to remove on `javax.persistence.EntityManager` must be in managed state.
====

=== Obtain an entity reference without initializing its data

Sometimes referred to as lazy loading, the ability to obtain a reference to an entity without having to load its data is hugely important.
The most common case being the need to create an association between an entity and another existing entity.

.Example of obtaining an entity reference without initializing its data
====
[source,java]
----
include::{sourcedir}/GetReferenceWithSession.java[]
----

[source,java]
----
include::{sourcedir}/GetReferenceWithEM.java[]
----
====

The above works on the assumption that the entity is defined to allow lazy loading, generally through use of runtime proxies.
In both cases an exception will be thrown later if the given entity does not refer to actual database state when the application attempts to use the returned proxy in any way that requires access to its data.

=== Obtain an entity with its data initialized

It is also quite common to want to obtain an entity along with its data (e.g. like when we need to display it in the UI).

.Example of obtaining an entity reference with its data initialized
====
[source,java]
----
include::{sourcedir}/LoadWithSession.java[]
----

[source,java]
----
include::{sourcedir}/LoadWithSession.java[]
----
====

In both cases null is returned if no matching database row was found.

=== Obtain an entity by natural-id

In addition to allowing to load by identifier, Hibernate allows applications to load by declared natural identifier.

.Example of simple natural-id access
====
[source,java]
----
include::{sourcedir}/SimpleNaturalIdLoading.java[]
----

[source,java]
----
include::{sourcedir}/NaturalIdLoading.java[]
----
====

We can also opt to fetch the entity or just retrieve a reference to it when using the natural identifier loading methods.

Hibernate offer a consistent API for accessing persistent data by identifier or by the natural-id. Each of these defines the same two data access methods:

getReference:: Should be used in cases where the identifier is assumed to exist, where non-existence would be an actual error.
Should never be used to test existence.
That is because this method will prefer to create and return a proxy if the data is not already associated with the Session rather than hit the database.
The quintessential use-case for using this method is to create foreign-key based associations.
load:: Will return the persistent data associated with the given identifier value or null if that identifier does not exist.

Each of these two methods define an overloading variant accepting a `org.hibernate.LockOptions` argument.
Locking is discussed in a separate <<chapters/locking/locking.adoc#locking,chapter>>.

=== Refresh entity state

You can reload an entity instance and its collections at any time.

.Example of refreshing entity state
====
[source,java]
----
include::{sourcedir}/RefreshWithSession.java[]
----

[source,java]
----
include::{sourcedir}/RefreshWithEM.java[]
----
====

One case where this is useful is when it is known that the database state has changed since the data was read.
Refreshing allows the current database state to be pulled into the entity instance and the persistence context.

Another case where this might be useful is when database triggers are used to initialize some of the properties of the entity.

[NOTE]
====
Only the entity instance and its value type collections are refreshed unless you specify `REFRESH` as a cascade style of any associations.
However, please note that Hibernate has the capability to handle this automatically through its notion of generated properties.
See the discussion of non-identifier <<chapters/domain/basic_types.adoc#mapping-generated,generated attributes>>.
====

=== Modifying managed/persistent state

Entities in managed/persistent state may be manipulated by the application and any changes will be automatically detected and persisted when the persistence context is flushed.
There is no need to call a particular method to make your modifications persistent.

.Example of modifying managed state
====
[source,java]
----
include::{sourcedir}/ManagedUpdateWithSession.java[]
----

[source,java]
----
include::{sourcedir}/ManagedUpdateWithEM.java[]
----
====

=== Working with detached data

Detachment is the process of working with data outside the scope of any persistence context.
Data becomes detached in a number of ways.
Once the persistence context is closed, all data that was associated with it becomes detached.
Clearing the persistence context has the same effect.
Evicting a particular entity from the persistence context makes it detached.
And finally, serialization will make the deserialized form be detached (the original instance is still managed).

Detached data can still be manipulated, however the persistence context will no longer automatically know about these modification and the application will need to intervene to make the changes persistent again.

==== Reattaching detached data

Reattachment is the process of taking an incoming entity instance that is in detached state and re-associating it with the current persistence context.

[IMPORTANT]
====
JPA does not provide for this model. This is only available through Hibernate `org.hibernate.Session`.
====

.Example of reattaching a detached entity
====
[source,java]
----
include::{sourcedir}/ReattachingWithSession1.java[]
----

[source,java]
----
include::{sourcedir}/ReattachingWithSession2.java[]
----
====

[NOTE]
====
The method name `update` is a bit misleading here.
It does not mean that an `SQL` `UPDATE` is immediately performed.
It does, however, mean that an `SQL` `UPDATE` will be performed when the persistence context is flushed since Hibernate does not know its previous state against which to compare for changes.
If the entity is mapped with `select-before-update`, Hibernate will pull the current state from the database and see if an update is needed.
====

Provided the entity is detached, `update` and `saveOrUpdate` operate exactly the same.

==== Merging detached data

Merging is the process of taking an incoming entity instance that is in detached state and copying its data over onto a new managed instance.

Although not exactly per se, the following example is a good visualization of the `merge` operation internals.

.Visualizing merge
====
[source,java]
----
include::{sourcedir}/VisualizingMerge.java[]
----
====

.Example of merging a detached entity
====
[source,java]
----
include::{sourcedir}/MergeWithSession.java[]
----

[source,java]
----
include::{sourcedir}/MergeWithEM.java[]
----
====

=== Checking persistent state

An application can verify the state of entities and collections in relation to the persistence context.

.Examples of verifying managed state
====
[source,java]
----
include::{sourcedir}/ContainsWithSession.java[]
----

[source,java]
----
include::{sourcedir}/ContainsWithEM.java[]
----
====

.Examples of verifying laziness
====
[source,java]
----
include::{sourcedir}/CheckingLazinessWithHibernate.java[]
----

[source,java]
----
include::{sourcedir}/CheckingLazinessWithJPA.java[]
----
====

In JPA there is an alternative means to check laziness using the following `javax.persistence.PersistenceUtil` pattern (which is recommended where ever possible).

.Alternative JPA means to verify laziness
====
[source,java]
----
include::{sourcedir}/CheckingLazinessWithJPA2.java[]
----
====

=== Evicting entities

When the `flush()` method is called, the state of the entity is synchronized with the database.
If you do not want this synchronization to occur, or if you are processing a huge number of objects and need to manage memory efficiently,
the `evict()` method can be used to remove the object and its collections from the first-level cache.

[[caching-management-jpa-detach-example]]
.Detaching an entity from the `EntityManager`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/../../../../../../test/java/org/hibernate/userguide/caching/FirstLevelCacheTest.java[tags=caching-management-jpa-detach-example]
----
====

[[caching-management-native-evict-example]]
.Evicting an entity from the Hibernate `Session`
====
[source, JAVA, indent=0]
----
include::{sourcedir}/../../../../../../test/java/org/hibernate/userguide/caching/FirstLevelCacheTest.java[tags=caching-management-native-evict-example]
----
====

To detach all entities from the current persistence context, both the `EntityManager` and the Hibernate `Session` define a `clear()` method.

[[caching-management-clear-example]]
.Clearing the persistence context
====
[source, JAVA, indent=0]
----
include::{sourcedir}/../../../../../../test/java/org/hibernate/userguide/caching/FirstLevelCacheTest.java[tags=caching-management-clear-example]
----
====

To verify if an entity instance is currently attached to the running persistence context, both the `EntityManager` and the Hibernate `Session` define a `contains(Object entity)` method.

[[caching-management-contains-example]]
.Verify if an entity is contained in a persistence context
====
[source, JAVA, indent=0]
----
include::{sourcedir}/../../../../../../test/java/org/hibernate/userguide/caching/FirstLevelCacheTest.java[tags=caching-management-contains-example]
----
====