package org.hibernate.testing.sql;

public class Column extends AbstractSqlObject implements NamedObject {

	public Name name;
	public String type;
	public int length;
	public int decimals;
	public boolean notNull;
	public Check check;
	public boolean generatedByDefaultAsIdentity;

	Column( SqlObject parent ) {
		super( parent );
	}

	/**
	 * {@inheritDoc}
	 *
	 * @see org.hibernate.testing.sql.NamedObject#name()
	 */
	@Override
	public Name name() {
		return name;
	}

	/**
	 * {@inheritDoc}
	 *
	 * @see org.hibernate.testing.sql.NamedObject#setName(org.hibernate.testing.sql.Name)
	 */
	@Override
	public void setName( Name name ) {
		this.name = name;
	}

	/**
	 * {@inheritDoc}
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		if ( name != null ) {
			builder.append( name );
		}
		builder.append( ' ' ).append( type );
		if ( length > 0 ) {
			builder.append( "( " ).append( length );
			if ( decimals > 0 ) {
				builder.append( ", " ).append( decimals );
			}
			builder.append( " )" );
		}
		if ( generatedByDefaultAsIdentity ) {
			builder.append( " GENERATED BY DEFAULT AS IDENTITY" );
		}
		if ( notNull ) {
			builder.append( " NOT NULL" );
		}
		if ( check != null ) {
			builder.append( ' ' ).append( check );
		}
		return builder.toString();
	}
}
