[[vector-module]]
== Hibernate Vector module
:vector-project-dir: {root-project-dir}/hibernate-vector
:example-dir-vector: {vector-project-dir}/src/test/java/org/hibernate/vector
:extrasdir: extras

[[vector-module-overview]]
=== Overview

The Hibernate ORM Vector module contains support for mathematical vector types and functions.
This is useful for AI/ML topics like vector similarity search and Retrieval-Augmented Generation (RAG).
The module comes with support for a special `vector` data type that essentially represents an array of bytes, floats, or doubles.

So far, both the PostgreSQL extension `pgvector` and the Oracle database 23ai+ `AI Vector Search` feature are supported, but in theory,
the vector specific functions could be implemented to work with every database that supports arrays.

For further details, refer to the https://github.com/pgvector/pgvector#querying[pgvector documentation] or the https://docs.oracle.com/en/database/oracle/oracle-database/23/vecse/overview-node.html[AI Vector Search documentation].

[[vector-module-setup]]
=== Setup

You need to include the `hibernate-vector` dependency in your build environment.
For Maven, you need to add the following dependency:

[[vector-module-setup-maven-example]]
.Maven dependency
====
[source,xml]
----
<dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-vector</artifactId>
    <version>${hibernate.version}</version>
</dependency>
----
====

The module contains service implementations that are picked up by the Java `ServiceLoader` automatically,
so no further configuration is necessary to make the features available.

[[vector-module-usage]]
==== Usage

Annotate a persistent attribute with `@JdbcTypeCode(SqlTypes.VECTOR)` and specify the vector length with `@Array(length = ...)`.

[WARNING]
====
As Oracle AI Vector Search supports different types of elements (to ensure better performance and compatibility with embedding models), you can also use:

- `@JdbcTypeCode(SqlTypes.VECTOR_INT8)` for `byte[]`
- `@JdbcTypeCode(SqlTypes.VECTOR_FLOAT32)` for `float[]`
- `@JdbcTypeCode(SqlTypes.VECTOR_FLOAT64)` for `double[]`.
====

[[vector-module-usage-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=usage-example]
----
====

To cast the string representation of a vector to the vector data type, simply use an HQL cast i.e. `cast('[1,2,3]' as vector)`.

[[vector-module-functions]]
==== Functions

Expressions of the vector type can be used with various vector functions.

[[vector-module-functions-overview]]
|===
| Function | Purpose

| `cosine_distance()` | Computes the https://en.wikipedia.org/wiki/Cosine_similarity[cosine distance] between two vectors. Maps to the `<``=``>` operator for `pgvector` and maps to the `vector_distance(v1, v2, COSINE)` function for `Oracle AI Vector Search`.

| `euclidean_distance()` | Computes the https://en.wikipedia.org/wiki/Euclidean_distance[euclidean distance] between two vectors. Maps to the `<``-``>` operator for `pgvector` and maps to the
`vector_distance(v1, v2, EUCLIDEAN)` function for `Oracle AI Vector Search`.

| `l2_distance()` | Alias for `euclidean_distance()`

| `taxicab_distance()` | Computes the https://en.wikipedia.org/wiki/Taxicab_geometry[taxicab distance] between two vectors. Maps to `vector_distance(v1, v2, MANHATTAN)` function for `Oracle AI Vector Search`.

| `l1_distance()` | Alias for `taxicab_distance()`

| `hamming_distance()` | Computes the https://en.wikipedia.org/wiki/Hamming_distance[hamming distance] between two vectors. Maps to `vector_distance(v1, v2, HAMMING)` function for `Oracle AI Vector Search`.

| `inner_product()` | Computes the https://en.wikipedia.org/wiki/Inner_product_space[inner product] between two vectors

| `negative_inner_product()` | Computes the negative inner product. Maps to the `<``#``>` operator for `pgvector` and maps to the
`vector_distance(v1, v2, DOT)` function for `Oracle AI Vector Search`.

| `vector_dims()` | Determines the dimensions of a vector

| `vector_norm()` | Computes the https://en.wikipedia.org/wiki/Euclidean_space#Euclidean_norm[Euclidean norm] of a vector
|===

In addition to these special vector functions, it is also possible to use vectors with the following builtin `pgvector` operators:

`<vector1> + <vector2> = <vector3>`:: Element-wise addition of vectors.
`<vector1> - <vector2> = <vector3>`:: Element-wise subtraction of vectors.
`<vector1> * <vector2> = <vector3>`:: Element-wise multiplication of vectors.
`sum(<vector1>) = <vector2>`:: Aggregate function support for element-wise summation of vectors.
`avg(<vector1>) = <vector2>`:: Aggregate function support for element-wise average of vectors.

[[vector-module-functions-cosine-distance]]
===== `cosine_distance()`

Computes the https://en.wikipedia.org/wiki/Cosine_similarity[cosine distance] between two vectors,
which is `1 - inner_product( v1, v2 ) / ( vector_norm( v1 ) * vector_norm( v2 ) )`. Maps to the `<``=``>` pgvector operator.

[[vector-module-functions-cosine-distance-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=cosine-distance-example]
----
====

[[vector-module-functions-euclidean-distance]]
===== `euclidean_distance()` and `l2_distance()`

Computes the https://en.wikipedia.org/wiki/Euclidean_distance[euclidean distance] between two vectors,
which is `sqrt( sum( (v1_i - v2_i)^2 ) )`. Maps to the `<``-``>` pgvector operator.
The `l2_distance()` function is an alias.

[[vector-module-functions-euclidean-distance-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=euclidean-distance-example]
----
====

[[vector-module-functions-taxicab-distance]]
===== `taxicab_distance()` and `l1_distance()`

Computes the https://en.wikipedia.org/wiki/Taxicab_geometry[taxicab distance] between two vectors,
which is `vector_norm(v1) - vector_norm(v2)`.
The `l1_distance()` function is an alias.

[[vector-module-functions-taxicab-distance-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=taxicab-distance-example]
----
====

[[vector-module-functions-inner-product]]
===== `inner_product()` and `negative_inner_product()`

Computes the https://en.wikipedia.org/wiki/Inner_product_space[inner product] between two vectors,
which is `sum( v1_i * v2_i )`. The `negative_inner_product()` function maps to the `<``#``>` pgvector operator,
and the `inner_product()` function as well, but multiplies the result time `-1`.

[[vector-module-functions-inner-product-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=inner-product-example]
----
====

[[vector-module-functions-vector-dims]]
===== `vector_dims()`

Determines the dimensions of a vector.

[[vector-module-functions-vector-dims-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=vector-dims-example]
----
====

[[vector-module-functions-vector-norm]]
===== `vector_norm()`

Computes the https://en.wikipedia.org/wiki/Euclidean_space#Euclidean_norm[Euclidean norm] of a vector,
which is `sqrt( sum( v_i^2 ) )`.

[[vector-module-functions-vector-norm-example]]
====
[source, java, indent=0]
----
include::{example-dir-vector}/PGVectorTest.java[tags=vector-norm-example]
----
====




