CREATE TABLE ORDERS (ID INT NOT NULL, NAME VARCHAR(20), PRIMARY KEY (ID))
CREATE TABLE ITEM  (CHILD_ID INT NOT NULL, NAME VARCHAR(50), ORDER_ID INT, RELATED_ORDER_ID INT, PRIMARY KEY (CHILD_ID), FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID), FOREIGN KEY (RELATED_ORDER_ID) REFERENCES ORDERS(ID) )
