/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
package org.hibernate.tuple;

/**
 * Java value generation is the responsibility of an associated {@link ValueGenerator}.
 * In this case, the generated value is written to the database just like any other field
 * or property value.
 *
 * @author Steve Ebersole
 *
 * @since 6.2
 */
public interface InMemoryValueGenerationStrategy extends ValueGenerationStrategy {

	/**
	 * Obtain the {@linkplain ValueGenerator Java value generator}, if the value is generated in
	 * Java, or return {@code null} if the value is generated by the database.
	 *
	 * @return The value generator
	 */
	ValueGenerator<?> getValueGenerator();

	default boolean generatedByDatabase() {
		return false;
	}
}
