services:
  mssql:
    image: ${MSSQL_IMAGE:-mcr.microsoft.com/mssql/server:2025-latest@sha256:4bab24f36c1ecd48e85f7d37df26e6bf301641d84c3fe652f9a0dcc947d512e1}
    container_name: mssql
    environment:
      SA_PASSWORD: Hibernate_orm_test
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Hibernate_orm_test -Q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
