services:
  mssql:
    image: ${MSSQL_IMAGE:-mcr.microsoft.com/mssql/server:2025-latest@sha256:2cd0aec4a3bfc3cf9205bed3f7922f4c6208f7c767dc62edcee308d0fd7d56d0}
    container_name: mssql
    environment:
      SA_PASSWORD: Hibernate_orm_test
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Hibernate_orm_test -Q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
