${templateHelper.getPackageDeclaration()}

// Generated by Hibernate Tools

<#assign classbody>
<#include "EntityTypeDeclaration.ftl"/> {

<#include "EntityFields.ftl"/>

<#include "EntityConstructors.ftl"/>

<#include "EntityPropertyAccessors.ftl"/>

<#include "EntityToString.ftl"/>

<#include "EntityEqualsHashcode.ftl"/>

<#include "EntityExtraClassCode.ftl"/>

}
</#assign>

${templateHelper.generateImports()}
${classbody}
