${templateHelper.getPackageDeclaration()}

// Generated by Hibernate Tools

<#assign classbody>
<#include "type-declaration.entity.ftl"/> {

<#include "fields.entity.ftl"/>

<#include "constructors.entity.ftl"/>

<#include "property-accessors.entity.ftl"/>

<#list templateHelper.getLifecycleCallbacks() as callback>
    ${templateHelper.generateLifecycleCallbackAnnotation(callback)}
    protected void ${callback.methodName()}() {
    }

</#list>
<#include "to-string.entity.ftl"/>

<#include "equals-hashcode.entity.ftl"/>

<#include "extra-class-code.entity.ftl"/>

}
</#assign>

${templateHelper.generateImports()}
${classbody}
