############################################################################
# Hibernate Tools, Tooling for your Hibernate Projects                     #
#                                                                          #
# Copyright 2004-2025 Red Hat, Inc.                                        #
#                                                                          #
# Licensed under the Apache License, Version 2.0 (the "License");          #
# you may not use this file except in compliance with the License.         #
# You may obtain a copy of the License at                                  #
#                                                                          #
#     http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                          #
# Unless required by applicable law or agreed to in writing, software      #
# distributed under the License is distributed on an "AS IS" basis,        #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
# See the License for the specific language governing permissions and      #
# limitations under the License.                                           #
############################################################################
drop table HTT.PERFTEST199
drop table HTT.PERFTEST198
drop table HTT.PERFTEST197
drop table HTT.PERFTEST196
drop table HTT.PERFTEST195
drop table HTT.PERFTEST194
drop table HTT.PERFTEST193
drop table HTT.PERFTEST192
drop table HTT.PERFTEST191
drop table HTT.PERFTEST190
drop table HTT.PERFTEST189
drop table HTT.PERFTEST188
drop table HTT.PERFTEST187
drop table HTT.PERFTEST186
drop table HTT.PERFTEST185
drop table HTT.PERFTEST184
drop table HTT.PERFTEST183
drop table HTT.PERFTEST182
drop table HTT.PERFTEST181
drop table HTT.PERFTEST180
drop table HTT.PERFTEST179
drop table HTT.PERFTEST178
drop table HTT.PERFTEST177
drop table HTT.PERFTEST176
drop table HTT.PERFTEST175
drop table HTT.PERFTEST174
drop table HTT.PERFTEST173
drop table HTT.PERFTEST172
drop table HTT.PERFTEST171
drop table HTT.PERFTEST170
drop table HTT.PERFTEST169
drop table HTT.PERFTEST168
drop table HTT.PERFTEST167
drop table HTT.PERFTEST166
drop table HTT.PERFTEST165
drop table HTT.PERFTEST164
drop table HTT.PERFTEST163
drop table HTT.PERFTEST162
drop table HTT.PERFTEST161
drop table HTT.PERFTEST160
drop table HTT.PERFTEST159
drop table HTT.PERFTEST158
drop table HTT.PERFTEST157
drop table HTT.PERFTEST156
drop table HTT.PERFTEST155
drop table HTT.PERFTEST154
drop table HTT.PERFTEST153
drop table HTT.PERFTEST152
drop table HTT.PERFTEST151
drop table HTT.PERFTEST150
drop table HTT.PERFTEST149
drop table HTT.PERFTEST148
drop table HTT.PERFTEST147
drop table HTT.PERFTEST146
drop table HTT.PERFTEST145
drop table HTT.PERFTEST144
drop table HTT.PERFTEST143
drop table HTT.PERFTEST142
drop table HTT.PERFTEST141
drop table HTT.PERFTEST140
drop table HTT.PERFTEST139
drop table HTT.PERFTEST138
drop table HTT.PERFTEST137
drop table HTT.PERFTEST136
drop table HTT.PERFTEST135
drop table HTT.PERFTEST134
drop table HTT.PERFTEST133
drop table HTT.PERFTEST132
drop table HTT.PERFTEST131
drop table HTT.PERFTEST130
drop table HTT.PERFTEST129
drop table HTT.PERFTEST128
drop table HTT.PERFTEST127
drop table HTT.PERFTEST126
drop table HTT.PERFTEST125
drop table HTT.PERFTEST124
drop table HTT.PERFTEST123
drop table HTT.PERFTEST122
drop table HTT.PERFTEST121
drop table HTT.PERFTEST120
drop table HTT.PERFTEST119
drop table HTT.PERFTEST118
drop table HTT.PERFTEST117
drop table HTT.PERFTEST116
drop table HTT.PERFTEST115
drop table HTT.PERFTEST114
drop table HTT.PERFTEST113
drop table HTT.PERFTEST112
drop table HTT.PERFTEST111
drop table HTT.PERFTEST110
drop table HTT.PERFTEST109
drop table HTT.PERFTEST108
drop table HTT.PERFTEST107
drop table HTT.PERFTEST106
drop table HTT.PERFTEST105
drop table HTT.PERFTEST104
drop table HTT.PERFTEST103
drop table HTT.PERFTEST102
drop table HTT.PERFTEST101
drop table HTT.PERFTEST100
drop table HTT.PERFTEST99
drop table HTT.PERFTEST98
drop table HTT.PERFTEST97
drop table HTT.PERFTEST96
drop table HTT.PERFTEST95
drop table HTT.PERFTEST94
drop table HTT.PERFTEST93
drop table HTT.PERFTEST92
drop table HTT.PERFTEST91
drop table HTT.PERFTEST90
drop table HTT.PERFTEST89
drop table HTT.PERFTEST88
drop table HTT.PERFTEST87
drop table HTT.PERFTEST86
drop table HTT.PERFTEST85
drop table HTT.PERFTEST84
drop table HTT.PERFTEST83
drop table HTT.PERFTEST82
drop table HTT.PERFTEST81
drop table HTT.PERFTEST80
drop table HTT.PERFTEST79
drop table HTT.PERFTEST78
drop table HTT.PERFTEST77
drop table HTT.PERFTEST76
drop table HTT.PERFTEST75
drop table HTT.PERFTEST74
drop table HTT.PERFTEST73
drop table HTT.PERFTEST72
drop table HTT.PERFTEST71
drop table HTT.PERFTEST70
drop table HTT.PERFTEST69
drop table HTT.PERFTEST68
drop table HTT.PERFTEST67
drop table HTT.PERFTEST66
drop table HTT.PERFTEST65
drop table HTT.PERFTEST64
drop table HTT.PERFTEST63
drop table HTT.PERFTEST62
drop table HTT.PERFTEST61
drop table HTT.PERFTEST60
drop table HTT.PERFTEST59
drop table HTT.PERFTEST58
drop table HTT.PERFTEST57
drop table HTT.PERFTEST56
drop table HTT.PERFTEST55
drop table HTT.PERFTEST54
drop table HTT.PERFTEST53
drop table HTT.PERFTEST52
drop table HTT.PERFTEST51
drop table HTT.PERFTEST50
drop table HTT.PERFTEST49
drop table HTT.PERFTEST48
drop table HTT.PERFTEST47
drop table HTT.PERFTEST46
drop table HTT.PERFTEST45
drop table HTT.PERFTEST44
drop table HTT.PERFTEST43
drop table HTT.PERFTEST42
drop table HTT.PERFTEST41
drop table HTT.PERFTEST40
drop table HTT.PERFTEST39
drop table HTT.PERFTEST38
drop table HTT.PERFTEST37
drop table HTT.PERFTEST36
drop table HTT.PERFTEST35
drop table HTT.PERFTEST34
drop table HTT.PERFTEST33
drop table HTT.PERFTEST32
drop table HTT.PERFTEST31
drop table HTT.PERFTEST30
drop table HTT.PERFTEST29
drop table HTT.PERFTEST28
drop table HTT.PERFTEST27
drop table HTT.PERFTEST26
drop table HTT.PERFTEST25
drop table HTT.PERFTEST24
drop table HTT.PERFTEST23
drop table HTT.PERFTEST22
drop table HTT.PERFTEST21
drop table HTT.PERFTEST20
drop table HTT.PERFTEST19
drop table HTT.PERFTEST18
drop table HTT.PERFTEST17
drop table HTT.PERFTEST16
drop table HTT.PERFTEST15
drop table HTT.PERFTEST14
drop table HTT.PERFTEST13
drop table HTT.PERFTEST12
drop table HTT.PERFTEST11
drop table HTT.PERFTEST10
drop table HTT.PERFTEST9
drop table HTT.PERFTEST8
drop table HTT.PERFTEST7
drop table HTT.PERFTEST6
drop table HTT.PERFTEST5
drop table HTT.PERFTEST4
drop table HTT.PERFTEST3
drop table HTT.PERFTEST2
drop table HTT.PERFTEST1
drop table HTT.PERFTEST0
drop schema HTT