/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.event.spi;

import org.hibernate.HibernateException;

/**
 * Defines the contract for handling of collection initialization events
 * generated by a session.
 *
 * @author Gavin King
 */
public interface InitializeCollectionEventListener {
	void onInitializeCollection(InitializeCollectionEvent event) throws HibernateException;
}
