/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */
package org.hibernate.processor.test.data.innerclass;

import org.hibernate.processor.test.util.CompilationTest;
import org.hibernate.processor.test.util.TestForIssue;
import org.hibernate.processor.test.util.TestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * During an incremental build, the processor must generate the Jakarta Data
 * static metamodel Java source ({@code _Entity.java}) when the existing
 * metamodel class was generated by the processor, not handwritten.
 * <p>
 * Maven may clear generated sources while leaving {@code _Entity.class} from a
 * previous compilation. The processor must not mistake that class for a
 * handwritten metamodel and skip generating the Java source.
 */
@CompilationTest
@TestForIssue(jiraKey = "HHH-20775")
class IncrementalCompilationTest {

	private final File outDir = new File( TestUtil.getOutBaseDir( IncrementalCompilationTest.class ), "incremental" );
	private final File classesDir = new File( outDir, "classes" );
	private final File generatedSourcesDir = new File( outDir, "generated-sources" );
	private final File dataMetamodelClass = TestUtil.getMetaModelClassFileFor(
			IncrementalItemEntity.class, true, classesDir );
	// classes/data/metamodel/generated/org.hibernate.processor.test.data.innerclass.IncrementalItemEntity
	private final Path dataMetamodelMarker = TestUtil.getDataMetamodelMarkerFile(
			IncrementalItemEntity.class, classesDir );

	@Test
	void testJakartaDataMetamodelSourceGeneratedOnIncrementalBuild() throws Exception {
		TestUtil.deleteFilesRecursive( outDir );
		Files.createDirectories( classesDir.toPath() );

		compileAndAssertMetamodel( 1 );

		deleteGeneratedSourcesAndAssertCompiledOutputSurvives();
		compileAndAssertMetamodel( 2 );

		deleteGeneratedSourcesAndAssertCompiledOutputSurvives();
		compileAndAssertMetamodel( 3 );
	}

	private void deleteGeneratedSourcesAndAssertCompiledOutputSurvives() {
		// Maven clears generated sources but retains compiled classes and their markers.
		TestUtil.deleteFilesRecursive( generatedSourcesDir );
		assertFalse( generatedSourcesDir.exists() );
		assertTrue( dataMetamodelClass.exists(), "Compiled metamodel must survive source cleanup" );
		assertMetamodelMarker();
	}

	private void assertMetamodelMarker() {
		assertTrue( Files.isRegularFile( dataMetamodelMarker ), "Metamodel marker must exist in the class output directory" );
	}

	private void compileAndAssertMetamodel(int compilation) throws Exception {
		final var sourceFile = TestUtil.getSourceFile( IncrementalItemEntity.class );
		final var dataMetamodelSource = TestUtil.getMetaModelSourceFileFor(
				IncrementalItemEntity.class, true, generatedSourcesDir );
		final var queriesClass = TestUtil.getNestedRepositoryClassFileFor(
				IncrementalItemEntity.Queries.class, true, classesDir );
		final var duplicateQueriesClass = TestUtil.getNestedRepositoryClassFileFor(
				IncrementalItemEntity.Queries.class, false, classesDir );

		Files.createDirectories( generatedSourcesDir.toPath() );
		TestUtil.compile( classesDir, generatedSourcesDir, new File[] { sourceFile } );
		assertMetamodelMarker();
		assertTrue( dataMetamodelSource.exists(),
				"Compilation " + compilation + " should generate _IncrementalItemEntity.java" );
		assertTrue( dataMetamodelClass.exists(),
				"Compilation " + compilation + " should compile _IncrementalItemEntity.class" );
		assertTrue( queriesClass.exists(),
				"Compilation " + compilation + " should compile the queries implementation" );
		assertFalse( duplicateQueriesClass.exists(),
				"Compilation " + compilation + " should not generate a duplicate queries class" );
	}
}
