# See https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request
name: Dependabot auto-merge Hibernate ORM update
on:
  pull_request:
    branches:
      - '7.4'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'hibernate/hibernate-tools'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check if Hibernate ORM Patch update
        id: orm-update-check
        run: |
          if [[ "${{ contains(steps.metadata.outputs.dependency-names, 'org.hibernate.orm') }}" == "true" && \
                "${{ steps.metadata.outputs.update-type }}" == "version-update:semver-patch" ]]; then
            echo "Match found. Proceeding with Jira update."
            echo "passed=true" >> $GITHUB_OUTPUT
          else
            echo "Not a Hibernate ORM patch update. Stopping workflow."
            echo "passed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Enable auto-merge for Dependabot PRs
        if: steps.orm-update-check.outputs.passed == 'true'
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
