name: GH Actions CI reporting

on:
  workflow_run:
    workflows: [ "GH Actions CI" ]
    types: [ completed ]

defaults:
  run:
    shell: bash

permissions: { } # none, jobs are defining their own if they need any

env:
  COMMON_GRADLE_ARGS: "-Igradle/init.gradle"
  MIRROR_MAVEN_CENTRAL_URL: "https://maven-central.storage-download.googleapis.com/maven2/"
  MIRROR_MAVEN_CENTRAL_FALLBACK: "true"

jobs:
  report:
    uses: hibernate/.github/.github/workflows/ci-reporting.yml@main
    permissions:
      actions: read
      contents: read
      pull-requests: write
    secrets: inherit
