# SPDX-License-Identifier: Apache-2.0
# Copyright Red Hat Inc. and Hibernate Authors

name: PR cleanup

on:
  pull_request_target:
    types: [ closed ]

permissions: { }

jobs:
  cleanup:
    uses: hibernate/.github/.github/workflows/pr-cleanup.yml@main
    permissions:
      pull-requests: write
    secrets: inherit
